CLASSES=\
	cyberscope.ai.AssetType	\
	cyberscope.ai.CanonicalID	\
	cyberscope.ai.CircuitType	\
	cyberscope.ai.ComputingDeviceType	\
	cyberscope.ai.IPAddressType	\
	cyberscope.ai.ITAssetType	\
	cyberscope.ai.Locations	\
	cyberscope.ai.NetworkInterfaceType	\
	cyberscope.ai.NetworkType	\
	cyberscope.ai.ObjectFactory	\
	cyberscope.ai.OrganizationType	\
	cyberscope.ai.package-info	\
	cyberscope.ai.PersonType	\
	cyberscope.ai.SoftwareType	\
	cyberscope.ai.SystemType	\
	cyberscope.arf.AssetIdentificationReferenceType	\
	cyberscope.arf.AssetReport	\
	cyberscope.arf.ObjectFactory	\
	cyberscope.arf.package-info	\
	cyberscope.arf.ReportInformation	\
	cyberscope.arf.ReportRequest	\
	cyberscope.lasr.AggregateValueType	\
	cyberscope.lasr.AggregationType	\
	cyberscope.lasr.AssetAttributeType	\
	cyberscope.lasr.AttributeType	\
	cyberscope.lasr.DataPointType	\
	cyberscope.lasr.GroupedDataType	\
	cyberscope.lasr.ObjectFactory	\
	cyberscope.lasr.package-info	\
	cyberscope.lasr.SummaryReportType	\
	cyberscope.oasis.address.AddressType	\
	cyberscope.oasis.address.AddressTypeList	\
	cyberscope.oasis.address.AddressUsageList	\
	cyberscope.oasis.address.AdministrativeAreaNameTypeList	\
	cyberscope.oasis.address.AdministrativeAreaTypeList	\
	cyberscope.oasis.address.CountryNameTypeList	\
	cyberscope.oasis.address.CountryType	\
	cyberscope.oasis.address.DirectionTypeList	\
	cyberscope.oasis.address.IdentifierElementTypeList	\
	cyberscope.oasis.address.IdentifierType	\
	cyberscope.oasis.address.LocalityNameTypeList	\
	cyberscope.oasis.address.LocalityTypeList	\
	cyberscope.oasis.address.ObjectFactory	\
	cyberscope.oasis.address.package-info	\
	cyberscope.oasis.address.PostalDeliveryPointTypeList	\
	cyberscope.oasis.address.PremisesElementTypeList	\
	cyberscope.oasis.address.PremisesType	\
	cyberscope.oasis.address.PremisesTypeList	\
	cyberscope.oasis.address.SubAdministrativeAreaNameTypeList	\
	cyberscope.oasis.address.SubAdministrativeAreaTypeList	\
	cyberscope.oasis.address.SubLocalityNameTypeList	\
	cyberscope.oasis.address.SubLocalityTypeList	\
	cyberscope.oasis.address.SubPremisesTypeList	\
	cyberscope.oasis.address.ThoroughfareNameTypeList	\
	cyberscope.oasis.address.ThoroughfareType	\
	cyberscope.oasis.name.NameLine	\
	cyberscope.oasis.name.ObjectFactory	\
	cyberscope.oasis.name.OrganisationNameElementList	\
	cyberscope.oasis.name.OrganisationNameType	\
	cyberscope.oasis.name.OrganisationNameTypeList	\
	cyberscope.oasis.name.package-info	\
	cyberscope.oasis.name.PartyNameType	\
	cyberscope.oasis.name.PersonNameElementList	\
	cyberscope.oasis.name.PersonNameType	\
	cyberscope.oasis.name.PersonNameTypeList	\
	cyberscope.oasis.name.SubDivisionTypeList	\
	cyberscope.oasis.types.DataQualityTypeList	\
	cyberscope.oasis.types.ObjectFactory
