CLASSES=\
	ocil.schemas.core.ArtifactRefsType	\
	ocil.schemas.core.ArtifactRefType	\
	ocil.schemas.core.ArtifactResultsType	\
	ocil.schemas.core.ArtifactResultType	\
	ocil.schemas.core.ArtifactsType	\
	ocil.schemas.core.ArtifactType	\
	ocil.schemas.core.ArtifactValueType	\
	ocil.schemas.core.BinaryArtifactValueType	\
	ocil.schemas.core.BooleanQuestionModelType	\
	ocil.schemas.core.BooleanQuestionResultType	\
	ocil.schemas.core.BooleanQuestionTestActionType	\
	ocil.schemas.core.BooleanQuestionType	\
	ocil.schemas.core.ChoiceAnswerType	\
	ocil.schemas.core.ChoiceGroupType	\
	ocil.schemas.core.ChoiceQuestionResultType	\
	ocil.schemas.core.ChoiceQuestionTestActionType	\
	ocil.schemas.core.ChoiceQuestionType	\
	ocil.schemas.core.ChoiceTestActionConditionType	\
	ocil.schemas.core.ChoiceType	\
	ocil.schemas.core.CompoundTestActionType	\
	ocil.schemas.core.ConstantVariableType	\
	ocil.schemas.core.DocumentType	\
	ocil.schemas.core.EmbeddedArtifactValueType	\
	ocil.schemas.core.EqualsTestActionConditionType	\
	ocil.schemas.core.ExceptionalResultType	\
	ocil.schemas.core.ExtensionContainerType	\
	ocil.schemas.core.ExternalVariableType	\
	ocil.schemas.core.GeneratorType	\
	ocil.schemas.core.InstructionsType	\
	ocil.schemas.core.ItemBaseType	\
	ocil.schemas.core.LocalVariableType	\
	ocil.schemas.core.NamedItemBaseType	\
	ocil.schemas.core.NumericQuestionResultType	\
	ocil.schemas.core.NumericQuestionTestActionType	\
	ocil.schemas.core.NumericQuestionType	\
	ocil.schemas.core.ObjectFactory	\
	ocil.schemas.core.OCILType	\
	ocil.schemas.core.OperationType	\
	ocil.schemas.core.OperatorType	\
	ocil.schemas.core.package-info	\
	ocil.schemas.core.PatternTestActionConditionType	\
	ocil.schemas.core.PatternType	\
	ocil.schemas.core.QuestionnaireResultsType	\
	ocil.schemas.core.QuestionnaireResultType	\
	ocil.schemas.core.QuestionnairesType	\
	ocil.schemas.core.QuestionnaireType	\
	ocil.schemas.core.QuestionResultsType	\
	ocil.schemas.core.QuestionResultType	\
	ocil.schemas.core.QuestionsType	\
	ocil.schemas.core.QuestionTestActionType	\
	ocil.schemas.core.QuestionTextType	\
	ocil.schemas.core.QuestionType	\
	ocil.schemas.core.RangeTestActionConditionType	\
	ocil.schemas.core.RangeType	\
	ocil.schemas.core.RangeValueType	\
	ocil.schemas.core.ReferenceArtifactValueType	\
	ocil.schemas.core.ReferencesType	\
	ocil.schemas.core.ReferenceType	\
	ocil.schemas.core.ResultsType	\
	ocil.schemas.core.SetExpressionBaseType	\
	ocil.schemas.core.SetExpressionBooleanType	\
	ocil.schemas.core.SetExpressionChoiceType	\
	ocil.schemas.core.SetExpressionPatternType	\
	ocil.schemas.core.SetExpressionRangeType	\
	ocil.schemas.core.StepType	\
	ocil.schemas.core.StringQuestionResultType	\
	ocil.schemas.core.StringQuestionTestActionType	\
	ocil.schemas.core.StringQuestionType	\
	ocil.schemas.core.SubstitutionTextType	\
	ocil.schemas.core.SystemTargetType	\
	ocil.schemas.core.TargetsType	\
	ocil.schemas.core.TestActionConditionType	\
	ocil.schemas.core.TestActionRefType	\
	ocil.schemas.core.TestActionResultsType	\
	ocil.schemas.core.TestActionResultType	\
	ocil.schemas.core.TestActionsType	\
	ocil.schemas.core.TextArtifactValueType	\
	ocil.schemas.core.TextType	\
	ocil.schemas.core.UserType	\
	ocil.schemas.core.VariableDataType	\
	ocil.schemas.core.VariableSetType	\
	ocil.schemas.core.VariablesType	\
	ocil.schemas.core.VariableType
