CLASSES=\
	org.joval.intf.arf.IReport					\
	org.joval.intf.cpe.IDictionary					\
	org.joval.intf.ocil.IChecklist					\
	org.joval.intf.ocil.IVariables					\
	org.joval.intf.scap.IDatastream					\
	org.joval.intf.scap.IDatastreamCollection			\
	org.joval.intf.scap.IView					\
	org.joval.intf.scap.SystemEnumeration				\
	org.joval.intf.xccdf.IBenchmark					\
	org.joval.intf.xccdf.IEngine					\
	org.joval.scap.Datastream					\
	org.joval.scap.Datastream					\
	org.joval.scap.ScapException					\
	org.joval.scap.ScapFactory					\
	org.joval.scap.arf.ArfException					\
	org.joval.scap.arf.Factories					\
	org.joval.scap.arf.Report					\
	org.joval.scap.cpe.CpeException					\
	org.joval.scap.cpe.Dictionary					\
	org.joval.scap.ocil.BooleanTestActionConditionType		\
	org.joval.scap.ocil.Checklist					\
	org.joval.scap.ocil.ChecklistResults				\
	org.joval.scap.ocil.Factories					\
	org.joval.scap.ocil.OcilException				\
	org.joval.scap.ocil.OcilFactory					\
	org.joval.scap.ocil.Variables					\
	org.joval.scap.sce.SceException					\
	org.joval.scap.sce.SCEScript					\
	org.joval.scap.xccdf.Benchmark					\
	org.joval.scap.xccdf.TestResult					\
	org.joval.scap.xccdf.XccdfException				\
	org.joval.scap.xccdf.engine.Engine				\
	org.joval.scap.xccdf.engine.RuleResult				\
	org.joval.scap.xccdf.engine.XPERT				\
	org.joval.scap.xccdf.handler.OCILHandler			\
	org.joval.scap.xccdf.handler.OVALHandler			\
	org.joval.scap.xccdf.handler.SCEHandler
