CLASSES=	\
	oval.schemas.common.CheckEnumeration	\
	oval.schemas.common.ClassEnumeration	\
	oval.schemas.common.ComplexDatatypeEnumeration	\
	oval.schemas.common.DeprecatedInfoType	\
	oval.schemas.common.ElementMapItemType	\
	oval.schemas.common.ElementMapType	\
	oval.schemas.common.ExistenceEnumeration	\
	oval.schemas.common.FamilyEnumeration	\
	oval.schemas.common.GeneratorType	\
	oval.schemas.common.MessageLevelEnumeration	\
	oval.schemas.common.MessageType	\
	oval.schemas.common.ObjectFactory	\
	oval.schemas.common.OperationEnumeration	\
	oval.schemas.common.OperatorEnumeration	\
	oval.schemas.common.package-info	\
	oval.schemas.common.SimpleDatatypeEnumeration	\
	oval.schemas.definitions.core.AffectedType	\
	oval.schemas.definitions.core.ArithmeticEnumeration	\
	oval.schemas.definitions.core.ArithmeticFunctionType	\
	oval.schemas.definitions.core.BeginFunctionType	\
	oval.schemas.definitions.core.ConcatFunctionType	\
	oval.schemas.definitions.core.ConstantVariable	\
	oval.schemas.definitions.core.CriteriaType	\
	oval.schemas.definitions.core.CriterionType	\
	oval.schemas.definitions.core.DateTimeFormatEnumeration	\
	oval.schemas.definitions.core.DefinitionsType	\
	oval.schemas.definitions.core.DefinitionType	\
	oval.schemas.definitions.core.EndFunctionType	\
	oval.schemas.definitions.core.EntityComplexBaseType	\
	oval.schemas.definitions.core.EntityObjectAnySimpleType	\
	oval.schemas.definitions.core.EntityObjectBinaryType	\
	oval.schemas.definitions.core.EntityObjectBoolType	\
	oval.schemas.definitions.core.EntityObjectFloatType	\
	oval.schemas.definitions.core.EntityObjectIntType	\
	oval.schemas.definitions.core.EntityObjectIPAddressStringType	\
	oval.schemas.definitions.core.EntityObjectIPAddressType	\
	oval.schemas.definitions.core.EntityObjectStringType	\
	oval.schemas.definitions.core.EntitySimpleBaseType	\
	oval.schemas.definitions.core.EntityStateAnySimpleType	\
	oval.schemas.definitions.core.EntityStateBinaryType	\
	oval.schemas.definitions.core.EntityStateBoolType	\
	oval.schemas.definitions.core.EntityStateComplexBaseType	\
	oval.schemas.definitions.core.EntityStateEVRStringType	\
	oval.schemas.definitions.core.EntityStateFieldType	\
	oval.schemas.definitions.core.EntityStateFileSetRevisionType	\
	oval.schemas.definitions.core.EntityStateFloatType	\
	oval.schemas.definitions.core.EntityStateIntType	\
	oval.schemas.definitions.core.EntityStateIOSVersionType	\
	oval.schemas.definitions.core.EntityStateIPAddressStringType	\
	oval.schemas.definitions.core.EntityStateIPAddressType	\
	oval.schemas.definitions.core.EntityStateRecordType	\
	oval.schemas.definitions.core.EntityStateSimpleBaseType	\
	oval.schemas.definitions.core.EntityStateStringType	\
	oval.schemas.definitions.core.EntityStateVersionType	\
	oval.schemas.definitions.core.EscapeRegexFunctionType	\
	oval.schemas.definitions.core.ExtendDefinitionType	\
	oval.schemas.definitions.core.ExternalVariable	\
	oval.schemas.definitions.core.Filter	\
	oval.schemas.definitions.core.FilterActionEnumeration	\
	oval.schemas.definitions.core.LiteralComponentType	\
	oval.schemas.definitions.core.LocalVariable	\
	oval.schemas.definitions.core.MetadataType	\
	oval.schemas.definitions.core.NotesType	\
	oval.schemas.definitions.core.ObjectComponentType	\
	oval.schemas.definitions.core.ObjectFactory	\
	oval.schemas.definitions.core.ObjectRefType	\
	oval.schemas.definitions.core.ObjectsType	\
	oval.schemas.definitions.core.ObjectType	\
	oval.schemas.definitions.core.OvalDefinitions	\
	oval.schemas.definitions.core.package-info	\
	oval.schemas.definitions.core.PossibleRestrictionType	\
	oval.schemas.definitions.core.PossibleValueType	\
	oval.schemas.definitions.core.ReferenceType	\
	oval.schemas.definitions.core.RegexCaptureFunctionType	\
	oval.schemas.definitions.core.RestrictionType	\
	oval.schemas.definitions.core.Set	\
	oval.schemas.definitions.core.SetOperatorEnumeration	\
	oval.schemas.definitions.core.SplitFunctionType	\
	oval.schemas.definitions.core.StateRefType	\
	oval.schemas.definitions.core.StatesType	\
	oval.schemas.definitions.core.StateType	\
	oval.schemas.definitions.core.SubstringFunctionType	\
	oval.schemas.definitions.core.TestsType	\
	oval.schemas.definitions.core.TestType	\
	oval.schemas.definitions.core.TimeDifferenceFunctionType	\
	oval.schemas.definitions.core.ValueType	\
	oval.schemas.definitions.core.VariableComponentType	\
	oval.schemas.definitions.core.VariablesType	\
	oval.schemas.definitions.core.VariableType	\
	oval.schemas.definitions.independent.EntityObjectEngineType	\
	oval.schemas.definitions.independent.EntityObjectHashTypeType	\
	oval.schemas.definitions.independent.EntityObjectVariableRefType	\
	oval.schemas.definitions.independent.EntityStateEngineType	\
	oval.schemas.definitions.independent.EntityStateFamilyType	\
	oval.schemas.definitions.independent.EntityStateHashTypeType	\
	oval.schemas.definitions.independent.EntityStateLdaptypeType	\
	oval.schemas.definitions.independent.EntityStateVariableRefType	\
	oval.schemas.definitions.independent.Environmentvariable58Object	\
	oval.schemas.definitions.independent.Environmentvariable58State	\
	oval.schemas.definitions.independent.Environmentvariable58Test	\
	oval.schemas.definitions.independent.EnvironmentvariableObject	\
	oval.schemas.definitions.independent.EnvironmentvariableState	\
	oval.schemas.definitions.independent.EnvironmentvariableTest	\
	oval.schemas.definitions.independent.FamilyObject	\
	oval.schemas.definitions.independent.FamilyState	\
	oval.schemas.definitions.independent.FamilyTest	\
	oval.schemas.definitions.independent.FileBehaviors	\
	oval.schemas.definitions.independent.Filehash58Object	\
	oval.schemas.definitions.independent.Filehash58State	\
	oval.schemas.definitions.independent.Filehash58Test	\
	oval.schemas.definitions.independent.FilehashObject	\
	oval.schemas.definitions.independent.FilehashState	\
	oval.schemas.definitions.independent.FilehashTest	\
	oval.schemas.definitions.independent.Ldap57Object	\
	oval.schemas.definitions.independent.Ldap57State	\
	oval.schemas.definitions.independent.Ldap57Test	\
	oval.schemas.definitions.independent.LdapBehaviors	\
	oval.schemas.definitions.independent.LdapObject	\
	oval.schemas.definitions.independent.LdapState	\
	oval.schemas.definitions.independent.LdapTest	\
	oval.schemas.definitions.independent.ObjectFactory	\
	oval.schemas.definitions.independent.package-info	\
	oval.schemas.definitions.independent.Sql57Object	\
	oval.schemas.definitions.independent.Sql57State	\
	oval.schemas.definitions.independent.Sql57Test	\
	oval.schemas.definitions.independent.SqlObject	\
	oval.schemas.definitions.independent.SqlState	\
	oval.schemas.definitions.independent.SqlTest	\
	oval.schemas.definitions.independent.Textfilecontent54Behaviors	\
	oval.schemas.definitions.independent.Textfilecontent54Object	\
	oval.schemas.definitions.independent.Textfilecontent54State	\
	oval.schemas.definitions.independent.Textfilecontent54Test	\
	oval.schemas.definitions.independent.TextfilecontentObject	\
	oval.schemas.definitions.independent.TextfilecontentState	\
	oval.schemas.definitions.independent.TextfilecontentTest	\
	oval.schemas.definitions.independent.UnknownTest	\
	oval.schemas.definitions.independent.VariableObject	\
	oval.schemas.definitions.independent.VariableState	\
	oval.schemas.definitions.independent.VariableTest	\
	oval.schemas.definitions.independent.XmlfilecontentObject	\
	oval.schemas.definitions.independent.XmlfilecontentState	\
	oval.schemas.definitions.independent.XmlfilecontentTest	\
	oval.schemas.definitions.linux.DpkginfoObject	\
	oval.schemas.definitions.linux.DpkginfoState	\
	oval.schemas.definitions.linux.DpkginfoTest	\
	oval.schemas.definitions.linux.EntityStateFileSystemTypeType	\
	oval.schemas.definitions.linux.EntityStateProtocolType	\
	oval.schemas.definitions.linux.EntityStateRpmVerifyResultType	\
	oval.schemas.definitions.linux.IflistenersObject	\
	oval.schemas.definitions.linux.IflistenersState	\
	oval.schemas.definitions.linux.IflistenersTest	\
	oval.schemas.definitions.linux.InetlisteningserversObject	\
	oval.schemas.definitions.linux.InetlisteningserversState	\
	oval.schemas.definitions.linux.InetlisteningserversTest	\
	oval.schemas.definitions.linux.ObjectFactory	\
	oval.schemas.definitions.linux.package-info	\
	oval.schemas.definitions.linux.PartitionObject	\
	oval.schemas.definitions.linux.PartitionState	\
	oval.schemas.definitions.linux.PartitionTest	\
	oval.schemas.definitions.linux.RpminfoObject	\
	oval.schemas.definitions.linux.RpminfoState	\
	oval.schemas.definitions.linux.RpminfoTest	\
	oval.schemas.definitions.linux.RpmVerifyBehaviors	\
	oval.schemas.definitions.linux.RpmverifyObject	\
	oval.schemas.definitions.linux.RpmverifyState	\
	oval.schemas.definitions.linux.RpmverifyTest	\
	oval.schemas.definitions.linux.SelinuxbooleanObject	\
	oval.schemas.definitions.linux.SelinuxbooleanState	\
	oval.schemas.definitions.linux.SelinuxbooleanTest	\
	oval.schemas.definitions.linux.SelinuxsecuritycontextObject	\
	oval.schemas.definitions.linux.SelinuxsecuritycontextState	\
	oval.schemas.definitions.linux.SelinuxsecuritycontextTest	\
	oval.schemas.definitions.linux.SlackwarepkginfoObject	\
	oval.schemas.definitions.linux.SlackwarepkginfoState	\
	oval.schemas.definitions.linux.SlackwarepkginfoTest	\
	oval.schemas.definitions.unix.DnscacheObject	\
	oval.schemas.definitions.unix.DnscacheState	\
	oval.schemas.definitions.unix.DnscacheTest	\
	oval.schemas.definitions.unix.EntityStateCapabilityType	\
	oval.schemas.definitions.unix.EntityStateEncryptMethodType	\
	oval.schemas.definitions.unix.EntityStateEndpointType	\
	oval.schemas.definitions.unix.EntityStateGconfTypeType	\
	oval.schemas.definitions.unix.EntityStateInterfaceType	\
	oval.schemas.definitions.unix.EntityStateRoutingTableFlagsType	\
	oval.schemas.definitions.unix.EntityStateWaitStatusType	\
	oval.schemas.definitions.unix.EntityStateXinetdTypeStatusType	\
	oval.schemas.definitions.unix.FileBehaviors	\
	oval.schemas.definitions.unix.FileextendedattributeObject	\
	oval.schemas.definitions.unix.FileextendedattributeState	\
	oval.schemas.definitions.unix.FileextendedattributeTest	\
	oval.schemas.definitions.unix.FileObject	\
	oval.schemas.definitions.unix.FileState	\
	oval.schemas.definitions.unix.FileTest	\
	oval.schemas.definitions.unix.GconfObject	\
	oval.schemas.definitions.unix.GconfState	\
	oval.schemas.definitions.unix.GconfTest	\
	oval.schemas.definitions.unix.InetdObject	\
	oval.schemas.definitions.unix.InetdState	\
	oval.schemas.definitions.unix.InetdTest	\
	oval.schemas.definitions.unix.InterfaceObject	\
	oval.schemas.definitions.unix.InterfaceState	\
	oval.schemas.definitions.unix.InterfaceTest	\
	oval.schemas.definitions.unix.ObjectFactory	\
	oval.schemas.definitions.unix.package-info	\
	oval.schemas.definitions.unix.PasswordObject	\
	oval.schemas.definitions.unix.PasswordState	\
	oval.schemas.definitions.unix.PasswordTest	\
	oval.schemas.definitions.unix.Process58Object	\
	oval.schemas.definitions.unix.Process58State	\
	oval.schemas.definitions.unix.Process58Test	\
	oval.schemas.definitions.unix.ProcessObject	\
	oval.schemas.definitions.unix.ProcessState	\
	oval.schemas.definitions.unix.ProcessTest	\
	oval.schemas.definitions.unix.RoutingtableObject	\
	oval.schemas.definitions.unix.RoutingtableState	\
	oval.schemas.definitions.unix.RoutingtableTest	\
	oval.schemas.definitions.unix.RunlevelObject	\
	oval.schemas.definitions.unix.RunlevelState	\
	oval.schemas.definitions.unix.RunlevelTest	\
	oval.schemas.definitions.unix.SccsObject	\
	oval.schemas.definitions.unix.SccsState	\
	oval.schemas.definitions.unix.SccsTest	\
	oval.schemas.definitions.unix.ShadowObject	\
	oval.schemas.definitions.unix.ShadowState	\
	oval.schemas.definitions.unix.ShadowTest	\
	oval.schemas.definitions.unix.SysctlObject	\
	oval.schemas.definitions.unix.SysctlState	\
	oval.schemas.definitions.unix.SysctlTest	\
	oval.schemas.definitions.unix.UnameObject	\
	oval.schemas.definitions.unix.UnameState	\
	oval.schemas.definitions.unix.UnameTest	\
	oval.schemas.definitions.unix.XinetdObject	\
	oval.schemas.definitions.unix.XinetdState	\
	oval.schemas.definitions.unix.XinetdTest	\
	oval.schemas.definitions.windows.AccesstokenBehaviors	\
	oval.schemas.definitions.windows.AccesstokenObject	\
	oval.schemas.definitions.windows.AccesstokenState	\
	oval.schemas.definitions.windows.AccesstokenTest	\
	oval.schemas.definitions.windows.Activedirectory57Object	\
	oval.schemas.definitions.windows.Activedirectory57State	\
	oval.schemas.definitions.windows.Activedirectory57Test	\
	oval.schemas.definitions.windows.ActivedirectoryObject	\
	oval.schemas.definitions.windows.ActivedirectoryState	\
	oval.schemas.definitions.windows.ActivedirectoryTest	\
	oval.schemas.definitions.windows.AuditeventpolicyObject	\
	oval.schemas.definitions.windows.AuditeventpolicyState	\
	oval.schemas.definitions.windows.AuditeventpolicysubcategoriesObject	\
	oval.schemas.definitions.windows.AuditeventpolicysubcategoriesState	\
	oval.schemas.definitions.windows.AuditeventpolicysubcategoriesTest	\
	oval.schemas.definitions.windows.AuditeventpolicyTest	\
	oval.schemas.definitions.windows.DnscacheObject	\
	oval.schemas.definitions.windows.DnscacheState	\
	oval.schemas.definitions.windows.DnscacheTest	\
	oval.schemas.definitions.windows.EntityObjectNamingContextType	\
	oval.schemas.definitions.windows.EntityObjectProtocolType	\
	oval.schemas.definitions.windows.EntityObjectRegistryHiveType	\
	oval.schemas.definitions.windows.EntityStateAddrTypeType	\
	oval.schemas.definitions.windows.EntityStateAdstypeType	\
	oval.schemas.definitions.windows.EntityStateAuditType	\
	oval.schemas.definitions.windows.EntityStateDriveTypeType	\
	oval.schemas.definitions.windows.EntityStateFileTypeType	\
	oval.schemas.definitions.windows.EntityStateInterfaceTypeType	\
	oval.schemas.definitions.windows.EntityStateNamingContextType	\
	oval.schemas.definitions.windows.EntityStateProtocolType	\
	oval.schemas.definitions.windows.EntityStateRegistryHiveType	\
	oval.schemas.definitions.windows.EntityStateRegistryTypeType	\
	oval.schemas.definitions.windows.EntityStateServiceControlsAcceptedType	\
	oval.schemas.definitions.windows.EntityStateServiceCurrentStateType	\
	oval.schemas.definitions.windows.EntityStateServiceStartTypeType	\
	oval.schemas.definitions.windows.EntityStateServiceTypeType	\
	oval.schemas.definitions.windows.EntityStateSharedResourceTypeType	\
	oval.schemas.definitions.windows.Fileauditedpermissions53Object	\
	oval.schemas.definitions.windows.Fileauditedpermissions53State	\
	oval.schemas.definitions.windows.Fileauditedpermissions53Test	\
	oval.schemas.definitions.windows.FileauditedpermissionsObject	\
	oval.schemas.definitions.windows.FileauditedpermissionsState	\
	oval.schemas.definitions.windows.FileauditedpermissionsTest	\
	oval.schemas.definitions.windows.FileAuditPermissions53Behaviors	\
	oval.schemas.definitions.windows.FileAuditPermissionsBehaviors	\
	oval.schemas.definitions.windows.FileBehaviors	\
	oval.schemas.definitions.windows.FileEffectiveRights53Behaviors	\
	oval.schemas.definitions.windows.Fileeffectiverights53Object	\
	oval.schemas.definitions.windows.Fileeffectiverights53State	\
	oval.schemas.definitions.windows.Fileeffectiverights53Test	\
	oval.schemas.definitions.windows.FileEffectiveRightsBehaviors	\
	oval.schemas.definitions.windows.FileeffectiverightsObject	\
	oval.schemas.definitions.windows.FileeffectiverightsState	\
	oval.schemas.definitions.windows.FileeffectiverightsTest	\
	oval.schemas.definitions.windows.FileObject	\
	oval.schemas.definitions.windows.FileState	\
	oval.schemas.definitions.windows.FileTest	\
	oval.schemas.definitions.windows.GroupObject	\
	oval.schemas.definitions.windows.GroupSidObject	\
	oval.schemas.definitions.windows.GroupSidState	\
	oval.schemas.definitions.windows.GroupSidTest	\
	oval.schemas.definitions.windows.GroupState	\
	oval.schemas.definitions.windows.GroupTest	\
	oval.schemas.definitions.windows.InterfaceObject	\
	oval.schemas.definitions.windows.InterfaceState	\
	oval.schemas.definitions.windows.InterfaceTest	\
	oval.schemas.definitions.windows.LockoutpolicyObject	\
	oval.schemas.definitions.windows.LockoutpolicyState	\
	oval.schemas.definitions.windows.LockoutpolicyTest	\
	oval.schemas.definitions.windows.MetabaseObject	\
	oval.schemas.definitions.windows.MetabaseState	\
	oval.schemas.definitions.windows.MetabaseTest	\
	oval.schemas.definitions.windows.ObjectFactory	\
	oval.schemas.definitions.windows.package-info	\
	oval.schemas.definitions.windows.PasswordpolicyObject	\
	oval.schemas.definitions.windows.PasswordpolicyState	\
	oval.schemas.definitions.windows.PasswordpolicyTest	\
	oval.schemas.definitions.windows.PortObject	\
	oval.schemas.definitions.windows.PortState	\
	oval.schemas.definitions.windows.PortTest	\
	oval.schemas.definitions.windows.PrinterEffectiveRightsBehaviors	\
	oval.schemas.definitions.windows.PrintereffectiverightsObject	\
	oval.schemas.definitions.windows.PrintereffectiverightsState	\
	oval.schemas.definitions.windows.PrintereffectiverightsTest	\
	oval.schemas.definitions.windows.Process58Object	\
	oval.schemas.definitions.windows.Process58State	\
	oval.schemas.definitions.windows.Process58Test	\
	oval.schemas.definitions.windows.ProcessObject	\
	oval.schemas.definitions.windows.ProcessState	\
	oval.schemas.definitions.windows.ProcessTest	\
	oval.schemas.definitions.windows.RegistryBehaviors	\
	oval.schemas.definitions.windows.RegistryObject	\
	oval.schemas.definitions.windows.RegistryState	\
	oval.schemas.definitions.windows.RegistryTest	\
	oval.schemas.definitions.windows.Regkeyauditedpermissions53Object	\
	oval.schemas.definitions.windows.Regkeyauditedpermissions53State	\
	oval.schemas.definitions.windows.Regkeyauditedpermissions53Test	\
	oval.schemas.definitions.windows.RegkeyauditedpermissionsObject	\
	oval.schemas.definitions.windows.RegkeyauditedpermissionsState	\
	oval.schemas.definitions.windows.RegkeyauditedpermissionsTest	\
	oval.schemas.definitions.windows.RegkeyAuditPermissions53Behaviors	\
	oval.schemas.definitions.windows.RegkeyAuditPermissionsBehaviors	\
	oval.schemas.definitions.windows.RegkeyEffectiveRights53Behaviors	\
	oval.schemas.definitions.windows.Regkeyeffectiverights53Object	\
	oval.schemas.definitions.windows.Regkeyeffectiverights53State	\
	oval.schemas.definitions.windows.Regkeyeffectiverights53Test	\
	oval.schemas.definitions.windows.RegkeyEffectiveRightsBehaviors	\
	oval.schemas.definitions.windows.RegkeyeffectiverightsObject	\
	oval.schemas.definitions.windows.RegkeyeffectiverightsState	\
	oval.schemas.definitions.windows.RegkeyeffectiverightsTest	\
	oval.schemas.definitions.windows.ServiceeffectiverightsObject	\
	oval.schemas.definitions.windows.ServiceeffectiverightsState	\
	oval.schemas.definitions.windows.ServiceeffectiverightsTest	\
	oval.schemas.definitions.windows.ServiceObject	\
	oval.schemas.definitions.windows.ServiceState	\
	oval.schemas.definitions.windows.ServiceTest	\
	oval.schemas.definitions.windows.SharedresourceObject	\
	oval.schemas.definitions.windows.SharedresourceState	\
	oval.schemas.definitions.windows.SharedresourceTest	\
	oval.schemas.definitions.windows.SidBehaviors	\
	oval.schemas.definitions.windows.SidObject	\
	oval.schemas.definitions.windows.SidSidBehaviors	\
	oval.schemas.definitions.windows.SidSidObject	\
	oval.schemas.definitions.windows.SidSidState	\
	oval.schemas.definitions.windows.SidSidTest	\
	oval.schemas.definitions.windows.SidState	\
	oval.schemas.definitions.windows.SidTest	\
	oval.schemas.definitions.windows.UacObject	\
	oval.schemas.definitions.windows.UacState	\
	oval.schemas.definitions.windows.UacTest	\
	oval.schemas.definitions.windows.UserObject	\
	oval.schemas.definitions.windows.UserSid55Object	\
	oval.schemas.definitions.windows.UserSid55State	\
	oval.schemas.definitions.windows.UserSid55Test	\
	oval.schemas.definitions.windows.UserSidObject	\
	oval.schemas.definitions.windows.UserSidState	\
	oval.schemas.definitions.windows.UserSidTest	\
	oval.schemas.definitions.windows.UserState	\
	oval.schemas.definitions.windows.UserTest	\
	oval.schemas.definitions.windows.VolumeObject	\
	oval.schemas.definitions.windows.VolumeState	\
	oval.schemas.definitions.windows.VolumeTest	\
	oval.schemas.definitions.windows.Wmi57Object	\
	oval.schemas.definitions.windows.Wmi57State	\
	oval.schemas.definitions.windows.Wmi57Test	\
	oval.schemas.definitions.windows.WmiObject	\
	oval.schemas.definitions.windows.WmiState	\
	oval.schemas.definitions.windows.WmiTest	\
	oval.schemas.definitions.windows.WuaUpdateSearcherBehaviors	\
	oval.schemas.definitions.windows.WuaupdatesearcherObject	\
	oval.schemas.definitions.windows.WuaupdatesearcherState	\
	oval.schemas.definitions.windows.WuaupdatesearcherTest	\
	oval.schemas.directives.core.ObjectFactory	\
	oval.schemas.directives.core.OvalDirectives	\
	oval.schemas.directives.core.package-info	\
	oval.schemas.evaluation.id.EvaluationDefinitionIds	\
	oval.schemas.evaluation.id.ObjectFactory	\
	oval.schemas.evaluation.id.package-info	\
	oval.schemas.results.core.ClassDirectivesType	\
	oval.schemas.results.core.ContentEnumeration	\
	oval.schemas.results.core.CriteriaType	\
	oval.schemas.results.core.CriterionType	\
	oval.schemas.results.core.DefaultDirectivesType	\
	oval.schemas.results.core.DefinitionsType	\
	oval.schemas.results.core.DefinitionType	\
	oval.schemas.results.core.DirectivesType	\
	oval.schemas.results.core.DirectiveType	\
	oval.schemas.results.core.ExtendDefinitionType	\
	oval.schemas.results.core.ObjectFactory	\
	oval.schemas.results.core.OvalResults	\
	oval.schemas.results.core.package-info	\
	oval.schemas.results.core.ResultEnumeration	\
	oval.schemas.results.core.ResultsType	\
	oval.schemas.results.core.SystemType	\
	oval.schemas.results.core.TestedItemType	\
	oval.schemas.results.core.TestedVariableType	\
	oval.schemas.results.core.TestsType	\
	oval.schemas.results.core.TestType	\
	oval.schemas.systemcharacteristics.core.CollectedObjectsType	\
	oval.schemas.systemcharacteristics.core.EntityItemAnySimpleType	\
	oval.schemas.systemcharacteristics.core.EntityItemBinaryType	\
	oval.schemas.systemcharacteristics.core.EntityItemBoolType	\
	oval.schemas.systemcharacteristics.core.EntityItemComplexBaseType	\
	oval.schemas.systemcharacteristics.core.EntityItemEVRStringType	\
	oval.schemas.systemcharacteristics.core.EntityItemFieldType	\
	oval.schemas.systemcharacteristics.core.EntityItemFilesetRevisionType	\
	oval.schemas.systemcharacteristics.core.EntityItemFloatType	\
	oval.schemas.systemcharacteristics.core.EntityItemIntType	\
	oval.schemas.systemcharacteristics.core.EntityItemIOSVersionType	\
	oval.schemas.systemcharacteristics.core.EntityItemIPAddressStringType	\
	oval.schemas.systemcharacteristics.core.EntityItemIPAddressType	\
	oval.schemas.systemcharacteristics.core.EntityItemRecordType	\
	oval.schemas.systemcharacteristics.core.EntityItemSimpleBaseType	\
	oval.schemas.systemcharacteristics.core.EntityItemStringType	\
	oval.schemas.systemcharacteristics.core.EntityItemVersionType	\
	oval.schemas.systemcharacteristics.core.FlagEnumeration	\
	oval.schemas.systemcharacteristics.core.InterfacesType	\
	oval.schemas.systemcharacteristics.core.InterfaceType	\
	oval.schemas.systemcharacteristics.core.ItemType	\
	oval.schemas.systemcharacteristics.core.ObjectFactory	\
	oval.schemas.systemcharacteristics.core.ObjectType	\
	oval.schemas.systemcharacteristics.core.OvalSystemCharacteristics	\
	oval.schemas.systemcharacteristics.core.package-info	\
	oval.schemas.systemcharacteristics.core.ReferenceType	\
	oval.schemas.systemcharacteristics.core.StatusEnumeration	\
	oval.schemas.systemcharacteristics.core.SystemDataType	\
	oval.schemas.systemcharacteristics.core.SystemInfoType	\
	oval.schemas.systemcharacteristics.core.VariableValueType	\
	oval.schemas.systemcharacteristics.independent.EntityItemEngineType	\
	oval.schemas.systemcharacteristics.independent.EntityItemFamilyType	\
	oval.schemas.systemcharacteristics.independent.EntityItemHashTypeType	\
	oval.schemas.systemcharacteristics.independent.EntityItemLdaptypeType	\
	oval.schemas.systemcharacteristics.independent.EntityItemVariableRefType	\
	oval.schemas.systemcharacteristics.independent.Environmentvariable58Item	\
	oval.schemas.systemcharacteristics.independent.EnvironmentvariableItem	\
	oval.schemas.systemcharacteristics.independent.FamilyItem	\
	oval.schemas.systemcharacteristics.independent.Filehash58Item	\
	oval.schemas.systemcharacteristics.independent.FilehashItem	\
	oval.schemas.systemcharacteristics.independent.Ldap57Item	\
	oval.schemas.systemcharacteristics.independent.LdapItem	\
	oval.schemas.systemcharacteristics.independent.ObjectFactory	\
	oval.schemas.systemcharacteristics.independent.package-info	\
	oval.schemas.systemcharacteristics.independent.Sql57Item	\
	oval.schemas.systemcharacteristics.independent.SqlItem	\
	oval.schemas.systemcharacteristics.independent.TextfilecontentItem	\
	oval.schemas.systemcharacteristics.independent.VariableItem	\
	oval.schemas.systemcharacteristics.independent.XmlfilecontentItem	\
	oval.schemas.systemcharacteristics.linux.DpkginfoItem	\
	oval.schemas.systemcharacteristics.linux.EntityItemFileSystemTypeType	\
	oval.schemas.systemcharacteristics.linux.EntityItemProtocolType	\
	oval.schemas.systemcharacteristics.linux.EntityItemRpmVerifyResultType	\
	oval.schemas.systemcharacteristics.linux.IflistenersItem	\
	oval.schemas.systemcharacteristics.linux.InetlisteningserverItem	\
	oval.schemas.systemcharacteristics.linux.ObjectFactory	\
	oval.schemas.systemcharacteristics.linux.package-info	\
	oval.schemas.systemcharacteristics.linux.PartitionItem	\
	oval.schemas.systemcharacteristics.linux.RpminfoItem	\
	oval.schemas.systemcharacteristics.linux.RpmverifyItem	\
	oval.schemas.systemcharacteristics.linux.SelinuxbooleanItem	\
	oval.schemas.systemcharacteristics.linux.SelinuxsecuritycontextItem	\
	oval.schemas.systemcharacteristics.linux.SlackwarepkginfoItem	\
	oval.schemas.systemcharacteristics.unix.DnscacheItem	\
	oval.schemas.systemcharacteristics.unix.EntityItemCapabilityType	\
	oval.schemas.systemcharacteristics.unix.EntityItemEncryptMethodType	\
	oval.schemas.systemcharacteristics.unix.EntityItemEndpointType	\
	oval.schemas.systemcharacteristics.unix.EntityItemGconfTypeType	\
	oval.schemas.systemcharacteristics.unix.EntityItemInterfaceType	\
	oval.schemas.systemcharacteristics.unix.EntityItemRoutingTableFlagsType	\
	oval.schemas.systemcharacteristics.unix.EntityItemWaitStatusType	\
	oval.schemas.systemcharacteristics.unix.EntityItemXinetdTypeStatusType	\
	oval.schemas.systemcharacteristics.unix.FileextendedattributeItem	\
	oval.schemas.systemcharacteristics.unix.FileItem	\
	oval.schemas.systemcharacteristics.unix.GconfItem	\
	oval.schemas.systemcharacteristics.unix.InetdItem	\
	oval.schemas.systemcharacteristics.unix.InterfaceItem	\
	oval.schemas.systemcharacteristics.unix.ObjectFactory	\
	oval.schemas.systemcharacteristics.unix.package-info	\
	oval.schemas.systemcharacteristics.unix.PasswordItem	\
	oval.schemas.systemcharacteristics.unix.Process58Item	\
	oval.schemas.systemcharacteristics.unix.ProcessItem	\
	oval.schemas.systemcharacteristics.unix.RoutingtableItem	\
	oval.schemas.systemcharacteristics.unix.RunlevelItem	\
	oval.schemas.systemcharacteristics.unix.SccsItem	\
	oval.schemas.systemcharacteristics.unix.ShadowItem	\
	oval.schemas.systemcharacteristics.unix.SysctlItem	\
	oval.schemas.systemcharacteristics.unix.UnameItem	\
	oval.schemas.systemcharacteristics.unix.XinetdItem	\
	oval.schemas.systemcharacteristics.windows.AccesstokenItem	\
	oval.schemas.systemcharacteristics.windows.Activedirectory57Item	\
	oval.schemas.systemcharacteristics.windows.ActivedirectoryItem	\
	oval.schemas.systemcharacteristics.windows.AuditeventpolicyItem	\
	oval.schemas.systemcharacteristics.windows.AuditeventpolicysubcategoriesItem	\
	oval.schemas.systemcharacteristics.windows.DnscacheItem	\
	oval.schemas.systemcharacteristics.windows.EntityItemAddrTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemAdstypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemAuditType	\
	oval.schemas.systemcharacteristics.windows.EntityItemDriveTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemFileTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemInterfaceTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemNamingContextType	\
	oval.schemas.systemcharacteristics.windows.EntityItemProtocolType	\
	oval.schemas.systemcharacteristics.windows.EntityItemRegistryHiveType	\
	oval.schemas.systemcharacteristics.windows.EntityItemRegistryTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemServiceControlsAcceptedType	\
	oval.schemas.systemcharacteristics.windows.EntityItemServiceCurrentStateType	\
	oval.schemas.systemcharacteristics.windows.EntityItemServiceStartTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemServiceTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemSharedResourceTypeType	\
	oval.schemas.systemcharacteristics.windows.FileauditedpermissionsItem	\
	oval.schemas.systemcharacteristics.windows.FileeffectiverightsItem	\
	oval.schemas.systemcharacteristics.windows.FileItem	\
	oval.schemas.systemcharacteristics.windows.GroupItem	\
	oval.schemas.systemcharacteristics.windows.GroupSidItem	\
	oval.schemas.systemcharacteristics.windows.InterfaceItem	\
	oval.schemas.systemcharacteristics.windows.LockoutpolicyItem	\
	oval.schemas.systemcharacteristics.windows.MetabaseItem	\
	oval.schemas.systemcharacteristics.windows.ObjectFactory	\
	oval.schemas.systemcharacteristics.windows.package-info	\
	oval.schemas.systemcharacteristics.windows.PasswordpolicyItem	\
	oval.schemas.systemcharacteristics.windows.PortItem	\
	oval.schemas.systemcharacteristics.windows.PrintereffectiverightsItem	\
	oval.schemas.systemcharacteristics.windows.ProcessItem	\
	oval.schemas.systemcharacteristics.windows.RegistryItem	\
	oval.schemas.systemcharacteristics.windows.RegkeyauditedpermissionsItem	\
	oval.schemas.systemcharacteristics.windows.RegkeyeffectiverightsItem	\
	oval.schemas.systemcharacteristics.windows.ServiceeffectiverightsItem	\
	oval.schemas.systemcharacteristics.windows.ServiceItem	\
	oval.schemas.systemcharacteristics.windows.SharedresourceItem	\
	oval.schemas.systemcharacteristics.windows.SidItem	\
	oval.schemas.systemcharacteristics.windows.SidSidItem	\
	oval.schemas.systemcharacteristics.windows.UacItem	\
	oval.schemas.systemcharacteristics.windows.UserItem	\
	oval.schemas.systemcharacteristics.windows.UserSidItem	\
	oval.schemas.systemcharacteristics.windows.VolumeItem	\
	oval.schemas.systemcharacteristics.windows.Wmi57Item	\
	oval.schemas.systemcharacteristics.windows.WmiItem	\
	oval.schemas.systemcharacteristics.windows.WuaupdatesearcherItem	\
	oval.schemas.variables.core.ObjectFactory	\
	oval.schemas.variables.core.OvalVariables	\
	oval.schemas.variables.core.package-info	\
	oval.schemas.variables.core.VariablesType	\
	oval.schemas.variables.core.VariableType	\
	org.w3c.xml.signature.CanonicalizationMethodType	\
	org.w3c.xml.signature.DigestMethodType	\
	org.w3c.xml.signature.DSAKeyValueType	\
	org.w3c.xml.signature.KeyInfoType	\
	org.w3c.xml.signature.KeyValueType	\
	org.w3c.xml.signature.ManifestType	\
	org.w3c.xml.signature.ObjectFactory	\
	org.w3c.xml.signature.ObjectType	\
	org.w3c.xml.signature.package-info	\
	org.w3c.xml.signature.PGPDataType	\
	org.w3c.xml.signature.ReferenceType	\
	org.w3c.xml.signature.RetrievalMethodType	\
	org.w3c.xml.signature.RSAKeyValueType	\
	org.w3c.xml.signature.SignatureMethodType	\
	org.w3c.xml.signature.SignaturePropertiesType	\
	org.w3c.xml.signature.SignaturePropertyType	\
	org.w3c.xml.signature.SignatureType	\
	org.w3c.xml.signature.SignatureValueType	\
	org.w3c.xml.signature.SignedInfoType	\
	org.w3c.xml.signature.SPKIDataType	\
	org.w3c.xml.signature.TransformsType	\
	org.w3c.xml.signature.TransformType	\
	org.w3c.xml.signature.X509DataType	\
	org.w3c.xml.signature.X509IssuerSerialType
