CLASSES=\
	org.joval.os.unix.macos.DsclTool						\
	org.joval.os.windows.pe.Characteristics						\
	org.joval.os.windows.pe.DLLCharacteristics					\
	org.joval.os.windows.pe.Header							\
	org.joval.os.windows.pe.ImageDataDirectory					\
	org.joval.os.windows.pe.ImageDOSHeader						\
	org.joval.os.windows.pe.ImageFileHeader						\
	org.joval.os.windows.pe.ImageNTHeaders						\
	org.joval.os.windows.pe.ImageOptionalHeader					\
	org.joval.os.windows.pe.ImageOptionalHeader32					\
	org.joval.os.windows.pe.ImageOptionalHeader64					\
	org.joval.os.windows.pe.ImageSectionHeader					\
	org.joval.os.windows.pe.LanguageConstants					\
	org.joval.os.windows.pe.resource.ImageResourceDataEntry				\
	org.joval.os.windows.pe.resource.ImageResourceDirectory				\
	org.joval.os.windows.pe.resource.ImageResourceDirectoryEntry			\
	org.joval.os.windows.pe.resource.Types						\
	org.joval.os.windows.pe.resource.version.StringFileInfo				\
	org.joval.os.windows.pe.resource.version.StringStructure			\
	org.joval.os.windows.pe.resource.version.StringTable				\
	org.joval.os.windows.pe.resource.version.Var					\
	org.joval.os.windows.pe.resource.version.VarFileInfo				\
	org.joval.os.windows.pe.resource.version.VsFixedFileInfo			\
	org.joval.os.windows.pe.resource.version.VsVersionInfo				\
	org.joval.scap.oval.adapter.aix.FilesetAdapter					\
	org.joval.scap.oval.adapter.aix.FixAdapter					\
	org.joval.scap.oval.adapter.aix.OslevelAdapter					\
	org.joval.scap.oval.adapter.cisco.ios.GlobalAdapter				\
	org.joval.scap.oval.adapter.cisco.ios.InterfaceAdapter				\
	org.joval.scap.oval.adapter.cisco.ios.LineAdapter				\
	org.joval.scap.oval.adapter.cisco.ios.SnmpAdapter				\
	org.joval.scap.oval.adapter.cisco.ios.TclshAdapter				\
	org.joval.scap.oval.adapter.cisco.ios.Version55Adapter				\
	org.joval.scap.oval.adapter.cisco.ios.VersionAdapter				\
	org.joval.scap.oval.adapter.independent.BaseFileAdapter				\
	org.joval.scap.oval.adapter.independent.Environmentvariable58Adapter		\
	org.joval.scap.oval.adapter.independent.EnvironmentvariableAdapter		\
	org.joval.scap.oval.adapter.independent.FamilyAdapter				\
	org.joval.scap.oval.adapter.independent.Filehash58Adapter			\
	org.joval.scap.oval.adapter.independent.FilehashAdapter				\
	org.joval.scap.oval.adapter.independent.Textfilecontent54Adapter		\
	org.joval.scap.oval.adapter.independent.TextfilecontentAdapter			\
	org.joval.scap.oval.adapter.independent.XmlfilecontentAdapter			\
	org.joval.scap.oval.adapter.junos.GlobalAdapter					\
	org.joval.scap.oval.adapter.junos.LineAdapter					\
	org.joval.scap.oval.adapter.junos.VersionAdapter				\
	org.joval.scap.oval.adapter.junos.XmlLineAdapter				\
	org.joval.scap.oval.adapter.linux.PartitionAdapter				\
	org.joval.scap.oval.adapter.linux.RpminfoAdapter				\
	org.joval.scap.oval.adapter.linux.SelinuxbooleanAdapter				\
	org.joval.scap.oval.adapter.linux.SelinuxsecuritycontextAdapter			\
	org.joval.scap.oval.adapter.macos.AccountinfoAdapter				\
	org.joval.scap.oval.adapter.macos.PlistAdapter					\
	org.joval.scap.oval.adapter.macos.Pwpolicy59Adapter				\
	org.joval.scap.oval.adapter.netconf.ConfigAdapter				\
	org.joval.scap.oval.adapter.solaris.IsainfoAdapter				\
	org.joval.scap.oval.adapter.solaris.PackageAdapter				\
	org.joval.scap.oval.adapter.solaris.Patch54Adapter				\
	org.joval.scap.oval.adapter.solaris.PatchAdapter				\
	org.joval.scap.oval.adapter.solaris.SmfAdapter					\
	org.joval.scap.oval.adapter.unix.FileAdapter					\
	org.joval.scap.oval.adapter.unix.InetdAdapter					\
	org.joval.scap.oval.adapter.unix.PasswordAdapter				\
	org.joval.scap.oval.adapter.unix.ProcessAdapter					\
	org.joval.scap.oval.adapter.unix.RunlevelAdapter				\
	org.joval.scap.oval.adapter.unix.ShadowAdapter					\
	org.joval.scap.oval.adapter.unix.UnameAdapter					\
	org.joval.scap.oval.adapter.unix.XinetdAdapter					\
	org.joval.scap.oval.adapter.windows.AccesstokenAdapter				\
	org.joval.scap.oval.adapter.windows.AuditeventpolicyAdapter			\
	org.joval.scap.oval.adapter.windows.AuditeventpolicysubcategoriesAdapter	\
	org.joval.scap.oval.adapter.windows.BaseRegkeyAdapter				\
	org.joval.scap.oval.adapter.windows.CmdletAdapter				\
	org.joval.scap.oval.adapter.windows.FileauditedpermissionsAdapter		\
	org.joval.scap.oval.adapter.windows.FileAdapter					\
	org.joval.scap.oval.adapter.windows.FileeffectiverightsAdapter			\
	org.joval.scap.oval.adapter.windows.GroupAdapter				\
	org.joval.scap.oval.adapter.windows.GroupSidAdapter				\
	org.joval.scap.oval.adapter.windows.LicenseAdapter				\
	org.joval.scap.oval.adapter.windows.LockoutpolicyAdapter			\
	org.joval.scap.oval.adapter.windows.PasswordpolicyAdapter			\
	org.joval.scap.oval.adapter.windows.Process58Adapter				\
	org.joval.scap.oval.adapter.windows.RegistryAdapter				\
	org.joval.scap.oval.adapter.windows.RegkeyeffectiverightsAdapter		\
	org.joval.scap.oval.adapter.windows.SidAdapter					\
	org.joval.scap.oval.adapter.windows.SidSidAdapter				\
	org.joval.scap.oval.adapter.windows.UserAdapter					\
	org.joval.scap.oval.adapter.windows.UserSid55Adapter				\
	org.joval.scap.oval.adapter.windows.UserSidAdapter				\
	org.joval.scap.oval.adapter.windows.Wmi57Adapter				\
	org.joval.scap.oval.adapter.windows.WmiAdapter					\
	org.joval.scap.oval.adapter.windows.WuaupdatesearcherAdapter
