CLASSES=\
	org.joval.os.unix.macos.DsclTool					\
	org.joval.os.windows.pe.Characteristics					\
	org.joval.os.windows.pe.DLLCharacteristics				\
	org.joval.os.windows.pe.Header						\
	org.joval.os.windows.pe.ImageDataDirectory				\
	org.joval.os.windows.pe.ImageDOSHeader					\
	org.joval.os.windows.pe.ImageFileHeader					\
	org.joval.os.windows.pe.ImageNTHeaders					\
	org.joval.os.windows.pe.ImageOptionalHeader				\
	org.joval.os.windows.pe.ImageOptionalHeader32				\
	org.joval.os.windows.pe.ImageOptionalHeader64				\
	org.joval.os.windows.pe.ImageSectionHeader				\
	org.joval.os.windows.pe.LanguageConstants				\
	org.joval.os.windows.pe.resource.ImageResourceDataEntry			\
	org.joval.os.windows.pe.resource.ImageResourceDirectory			\
	org.joval.os.windows.pe.resource.ImageResourceDirectoryEntry		\
	org.joval.os.windows.pe.resource.Types					\
	org.joval.os.windows.pe.resource.version.StringFileInfo			\
	org.joval.os.windows.pe.resource.version.StringStructure		\
	org.joval.os.windows.pe.resource.version.StringTable			\
	org.joval.os.windows.pe.resource.version.Var				\
	org.joval.os.windows.pe.resource.version.VarFileInfo			\
	org.joval.os.windows.pe.resource.version.VsFixedFileInfo		\
	org.joval.os.windows.pe.resource.version.VsVersionInfo			\
	org.joval.oval.adapter.aix.FilesetAdapter				\
	org.joval.oval.adapter.aix.FixAdapter					\
	org.joval.oval.adapter.aix.OslevelAdapter				\
	org.joval.oval.adapter.cisco.ios.GlobalAdapter				\
	org.joval.oval.adapter.cisco.ios.InterfaceAdapter			\
	org.joval.oval.adapter.cisco.ios.LineAdapter				\
	org.joval.oval.adapter.cisco.ios.SnmpAdapter				\
	org.joval.oval.adapter.cisco.ios.TclshAdapter				\
	org.joval.oval.adapter.cisco.ios.Version55Adapter			\
	org.joval.oval.adapter.cisco.ios.VersionAdapter				\
	org.joval.oval.adapter.independent.BaseFileAdapter			\
	org.joval.oval.adapter.independent.Environmentvariable58Adapter		\
	org.joval.oval.adapter.independent.EnvironmentvariableAdapter		\
	org.joval.oval.adapter.independent.FamilyAdapter			\
	org.joval.oval.adapter.independent.Filehash58Adapter			\
	org.joval.oval.adapter.independent.FilehashAdapter			\
	org.joval.oval.adapter.independent.Textfilecontent54Adapter		\
	org.joval.oval.adapter.independent.TextfilecontentAdapter		\
	org.joval.oval.adapter.independent.XmlfilecontentAdapter		\
	org.joval.oval.adapter.junos.GlobalAdapter				\
	org.joval.oval.adapter.junos.LineAdapter				\
	org.joval.oval.adapter.junos.VersionAdapter				\
	org.joval.oval.adapter.junos.XmlLineAdapter				\
	org.joval.oval.adapter.linux.RpminfoAdapter				\
	org.joval.oval.adapter.linux.SelinuxbooleanAdapter			\
	org.joval.oval.adapter.linux.SelinuxsecuritycontextAdapter		\
	org.joval.oval.adapter.macos.AccountinfoAdapter				\
	org.joval.oval.adapter.macos.PlistAdapter				\
	org.joval.oval.adapter.macos.Pwpolicy59Adapter				\
	org.joval.oval.adapter.netconf.ConfigAdapter				\
	org.joval.oval.adapter.solaris.IsainfoAdapter				\
	org.joval.oval.adapter.solaris.PackageAdapter				\
	org.joval.oval.adapter.solaris.Patch54Adapter				\
	org.joval.oval.adapter.solaris.PatchAdapter				\
	org.joval.oval.adapter.solaris.SmfAdapter				\
	org.joval.oval.adapter.unix.FileAdapter					\
	org.joval.oval.adapter.unix.PasswordAdapter				\
	org.joval.oval.adapter.unix.ProcessAdapter				\
	org.joval.oval.adapter.unix.RunlevelAdapter				\
	org.joval.oval.adapter.unix.ShadowAdapter				\
	org.joval.oval.adapter.unix.UnameAdapter				\
	org.joval.oval.adapter.windows.AccesstokenAdapter			\
	org.joval.oval.adapter.windows.AuditeventpolicyAdapter			\
	org.joval.oval.adapter.windows.AuditeventpolicysubcategoriesAdapter	\
	org.joval.oval.adapter.windows.CmdletAdapter				\
	org.joval.oval.adapter.windows.FileauditedpermissionsAdapter		\
	org.joval.oval.adapter.windows.FileAdapter				\
	org.joval.oval.adapter.windows.FileeffectiverightsAdapter		\
	org.joval.oval.adapter.windows.GroupAdapter				\
	org.joval.oval.adapter.windows.GroupSidAdapter				\
	org.joval.oval.adapter.windows.LicenseAdapter				\
	org.joval.oval.adapter.windows.LockoutpolicyAdapter			\
	org.joval.oval.adapter.windows.PasswordpolicyAdapter			\
	org.joval.oval.adapter.windows.Process58Adapter				\
	org.joval.oval.adapter.windows.RegistryAdapter				\
	org.joval.oval.adapter.windows.SidAdapter				\
	org.joval.oval.adapter.windows.SidSidAdapter				\
	org.joval.oval.adapter.windows.UserAdapter				\
	org.joval.oval.adapter.windows.UserSid55Adapter				\
	org.joval.oval.adapter.windows.UserSidAdapter				\
	org.joval.oval.adapter.windows.Wmi57Adapter				\
	org.joval.oval.adapter.windows.WmiAdapter				\
	org.joval.oval.adapter.windows.WuaupdatesearcherAdapter
