CLASSES=\
	org.joval.intf.cisco.system.IIosSession				\
	org.joval.intf.cisco.system.ITechSupport			\
	org.joval.intf.io.IFile						\
	org.joval.intf.io.IFileEx					\
	org.joval.intf.io.IFilesystem					\
	org.joval.intf.io.IRandomAccess					\
	org.joval.intf.io.IReader					\
	org.joval.intf.juniper.system.IJunosSession			\
	org.joval.intf.juniper.system.ISupportInformation		\
	org.joval.intf.net.INetconf					\
	org.joval.intf.system.IEnvironment				\
	org.joval.intf.system.ISession					\
	org.joval.intf.unix.io.IUnixFileInfo				\
	org.joval.intf.unix.io.IUnixFilesystem				\
	org.joval.intf.unix.system.IUnixSession				\
	org.joval.intf.util.IPathRedirector				\
	org.joval.intf.windows.identity.IACE				\
	org.joval.intf.windows.identity.IDirectory			\
	org.joval.intf.windows.identity.IGroup				\
	org.joval.intf.windows.identity.IPrincipal			\
	org.joval.intf.windows.identity.IUser				\
	org.joval.intf.windows.io.IWindowsFileInfo			\
	org.joval.intf.windows.io.IWindowsFilesystem			\
	org.joval.intf.windows.registry.IBinaryValue			\
	org.joval.intf.windows.registry.IDwordValue			\
	org.joval.intf.windows.registry.IExpandStringValue		\
	org.joval.intf.windows.registry.IKey				\
	org.joval.intf.windows.registry.ILicenseData			\
	org.joval.intf.windows.registry.IMultiStringValue		\
	org.joval.intf.windows.registry.INoneValue			\
	org.joval.intf.windows.registry.IQwordValue			\
	org.joval.intf.windows.registry.IRegistry			\
	org.joval.intf.windows.registry.IStringValue			\
	org.joval.intf.windows.registry.IValue				\
	org.joval.intf.windows.system.IWindowsSession			\
	org.joval.intf.windows.wmi.ISWbemObject				\
	org.joval.intf.windows.wmi.ISWbemObjectSet			\
	org.joval.intf.windows.wmi.ISWbemProperty			\
	org.joval.intf.windows.wmi.ISWbemPropertySet			\
	org.joval.intf.windows.wmi.IWmiProvider				\
	org.joval.io.LittleEndian					\
	org.joval.io.PerishableReader					\
	org.joval.os.windows.pe.Characteristics				\
	org.joval.os.windows.pe.DLLCharacteristics			\
	org.joval.os.windows.pe.Header					\
	org.joval.os.windows.pe.ImageDataDirectory			\
	org.joval.os.windows.pe.ImageDOSHeader				\
	org.joval.os.windows.pe.ImageFileHeader				\
	org.joval.os.windows.pe.ImageNTHeaders				\
	org.joval.os.windows.pe.ImageOptionalHeader			\
	org.joval.os.windows.pe.ImageOptionalHeader32			\
	org.joval.os.windows.pe.ImageOptionalHeader64			\
	org.joval.os.windows.pe.ImageSectionHeader			\
	org.joval.os.windows.pe.LanguageConstants			\
	org.joval.os.windows.pe.resource.ImageResourceDataEntry		\
	org.joval.os.windows.pe.resource.ImageResourceDirectory		\
	org.joval.os.windows.pe.resource.ImageResourceDirectoryEntry	\
	org.joval.os.windows.pe.resource.Types				\
	org.joval.os.windows.pe.resource.version.StringFileInfo		\
	org.joval.os.windows.pe.resource.version.StringStructure	\
	org.joval.os.windows.pe.resource.version.StringTable		\
	org.joval.os.windows.pe.resource.version.Var			\
	org.joval.os.windows.pe.resource.version.VarFileInfo		\
	org.joval.os.windows.pe.resource.version.VsFixedFileInfo	\
	org.joval.os.windows.pe.resource.version.VsVersionInfo		\
	org.joval.os.windows.wmi.WmiException				\
	org.joval.oval.adapter.aix.FilesetAdapter			\
	org.joval.oval.adapter.aix.FixAdapter				\
	org.joval.oval.adapter.aix.OslevelAdapter			\
	org.joval.oval.adapter.cisco.ios.GlobalAdapter			\
	org.joval.oval.adapter.cisco.ios.InterfaceAdapter		\
	org.joval.oval.adapter.cisco.ios.LineAdapter			\
	org.joval.oval.adapter.cisco.ios.SnmpAdapter			\
	org.joval.oval.adapter.cisco.ios.TclshAdapter			\
	org.joval.oval.adapter.cisco.ios.Version55Adapter		\
	org.joval.oval.adapter.cisco.ios.VersionAdapter			\
	org.joval.oval.adapter.independent.BaseFileAdapter		\
	org.joval.oval.adapter.independent.Environmentvariable58Adapter	\
	org.joval.oval.adapter.independent.EnvironmentvariableAdapter	\
	org.joval.oval.adapter.independent.FamilyAdapter		\
	org.joval.oval.adapter.independent.Textfilecontent54Adapter	\
	org.joval.oval.adapter.independent.TextfilecontentAdapter	\
	org.joval.oval.adapter.independent.VariableAdapter		\
	org.joval.oval.adapter.independent.XmlfilecontentAdapter	\
	org.joval.oval.adapter.linux.RpminfoAdapter			\
	org.joval.oval.adapter.macos.PlistAdapter			\
	org.joval.oval.adapter.solaris.IsainfoAdapter			\
	org.joval.oval.adapter.solaris.PackageAdapter			\
	org.joval.oval.adapter.solaris.Patch54Adapter			\
	org.joval.oval.adapter.solaris.PatchAdapter			\
	org.joval.oval.adapter.solaris.SmfAdapter			\
	org.joval.oval.adapter.unix.FileAdapter				\
	org.joval.oval.adapter.unix.PasswordAdapter			\
	org.joval.oval.adapter.unix.ProcessAdapter			\
	org.joval.oval.adapter.unix.RunlevelAdapter			\
	org.joval.oval.adapter.unix.UnameAdapter			\
	org.joval.oval.adapter.windows.FileAdapter			\
	org.joval.oval.adapter.windows.Fileeffectiverights53Adapter	\
	org.joval.oval.adapter.windows.GroupAdapter			\
	org.joval.oval.adapter.windows.GroupSidAdapter			\
	org.joval.oval.adapter.windows.RegistryAdapter			\
	org.joval.oval.adapter.windows.SidAdapter			\
	org.joval.oval.adapter.windows.SidSidAdapter			\
	org.joval.oval.adapter.windows.UserAdapter			\
	org.joval.oval.adapter.windows.UserSid55Adapter			\
	org.joval.oval.adapter.windows.UserSidAdapter			\
	org.joval.oval.adapter.windows.Wmi57Adapter			\
	org.joval.oval.adapter.windows.WmiAdapter			\
	org.joval.util.AbstractEnvironment				\
	org.joval.util.SafeCLI
