CLASSES=\
	org.gocil.diagnostics.ActionSequenceType	\
	org.gocil.diagnostics.ActionsType	\
	org.gocil.diagnostics.ActionType	\
	org.gocil.diagnostics.ObjectFactory	\
	org.gocil.diagnostics.OcilResultDiagnostics	\
	org.gocil.diagnostics.package-info	\
	org.gocil.diagnostics.QuestionnaireRef	\
	org.gocil.diagnostics.QuestionnaireType	\
	org.gocil.diagnostics.QuestionRef	\
	org.iso.svrl.ActivePattern      \
	org.iso.svrl.DiagnosticReference	\
	org.iso.svrl.FailedAssert       \
	org.iso.svrl.FiredRule  \
	org.iso.svrl.NsPrefixInAttributeValues  \
	org.iso.svrl.ObjectFactory      \
	org.iso.svrl.package-info       \
	org.iso.svrl.SchematronOutput   \
	org.iso.svrl.SuccessfulReport	\
	org.joval.scap.diagnostics.CheckDiagnostics	\
	org.joval.scap.diagnostics.Error	\
	org.joval.scap.diagnostics.ObjectFactory	\
	org.joval.scap.diagnostics.package-info	\
	org.joval.scap.diagnostics.RuleDiagnostics	\
	org.oasis.address.AddressDetails	\
	org.oasis.address.AddressLine	\
	org.oasis.address.AddressLinesType	\
	org.oasis.address.AdministrativeArea	\
	org.oasis.address.BuildingNameType	\
	org.oasis.address.CountryName	\
	org.oasis.address.Department	\
	org.oasis.address.DependentLocalityType	\
	org.oasis.address.FirmType	\
	org.oasis.address.LargeMailUserType	\
	org.oasis.address.Locality	\
	org.oasis.address.MailStopType	\
	org.oasis.address.ObjectFactory	\
	org.oasis.address.package-info	\
	org.oasis.address.PostalCode	\
	org.oasis.address.PostalRouteType	\
	org.oasis.address.PostBox	\
	org.oasis.address.PostOffice	\
	org.oasis.address.Premise	\
	org.oasis.address.PremiseNumber	\
	org.oasis.address.PremiseNumberPrefix	\
	org.oasis.address.PremiseNumberSuffix	\
	org.oasis.address.SubPremiseType	\
	org.oasis.address.Thoroughfare	\
	org.oasis.address.ThoroughfareLeadingTypeType	\
	org.oasis.address.ThoroughfareNameType	\
	org.oasis.address.ThoroughfareNumber	\
	org.oasis.address.ThoroughfareNumberPrefix	\
	org.oasis.address.ThoroughfareNumberSuffix	\
	org.oasis.address.ThoroughfarePostDirectionType	\
	org.oasis.address.ThoroughfarePreDirectionType	\
	org.oasis.address.ThoroughfareTrailingTypeType	\
	org.oasis.address.XAL	\
	org.oasis.catalog.Catalog	\
	org.oasis.catalog.DelegatePublic	\
	org.oasis.catalog.DelegateSystem	\
	org.oasis.catalog.DelegateURI	\
	org.oasis.catalog.Group	\
	org.oasis.catalog.NextCatalog	\
	org.oasis.catalog.ObjectFactory	\
	org.oasis.catalog.package-info	\
	org.oasis.catalog.Public	\
	org.oasis.catalog.RewriteSystem	\
	org.oasis.catalog.RewriteURI	\
	org.oasis.catalog.System	\
	org.oasis.catalog.SystemOrPublic	\
	org.oasis.catalog.Uri	\
	org.oasis.name.Function	\
	org.oasis.name.JointPersonName	\
	org.oasis.name.NameDetails	\
	org.oasis.name.NameDetailsType	\
	org.oasis.name.NameLineType	\
	org.oasis.name.ObjectFactory	\
	org.oasis.name.OrganizationNameDetails	\
	org.oasis.name.OrganizationNameDetailsType	\
	org.oasis.name.package-info	\
	org.oasis.name.PersonName	\
	org.oasis.name.PersonNameType	\
	org.oasis.name.XNL	\
	org.openscap.sce.results.EnvironmentType	\
	org.openscap.sce.results.ObjectFactory	\
	org.openscap.sce.results.package-info	\
	org.openscap.sce.results.SceResultsType	\
	org.openscap.sce.xccdf.LangEnumeration	\
	org.openscap.sce.xccdf.ObjectFactory	\
	org.openscap.sce.xccdf.package-info	\
	org.openscap.sce.xccdf.ScriptDataType	\
	org.purl.dc.ElementType	\
	org.purl.dc.ObjectFactory	\
	org.purl.dc.package-info	\
	org.w3c.xhtml.A	\
	org.w3c.xhtml.Abbr	\
	org.w3c.xhtml.AContent	\
	org.w3c.xhtml.Acronym	\
	org.w3c.xhtml.Address	\
	org.w3c.xhtml.Area	\
	org.w3c.xhtml.B	\
	org.w3c.xhtml.Base	\
	org.w3c.xhtml.Bdo	\
	org.w3c.xhtml.Big	\
	org.w3c.xhtml.Block	\
	org.w3c.xhtml.Blockquote	\
	org.w3c.xhtml.Body	\
	org.w3c.xhtml.Br	\
	org.w3c.xhtml.Button	\
	org.w3c.xhtml.ButtonContent	\
	org.w3c.xhtml.Caption	\
	org.w3c.xhtml.Cite	\
	org.w3c.xhtml.Code	\
	org.w3c.xhtml.Col	\
	org.w3c.xhtml.Colgroup	\
	org.w3c.xhtml.Dd	\
	org.w3c.xhtml.Del	\
	org.w3c.xhtml.Dfn	\
	org.w3c.xhtml.Div	\
	org.w3c.xhtml.Dl	\
	org.w3c.xhtml.Dt	\
	org.w3c.xhtml.Em	\
	org.w3c.xhtml.Fieldset	\
	org.w3c.xhtml.Flow	\
	org.w3c.xhtml.Form	\
	org.w3c.xhtml.FormContent	\
	org.w3c.xhtml.H1	\
	org.w3c.xhtml.H2	\
	org.w3c.xhtml.H3	\
	org.w3c.xhtml.H4	\
	org.w3c.xhtml.H5	\
	org.w3c.xhtml.H6	\
	org.w3c.xhtml.Head	\
	org.w3c.xhtml.Hr	\
	org.w3c.xhtml.Html	\
	org.w3c.xhtml.I	\
	org.w3c.xhtml.Img	\
	org.w3c.xhtml.Inline	\
	org.w3c.xhtml.Input	\
	org.w3c.xhtml.InputType	\
	org.w3c.xhtml.Ins	\
	org.w3c.xhtml.Kbd	\
	org.w3c.xhtml.Label	\
	org.w3c.xhtml.Legend	\
	org.w3c.xhtml.Li	\
	org.w3c.xhtml.Link	\
	org.w3c.xhtml.Map	\
	org.w3c.xhtml.Meta	\
	org.w3c.xhtml.Noscript	\
	org.w3c.xhtml.Object	\
	org.w3c.xhtml.ObjectFactory	\
	org.w3c.xhtml.Ol	\
	org.w3c.xhtml.Optgroup	\
	org.w3c.xhtml.Option	\
	org.w3c.xhtml.P	\
	org.w3c.xhtml.package-info	\
	org.w3c.xhtml.Param	\
	org.w3c.xhtml.Pre	\
	org.w3c.xhtml.PreContent	\
	org.w3c.xhtml.Q	\
	org.w3c.xhtml.Samp	\
	org.w3c.xhtml.Scope	\
	org.w3c.xhtml.Script	\
	org.w3c.xhtml.Select	\
	org.w3c.xhtml.Shape	\
	org.w3c.xhtml.Small	\
	org.w3c.xhtml.Span	\
	org.w3c.xhtml.Strong	\
	org.w3c.xhtml.Style	\
	org.w3c.xhtml.Sub	\
	org.w3c.xhtml.Sup	\
	org.w3c.xhtml.Table	\
	org.w3c.xhtml.Tbody	\
	org.w3c.xhtml.Td	\
	org.w3c.xhtml.Textarea	\
	org.w3c.xhtml.Tfoot	\
	org.w3c.xhtml.TFrame	\
	org.w3c.xhtml.Th	\
	org.w3c.xhtml.Thead	\
	org.w3c.xhtml.Title	\
	org.w3c.xhtml.Tr	\
	org.w3c.xhtml.TRules	\
	org.w3c.xhtml.Tt	\
	org.w3c.xhtml.Ul	\
	org.w3c.xhtml.Var	\
	org.w3c.xml.signature.CanonicalizationMethodType	\
	org.w3c.xml.signature.DigestMethodType	\
	org.w3c.xml.signature.DSAKeyValueType	\
	org.w3c.xml.signature.KeyInfoType	\
	org.w3c.xml.signature.KeyValueType	\
	org.w3c.xml.signature.ManifestType	\
	org.w3c.xml.signature.ObjectFactory	\
	org.w3c.xml.signature.ObjectType	\
	org.w3c.xml.signature.package-info	\
	org.w3c.xml.signature.PGPDataType	\
	org.w3c.xml.signature.ReferenceType	\
	org.w3c.xml.signature.RetrievalMethodType	\
	org.w3c.xml.signature.RSAKeyValueType	\
	org.w3c.xml.signature.SignatureMethodType	\
	org.w3c.xml.signature.SignaturePropertiesType	\
	org.w3c.xml.signature.SignaturePropertyType	\
	org.w3c.xml.signature.SignatureType	\
	org.w3c.xml.signature.SignatureValueType	\
	org.w3c.xml.signature.SignedInfoType	\
	org.w3c.xml.signature.SPKIDataType	\
	org.w3c.xml.signature.TransformsType	\
	org.w3c.xml.signature.TransformType	\
	org.w3c.xml.signature.X509DataType	\
	org.w3c.xml.signature.X509IssuerSerialType	\
	org.w3c.xml.xlink.ActuateType	\
	org.w3c.xml.xlink.ArcType	\
	org.w3c.xml.xlink.Extended	\
	org.w3c.xml.xlink.LocatorType	\
	org.w3c.xml.xlink.ObjectFactory	\
	org.w3c.xml.xlink.package-info	\
	org.w3c.xml.xlink.ResourceType	\
	org.w3c.xml.xlink.ShowType	\
	org.w3c.xml.xlink.Simple	\
	org.w3c.xml.xlink.TitleEltType	\
	org.w3c.xml.xlink.TypeType	\
	scap.ai.AssetIdentificationType	\
	scap.ai.AssetsType	\
	scap.ai.AssetType	\
	scap.ai.CircuitType	\
	scap.ai.ComputingDeviceType	\
	scap.ai.Cpe	\
	scap.ai.DatabaseType	\
	scap.ai.DataType	\
	scap.ai.EmailAddress	\
	scap.ai.Fqdn	\
	scap.ai.IpAddressType	\
	scap.ai.ItAssetType	\
	scap.ai.LocationPoint	\
	scap.ai.LocationRegion	\
	scap.ai.Locations	\
	scap.ai.NetworkInterfaceType	\
	scap.ai.NetworkType	\
	scap.ai.ObjectFactory	\
	scap.ai.OrganizationType	\
	scap.ai.package-info	\
	scap.ai.PersonType	\
	scap.ai.ServiceType	\
	scap.ai.SoftwareType	\
	scap.ai.SyntheticId	\
	scap.ai.SystemType	\
	scap.ai.TelephoneNumber	\
	scap.ai.WebsiteType	\
	scap.ai.WebsiteUrl	\
	scap.arf.core.AssetReportCollection	\
	scap.arf.core.ObjectFactory	\
	scap.arf.core.ObjectRef	\
	scap.arf.core.package-info	\
	scap.arf.core.RemoteResource	\
	scap.arf.core.ReportRequestType	\
	scap.arf.core.ReportType	\
	scap.arf.reporting.ObjectFactory	\
	scap.arf.reporting.package-info	\
	scap.arf.reporting.RelationshipsContainerType	\
	scap.arf.reporting.RelationshipType	\
	scap.constructs.AssetIdentification	\
	scap.constructs.ObjectFactory	\
	scap.constructs.package-info	\
	scap.cpe.dictionary.CheckType	\
	scap.cpe.dictionary.ext.ChangeDescriptionType	\
	scap.cpe.dictionary.ext.ChangeTypeType	\
	scap.cpe.dictionary.ext.DeprecatedInfoType	\
	scap.cpe.dictionary.ext.DeprecationType	\
	scap.cpe.dictionary.ext.DeprecationTypeType	\
	scap.cpe.dictionary.ext.EvidenceReferenceType	\
	scap.cpe.dictionary.ext.EvidenceType	\
	scap.cpe.dictionary.ext.ItemType	\
	scap.cpe.dictionary.ext.ObjectFactory	\
	scap.cpe.dictionary.ext.OrganizationType	\
	scap.cpe.dictionary.ext.package-info	\
	scap.cpe.dictionary.ext.ProvenanceRecordType	\
	scap.cpe.dictionary.GeneratorType	\
	scap.cpe.dictionary.ItemType	\
	scap.cpe.dictionary.ListType	\
	scap.cpe.dictionary.NotesType	\
	scap.cpe.dictionary.ObjectFactory	\
	scap.cpe.dictionary.package-info	\
	scap.cpe.dictionary.ReferencesType	\
	scap.cpe.dictionary.TextType	\
	scap.cpe.language.CheckFactRefType	\
	scap.cpe.language.CPEFactRefType	\
	scap.cpe.language.FactRefType	\
	scap.cpe.language.LogicalTestType	\
	scap.cpe.language.ObjectFactory	\
	scap.cpe.language.OperatorEnumeration	\
	scap.cpe.language.package-info	\
	scap.cpe.language.PlatformBaseType	\
	scap.cpe.language.PlatformSpecificationType	\
	scap.cpe.language.PlatformType	\
	scap.cpe.language.TextType	\
	scap.datastream.Component	\
	scap.datastream.ComponentRef	\
	scap.datastream.ContentSourceType	\
	scap.datastream.DataStream	\
	scap.datastream.DataStreamCollection	\
	scap.datastream.ExtendedComponent	\
	scap.datastream.ObjectFactory	\
	scap.datastream.package-info	\
	scap.datastream.RefListType	\
	scap.datastream.UseCaseType	\
	scap.ocil.core.ArtifactRefsType	\
	scap.ocil.core.ArtifactRefType	\
	scap.ocil.core.ArtifactResultsType	\
	scap.ocil.core.ArtifactResultType	\
	scap.ocil.core.ArtifactsType	\
	scap.ocil.core.ArtifactType	\
	scap.ocil.core.ArtifactValueType	\
	scap.ocil.core.BinaryArtifactValueType	\
	scap.ocil.core.BooleanQuestionModelType	\
	scap.ocil.core.BooleanQuestionResultType	\
	scap.ocil.core.BooleanQuestionTestActionType	\
	scap.ocil.core.BooleanQuestionType	\
	scap.ocil.core.ChoiceAnswerType	\
	scap.ocil.core.ChoiceGroupType	\
	scap.ocil.core.ChoiceQuestionResultType	\
	scap.ocil.core.ChoiceQuestionTestActionType	\
	scap.ocil.core.ChoiceQuestionType	\
	scap.ocil.core.ChoiceTestActionConditionType	\
	scap.ocil.core.ChoiceType	\
	scap.ocil.core.CompoundTestActionType	\
	scap.ocil.core.ConstantVariableType	\
	scap.ocil.core.DocumentType	\
	scap.ocil.core.EmbeddedArtifactValueType	\
	scap.ocil.core.EqualsTestActionConditionType	\
	scap.ocil.core.ExceptionalResultType	\
	scap.ocil.core.ExtensionContainerType	\
	scap.ocil.core.ExternalVariableType	\
	scap.ocil.core.GeneratorType	\
	scap.ocil.core.InstructionsType	\
	scap.ocil.core.ItemBaseType	\
	scap.ocil.core.LocalVariableType	\
	scap.ocil.core.NamedItemBaseType	\
	scap.ocil.core.NumericQuestionResultType	\
	scap.ocil.core.NumericQuestionTestActionType	\
	scap.ocil.core.NumericQuestionType	\
	scap.ocil.core.ObjectFactory	\
	scap.ocil.core.OCILType	\
	scap.ocil.core.OperationType	\
	scap.ocil.core.OperatorType	\
	scap.ocil.core.package-info	\
	scap.ocil.core.PatternTestActionConditionType	\
	scap.ocil.core.PatternType	\
	scap.ocil.core.QuestionnaireResultsType	\
	scap.ocil.core.QuestionnaireResultType	\
	scap.ocil.core.QuestionnairesType	\
	scap.ocil.core.QuestionnaireType	\
	scap.ocil.core.QuestionResultsType	\
	scap.ocil.core.QuestionResultType	\
	scap.ocil.core.QuestionsType	\
	scap.ocil.core.QuestionTestActionType	\
	scap.ocil.core.QuestionTextType	\
	scap.ocil.core.QuestionType	\
	scap.ocil.core.RangeTestActionConditionType	\
	scap.ocil.core.RangeType	\
	scap.ocil.core.RangeValueType	\
	scap.ocil.core.ReferenceArtifactValueType	\
	scap.ocil.core.ReferencesType	\
	scap.ocil.core.ReferenceType	\
	scap.ocil.core.ResultsType	\
	scap.ocil.core.SetExpressionBaseType	\
	scap.ocil.core.SetExpressionBooleanType	\
	scap.ocil.core.SetExpressionChoiceType	\
	scap.ocil.core.SetExpressionPatternType	\
	scap.ocil.core.SetExpressionRangeType	\
	scap.ocil.core.StepType	\
	scap.ocil.core.StringQuestionResultType	\
	scap.ocil.core.StringQuestionTestActionType	\
	scap.ocil.core.StringQuestionType	\
	scap.ocil.core.SubstitutionTextType	\
	scap.ocil.core.SystemTargetType	\
	scap.ocil.core.TargetsType	\
	scap.ocil.core.TestActionConditionType	\
	scap.ocil.core.TestActionRefType	\
	scap.ocil.core.TestActionResultsType	\
	scap.ocil.core.TestActionResultType	\
	scap.ocil.core.TestActionsType	\
	scap.ocil.core.TextArtifactValueType	\
	scap.ocil.core.TextType	\
	scap.ocil.core.UserType	\
	scap.ocil.core.VariableDataType	\
	scap.ocil.core.VariableSetType	\
	scap.ocil.core.VariablesType	\
	scap.ocil.core.VariableType	\
	scap.ocil.variables.ObjectFactory	\
	scap.ocil.variables.OcilVariables	\
	scap.ocil.variables.package-info	\
	scap.ocil.variables.VariablesType	\
	scap.ocil.variables.VariableType	\
	scap.oval.common.CheckEnumeration	\
	scap.oval.common.ClassEnumeration	\
	scap.oval.common.ComplexDatatypeEnumeration	\
	scap.oval.common.DeprecatedInfoType	\
	scap.oval.common.ElementMapItemType	\
	scap.oval.common.ElementMapType	\
	scap.oval.common.ExistenceEnumeration	\
	scap.oval.common.FamilyEnumeration	\
	scap.oval.common.GeneratorType	\
	scap.oval.common.MessageLevelEnumeration	\
	scap.oval.common.MessageType	\
	scap.oval.common.NotesType	\
	scap.oval.common.ObjectFactory	\
	scap.oval.common.OperationEnumeration	\
	scap.oval.common.OperatorEnumeration	\
	scap.oval.common.package-info	\
	scap.oval.common.SchemaVersionType	\
	scap.oval.common.SimpleDatatypeEnumeration	\
	scap.oval.def.aix.EntityStateFilesetStateType	\
	scap.oval.def.aix.EntityStateFixInstallationStatusType	\
	scap.oval.def.aix.EntityStateInterimFixStateType	\
	scap.oval.def.aix.FilesetObject	\
	scap.oval.def.aix.FilesetState	\
	scap.oval.def.aix.FilesetTest	\
	scap.oval.def.aix.FixObject	\
	scap.oval.def.aix.FixState	\
	scap.oval.def.aix.FixTest	\
	scap.oval.def.aix.InterimFixObject	\
	scap.oval.def.aix.InterimFixState	\
	scap.oval.def.aix.InterimFixTest	\
	scap.oval.def.aix.NoObject	\
	scap.oval.def.aix.NoState	\
	scap.oval.def.aix.NoTest	\
	scap.oval.def.aix.ObjectFactory	\
	scap.oval.def.aix.OslevelObject	\
	scap.oval.def.aix.OslevelState	\
	scap.oval.def.aix.OslevelTest	\
	scap.oval.def.aix.package-info	\
	scap.oval.def.android.AppmanagerObject	\
	scap.oval.def.android.AppmanagerState	\
	scap.oval.def.android.AppmanagerTest	\
	scap.oval.def.android.BluetoothObject	\
	scap.oval.def.android.BluetoothState	\
	scap.oval.def.android.BluetoothTest	\
	scap.oval.def.android.CameraObject	\
	scap.oval.def.android.CameraState	\
	scap.oval.def.android.CameraTest	\
	scap.oval.def.android.CertificateObject	\
	scap.oval.def.android.CertificateState	\
	scap.oval.def.android.CertificateTest	\
	scap.oval.def.android.DevicesettingsObject	\
	scap.oval.def.android.DevicesettingsState	\
	scap.oval.def.android.DevicesettingsTest	\
	scap.oval.def.android.EncryptionObject	\
	scap.oval.def.android.EncryptionState	\
	scap.oval.def.android.EncryptionTest	\
	scap.oval.def.android.EntityStateEncryptionStatusType	\
	scap.oval.def.android.EntityStateKeyguardDisabledFeaturesType	\
	scap.oval.def.android.EntityStateNetworkType	\
	scap.oval.def.android.EntityStatePasswordQualityType	\
	scap.oval.def.android.EntityStateWifiAuthAlgorithmType	\
	scap.oval.def.android.EntityStateWifiCurrentStatusType	\
	scap.oval.def.android.EntityStateWifiGroupCipherType	\
	scap.oval.def.android.EntityStateWifiKeyMgmtType	\
	scap.oval.def.android.EntityStateWifiPairwiseCipherType	\
	scap.oval.def.android.EntityStateWifiProtocolType	\
	scap.oval.def.android.LocationserviceObject	\
	scap.oval.def.android.LocationserviceState	\
	scap.oval.def.android.LocationserviceTest	\
	scap.oval.def.android.NetworkObject	\
	scap.oval.def.android.NetworkState	\
	scap.oval.def.android.NetworkTest	\
	scap.oval.def.android.ObjectFactory	\
	scap.oval.def.android.package-info	\
	scap.oval.def.android.PasswordObject	\
	scap.oval.def.android.PasswordState	\
	scap.oval.def.android.PasswordTest	\
	scap.oval.def.android.SystemdetailsObject	\
	scap.oval.def.android.SystemdetailsState	\
	scap.oval.def.android.SystemdetailsTest	\
	scap.oval.def.android.TelephonyObject	\
	scap.oval.def.android.TelephonyState	\
	scap.oval.def.android.TelephonyTest	\
	scap.oval.def.android.WifinetworkObject	\
	scap.oval.def.android.WifinetworkState	\
	scap.oval.def.android.WifinetworkTest	\
	scap.oval.def.android.WifiObject	\
	scap.oval.def.android.WifiState	\
	scap.oval.def.android.WifiTest	\
	scap.oval.def.apache.HttpdObject	\
	scap.oval.def.apache.HttpdState	\
	scap.oval.def.apache.HttpdTest	\
	scap.oval.def.apache.ObjectFactory	\
	scap.oval.def.apache.package-info	\
	scap.oval.def.appleios.GlobalrestrictionsObject	\
	scap.oval.def.appleios.GlobalrestrictionsState	\
	scap.oval.def.appleios.GlobalrestrictionsTest	\
	scap.oval.def.appleios.ObjectFactory	\
	scap.oval.def.appleios.package-info	\
	scap.oval.def.appleios.PasscodepolicyObject	\
	scap.oval.def.appleios.PasscodepolicyState	\
	scap.oval.def.appleios.PasscodepolicyTest	\
	scap.oval.def.appleios.ProfileObject	\
	scap.oval.def.appleios.ProfileState	\
	scap.oval.def.appleios.ProfileTest	\
	scap.oval.def.asa.AclObject	\
	scap.oval.def.asa.AclState	\
	scap.oval.def.asa.AclTest	\
	scap.oval.def.asa.ClassMapObject	\
	scap.oval.def.asa.ClassMapState	\
	scap.oval.def.asa.ClassMapTest	\
	scap.oval.def.asa.EntityObjectAccessListIPVersionType	\
	scap.oval.def.asa.EntityStateAccessListInterfaceDirectionType	\
	scap.oval.def.asa.EntityStateAccessListIPVersionType	\
	scap.oval.def.asa.EntityStateAccessListUseType	\
	scap.oval.def.asa.EntityStateApplyServicePolicyType	\
	scap.oval.def.asa.EntityStateClassMapType	\
	scap.oval.def.asa.EntityStateInspectionType	\
	scap.oval.def.asa.EntityStateMatchType	\
	scap.oval.def.asa.EntityStateSNMPAuthStringType	\
	scap.oval.def.asa.EntityStateSNMPPrivStringType	\
	scap.oval.def.asa.EntityStateSNMPSecLevelStringType	\
	scap.oval.def.asa.EntityStateSNMPVersionStringType	\
	scap.oval.def.asa.InterfaceObject	\
	scap.oval.def.asa.InterfaceState	\
	scap.oval.def.asa.InterfaceTest	\
	scap.oval.def.asa.LineObject	\
	scap.oval.def.asa.LineState	\
	scap.oval.def.asa.LineTest	\
	scap.oval.def.asa.ObjectFactory	\
	scap.oval.def.asa.package-info	\
	scap.oval.def.asa.PolicyMapObject	\
	scap.oval.def.asa.PolicyMapState	\
	scap.oval.def.asa.PolicyMapTest	\
	scap.oval.def.asa.ServicePolicyObject	\
	scap.oval.def.asa.ServicePolicyState	\
	scap.oval.def.asa.ServicePolicyTest	\
	scap.oval.def.asa.SnmpGroupObject	\
	scap.oval.def.asa.SnmpGroupState	\
	scap.oval.def.asa.SnmpGroupTest	\
	scap.oval.def.asa.SnmpHostObject	\
	scap.oval.def.asa.SnmpHostState	\
	scap.oval.def.asa.SnmpHostTest	\
	scap.oval.def.asa.SnmpUserObject	\
	scap.oval.def.asa.SnmpUserState	\
	scap.oval.def.asa.SnmpUserTest	\
	scap.oval.def.asa.TcpMapObject	\
	scap.oval.def.asa.TcpMapState	\
	scap.oval.def.asa.TcpMapTest	\
	scap.oval.def.asa.VersionObject	\
	scap.oval.def.asa.VersionState	\
	scap.oval.def.asa.VersionTest	\
	scap.oval.def.catos.LineObject	\
	scap.oval.def.catos.LineState	\
	scap.oval.def.catos.LineTest	\
	scap.oval.def.catos.ModuleObject	\
	scap.oval.def.catos.ModuleState	\
	scap.oval.def.catos.ModuleTest	\
	scap.oval.def.catos.ObjectFactory	\
	scap.oval.def.catos.package-info	\
	scap.oval.def.catos.Version55Object	\
	scap.oval.def.catos.Version55State	\
	scap.oval.def.catos.Version55Test	\
	scap.oval.def.catos.VersionObject	\
	scap.oval.def.catos.VersionState	\
	scap.oval.def.catos.VersionTest	\
	scap.oval.def.core.AffectedCPEListType	\
	scap.oval.def.core.AffectedType	\
	scap.oval.def.core.ArithmeticEnumeration	\
	scap.oval.def.core.ArithmeticFunctionType	\
	scap.oval.def.core.BeginFunctionType	\
	scap.oval.def.core.ConcatFunctionType	\
	scap.oval.def.core.ConstantVariable	\
	scap.oval.def.core.CountFunctionType	\
	scap.oval.def.core.CriteriaType	\
	scap.oval.def.core.CriterionType	\
	scap.oval.def.core.DateTimeFormatEnumeration	\
	scap.oval.def.core.DefinitionsType	\
	scap.oval.def.core.DefinitionType	\
	scap.oval.def.core.EndFunctionType	\
	scap.oval.def.core.EntityComplexBaseType	\
	scap.oval.def.core.EntityObjectAnySimpleType	\
	scap.oval.def.core.EntityObjectBinaryType	\
	scap.oval.def.core.EntityObjectBoolType	\
	scap.oval.def.core.EntityObjectFieldType	\
	scap.oval.def.core.EntityObjectFloatType	\
	scap.oval.def.core.EntityObjectIntType	\
	scap.oval.def.core.EntityObjectIPAddressStringType	\
	scap.oval.def.core.EntityObjectIPAddressType	\
	scap.oval.def.core.EntityObjectRecordType	\
	scap.oval.def.core.EntityObjectStringType	\
	scap.oval.def.core.EntityObjectVersionType	\
	scap.oval.def.core.EntitySimpleBaseType	\
	scap.oval.def.core.EntityStateAnySimpleType	\
	scap.oval.def.core.EntityStateBinaryType	\
	scap.oval.def.core.EntityStateBoolType	\
	scap.oval.def.core.EntityStateComplexBaseType	\
	scap.oval.def.core.EntityStateDebianEVRStringType	\
	scap.oval.def.core.EntityStateEVRStringType	\
	scap.oval.def.core.EntityStateFieldType	\
	scap.oval.def.core.EntityStateFileSetRevisionType	\
	scap.oval.def.core.EntityStateFloatType	\
	scap.oval.def.core.EntityStateIntType	\
	scap.oval.def.core.EntityStateIOSVersionType	\
	scap.oval.def.core.EntityStateIPAddressStringType	\
	scap.oval.def.core.EntityStateIPAddressType	\
	scap.oval.def.core.EntityStateRecordType	\
	scap.oval.def.core.EntityStateSimpleBaseType	\
	scap.oval.def.core.EntityStateStringType	\
	scap.oval.def.core.EntityStateVersionType	\
	scap.oval.def.core.EscapeRegexFunctionType	\
	scap.oval.def.core.ExpectedResults	\
	scap.oval.def.core.ExpectedResultType	\
	scap.oval.def.core.ExtendDefinitionType	\
	scap.oval.def.core.ExternalVariable	\
	scap.oval.def.core.Filter	\
	scap.oval.def.core.FilterActionEnumeration	\
	scap.oval.def.core.GlobToRegexFunctionType	\
	scap.oval.def.core.LiteralComponentType	\
	scap.oval.def.core.LocalVariable	\
	scap.oval.def.core.MetadataContributorType	\
	scap.oval.def.core.MetadataDatesType	\
	scap.oval.def.core.MetadataStatusEnumeration	\
	scap.oval.def.core.MetadataType	\
	scap.oval.def.core.Notes	\
	scap.oval.def.core.ObjectComponentType	\
	scap.oval.def.core.ObjectFactory	\
	scap.oval.def.core.ObjectRefType	\
	scap.oval.def.core.ObjectsType	\
	scap.oval.def.core.ObjectType	\
	scap.oval.def.core.OvalDefinitions	\
	scap.oval.def.core.OvalRepository	\
	scap.oval.def.core.package-info	\
	scap.oval.def.core.PossibleRestrictionType	\
	scap.oval.def.core.PossibleValueType	\
	scap.oval.def.core.ReferenceType	\
	scap.oval.def.core.RegexCaptureFunctionType	\
	scap.oval.def.core.RestrictionType	\
	scap.oval.def.core.Set	\
	scap.oval.def.core.SetOperatorEnumeration	\
	scap.oval.def.core.SplitFunctionType	\
	scap.oval.def.core.StateRefType	\
	scap.oval.def.core.StatesType	\
	scap.oval.def.core.StateType	\
	scap.oval.def.core.SubstringFunctionType	\
	scap.oval.def.core.TestsType	\
	scap.oval.def.core.TestType	\
	scap.oval.def.core.TimeDifferenceFunctionType	\
	scap.oval.def.core.UniqueFunctionType	\
	scap.oval.def.core.ValueType	\
	scap.oval.def.core.VariableComponentType	\
	scap.oval.def.core.VariablesType	\
	scap.oval.def.core.VariableType	\
	scap.oval.def.esx.EntityStateClassificationType	\
	scap.oval.def.esx.EntityStateSupportLevelType	\
	scap.oval.def.esx.ObjectFactory	\
	scap.oval.def.esx.package-info	\
	scap.oval.def.esx.Patch56Behaviors	\
	scap.oval.def.esx.Patch56Object	\
	scap.oval.def.esx.Patch56State	\
	scap.oval.def.esx.Patch56Test	\
	scap.oval.def.esx.PatchBehaviors	\
	scap.oval.def.esx.PatchObject	\
	scap.oval.def.esx.PatchState	\
	scap.oval.def.esx.PatchTest	\
	scap.oval.def.esx.VersionObject	\
	scap.oval.def.esx.VersionState	\
	scap.oval.def.esx.VersionTest	\
	scap.oval.def.esx.ViSdkManagedEntityBehaviors	\
	scap.oval.def.esx.VisdkmanagedobjectObject	\
	scap.oval.def.esx.VisdkmanagedobjectState	\
	scap.oval.def.esx.VisdkmanagedobjectTest	\
	scap.oval.def.freebsd.ObjectFactory	\
	scap.oval.def.freebsd.package-info	\
	scap.oval.def.freebsd.PortinfoObject	\
	scap.oval.def.freebsd.PortinfoState	\
	scap.oval.def.freebsd.PortinfoTest	\
	scap.oval.def.hpux.GetconfObject	\
	scap.oval.def.hpux.GetconfState	\
	scap.oval.def.hpux.GetconfTest	\
	scap.oval.def.hpux.NddObject	\
	scap.oval.def.hpux.NddState	\
	scap.oval.def.hpux.NddTest	\
	scap.oval.def.hpux.ObjectFactory	\
	scap.oval.def.hpux.package-info	\
	scap.oval.def.hpux.Patch53Behaviors	\
	scap.oval.def.hpux.Patch53Object	\
	scap.oval.def.hpux.Patch53State	\
	scap.oval.def.hpux.Patch53Test	\
	scap.oval.def.hpux.PatchObject	\
	scap.oval.def.hpux.PatchState	\
	scap.oval.def.hpux.PatchTest	\
	scap.oval.def.hpux.SwlistObject	\
	scap.oval.def.hpux.SwlistState	\
	scap.oval.def.hpux.SwlistTest	\
	scap.oval.def.hpux.TrustedObject	\
	scap.oval.def.hpux.TrustedState	\
	scap.oval.def.hpux.TrustedTest	\
	scap.oval.def.independent.EntityObjectEngineType	\
	scap.oval.def.independent.EntityObjectHashTypeType	\
	scap.oval.def.independent.EntityObjectVariableRefType	\
	scap.oval.def.independent.EntityStateEngineType	\
	scap.oval.def.independent.EntityStateFamilyType	\
	scap.oval.def.independent.EntityStateHashTypeType	\
	scap.oval.def.independent.EntityStateLdaptypeType	\
	scap.oval.def.independent.EntityStateVariableRefType	\
	scap.oval.def.independent.EntityStateWindowsViewType	\
	scap.oval.def.independent.Environmentvariable58Object	\
	scap.oval.def.independent.Environmentvariable58State	\
	scap.oval.def.independent.Environmentvariable58Test	\
	scap.oval.def.independent.EnvironmentvariableObject	\
	scap.oval.def.independent.EnvironmentvariableState	\
	scap.oval.def.independent.EnvironmentvariableTest	\
	scap.oval.def.independent.FamilyObject	\
	scap.oval.def.independent.FamilyState	\
	scap.oval.def.independent.FamilyTest	\
	scap.oval.def.independent.FileBehaviors	\
	scap.oval.def.independent.Filehash58Object	\
	scap.oval.def.independent.Filehash58State	\
	scap.oval.def.independent.Filehash58Test	\
	scap.oval.def.independent.FilehashObject	\
	scap.oval.def.independent.FilehashState	\
	scap.oval.def.independent.FilehashTest	\
	scap.oval.def.independent.Ldap57Object	\
	scap.oval.def.independent.Ldap57State	\
	scap.oval.def.independent.Ldap57Test	\
	scap.oval.def.independent.LdapBehaviors	\
	scap.oval.def.independent.LdapObject	\
	scap.oval.def.independent.LdapState	\
	scap.oval.def.independent.LdapTest	\
	scap.oval.def.independent.ObjectFactory	\
	scap.oval.def.independent.package-info	\
	scap.oval.def.independent.Sql57Object	\
	scap.oval.def.independent.Sql57State	\
	scap.oval.def.independent.Sql57Test	\
	scap.oval.def.independent.SqlObject	\
	scap.oval.def.independent.SqlState	\
	scap.oval.def.independent.SqlTest	\
	scap.oval.def.independent.Textfilecontent54Behaviors	\
	scap.oval.def.independent.Textfilecontent54Object	\
	scap.oval.def.independent.Textfilecontent54State	\
	scap.oval.def.independent.Textfilecontent54Test	\
	scap.oval.def.independent.TextfilecontentObject	\
	scap.oval.def.independent.TextfilecontentState	\
	scap.oval.def.independent.TextfilecontentTest	\
	scap.oval.def.independent.UnknownTest	\
	scap.oval.def.independent.VariableObject	\
	scap.oval.def.independent.VariableState	\
	scap.oval.def.independent.VariableTest	\
	scap.oval.def.independent.XmlfilecontentObject	\
	scap.oval.def.independent.XmlfilecontentState	\
	scap.oval.def.independent.XmlfilecontentTest	\
	scap.oval.def.ios.AclObject	\
	scap.oval.def.ios.AclState	\
	scap.oval.def.ios.AclTest	\
	scap.oval.def.ios.BgpneighborObject	\
	scap.oval.def.ios.BgpneighborState	\
	scap.oval.def.ios.BgpneighborTest	\
	scap.oval.def.ios.EntityObjectAccessListIPVersionType	\
	scap.oval.def.ios.EntityObjectRoutingProtocolType	\
	scap.oval.def.ios.EntityStateAccessListInterfaceDirectionType	\
	scap.oval.def.ios.EntityStateAccessListIPVersionType	\
	scap.oval.def.ios.EntityStateAccessListUseType	\
	scap.oval.def.ios.EntityStateRoutingAuthTypeStringType	\
	scap.oval.def.ios.EntityStateRoutingProtocolType	\
	scap.oval.def.ios.EntityStateSNMPAuthStringType	\
	scap.oval.def.ios.EntityStateSNMPModeStringType	\
	scap.oval.def.ios.EntityStateSNMPPrivStringType	\
	scap.oval.def.ios.EntityStateSNMPSecLevelStringType	\
	scap.oval.def.ios.EntityStateSNMPVersionStringType	\
	scap.oval.def.ios.EntityStateSwitchportModeType	\
	scap.oval.def.ios.EntityStateTrainIdentifierType	\
	scap.oval.def.ios.EntityStateTrunkEncapType	\
	scap.oval.def.ios.GlobalObject	\
	scap.oval.def.ios.GlobalState	\
	scap.oval.def.ios.GlobalTest	\
	scap.oval.def.ios.InterfaceObject	\
	scap.oval.def.ios.InterfaceState	\
	scap.oval.def.ios.InterfaceTest	\
	scap.oval.def.ios.LineObject	\
	scap.oval.def.ios.LineState	\
	scap.oval.def.ios.LineTest	\
	scap.oval.def.ios.ObjectFactory	\
	scap.oval.def.ios.package-info	\
	scap.oval.def.ios.RouterObject	\
	scap.oval.def.ios.RouterState	\
	scap.oval.def.ios.RouterTest	\
	scap.oval.def.ios.RoutingprotocolauthintfObject	\
	scap.oval.def.ios.RoutingprotocolauthintfState	\
	scap.oval.def.ios.RoutingprotocolauthintfTest	\
	scap.oval.def.ios.SectionObject	\
	scap.oval.def.ios.SectionState	\
	scap.oval.def.ios.SectionTest	\
	scap.oval.def.ios.SnmpcommunityObject	\
	scap.oval.def.ios.SnmpcommunityState	\
	scap.oval.def.ios.SnmpcommunityTest	\
	scap.oval.def.ios.SnmpgroupObject	\
	scap.oval.def.ios.SnmpgroupState	\
	scap.oval.def.ios.SnmpgroupTest	\
	scap.oval.def.ios.SnmphostObject	\
	scap.oval.def.ios.SnmphostState	\
	scap.oval.def.ios.SnmphostTest	\
	scap.oval.def.ios.SnmpObject	\
	scap.oval.def.ios.SnmpState	\
	scap.oval.def.ios.SnmpTest	\
	scap.oval.def.ios.SnmpuserObject	\
	scap.oval.def.ios.SnmpuserState	\
	scap.oval.def.ios.SnmpuserTest	\
	scap.oval.def.ios.SnmpviewObject	\
	scap.oval.def.ios.SnmpviewState	\
	scap.oval.def.ios.SnmpviewTest	\
	scap.oval.def.ios.TclshObject	\
	scap.oval.def.ios.TclshState	\
	scap.oval.def.ios.TclshTest	\
	scap.oval.def.ios.Version55Object	\
	scap.oval.def.ios.Version55State	\
	scap.oval.def.ios.Version55Test	\
	scap.oval.def.ios.VersionObject	\
	scap.oval.def.ios.VersionState	\
	scap.oval.def.ios.VersionTest	\
	scap.oval.def.iosxe.AclObject	\
	scap.oval.def.iosxe.AclState	\
	scap.oval.def.iosxe.AclTest	\
	scap.oval.def.iosxe.BgpneighborObject	\
	scap.oval.def.iosxe.BgpneighborState	\
	scap.oval.def.iosxe.BgpneighborTest	\
	scap.oval.def.iosxe.EntityObjectAccessListIPVersionType	\
	scap.oval.def.iosxe.EntityObjectRoutingProtocolType	\
	scap.oval.def.iosxe.EntityStateAccessListInterfaceDirectionType	\
	scap.oval.def.iosxe.EntityStateAccessListIPVersionType	\
	scap.oval.def.iosxe.EntityStateAccessListUseType	\
	scap.oval.def.iosxe.EntityStateRoutingAuthTypeStringType	\
	scap.oval.def.iosxe.EntityStateRoutingProtocolType	\
	scap.oval.def.iosxe.EntityStateSNMPAuthStringType	\
	scap.oval.def.iosxe.EntityStateSNMPModeStringType	\
	scap.oval.def.iosxe.EntityStateSNMPPrivStringType	\
	scap.oval.def.iosxe.EntityStateSNMPSecLevelStringType	\
	scap.oval.def.iosxe.EntityStateSNMPVersionStringType	\
	scap.oval.def.iosxe.EntityStateSwitchportModeType	\
	scap.oval.def.iosxe.EntityStateTrunkEncapType	\
	scap.oval.def.iosxe.GlobalObject	\
	scap.oval.def.iosxe.GlobalState	\
	scap.oval.def.iosxe.GlobalTest	\
	scap.oval.def.iosxe.InterfaceObject	\
	scap.oval.def.iosxe.InterfaceState	\
	scap.oval.def.iosxe.InterfaceTest	\
	scap.oval.def.iosxe.LineObject	\
	scap.oval.def.iosxe.LineState	\
	scap.oval.def.iosxe.LineTest	\
	scap.oval.def.iosxe.ObjectFactory	\
	scap.oval.def.iosxe.package-info	\
	scap.oval.def.iosxe.RouterObject	\
	scap.oval.def.iosxe.RouterState	\
	scap.oval.def.iosxe.RouterTest	\
	scap.oval.def.iosxe.RoutingprotocolauthintfObject	\
	scap.oval.def.iosxe.RoutingprotocolauthintfState	\
	scap.oval.def.iosxe.RoutingprotocolauthintfTest	\
	scap.oval.def.iosxe.SectionObject	\
	scap.oval.def.iosxe.SectionState	\
	scap.oval.def.iosxe.SectionTest	\
	scap.oval.def.iosxe.SnmpcommunityObject	\
	scap.oval.def.iosxe.SnmpcommunityState	\
	scap.oval.def.iosxe.SnmpcommunityTest	\
	scap.oval.def.iosxe.SnmpgroupObject	\
	scap.oval.def.iosxe.SnmpgroupState	\
	scap.oval.def.iosxe.SnmpgroupTest	\
	scap.oval.def.iosxe.SnmphostObject	\
	scap.oval.def.iosxe.SnmphostState	\
	scap.oval.def.iosxe.SnmphostTest	\
	scap.oval.def.iosxe.SnmpuserObject	\
	scap.oval.def.iosxe.SnmpuserState	\
	scap.oval.def.iosxe.SnmpuserTest	\
	scap.oval.def.iosxe.SnmpviewObject	\
	scap.oval.def.iosxe.SnmpviewState	\
	scap.oval.def.iosxe.SnmpviewTest	\
	scap.oval.def.iosxe.VersionObject	\
	scap.oval.def.iosxe.VersionState	\
	scap.oval.def.iosxe.VersionTest	\
	scap.oval.def.junos.EntityStateJunosReleaseTypeType	\
	scap.oval.def.junos.ObjectFactory	\
	scap.oval.def.junos.package-info	\
	scap.oval.def.junos.ShowObject	\
	scap.oval.def.junos.ShowState	\
	scap.oval.def.junos.ShowTest	\
	scap.oval.def.junos.VersionObject	\
	scap.oval.def.junos.VersionState	\
	scap.oval.def.junos.VersionTest	\
	scap.oval.def.junos.XmlConfigObject	\
	scap.oval.def.junos.XmlConfigState	\
	scap.oval.def.junos.XmlConfigTest	\
	scap.oval.def.junos.XmlShowObject	\
	scap.oval.def.junos.XmlShowState	\
	scap.oval.def.junos.XmlShowTest	\
	scap.oval.def.linux.ApparmorstatusObject	\
	scap.oval.def.linux.ApparmorstatusState	\
	scap.oval.def.linux.ApparmorstatusTest	\
	scap.oval.def.linux.DpkginfoObject	\
	scap.oval.def.linux.DpkginfoState	\
	scap.oval.def.linux.DpkginfoTest	\
	scap.oval.def.linux.EntityStateProtocolType	\
	scap.oval.def.linux.EntityStateRpmVerifyResultType	\
	scap.oval.def.linux.FileBehaviors	\
	scap.oval.def.linux.IflistenersObject	\
	scap.oval.def.linux.IflistenersState	\
	scap.oval.def.linux.IflistenersTest	\
	scap.oval.def.linux.InetlisteningserversObject	\
	scap.oval.def.linux.InetlisteningserversState	\
	scap.oval.def.linux.InetlisteningserversTest	\
	scap.oval.def.linux.ObjectFactory	\
	scap.oval.def.linux.package-info	\
	scap.oval.def.linux.PartitionObject	\
	scap.oval.def.linux.PartitionState	\
	scap.oval.def.linux.PartitionTest	\
	scap.oval.def.linux.RpmInfoBehaviors	\
	scap.oval.def.linux.RpminfoObject	\
	scap.oval.def.linux.RpminfoState	\
	scap.oval.def.linux.RpminfoTest	\
	scap.oval.def.linux.RpmVerifyBehaviors	\
	scap.oval.def.linux.RpmVerifyFileBehaviors	\
	scap.oval.def.linux.RpmverifyfileObject	\
	scap.oval.def.linux.RpmverifyfileState	\
	scap.oval.def.linux.RpmverifyfileTest	\
	scap.oval.def.linux.RpmverifyObject	\
	scap.oval.def.linux.RpmVerifyPackageBehaviors	\
	scap.oval.def.linux.RpmverifypackageObject	\
	scap.oval.def.linux.RpmverifypackageState	\
	scap.oval.def.linux.RpmverifypackageTest	\
	scap.oval.def.linux.RpmverifyState	\
	scap.oval.def.linux.RpmverifyTest	\
	scap.oval.def.linux.SelinuxbooleanObject	\
	scap.oval.def.linux.SelinuxbooleanState	\
	scap.oval.def.linux.SelinuxbooleanTest	\
	scap.oval.def.linux.SelinuxsecuritycontextObject	\
	scap.oval.def.linux.SelinuxsecuritycontextState	\
	scap.oval.def.linux.SelinuxsecuritycontextTest	\
	scap.oval.def.linux.SlackwarepkginfoObject	\
	scap.oval.def.linux.SlackwarepkginfoState	\
	scap.oval.def.linux.SlackwarepkginfoTest	\
	scap.oval.def.linux.SystemdunitdependencyObject	\
	scap.oval.def.linux.SystemdunitdependencyState	\
	scap.oval.def.linux.SystemdunitdependencyTest	\
	scap.oval.def.linux.SystemdunitpropertyObject	\
	scap.oval.def.linux.SystemdunitpropertyState	\
	scap.oval.def.linux.SystemdunitpropertyTest	\
	scap.oval.def.macos.AccountinfoObject	\
	scap.oval.def.macos.AccountinfoState	\
	scap.oval.def.macos.AccountinfoTest	\
	scap.oval.def.macos.AuthorizationdbObject	\
	scap.oval.def.macos.AuthorizationdbState	\
	scap.oval.def.macos.AuthorizationdbTest	\
	scap.oval.def.macos.CorestorageObject	\
	scap.oval.def.macos.CorestorageState	\
	scap.oval.def.macos.CorestorageTest	\
	scap.oval.def.macos.DiskutilObject	\
	scap.oval.def.macos.DiskutilState	\
	scap.oval.def.macos.DiskutilTest	\
	scap.oval.def.macos.EntityObjectDataTypeType	\
	scap.oval.def.macos.EntityStateDataTypeType	\
	scap.oval.def.macos.EntityStatePermissionCompareType	\
	scap.oval.def.macos.EntityStatePlistTypeType	\
	scap.oval.def.macos.GatekeeperObject	\
	scap.oval.def.macos.GatekeeperState	\
	scap.oval.def.macos.GatekeeperTest	\
	scap.oval.def.macos.Inetlisteningserver510Object	\
	scap.oval.def.macos.Inetlisteningserver510State	\
	scap.oval.def.macos.Inetlisteningserver510Test	\
	scap.oval.def.macos.InetlisteningserversObject	\
	scap.oval.def.macos.InetlisteningserversState	\
	scap.oval.def.macos.InetlisteningserversTest	\
	scap.oval.def.macos.KeychainObject	\
	scap.oval.def.macos.KeychainState	\
	scap.oval.def.macos.KeychainTest	\
	scap.oval.def.macos.LaunchdObject	\
	scap.oval.def.macos.LaunchdState	\
	scap.oval.def.macos.LaunchdTest	\
	scap.oval.def.macos.NvramObject	\
	scap.oval.def.macos.NvramState	\
	scap.oval.def.macos.NvramTest	\
	scap.oval.def.macos.ObjectFactory	\
	scap.oval.def.macos.package-info	\
	scap.oval.def.macos.Plist510Object	\
	scap.oval.def.macos.Plist510State	\
	scap.oval.def.macos.Plist510Test	\
	scap.oval.def.macos.Plist511Object	\
	scap.oval.def.macos.Plist511State	\
	scap.oval.def.macos.Plist511Test	\
	scap.oval.def.macos.PlistObject	\
	scap.oval.def.macos.PlistState	\
	scap.oval.def.macos.PlistTest	\
	scap.oval.def.macos.Pwpolicy59Object	\
	scap.oval.def.macos.Pwpolicy59State	\
	scap.oval.def.macos.Pwpolicy59Test	\
	scap.oval.def.macos.PwpolicyObject	\
	scap.oval.def.macos.PwpolicyState	\
	scap.oval.def.macos.PwpolicyTest	\
	scap.oval.def.macos.RlimitObject	\
	scap.oval.def.macos.RlimitState	\
	scap.oval.def.macos.RlimitTest	\
	scap.oval.def.macos.SoftwareupdateObject	\
	scap.oval.def.macos.SoftwareupdateState	\
	scap.oval.def.macos.SoftwareupdateTest	\
	scap.oval.def.macos.SystemprofilerObject	\
	scap.oval.def.macos.SystemprofilerState	\
	scap.oval.def.macos.SystemprofilerTest	\
	scap.oval.def.macos.SystemsetupObject	\
	scap.oval.def.macos.SystemsetupState	\
	scap.oval.def.macos.SystemsetupTest	\
	scap.oval.def.netconf.ConfigObject	\
	scap.oval.def.netconf.ConfigState	\
	scap.oval.def.netconf.ConfigTest	\
	scap.oval.def.netconf.ObjectFactory	\
	scap.oval.def.netconf.package-info	\
	scap.oval.def.pixos.LineObject	\
	scap.oval.def.pixos.LineState	\
	scap.oval.def.pixos.LineTest	\
	scap.oval.def.pixos.ObjectFactory	\
	scap.oval.def.pixos.package-info	\
	scap.oval.def.pixos.VersionObject	\
	scap.oval.def.pixos.VersionState	\
	scap.oval.def.pixos.VersionTest	\
	scap.oval.def.sharepoint.BestbetObject	\
	scap.oval.def.sharepoint.BestbetState	\
	scap.oval.def.sharepoint.BestbetTest	\
	scap.oval.def.sharepoint.EntityObjectUrlZoneType	\
	scap.oval.def.sharepoint.EntityStateEventSeverityType	\
	scap.oval.def.sharepoint.EntityStatePolicyFeatureStateType	\
	scap.oval.def.sharepoint.EntityStatePolicyRoleType	\
	scap.oval.def.sharepoint.EntityStateTraceSeverityType	\
	scap.oval.def.sharepoint.EntityStateUrlZoneType	\
	scap.oval.def.sharepoint.InfopolicycollObject	\
	scap.oval.def.sharepoint.InfopolicycollState	\
	scap.oval.def.sharepoint.InfopolicycollTest	\
	scap.oval.def.sharepoint.ObjectFactory	\
	scap.oval.def.sharepoint.package-info	\
	scap.oval.def.sharepoint.SpantivirussettingsObject	\
	scap.oval.def.sharepoint.SpantivirussettingsState	\
	scap.oval.def.sharepoint.SpantivirussettingsTest	\
	scap.oval.def.sharepoint.SpcrawlruleObject	\
	scap.oval.def.sharepoint.SpcrawlruleState	\
	scap.oval.def.sharepoint.SpcrawlruleTest	\
	scap.oval.def.sharepoint.SpdiagnosticslevelObject	\
	scap.oval.def.sharepoint.SpdiagnosticslevelState	\
	scap.oval.def.sharepoint.SpdiagnosticslevelTest	\
	scap.oval.def.sharepoint.SpdiagnosticsserviceObject	\
	scap.oval.def.sharepoint.SpdiagnosticsserviceState	\
	scap.oval.def.sharepoint.SpdiagnosticsserviceTest	\
	scap.oval.def.sharepoint.SpgroupObject	\
	scap.oval.def.sharepoint.SpgroupState	\
	scap.oval.def.sharepoint.SpgroupTest	\
	scap.oval.def.sharepoint.Spjobdefinition510Object	\
	scap.oval.def.sharepoint.Spjobdefinition510State	\
	scap.oval.def.sharepoint.Spjobdefinition510Test	\
	scap.oval.def.sharepoint.SpjobdefinitionObject	\
	scap.oval.def.sharepoint.SpjobdefinitionState	\
	scap.oval.def.sharepoint.SpjobdefinitionTest	\
	scap.oval.def.sharepoint.SplistObject	\
	scap.oval.def.sharepoint.SplistState	\
	scap.oval.def.sharepoint.SplistTest	\
	scap.oval.def.sharepoint.SppolicyfeatureObject	\
	scap.oval.def.sharepoint.SppolicyfeatureState	\
	scap.oval.def.sharepoint.SppolicyfeatureTest	\
	scap.oval.def.sharepoint.SppolicyObject	\
	scap.oval.def.sharepoint.SppolicyState	\
	scap.oval.def.sharepoint.SppolicyTest	\
	scap.oval.def.sharepoint.SpsiteadministrationObject	\
	scap.oval.def.sharepoint.SpsiteadministrationState	\
	scap.oval.def.sharepoint.SpsiteadministrationTest	\
	scap.oval.def.sharepoint.SpsiteObject	\
	scap.oval.def.sharepoint.SpsiteState	\
	scap.oval.def.sharepoint.SpsiteTest	\
	scap.oval.def.sharepoint.SpwebapplicationObject	\
	scap.oval.def.sharepoint.SpwebapplicationState	\
	scap.oval.def.sharepoint.SpwebapplicationTest	\
	scap.oval.def.sharepoint.SpwebObject	\
	scap.oval.def.sharepoint.SpwebState	\
	scap.oval.def.sharepoint.SpwebTest	\
	scap.oval.def.solaris.EntityObjectPublisherTypeType	\
	scap.oval.def.solaris.EntityStateClientUUIDType	\
	scap.oval.def.solaris.EntityStateLDOMRoleType	\
	scap.oval.def.solaris.EntityStatePermissionCompareType	\
	scap.oval.def.solaris.EntityStatePublisherTypeType	\
	scap.oval.def.solaris.EntityStateSmfServiceStateType	\
	scap.oval.def.solaris.EntityStateV12NEnvType	\
	scap.oval.def.solaris.FacetObject	\
	scap.oval.def.solaris.FacetState	\
	scap.oval.def.solaris.FacetTest	\
	scap.oval.def.solaris.ImageObject	\
	scap.oval.def.solaris.ImageState	\
	scap.oval.def.solaris.ImageTest	\
	scap.oval.def.solaris.IsainfoObject	\
	scap.oval.def.solaris.IsainfoState	\
	scap.oval.def.solaris.IsainfoTest	\
	scap.oval.def.solaris.NddObject	\
	scap.oval.def.solaris.NddState	\
	scap.oval.def.solaris.NddTest	\
	scap.oval.def.solaris.ObjectFactory	\
	scap.oval.def.solaris.package-info	\
	scap.oval.def.solaris.Package511Object	\
	scap.oval.def.solaris.Package511State	\
	scap.oval.def.solaris.Package511Test	\
	scap.oval.def.solaris.PackageavoidlistObject	\
	scap.oval.def.solaris.PackageavoidlistState	\
	scap.oval.def.solaris.PackageavoidlistTest	\
	scap.oval.def.solaris.PackageCheckBehaviors	\
	scap.oval.def.solaris.PackagecheckObject	\
	scap.oval.def.solaris.PackagecheckState	\
	scap.oval.def.solaris.PackagecheckTest	\
	scap.oval.def.solaris.PackagefreezelistObject	\
	scap.oval.def.solaris.PackagefreezelistState	\
	scap.oval.def.solaris.PackagefreezelistTest	\
	scap.oval.def.solaris.PackageObject	\
	scap.oval.def.solaris.PackagepublisherObject	\
	scap.oval.def.solaris.PackagepublisherState	\
	scap.oval.def.solaris.PackagepublisherTest	\
	scap.oval.def.solaris.PackageState	\
	scap.oval.def.solaris.PackageTest	\
	scap.oval.def.solaris.Patch54Object	\
	scap.oval.def.solaris.Patch54Test	\
	scap.oval.def.solaris.PatchBehaviors	\
	scap.oval.def.solaris.PatchObject	\
	scap.oval.def.solaris.PatchState	\
	scap.oval.def.solaris.PatchTest	\
	scap.oval.def.solaris.SmfObject	\
	scap.oval.def.solaris.SmfpropertyObject	\
	scap.oval.def.solaris.SmfpropertyState	\
	scap.oval.def.solaris.SmfpropertyTest	\
	scap.oval.def.solaris.SmfState	\
	scap.oval.def.solaris.SmfTest	\
	scap.oval.def.solaris.VariantObject	\
	scap.oval.def.solaris.VariantState	\
	scap.oval.def.solaris.VariantTest	\
	scap.oval.def.solaris.VirtualizationinfoObject	\
	scap.oval.def.solaris.VirtualizationinfoState	\
	scap.oval.def.solaris.VirtualizationinfoTest	\
	scap.oval.def.unix.DnscacheObject	\
	scap.oval.def.unix.DnscacheState	\
	scap.oval.def.unix.DnscacheTest	\
	scap.oval.def.unix.EntityStateCapabilityType	\
	scap.oval.def.unix.EntityStateEncryptMethodType	\
	scap.oval.def.unix.EntityStateEndpointType	\
	scap.oval.def.unix.EntityStateGconfTypeType	\
	scap.oval.def.unix.EntityStateInterfaceType	\
	scap.oval.def.unix.EntityStateRoutingTableFlagsType	\
	scap.oval.def.unix.EntityStateWaitStatusType	\
	scap.oval.def.unix.EntityStateXinetdTypeStatusType	\
	scap.oval.def.unix.FileBehaviors	\
	scap.oval.def.unix.FileextendedattributeObject	\
	scap.oval.def.unix.FileextendedattributeState	\
	scap.oval.def.unix.FileextendedattributeTest	\
	scap.oval.def.unix.FileObject	\
	scap.oval.def.unix.FileState	\
	scap.oval.def.unix.FileTest	\
	scap.oval.def.unix.GconfObject	\
	scap.oval.def.unix.GconfState	\
	scap.oval.def.unix.GconfTest	\
	scap.oval.def.unix.InetdObject	\
	scap.oval.def.unix.InetdState	\
	scap.oval.def.unix.InetdTest	\
	scap.oval.def.unix.InterfaceObject	\
	scap.oval.def.unix.InterfaceState	\
	scap.oval.def.unix.InterfaceTest	\
	scap.oval.def.unix.ObjectFactory	\
	scap.oval.def.unix.package-info	\
	scap.oval.def.unix.PasswordObject	\
	scap.oval.def.unix.PasswordState	\
	scap.oval.def.unix.PasswordTest	\
	scap.oval.def.unix.Process58Object	\
	scap.oval.def.unix.Process58State	\
	scap.oval.def.unix.Process58Test	\
	scap.oval.def.unix.ProcessObject	\
	scap.oval.def.unix.ProcessState	\
	scap.oval.def.unix.ProcessTest	\
	scap.oval.def.unix.RoutingtableObject	\
	scap.oval.def.unix.RoutingtableState	\
	scap.oval.def.unix.RoutingtableTest	\
	scap.oval.def.unix.RunlevelObject	\
	scap.oval.def.unix.RunlevelState	\
	scap.oval.def.unix.RunlevelTest	\
	scap.oval.def.unix.SccsObject	\
	scap.oval.def.unix.SccsState	\
	scap.oval.def.unix.SccsTest	\
	scap.oval.def.unix.ShadowObject	\
	scap.oval.def.unix.ShadowState	\
	scap.oval.def.unix.ShadowTest	\
	scap.oval.def.unix.SymlinkObject	\
	scap.oval.def.unix.SymlinkState	\
	scap.oval.def.unix.SymlinkTest	\
	scap.oval.def.unix.SysctlObject	\
	scap.oval.def.unix.SysctlState	\
	scap.oval.def.unix.SysctlTest	\
	scap.oval.def.unix.UnameObject	\
	scap.oval.def.unix.UnameState	\
	scap.oval.def.unix.UnameTest	\
	scap.oval.def.unix.XinetdObject	\
	scap.oval.def.unix.XinetdState	\
	scap.oval.def.unix.XinetdTest	\
	scap.oval.def.windows.AccesstokenBehaviors	\
	scap.oval.def.windows.AccesstokenObject	\
	scap.oval.def.windows.AccesstokenState	\
	scap.oval.def.windows.AccesstokenTest	\
	scap.oval.def.windows.Activedirectory57Object	\
	scap.oval.def.windows.Activedirectory57State	\
	scap.oval.def.windows.Activedirectory57Test	\
	scap.oval.def.windows.ActivedirectoryObject	\
	scap.oval.def.windows.ActivedirectoryState	\
	scap.oval.def.windows.ActivedirectoryTest	\
	scap.oval.def.windows.AuditeventpolicyObject	\
	scap.oval.def.windows.AuditeventpolicyState	\
	scap.oval.def.windows.AuditeventpolicysubcategoriesObject	\
	scap.oval.def.windows.AuditeventpolicysubcategoriesState	\
	scap.oval.def.windows.AuditeventpolicysubcategoriesTest	\
	scap.oval.def.windows.AuditeventpolicyTest	\
	scap.oval.def.windows.CmdletObject	\
	scap.oval.def.windows.CmdletState	\
	scap.oval.def.windows.CmdletTest	\
	scap.oval.def.windows.DnscacheObject	\
	scap.oval.def.windows.DnscacheState	\
	scap.oval.def.windows.DnscacheTest	\
	scap.oval.def.windows.EntityObjectCmdletVerbType	\
	scap.oval.def.windows.EntityObjectGUIDType	\
	scap.oval.def.windows.EntityObjectNamingContextType	\
	scap.oval.def.windows.EntityObjectProtocolType	\
	scap.oval.def.windows.EntityObjectRegistryHiveType	\
	scap.oval.def.windows.EntityObjectSystemMetricIndexType	\
	scap.oval.def.windows.EntityObjectUserRightType	\
	scap.oval.def.windows.EntityStateAddrTypeType	\
	scap.oval.def.windows.EntityStateAdstypeType	\
	scap.oval.def.windows.EntityStateAuditType	\
	scap.oval.def.windows.EntityStateCmdletVerbType	\
	scap.oval.def.windows.EntityStateDriveTypeType	\
	scap.oval.def.windows.EntityStateFileAttributeType	\
	scap.oval.def.windows.EntityStateFileTypeType	\
	scap.oval.def.windows.EntityStateGUIDType	\
	scap.oval.def.windows.EntityStateInterfaceTypeType	\
	scap.oval.def.windows.EntityStateNamingContextType	\
	scap.oval.def.windows.EntityStateNTUserAccountTypeType	\
	scap.oval.def.windows.EntityStatePeSubsystemType	\
	scap.oval.def.windows.EntityStatePeTargetMachineType	\
	scap.oval.def.windows.EntityStateProtocolType	\
	scap.oval.def.windows.EntityStateRegistryHiveType	\
	scap.oval.def.windows.EntityStateRegistryTypeType	\
	scap.oval.def.windows.EntityStateServiceControlsAcceptedType	\
	scap.oval.def.windows.EntityStateServiceCurrentStateType	\
	scap.oval.def.windows.EntityStateServiceStartTypeType	\
	scap.oval.def.windows.EntityStateServiceTypeType	\
	scap.oval.def.windows.EntityStateSharedResourceTypeType	\
	scap.oval.def.windows.EntityStateSystemMetricIndexType	\
	scap.oval.def.windows.EntityStateUserRightType	\
	scap.oval.def.windows.EntityStateWindowsViewType	\
	scap.oval.def.windows.Fileauditedpermissions53Object	\
	scap.oval.def.windows.Fileauditedpermissions53State	\
	scap.oval.def.windows.Fileauditedpermissions53Test	\
	scap.oval.def.windows.FileauditedpermissionsObject	\
	scap.oval.def.windows.FileauditedpermissionsState	\
	scap.oval.def.windows.FileauditedpermissionsTest	\
	scap.oval.def.windows.FileAuditPermissions53Behaviors	\
	scap.oval.def.windows.FileAuditPermissionsBehaviors	\
	scap.oval.def.windows.FileBehaviors	\
	scap.oval.def.windows.FileEffectiveRights53Behaviors	\
	scap.oval.def.windows.Fileeffectiverights53Object	\
	scap.oval.def.windows.Fileeffectiverights53State	\
	scap.oval.def.windows.Fileeffectiverights53Test	\
	scap.oval.def.windows.FileEffectiveRightsBehaviors	\
	scap.oval.def.windows.FileeffectiverightsObject	\
	scap.oval.def.windows.FileeffectiverightsState	\
	scap.oval.def.windows.FileeffectiverightsTest	\
	scap.oval.def.windows.FileObject	\
	scap.oval.def.windows.FileState	\
	scap.oval.def.windows.FileTest	\
	scap.oval.def.windows.GroupObject	\
	scap.oval.def.windows.GroupSidObject	\
	scap.oval.def.windows.GroupSidState	\
	scap.oval.def.windows.GroupSidTest	\
	scap.oval.def.windows.GroupState	\
	scap.oval.def.windows.GroupTest	\
	scap.oval.def.windows.InterfaceObject	\
	scap.oval.def.windows.InterfaceState	\
	scap.oval.def.windows.InterfaceTest	\
	scap.oval.def.windows.JunctionObject	\
	scap.oval.def.windows.JunctionState	\
	scap.oval.def.windows.JunctionTest	\
	scap.oval.def.windows.LicenseObject	\
	scap.oval.def.windows.LicenseState	\
	scap.oval.def.windows.LicenseTest	\
	scap.oval.def.windows.LockoutpolicyObject	\
	scap.oval.def.windows.LockoutpolicyState	\
	scap.oval.def.windows.LockoutpolicyTest	\
	scap.oval.def.windows.MetabaseObject	\
	scap.oval.def.windows.MetabaseState	\
	scap.oval.def.windows.MetabaseTest	\
	scap.oval.def.windows.NTUserBehaviors	\
	scap.oval.def.windows.NtuserObject	\
	scap.oval.def.windows.NtuserState	\
	scap.oval.def.windows.NtuserTest	\
	scap.oval.def.windows.ObjectFactory	\
	scap.oval.def.windows.package-info	\
	scap.oval.def.windows.PasswordpolicyObject	\
	scap.oval.def.windows.PasswordpolicyState	\
	scap.oval.def.windows.PasswordpolicyTest	\
	scap.oval.def.windows.PeheaderObject	\
	scap.oval.def.windows.PeheaderState	\
	scap.oval.def.windows.PeheaderTest	\
	scap.oval.def.windows.PortObject	\
	scap.oval.def.windows.PortState	\
	scap.oval.def.windows.PortTest	\
	scap.oval.def.windows.PrinterEffectiveRightsBehaviors	\
	scap.oval.def.windows.PrintereffectiverightsObject	\
	scap.oval.def.windows.PrintereffectiverightsState	\
	scap.oval.def.windows.PrintereffectiverightsTest	\
	scap.oval.def.windows.Process58Object	\
	scap.oval.def.windows.Process58State	\
	scap.oval.def.windows.Process58Test	\
	scap.oval.def.windows.ProcessObject	\
	scap.oval.def.windows.ProcessState	\
	scap.oval.def.windows.ProcessTest	\
	scap.oval.def.windows.RegistryBehaviors	\
	scap.oval.def.windows.RegistryObject	\
	scap.oval.def.windows.RegistryState	\
	scap.oval.def.windows.RegistryTest	\
	scap.oval.def.windows.Regkeyauditedpermissions53Object	\
	scap.oval.def.windows.Regkeyauditedpermissions53State	\
	scap.oval.def.windows.Regkeyauditedpermissions53Test	\
	scap.oval.def.windows.RegkeyauditedpermissionsObject	\
	scap.oval.def.windows.RegkeyauditedpermissionsState	\
	scap.oval.def.windows.RegkeyauditedpermissionsTest	\
	scap.oval.def.windows.RegkeyAuditPermissions53Behaviors	\
	scap.oval.def.windows.RegkeyAuditPermissionsBehaviors	\
	scap.oval.def.windows.RegkeyEffectiveRights53Behaviors	\
	scap.oval.def.windows.Regkeyeffectiverights53Object	\
	scap.oval.def.windows.Regkeyeffectiverights53State	\
	scap.oval.def.windows.Regkeyeffectiverights53Test	\
	scap.oval.def.windows.RegkeyEffectiveRightsBehaviors	\
	scap.oval.def.windows.RegkeyeffectiverightsObject	\
	scap.oval.def.windows.RegkeyeffectiverightsState	\
	scap.oval.def.windows.RegkeyeffectiverightsTest	\
	scap.oval.def.windows.ServiceEffectiveRightsBehaviors	\
	scap.oval.def.windows.ServiceeffectiverightsObject	\
	scap.oval.def.windows.ServiceeffectiverightsState	\
	scap.oval.def.windows.ServiceeffectiverightsTest	\
	scap.oval.def.windows.ServiceObject	\
	scap.oval.def.windows.ServiceState	\
	scap.oval.def.windows.ServiceTest	\
	scap.oval.def.windows.SharedResourceAuditedPermissionsBehaviors	\
	scap.oval.def.windows.SharedresourceauditedpermissionsObject	\
	scap.oval.def.windows.SharedresourceauditedpermissionsState	\
	scap.oval.def.windows.SharedresourceauditedpermissionsTest	\
	scap.oval.def.windows.SharedResourceEffectiveRightsBehaviors	\
	scap.oval.def.windows.SharedresourceeffectiverightsObject	\
	scap.oval.def.windows.SharedresourceeffectiverightsState	\
	scap.oval.def.windows.SharedresourceeffectiverightsTest	\
	scap.oval.def.windows.SharedresourceObject	\
	scap.oval.def.windows.SharedresourceState	\
	scap.oval.def.windows.SharedresourceTest	\
	scap.oval.def.windows.SidBehaviors	\
	scap.oval.def.windows.SidObject	\
	scap.oval.def.windows.SidSidBehaviors	\
	scap.oval.def.windows.SidSidObject	\
	scap.oval.def.windows.SidSidState	\
	scap.oval.def.windows.SidSidTest	\
	scap.oval.def.windows.SidState	\
	scap.oval.def.windows.SidTest	\
	scap.oval.def.windows.SystemmetricObject	\
	scap.oval.def.windows.SystemmetricState	\
	scap.oval.def.windows.SystemmetricTest	\
	scap.oval.def.windows.UacObject	\
	scap.oval.def.windows.UacState	\
	scap.oval.def.windows.UacTest	\
	scap.oval.def.windows.UserObject	\
	scap.oval.def.windows.UserrightObject	\
	scap.oval.def.windows.UserrightState	\
	scap.oval.def.windows.UserrightTest	\
	scap.oval.def.windows.UserSid55Object	\
	scap.oval.def.windows.UserSid55State	\
	scap.oval.def.windows.UserSid55Test	\
	scap.oval.def.windows.UserSidObject	\
	scap.oval.def.windows.UserSidState	\
	scap.oval.def.windows.UserSidTest	\
	scap.oval.def.windows.UserState	\
	scap.oval.def.windows.UserTest	\
	scap.oval.def.windows.VolumeObject	\
	scap.oval.def.windows.VolumeState	\
	scap.oval.def.windows.VolumeTest	\
	scap.oval.def.windows.Wmi57Object	\
	scap.oval.def.windows.Wmi57State	\
	scap.oval.def.windows.Wmi57Test	\
	scap.oval.def.windows.WmiObject	\
	scap.oval.def.windows.WmiState	\
	scap.oval.def.windows.WmiTest	\
	scap.oval.def.windows.WuaUpdateSearcherBehaviors	\
	scap.oval.def.windows.WuaupdatesearcherObject	\
	scap.oval.def.windows.WuaupdatesearcherState	\
	scap.oval.def.windows.WuaupdatesearcherTest	\
	scap.oval.directives.ObjectFactory	\
	scap.oval.directives.OvalDirectives	\
	scap.oval.directives.package-info	\
	scap.oval.evaluation.EvaluationDefinitionIds	\
	scap.oval.evaluation.ObjectFactory	\
	scap.oval.evaluation.package-info	\
	scap.oval.results.ClassDirectivesType	\
	scap.oval.results.ContentEnumeration	\
	scap.oval.results.CriteriaType	\
	scap.oval.results.CriterionType	\
	scap.oval.results.DefaultDirectivesType	\
	scap.oval.results.DefinitionsType	\
	scap.oval.results.DefinitionType	\
	scap.oval.results.DirectivesType	\
	scap.oval.results.DirectiveType	\
	scap.oval.results.ExtendDefinitionType	\
	scap.oval.results.ObjectFactory	\
	scap.oval.results.OvalResults	\
	scap.oval.results.package-info	\
	scap.oval.results.ResultEnumeration	\
	scap.oval.results.ResultsType	\
	scap.oval.results.SystemType	\
	scap.oval.results.TestedItemType	\
	scap.oval.results.TestedVariableType	\
	scap.oval.results.TestsType	\
	scap.oval.results.TestType	\
	scap.oval.sc.aix.EntityItemFilesetStateType	\
	scap.oval.sc.aix.EntityItemFixInstallationStatusType	\
	scap.oval.sc.aix.EntityItemInterimFixStateType	\
	scap.oval.sc.aix.FilesetItem	\
	scap.oval.sc.aix.FixItem	\
	scap.oval.sc.aix.InterimFixItem	\
	scap.oval.sc.aix.NoItem	\
	scap.oval.sc.aix.ObjectFactory	\
	scap.oval.sc.aix.OslevelItem	\
	scap.oval.sc.aix.package-info	\
	scap.oval.sc.android.AppmanagerItem	\
	scap.oval.sc.android.BluetoothItem	\
	scap.oval.sc.android.CameraItem	\
	scap.oval.sc.android.CertificateItem	\
	scap.oval.sc.android.DevicesettingsItem	\
	scap.oval.sc.android.EncryptionItem	\
	scap.oval.sc.android.EntityItemEncryptionStatusType	\
	scap.oval.sc.android.EntityItemKeyguardDisabledFeaturesType	\
	scap.oval.sc.android.EntityItemNetworkType	\
	scap.oval.sc.android.EntityItemPasswordQualityType	\
	scap.oval.sc.android.EntityItemWifiAuthAlgorithmType	\
	scap.oval.sc.android.EntityItemWifiCurrentStatusType	\
	scap.oval.sc.android.EntityItemWifiGroupCipherType	\
	scap.oval.sc.android.EntityItemWifiKeyMgmtType	\
	scap.oval.sc.android.EntityItemWifiPairwiseCipherType	\
	scap.oval.sc.android.EntityItemWifiProtocolType	\
	scap.oval.sc.android.LocationserviceItem	\
	scap.oval.sc.android.NetworkItem	\
	scap.oval.sc.android.ObjectFactory	\
	scap.oval.sc.android.package-info	\
	scap.oval.sc.android.PasswordItem	\
	scap.oval.sc.android.SystemdetailsItem	\
	scap.oval.sc.android.TelephonyItem	\
	scap.oval.sc.android.WifiItem	\
	scap.oval.sc.android.WifinetworkItem	\
	scap.oval.sc.apache.HttpdItem	\
	scap.oval.sc.apache.ObjectFactory	\
	scap.oval.sc.apache.package-info	\
	scap.oval.sc.appleios.GlobalrestrictionsItem	\
	scap.oval.sc.appleios.ObjectFactory	\
	scap.oval.sc.appleios.package-info	\
	scap.oval.sc.appleios.PasscodepolicyItem	\
	scap.oval.sc.appleios.ProfileItem	\
	scap.oval.sc.asa.AclItem	\
	scap.oval.sc.asa.ClassMapItem	\
	scap.oval.sc.asa.EntityItemAccessListInterfaceDirectionType	\
	scap.oval.sc.asa.EntityItemAccessListIPVersionType	\
	scap.oval.sc.asa.EntityItemAccessListUseType	\
	scap.oval.sc.asa.EntityItemApplyServicePolicyType	\
	scap.oval.sc.asa.EntityItemClassMapType	\
	scap.oval.sc.asa.EntityItemInspectionType	\
	scap.oval.sc.asa.EntityItemMatchType	\
	scap.oval.sc.asa.EntityItemSNMPAuthStringType	\
	scap.oval.sc.asa.EntityItemSNMPPrivStringType	\
	scap.oval.sc.asa.EntityItemSNMPSecLevelStringType	\
	scap.oval.sc.asa.EntityItemSNMPVersionStringType	\
	scap.oval.sc.asa.InterfaceItem	\
	scap.oval.sc.asa.LineItem	\
	scap.oval.sc.asa.ObjectFactory	\
	scap.oval.sc.asa.package-info	\
	scap.oval.sc.asa.PolicyMapItem	\
	scap.oval.sc.asa.ServicePolicyItem	\
	scap.oval.sc.asa.SnmpGroupItem	\
	scap.oval.sc.asa.SnmpHostItem	\
	scap.oval.sc.asa.SnmpUserItem	\
	scap.oval.sc.asa.TcpMapItem	\
	scap.oval.sc.asa.VersionItem	\
	scap.oval.sc.catos.LineItem	\
	scap.oval.sc.catos.ModuleItem	\
	scap.oval.sc.catos.ObjectFactory	\
	scap.oval.sc.catos.package-info	\
	scap.oval.sc.catos.VersionItem	\
	scap.oval.sc.core.CollectedObjectsType	\
	scap.oval.sc.core.EntityItemAnySimpleType	\
	scap.oval.sc.core.EntityItemBinaryType	\
	scap.oval.sc.core.EntityItemBoolType	\
	scap.oval.sc.core.EntityItemComplexBaseType	\
	scap.oval.sc.core.EntityItemDebianEVRStringType	\
	scap.oval.sc.core.EntityItemEVRStringType	\
	scap.oval.sc.core.EntityItemFieldType	\
	scap.oval.sc.core.EntityItemFilesetRevisionType	\
	scap.oval.sc.core.EntityItemFloatType	\
	scap.oval.sc.core.EntityItemIntType	\
	scap.oval.sc.core.EntityItemIOSVersionType	\
	scap.oval.sc.core.EntityItemIPAddressStringType	\
	scap.oval.sc.core.EntityItemIPAddressType	\
	scap.oval.sc.core.EntityItemRecordType	\
	scap.oval.sc.core.EntityItemSimpleBaseType	\
	scap.oval.sc.core.EntityItemStringType	\
	scap.oval.sc.core.EntityItemVersionType	\
	scap.oval.sc.core.FlagEnumeration	\
	scap.oval.sc.core.InterfacesType	\
	scap.oval.sc.core.InterfaceType	\
	scap.oval.sc.core.ItemType	\
	scap.oval.sc.core.ObjectFactory	\
	scap.oval.sc.core.ObjectType	\
	scap.oval.sc.core.OvalSystemCharacteristics	\
	scap.oval.sc.core.package-info	\
	scap.oval.sc.core.ReferenceType	\
	scap.oval.sc.core.StatusEnumeration	\
	scap.oval.sc.core.SystemDataType	\
	scap.oval.sc.core.SystemInfoType	\
	scap.oval.sc.core.VariableValueType	\
	scap.oval.sc.esx.EntityItemClassificationType	\
	scap.oval.sc.esx.EntityItemSupportLevelType	\
	scap.oval.sc.esx.ObjectFactory	\
	scap.oval.sc.esx.package-info	\
	scap.oval.sc.esx.PatchItem	\
	scap.oval.sc.esx.VersionItem	\
	scap.oval.sc.esx.VisdkmanagedobjectItem	\
	scap.oval.sc.freebsd.ObjectFactory	\
	scap.oval.sc.freebsd.package-info	\
	scap.oval.sc.freebsd.PortinfoItem	\
	scap.oval.sc.hpux.GetconfItem	\
	scap.oval.sc.hpux.NddItem	\
	scap.oval.sc.hpux.ObjectFactory	\
	scap.oval.sc.hpux.package-info	\
	scap.oval.sc.hpux.PatchItem	\
	scap.oval.sc.hpux.SwlistItem	\
	scap.oval.sc.hpux.TrustedItem	\
	scap.oval.sc.independent.EntityItemEngineType	\
	scap.oval.sc.independent.EntityItemFamilyType	\
	scap.oval.sc.independent.EntityItemHashTypeType	\
	scap.oval.sc.independent.EntityItemLdaptypeType	\
	scap.oval.sc.independent.EntityItemVariableRefType	\
	scap.oval.sc.independent.EntityItemWindowsViewType	\
	scap.oval.sc.independent.Environmentvariable58Item	\
	scap.oval.sc.independent.EnvironmentvariableItem	\
	scap.oval.sc.independent.FamilyItem	\
	scap.oval.sc.independent.Filehash58Item	\
	scap.oval.sc.independent.FilehashItem	\
	scap.oval.sc.independent.Ldap57Item	\
	scap.oval.sc.independent.LdapItem	\
	scap.oval.sc.independent.ObjectFactory	\
	scap.oval.sc.independent.package-info	\
	scap.oval.sc.independent.Sql57Item	\
	scap.oval.sc.independent.SqlItem	\
	scap.oval.sc.independent.TextfilecontentItem	\
	scap.oval.sc.independent.VariableItem	\
	scap.oval.sc.independent.XmlfilecontentItem	\
	scap.oval.sc.ios.AclItem	\
	scap.oval.sc.ios.BgpneighborItem	\
	scap.oval.sc.ios.EntityItemAccessListInterfaceDirectionType	\
	scap.oval.sc.ios.EntityItemAccessListIPVersionType	\
	scap.oval.sc.ios.EntityItemAccessListUseType	\
	scap.oval.sc.ios.EntityItemRoutingAuthTypeStringType	\
	scap.oval.sc.ios.EntityItemRoutingProtocolType	\
	scap.oval.sc.ios.EntityItemSNMPAuthStringType	\
	scap.oval.sc.ios.EntityItemSNMPModeStringType	\
	scap.oval.sc.ios.EntityItemSNMPPrivStringType	\
	scap.oval.sc.ios.EntityItemSNMPSecLevelStringType	\
	scap.oval.sc.ios.EntityItemSNMPVersionStringType	\
	scap.oval.sc.ios.EntityItemSwitchportModeType	\
	scap.oval.sc.ios.EntityItemTrunkEncapType	\
	scap.oval.sc.ios.GlobalItem	\
	scap.oval.sc.ios.InterfaceItem	\
	scap.oval.sc.ios.LineItem	\
	scap.oval.sc.ios.ObjectFactory	\
	scap.oval.sc.ios.package-info	\
	scap.oval.sc.ios.RouterItem	\
	scap.oval.sc.ios.RoutingprotocolauthintfItem	\
	scap.oval.sc.ios.SectionItem	\
	scap.oval.sc.ios.SnmpcommunityItem	\
	scap.oval.sc.ios.SnmpgroupItem	\
	scap.oval.sc.ios.SnmphostItem	\
	scap.oval.sc.ios.SnmpItem	\
	scap.oval.sc.ios.SnmpuserItem	\
	scap.oval.sc.ios.SnmpviewItem	\
	scap.oval.sc.ios.TclshItem	\
	scap.oval.sc.ios.VersionItem	\
	scap.oval.sc.iosxe.AclItem	\
	scap.oval.sc.iosxe.BgpneighborItem	\
	scap.oval.sc.iosxe.EntityItemAccessListInterfaceDirectionType	\
	scap.oval.sc.iosxe.EntityItemAccessListIPVersionType	\
	scap.oval.sc.iosxe.EntityItemAccessListUseType	\
	scap.oval.sc.iosxe.EntityItemRoutingAuthTypeStringType	\
	scap.oval.sc.iosxe.EntityItemRoutingProtocolType	\
	scap.oval.sc.iosxe.EntityItemSNMPAuthStringType	\
	scap.oval.sc.iosxe.EntityItemSNMPModeStringType	\
	scap.oval.sc.iosxe.EntityItemSNMPPrivStringType	\
	scap.oval.sc.iosxe.EntityItemSNMPSecLevelStringType	\
	scap.oval.sc.iosxe.EntityItemSNMPVersionStringType	\
	scap.oval.sc.iosxe.EntityItemSwitchportModeType	\
	scap.oval.sc.iosxe.EntityItemTrunkEncapType	\
	scap.oval.sc.iosxe.GlobalItem	\
	scap.oval.sc.iosxe.InterfaceItem	\
	scap.oval.sc.iosxe.LineItem	\
	scap.oval.sc.iosxe.ObjectFactory	\
	scap.oval.sc.iosxe.package-info	\
	scap.oval.sc.iosxe.RouterItem	\
	scap.oval.sc.iosxe.RoutingprotocolauthintfItem	\
	scap.oval.sc.iosxe.SectionItem	\
	scap.oval.sc.iosxe.SnmpcommunityItem	\
	scap.oval.sc.iosxe.SnmpgroupItem	\
	scap.oval.sc.iosxe.SnmphostItem	\
	scap.oval.sc.iosxe.SnmpuserItem	\
	scap.oval.sc.iosxe.SnmpviewItem	\
	scap.oval.sc.iosxe.VersionItem	\
	scap.oval.sc.junos.EntityItemJunosReleaseTypeType	\
	scap.oval.sc.junos.ObjectFactory	\
	scap.oval.sc.junos.package-info	\
	scap.oval.sc.junos.ShowItem	\
	scap.oval.sc.junos.VersionItem	\
	scap.oval.sc.junos.XmlConfigItem	\
	scap.oval.sc.junos.XmlShowItem	\
	scap.oval.sc.linux.ApparmorstatusItem	\
	scap.oval.sc.linux.DpkginfoItem	\
	scap.oval.sc.linux.EntityItemProtocolType	\
	scap.oval.sc.linux.EntityItemRpmVerifyResultType	\
	scap.oval.sc.linux.IflistenersItem	\
	scap.oval.sc.linux.InetlisteningserversItem	\
	scap.oval.sc.linux.ObjectFactory	\
	scap.oval.sc.linux.package-info	\
	scap.oval.sc.linux.PartitionItem	\
	scap.oval.sc.linux.RpminfoItem	\
	scap.oval.sc.linux.RpmverifyfileItem	\
	scap.oval.sc.linux.RpmverifyItem	\
	scap.oval.sc.linux.RpmverifypackageItem	\
	scap.oval.sc.linux.SelinuxbooleanItem	\
	scap.oval.sc.linux.SelinuxsecuritycontextItem	\
	scap.oval.sc.linux.SlackwarepkginfoItem	\
	scap.oval.sc.linux.SystemdunitdependencyItem	\
	scap.oval.sc.linux.SystemdunitpropertyItem	\
	scap.oval.sc.macos.AccountinfoItem	\
	scap.oval.sc.macos.AuthorizationdbItem	\
	scap.oval.sc.macos.CorestorageItem	\
	scap.oval.sc.macos.DiskutilItem	\
	scap.oval.sc.macos.EntityItemDataTypeType	\
	scap.oval.sc.macos.EntityItemPermissionCompareType	\
	scap.oval.sc.macos.EntityItemPlistTypeType	\
	scap.oval.sc.macos.GatekeeperItem	\
	scap.oval.sc.macos.Inetlisteningserver510Item	\
	scap.oval.sc.macos.InetlisteningserversItem	\
	scap.oval.sc.macos.KeychainItem	\
	scap.oval.sc.macos.LaunchdItem	\
	scap.oval.sc.macos.NvramItem	\
	scap.oval.sc.macos.ObjectFactory	\
	scap.oval.sc.macos.package-info	\
	scap.oval.sc.macos.Plist511Item	\
	scap.oval.sc.macos.PlistItem	\
	scap.oval.sc.macos.Pwpolicy59Item	\
	scap.oval.sc.macos.PwpolicyItem	\
	scap.oval.sc.macos.RlimitItem	\
	scap.oval.sc.macos.SoftwareupdateItem	\
	scap.oval.sc.macos.SystemprofilerItem	\
	scap.oval.sc.macos.SystemsetupItem	\
	scap.oval.sc.netconf.ConfigItem	\
	scap.oval.sc.netconf.ObjectFactory	\
	scap.oval.sc.netconf.package-info	\
	scap.oval.sc.pixos.LineItem	\
	scap.oval.sc.pixos.ObjectFactory	\
	scap.oval.sc.pixos.package-info	\
	scap.oval.sc.pixos.VersionItem	\
	scap.oval.sc.sharepoint.BestbetItem	\
	scap.oval.sc.sharepoint.EntityItemEventSeverityType	\
	scap.oval.sc.sharepoint.EntityItemPolicyFeatureStateType	\
	scap.oval.sc.sharepoint.EntityItemPolicyRoleType	\
	scap.oval.sc.sharepoint.EntityItemTraceSeverityType	\
	scap.oval.sc.sharepoint.EntityItemUrlZoneType	\
	scap.oval.sc.sharepoint.InfopolicycollItem	\
	scap.oval.sc.sharepoint.ObjectFactory	\
	scap.oval.sc.sharepoint.package-info	\
	scap.oval.sc.sharepoint.SpantivirussettingsItem	\
	scap.oval.sc.sharepoint.SpcrawlruleItem	\
	scap.oval.sc.sharepoint.SpdiagnosticslevelItem	\
	scap.oval.sc.sharepoint.SpdiagnosticsserviceItem	\
	scap.oval.sc.sharepoint.SpgroupItem	\
	scap.oval.sc.sharepoint.Spjobdefinition510Item	\
	scap.oval.sc.sharepoint.SpjobdefinitionItem	\
	scap.oval.sc.sharepoint.SplistItem	\
	scap.oval.sc.sharepoint.SppolicyfeatureItem	\
	scap.oval.sc.sharepoint.SppolicyItem	\
	scap.oval.sc.sharepoint.SpsiteadministrationItem	\
	scap.oval.sc.sharepoint.SpsiteItem	\
	scap.oval.sc.sharepoint.SpwebapplicationItem	\
	scap.oval.sc.sharepoint.SpwebItem	\
	scap.oval.sc.solaris.EntityItemClientUUIDType	\
	scap.oval.sc.solaris.EntityItemLDOMRoleType	\
	scap.oval.sc.solaris.EntityItemPermissionCompareType	\
	scap.oval.sc.solaris.EntityItemPublisherTypeType	\
	scap.oval.sc.solaris.EntityItemSmfServiceStateType	\
	scap.oval.sc.solaris.EntityItemV12NEnvType	\
	scap.oval.sc.solaris.FacetItem	\
	scap.oval.sc.solaris.ImageItem	\
	scap.oval.sc.solaris.IsainfoItem	\
	scap.oval.sc.solaris.NddItem	\
	scap.oval.sc.solaris.ObjectFactory	\
	scap.oval.sc.solaris.package-info	\
	scap.oval.sc.solaris.Package511Item	\
	scap.oval.sc.solaris.PackageavoidlistItem	\
	scap.oval.sc.solaris.PackagecheckItem	\
	scap.oval.sc.solaris.PackagefreezelistItem	\
	scap.oval.sc.solaris.PackageItem	\
	scap.oval.sc.solaris.PackagepublisherItem	\
	scap.oval.sc.solaris.PatchItem	\
	scap.oval.sc.solaris.SmfItem	\
	scap.oval.sc.solaris.SmfpropertyItem	\
	scap.oval.sc.solaris.VariantItem	\
	scap.oval.sc.solaris.VirtualizationinfoItem	\
	scap.oval.sc.unix.DnscacheItem	\
	scap.oval.sc.unix.EntityItemCapabilityType	\
	scap.oval.sc.unix.EntityItemEncryptMethodType	\
	scap.oval.sc.unix.EntityItemEndpointType	\
	scap.oval.sc.unix.EntityItemGconfTypeType	\
	scap.oval.sc.unix.EntityItemInterfaceType	\
	scap.oval.sc.unix.EntityItemRoutingTableFlagsType	\
	scap.oval.sc.unix.EntityItemWaitStatusType	\
	scap.oval.sc.unix.EntityItemXinetdTypeStatusType	\
	scap.oval.sc.unix.FileextendedattributeItem	\
	scap.oval.sc.unix.FileItem	\
	scap.oval.sc.unix.GconfItem	\
	scap.oval.sc.unix.InetdItem	\
	scap.oval.sc.unix.InterfaceItem	\
	scap.oval.sc.unix.ObjectFactory	\
	scap.oval.sc.unix.package-info	\
	scap.oval.sc.unix.PasswordItem	\
	scap.oval.sc.unix.Process58Item	\
	scap.oval.sc.unix.ProcessItem	\
	scap.oval.sc.unix.RoutingtableItem	\
	scap.oval.sc.unix.RunlevelItem	\
	scap.oval.sc.unix.SccsItem	\
	scap.oval.sc.unix.ShadowItem	\
	scap.oval.sc.unix.SymlinkItem	\
	scap.oval.sc.unix.SysctlItem	\
	scap.oval.sc.unix.UnameItem	\
	scap.oval.sc.unix.XinetdItem	\
	scap.oval.sc.windows.AccesstokenItem	\
	scap.oval.sc.windows.Activedirectory57Item	\
	scap.oval.sc.windows.ActivedirectoryItem	\
	scap.oval.sc.windows.AuditeventpolicyItem	\
	scap.oval.sc.windows.AuditeventpolicysubcategoriesItem	\
	scap.oval.sc.windows.CmdletItem	\
	scap.oval.sc.windows.DnscacheItem	\
	scap.oval.sc.windows.EntityItemAddrTypeType	\
	scap.oval.sc.windows.EntityItemAdstypeType	\
	scap.oval.sc.windows.EntityItemAuditType	\
	scap.oval.sc.windows.EntityItemCmdletVerbType	\
	scap.oval.sc.windows.EntityItemDriveTypeType	\
	scap.oval.sc.windows.EntityItemFileAttributeType	\
	scap.oval.sc.windows.EntityItemFileTypeType	\
	scap.oval.sc.windows.EntityItemGUIDType	\
	scap.oval.sc.windows.EntityItemInterfaceTypeType	\
	scap.oval.sc.windows.EntityItemNamingContextType	\
	scap.oval.sc.windows.EntityItemNTUserAccountTypeType	\
	scap.oval.sc.windows.EntityItemPeSubsystemType	\
	scap.oval.sc.windows.EntityItemPeTargetMachineType	\
	scap.oval.sc.windows.EntityItemProtocolType	\
	scap.oval.sc.windows.EntityItemRegistryHiveType	\
	scap.oval.sc.windows.EntityItemRegistryTypeType	\
	scap.oval.sc.windows.EntityItemServiceControlsAcceptedType	\
	scap.oval.sc.windows.EntityItemServiceCurrentStateType	\
	scap.oval.sc.windows.EntityItemServiceStartTypeType	\
	scap.oval.sc.windows.EntityItemServiceTypeType	\
	scap.oval.sc.windows.EntityItemSharedResourceTypeType	\
	scap.oval.sc.windows.EntityItemSystemMetricIndexType	\
	scap.oval.sc.windows.EntityItemUserRightType	\
	scap.oval.sc.windows.EntityItemWindowsViewType	\
	scap.oval.sc.windows.FileauditedpermissionsItem	\
	scap.oval.sc.windows.FileeffectiverightsItem	\
	scap.oval.sc.windows.FileItem	\
	scap.oval.sc.windows.GroupItem	\
	scap.oval.sc.windows.GroupSidItem	\
	scap.oval.sc.windows.InterfaceItem	\
	scap.oval.sc.windows.JunctionItem	\
	scap.oval.sc.windows.LicenseItem	\
	scap.oval.sc.windows.LockoutpolicyItem	\
	scap.oval.sc.windows.MetabaseItem	\
	scap.oval.sc.windows.NtuserItem	\
	scap.oval.sc.windows.ObjectFactory	\
	scap.oval.sc.windows.package-info	\
	scap.oval.sc.windows.PasswordpolicyItem	\
	scap.oval.sc.windows.PeheaderItem	\
	scap.oval.sc.windows.PortItem	\
	scap.oval.sc.windows.PrintereffectiverightsItem	\
	scap.oval.sc.windows.ProcessItem	\
	scap.oval.sc.windows.RegistryItem	\
	scap.oval.sc.windows.RegkeyauditedpermissionsItem	\
	scap.oval.sc.windows.RegkeyeffectiverightsItem	\
	scap.oval.sc.windows.ServiceeffectiverightsItem	\
	scap.oval.sc.windows.ServiceItem	\
	scap.oval.sc.windows.SharedresourceauditedpermissionsItem	\
	scap.oval.sc.windows.SharedresourceeffectiverightsItem	\
	scap.oval.sc.windows.SharedresourceItem	\
	scap.oval.sc.windows.SidItem	\
	scap.oval.sc.windows.SidSidItem	\
	scap.oval.sc.windows.SystemmetricItem	\
	scap.oval.sc.windows.UacItem	\
	scap.oval.sc.windows.UserItem	\
	scap.oval.sc.windows.UserrightItem	\
	scap.oval.sc.windows.UserSidItem	\
	scap.oval.sc.windows.VolumeItem	\
	scap.oval.sc.windows.Wmi57Item	\
	scap.oval.sc.windows.WmiItem	\
	scap.oval.sc.windows.WuaupdatesearcherItem	\
	scap.oval.variables.ObjectFactory	\
	scap.oval.variables.OvalVariables	\
	scap.oval.variables.package-info	\
	scap.oval.variables.VariablesType	\
	scap.oval.variables.VariableType	\
	scap.xccdf.BenchmarkReferenceType	\
	scap.xccdf.CcOperatorEnumType	\
	scap.xccdf.CheckContentRefType	\
	scap.xccdf.CheckContentType	\
	scap.xccdf.CheckExportType	\
	scap.xccdf.CheckImportType	\
	scap.xccdf.CheckType	\
	scap.xccdf.ComplexCheckType	\
	scap.xccdf.ComplexValueType	\
	scap.xccdf.CPE2IdrefType	\
	scap.xccdf.DcStatusType	\
	scap.xccdf.FactType	\
	scap.xccdf.FixStrategyEnumType	\
	scap.xccdf.FixTextType	\
	scap.xccdf.FixType	\
	scap.xccdf.GroupType	\
	scap.xccdf.HtmlTextType	\
	scap.xccdf.HtmlTextWithSubType	\
	scap.xccdf.IdentityType	\
	scap.xccdf.IdentType	\
	scap.xccdf.IdrefListType	\
	scap.xccdf.IdrefType	\
	scap.xccdf.InstanceFixType	\
	scap.xccdf.InstanceResultType	\
	scap.xccdf.InterfaceHintType	\
	scap.xccdf.ItemType	\
	scap.xccdf.MessageType	\
	scap.xccdf.MetadataType	\
	scap.xccdf.Model	\
	scap.xccdf.MsgSevEnumType	\
	scap.xccdf.NoticeType	\
	scap.xccdf.ObjectFactory	\
	scap.xccdf.OverrideableCPE2IdrefType	\
	scap.xccdf.OverrideType	\
	scap.xccdf.package-info	\
	scap.xccdf.ParamType	\
	scap.xccdf.PlainTextType	\
	scap.xccdf.ProfileNoteType	\
	scap.xccdf.ProfileRefineRuleType	\
	scap.xccdf.ProfileRefineValueType	\
	scap.xccdf.ProfileSelectType	\
	scap.xccdf.ProfileSetComplexValueType	\
	scap.xccdf.ProfileSetValueType	\
	scap.xccdf.ProfileType	\
	scap.xccdf.RatingEnumType	\
	scap.xccdf.ReferenceType	\
	scap.xccdf.ResultEnumType	\
	scap.xccdf.RoleEnumType	\
	scap.xccdf.RuleResultType	\
	scap.xccdf.RuleType	\
	scap.xccdf.ScoreType	\
	scap.xccdf.SelChoicesType	\
	scap.xccdf.SelComplexValueType	\
	scap.xccdf.SelectableItemType	\
	scap.xccdf.SelNumType	\
	scap.xccdf.SelStringType	\
	scap.xccdf.SeverityEnumType	\
	scap.xccdf.SignatureType	\
	scap.xccdf.Status	\
	scap.xccdf.StatusType	\
	scap.xccdf.SubType	\
	scap.xccdf.SubUseEnumType	\
	scap.xccdf.TailoringBenchmarkReferenceType	\
	scap.xccdf.TailoringReferenceType	\
	scap.xccdf.TailoringType	\
	scap.xccdf.TailoringVersionType	\
	scap.xccdf.TargetFactsType	\
	scap.xccdf.TargetIdRefType	\
	scap.xccdf.TestResultType	\
	scap.xccdf.TextType	\
	scap.xccdf.TextWithSubType	\
	scap.xccdf.UriRefType	\
	scap.xccdf.ValueOperatorType	\
	scap.xccdf.ValueType	\
	scap.xccdf.ValueTypeType	\
	scap.xccdf.VersionType	\
	scap.xccdf.WarningCategoryEnumType	\
	scap.xccdf.WarningType	\
	scap.xccdf.XccdfBenchmark
