CLASSES=\
	org.gocil.diagnostics.ObjectFactory	\
	org.gocil.diagnostics.package-info	\
	org.iso.svrl.ObjectFactory	\
	org.iso.svrl.package-info	\
	org.joval.scap.diagnostics.ObjectFactory	\
	org.joval.scap.diagnostics.package-info	\
	org.joval.scap.oval.metadata.ObjectFactory	\
	org.joval.scap.oval.metadata.package-info	\
	org.oasis.address.ObjectFactory	\
	org.oasis.address.package-info	\
	org.oasis.catalog.ObjectFactory	\
	org.oasis.catalog.package-info	\
	org.oasis.name.ObjectFactory	\
	org.oasis.name.package-info	\
	org.openscap.sce.results.ObjectFactory	\
	org.openscap.sce.results.package-info	\
	org.openscap.sce.xccdf.ObjectFactory	\
	org.openscap.sce.xccdf.package-info	\
	org.purl.dc.ObjectFactory	\
	org.purl.dc.package-info	\
	org.purl.dc.terms.ObjectFactory	\
	org.purl.dc.terms.package-info	\
	org.w3c.xhtml.ObjectFactory	\
	org.w3c.xhtml.package-info	\
	org.w3c.xml.signature.ObjectFactory	\
	org.w3c.xml.signature.package-info	\
	org.w3c.xml.xlink.ObjectFactory	\
	org.w3c.xml.xlink.package-info	\
	scap.ai.ObjectFactory	\
	scap.ai.package-info	\
	scap.arf.core.ObjectFactory	\
	scap.arf.core.package-info	\
	scap.arf.reporting.ObjectFactory	\
	scap.arf.reporting.package-info	\
	scap.constructs.ObjectFactory	\
	scap.constructs.package-info	\
	scap.cce.list.ObjectFactory	\
	scap.cce.list.package-info	\
	scap.cpe.dictionary.ext.ObjectFactory	\
	scap.cpe.dictionary.ext.package-info	\
	scap.cpe.dictionary.ObjectFactory	\
	scap.cpe.dictionary.package-info	\
	scap.cpe.language.ObjectFactory	\
	scap.cpe.language.package-info	\
	scap.datastream.ObjectFactory	\
	scap.datastream.UseCaseType	\
	scap.datastream.package-info	\
	scap.ocil.core.ExceptionalResultType	\
	scap.ocil.core.ObjectFactory	\
	scap.ocil.core.package-info	\
	scap.ocil.variables.ObjectFactory	\
	scap.ocil.variables.package-info	\
	scap.oval.common.ComplexDatatypeEnumeration	\
	scap.oval.common.ObjectFactory	\
	scap.oval.common.package-info	\
	scap.oval.def.aix.ObjectFactory	\
	scap.oval.def.aix.package-info	\
	scap.oval.def.android.ObjectFactory	\
	scap.oval.def.android.package-info	\
	scap.oval.def.apache.ObjectFactory	\
	scap.oval.def.apache.package-info	\
	scap.oval.def.appleios.ObjectFactory	\
	scap.oval.def.appleios.package-info	\
	scap.oval.def.asa.ObjectFactory	\
	scap.oval.def.asa.package-info	\
	scap.oval.def.catos.ObjectFactory	\
	scap.oval.def.catos.package-info	\
	scap.oval.def.core.ObjectFactory	\
	scap.oval.def.core.package-info	\
	scap.oval.def.esx.ObjectFactory	\
	scap.oval.def.esx.package-info	\
	scap.oval.def.freebsd.ObjectFactory	\
	scap.oval.def.freebsd.package-info	\
	scap.oval.def.hpux.ObjectFactory	\
	scap.oval.def.hpux.package-info	\
	scap.oval.def.independent.ObjectFactory	\
	scap.oval.def.independent.package-info	\
	scap.oval.def.ios.ObjectFactory	\
	scap.oval.def.ios.package-info	\
	scap.oval.def.iosxe.ObjectFactory	\
	scap.oval.def.iosxe.package-info	\
	scap.oval.def.junos.ObjectFactory	\
	scap.oval.def.junos.package-info	\
	scap.oval.def.linux.ObjectFactory	\
	scap.oval.def.linux.package-info	\
	scap.oval.def.macos.ObjectFactory	\
	scap.oval.def.macos.package-info	\
	scap.oval.def.netconf.ObjectFactory	\
	scap.oval.def.netconf.package-info	\
	scap.oval.def.pixos.ObjectFactory	\
	scap.oval.def.pixos.package-info	\
	scap.oval.def.sharepoint.ObjectFactory	\
	scap.oval.def.sharepoint.package-info	\
	scap.oval.def.solaris.ObjectFactory	\
	scap.oval.def.solaris.package-info	\
	scap.oval.def.unix.ObjectFactory	\
	scap.oval.def.unix.package-info	\
	scap.oval.def.windows.ObjectFactory	\
	scap.oval.def.windows.package-info	\
	scap.oval.directives.ObjectFactory	\
	scap.oval.directives.package-info	\
	scap.oval.evaluation.ObjectFactory	\
	scap.oval.evaluation.package-info	\
	scap.oval.results.ObjectFactory	\
	scap.oval.results.package-info	\
	scap.oval.sc.aix.ObjectFactory	\
	scap.oval.sc.aix.package-info	\
	scap.oval.sc.android.ObjectFactory	\
	scap.oval.sc.android.package-info	\
	scap.oval.sc.apache.ObjectFactory	\
	scap.oval.sc.apache.package-info	\
	scap.oval.sc.appleios.ObjectFactory	\
	scap.oval.sc.appleios.package-info	\
	scap.oval.sc.asa.ObjectFactory	\
	scap.oval.sc.asa.package-info	\
	scap.oval.sc.catos.ObjectFactory	\
	scap.oval.sc.catos.package-info	\
	scap.oval.sc.core.ObjectFactory	\
	scap.oval.sc.core.package-info	\
	scap.oval.sc.esx.ObjectFactory	\
	scap.oval.sc.esx.package-info	\
	scap.oval.sc.freebsd.ObjectFactory	\
	scap.oval.sc.freebsd.package-info	\
	scap.oval.sc.hpux.ObjectFactory	\
	scap.oval.sc.hpux.package-info	\
	scap.oval.sc.independent.ObjectFactory	\
	scap.oval.sc.independent.package-info	\
	scap.oval.sc.ios.ObjectFactory	\
	scap.oval.sc.ios.package-info	\
	scap.oval.sc.iosxe.ObjectFactory	\
	scap.oval.sc.iosxe.package-info	\
	scap.oval.sc.junos.ObjectFactory	\
	scap.oval.sc.junos.package-info	\
	scap.oval.sc.linux.ObjectFactory	\
	scap.oval.sc.linux.package-info	\
	scap.oval.sc.macos.ObjectFactory	\
	scap.oval.sc.macos.package-info	\
	scap.oval.sc.netconf.ObjectFactory	\
	scap.oval.sc.netconf.package-info	\
	scap.oval.sc.pixos.ObjectFactory	\
	scap.oval.sc.pixos.package-info	\
	scap.oval.sc.sharepoint.ObjectFactory	\
	scap.oval.sc.sharepoint.package-info	\
	scap.oval.sc.solaris.ObjectFactory	\
	scap.oval.sc.solaris.package-info	\
	scap.oval.sc.unix.ObjectFactory	\
	scap.oval.sc.unix.package-info	\
	scap.oval.sc.windows.ObjectFactory	\
	scap.oval.sc.windows.package-info	\
	scap.oval.variables.ObjectFactory	\
	scap.oval.variables.package-info	\
	scap.tmsad.ObjectFactory	\
	scap.tmsad.package-info	\
	scap.xccdf.ObjectFactory	\
	scap.xccdf.package-info
