CLASSES=\
	org.gocil.diagnostics.ActionSequenceType	\
	org.gocil.diagnostics.ActionsType	\
	org.gocil.diagnostics.ActionType	\
	org.gocil.diagnostics.ObjectFactory	\
	org.gocil.diagnostics.OcilResultDiagnostics	\
	org.gocil.diagnostics.package-info	\
	org.gocil.diagnostics.QuestionnaireRef	\
	org.gocil.diagnostics.QuestionnaireType	\
	org.gocil.diagnostics.QuestionRef	\
	org.joval.scap.diagnostics.CheckDiagnostics	\
	org.joval.scap.diagnostics.Error	\
	org.joval.scap.diagnostics.ObjectFactory	\
	org.joval.scap.diagnostics.package-info	\
	org.joval.scap.diagnostics.RuleDiagnostics	\
	org.oasis.address.AddressDetails	\
	org.oasis.address.AddressLine	\
	org.oasis.address.AddressLinesType	\
	org.oasis.address.AdministrativeArea	\
	org.oasis.address.BuildingNameType	\
	org.oasis.address.CountryName	\
	org.oasis.address.Department	\
	org.oasis.address.DependentLocalityType	\
	org.oasis.address.FirmType	\
	org.oasis.address.LargeMailUserType	\
	org.oasis.address.Locality	\
	org.oasis.address.MailStopType	\
	org.oasis.address.ObjectFactory	\
	org.oasis.address.package-info	\
	org.oasis.address.PostalCode	\
	org.oasis.address.PostalRouteType	\
	org.oasis.address.PostBox	\
	org.oasis.address.PostOffice	\
	org.oasis.address.Premise	\
	org.oasis.address.PremiseNumber	\
	org.oasis.address.PremiseNumberPrefix	\
	org.oasis.address.PremiseNumberSuffix	\
	org.oasis.address.SubPremiseType	\
	org.oasis.address.Thoroughfare	\
	org.oasis.address.ThoroughfareLeadingTypeType	\
	org.oasis.address.ThoroughfareNameType	\
	org.oasis.address.ThoroughfareNumber	\
	org.oasis.address.ThoroughfareNumberPrefix	\
	org.oasis.address.ThoroughfareNumberSuffix	\
	org.oasis.address.ThoroughfarePostDirectionType	\
	org.oasis.address.ThoroughfarePreDirectionType	\
	org.oasis.address.ThoroughfareTrailingTypeType	\
	org.oasis.address.XAL	\
	org.oasis.catalog.Catalog	\
	org.oasis.catalog.DelegatePublic	\
	org.oasis.catalog.DelegateSystem	\
	org.oasis.catalog.DelegateURI	\
	org.oasis.catalog.Group	\
	org.oasis.catalog.NextCatalog	\
	org.oasis.catalog.ObjectFactory	\
	org.oasis.catalog.package-info	\
	org.oasis.catalog.Public	\
	org.oasis.catalog.RewriteSystem	\
	org.oasis.catalog.RewriteURI	\
	org.oasis.catalog.System	\
	org.oasis.catalog.SystemOrPublic	\
	org.oasis.catalog.Uri	\
	org.oasis.name.Function	\
	org.oasis.name.JointPersonName	\
	org.oasis.name.NameDetails	\
	org.oasis.name.NameDetailsType	\
	org.oasis.name.NameLineType	\
	org.oasis.name.ObjectFactory	\
	org.oasis.name.OrganizationNameDetails	\
	org.oasis.name.OrganizationNameDetailsType	\
	org.oasis.name.package-info	\
	org.oasis.name.PersonName	\
	org.oasis.name.PersonNameType	\
	org.oasis.name.XNL	\
	org.openscap.sce.results.EnvironmentType	\
	org.openscap.sce.results.ObjectFactory	\
	org.openscap.sce.results.package-info	\
	org.openscap.sce.results.SceResultsType	\
	org.openscap.sce.xccdf.LangEnumeration	\
	org.openscap.sce.xccdf.ObjectFactory	\
	org.openscap.sce.xccdf.package-info	\
	org.openscap.sce.xccdf.ScriptDataType	\
	org.purl.dc.ElementType	\
	org.purl.dc.ObjectFactory	\
	org.purl.dc.package-info	\
	org.w3c.xml.signature.CanonicalizationMethodType	\
	org.w3c.xml.signature.DigestMethodType	\
	org.w3c.xml.signature.DSAKeyValueType	\
	org.w3c.xml.signature.KeyInfoType	\
	org.w3c.xml.signature.KeyValueType	\
	org.w3c.xml.signature.ManifestType	\
	org.w3c.xml.signature.ObjectFactory	\
	org.w3c.xml.signature.ObjectType	\
	org.w3c.xml.signature.package-info	\
	org.w3c.xml.signature.PGPDataType	\
	org.w3c.xml.signature.ReferenceType	\
	org.w3c.xml.signature.RetrievalMethodType	\
	org.w3c.xml.signature.RSAKeyValueType	\
	org.w3c.xml.signature.SignatureMethodType	\
	org.w3c.xml.signature.SignaturePropertiesType	\
	org.w3c.xml.signature.SignaturePropertyType	\
	org.w3c.xml.signature.SignatureType	\
	org.w3c.xml.signature.SignatureValueType	\
	org.w3c.xml.signature.SignedInfoType	\
	org.w3c.xml.signature.SPKIDataType	\
	org.w3c.xml.signature.TransformsType	\
	org.w3c.xml.signature.TransformType	\
	org.w3c.xml.signature.X509DataType	\
	org.w3c.xml.signature.X509IssuerSerialType	\
	org.w3c.xml.xlink.ActuateType	\
	org.w3c.xml.xlink.ArcType	\
	org.w3c.xml.xlink.Extended	\
	org.w3c.xml.xlink.LocatorType	\
	org.w3c.xml.xlink.ObjectFactory	\
	org.w3c.xml.xlink.package-info	\
	org.w3c.xml.xlink.ResourceType	\
	org.w3c.xml.xlink.ShowType	\
	org.w3c.xml.xlink.Simple	\
	org.w3c.xml.xlink.TitleEltType	\
	org.w3c.xml.xlink.TypeType	\
	scap.ai.AssetIdentificationType	\
	scap.ai.AssetsType	\
	scap.ai.AssetType	\
	scap.ai.CircuitType	\
	scap.ai.ComputingDeviceType	\
	scap.ai.Cpe	\
	scap.ai.DatabaseType	\
	scap.ai.DataType	\
	scap.ai.EmailAddress	\
	scap.ai.Fqdn	\
	scap.ai.IpAddressType	\
	scap.ai.ItAssetType	\
	scap.ai.LocationPoint	\
	scap.ai.LocationRegion	\
	scap.ai.Locations	\
	scap.ai.NetworkInterfaceType	\
	scap.ai.NetworkType	\
	scap.ai.ObjectFactory	\
	scap.ai.OrganizationType	\
	scap.ai.package-info	\
	scap.ai.PersonType	\
	scap.ai.ServiceType	\
	scap.ai.SoftwareType	\
	scap.ai.SyntheticId	\
	scap.ai.SystemType	\
	scap.ai.TelephoneNumber	\
	scap.ai.WebsiteType	\
	scap.ai.WebsiteUrl	\
	scap.arf.core.AssetReportCollection	\
	scap.arf.core.ObjectFactory	\
	scap.arf.core.ObjectRef	\
	scap.arf.core.package-info	\
	scap.arf.core.RemoteResource	\
	scap.arf.core.ReportRequestType	\
	scap.arf.core.ReportType	\
	scap.arf.reporting.ObjectFactory	\
	scap.arf.reporting.package-info	\
	scap.arf.reporting.RelationshipsContainerType	\
	scap.arf.reporting.RelationshipType	\
	scap.constructs.AssetIdentification	\
	scap.constructs.ObjectFactory	\
	scap.constructs.package-info	\
	scap.cpe.dictionary.CheckType	\
	scap.cpe.dictionary.ext.ChangeDescriptionType	\
	scap.cpe.dictionary.ext.ChangeTypeType	\
	scap.cpe.dictionary.ext.DeprecatedInfoType	\
	scap.cpe.dictionary.ext.DeprecationType	\
	scap.cpe.dictionary.ext.DeprecationTypeType	\
	scap.cpe.dictionary.ext.EvidenceReferenceType	\
	scap.cpe.dictionary.ext.EvidenceType	\
	scap.cpe.dictionary.ext.ItemType	\
	scap.cpe.dictionary.ext.ObjectFactory	\
	scap.cpe.dictionary.ext.OrganizationType	\
	scap.cpe.dictionary.ext.package-info	\
	scap.cpe.dictionary.ext.ProvenanceRecordType	\
	scap.cpe.dictionary.GeneratorType	\
	scap.cpe.dictionary.ItemType	\
	scap.cpe.dictionary.ListType	\
	scap.cpe.dictionary.NotesType	\
	scap.cpe.dictionary.ObjectFactory	\
	scap.cpe.dictionary.package-info	\
	scap.cpe.dictionary.ReferencesType	\
	scap.cpe.dictionary.TextType	\
	scap.cpe.language.CheckFactRefType	\
	scap.cpe.language.CPEFactRefType	\
	scap.cpe.language.FactRefType	\
	scap.cpe.language.LogicalTestType	\
	scap.cpe.language.ObjectFactory	\
	scap.cpe.language.OperatorEnumeration	\
	scap.cpe.language.package-info	\
	scap.cpe.language.PlatformBaseType	\
	scap.cpe.language.PlatformSpecificationType	\
	scap.cpe.language.PlatformType	\
	scap.cpe.language.TextType	\
	scap.datastream.Component	\
	scap.datastream.ComponentRef	\
	scap.datastream.ContentSourceType	\
	scap.datastream.DataStream	\
	scap.datastream.DataStreamCollection	\
	scap.datastream.ExtendedComponent	\
	scap.datastream.ObjectFactory	\
	scap.datastream.package-info	\
	scap.datastream.RefListType	\
	scap.datastream.UseCaseType	\
	scap.ocil.core.ArtifactRefsType	\
	scap.ocil.core.ArtifactRefType	\
	scap.ocil.core.ArtifactResultsType	\
	scap.ocil.core.ArtifactResultType	\
	scap.ocil.core.ArtifactsType	\
	scap.ocil.core.ArtifactType	\
	scap.ocil.core.ArtifactValueType	\
	scap.ocil.core.BinaryArtifactValueType	\
	scap.ocil.core.BooleanQuestionModelType	\
	scap.ocil.core.BooleanQuestionResultType	\
	scap.ocil.core.BooleanQuestionTestActionType	\
	scap.ocil.core.BooleanQuestionType	\
	scap.ocil.core.ChoiceAnswerType	\
	scap.ocil.core.ChoiceGroupType	\
	scap.ocil.core.ChoiceQuestionResultType	\
	scap.ocil.core.ChoiceQuestionTestActionType	\
	scap.ocil.core.ChoiceQuestionType	\
	scap.ocil.core.ChoiceTestActionConditionType	\
	scap.ocil.core.ChoiceType	\
	scap.ocil.core.CompoundTestActionType	\
	scap.ocil.core.ConstantVariableType	\
	scap.ocil.core.DocumentType	\
	scap.ocil.core.EmbeddedArtifactValueType	\
	scap.ocil.core.EqualsTestActionConditionType	\
	scap.ocil.core.ExceptionalResultType	\
	scap.ocil.core.ExtensionContainerType	\
	scap.ocil.core.ExternalVariableType	\
	scap.ocil.core.GeneratorType	\
	scap.ocil.core.InstructionsType	\
	scap.ocil.core.ItemBaseType	\
	scap.ocil.core.LocalVariableType	\
	scap.ocil.core.NamedItemBaseType	\
	scap.ocil.core.NumericQuestionResultType	\
	scap.ocil.core.NumericQuestionTestActionType	\
	scap.ocil.core.NumericQuestionType	\
	scap.ocil.core.ObjectFactory	\
	scap.ocil.core.OCILType	\
	scap.ocil.core.OperationType	\
	scap.ocil.core.OperatorType	\
	scap.ocil.core.package-info	\
	scap.ocil.core.PatternTestActionConditionType	\
	scap.ocil.core.PatternType	\
	scap.ocil.core.QuestionnaireResultsType	\
	scap.ocil.core.QuestionnaireResultType	\
	scap.ocil.core.QuestionnairesType	\
	scap.ocil.core.QuestionnaireType	\
	scap.ocil.core.QuestionResultsType	\
	scap.ocil.core.QuestionResultType	\
	scap.ocil.core.QuestionsType	\
	scap.ocil.core.QuestionTestActionType	\
	scap.ocil.core.QuestionTextType	\
	scap.ocil.core.QuestionType	\
	scap.ocil.core.RangeTestActionConditionType	\
	scap.ocil.core.RangeType	\
	scap.ocil.core.RangeValueType	\
	scap.ocil.core.ReferenceArtifactValueType	\
	scap.ocil.core.ReferencesType	\
	scap.ocil.core.ReferenceType	\
	scap.ocil.core.ResultsType	\
	scap.ocil.core.SetExpressionBaseType	\
	scap.ocil.core.SetExpressionBooleanType	\
	scap.ocil.core.SetExpressionChoiceType	\
	scap.ocil.core.SetExpressionPatternType	\
	scap.ocil.core.SetExpressionRangeType	\
	scap.ocil.core.StepType	\
	scap.ocil.core.StringQuestionResultType	\
	scap.ocil.core.StringQuestionTestActionType	\
	scap.ocil.core.StringQuestionType	\
	scap.ocil.core.SubstitutionTextType	\
	scap.ocil.core.SystemTargetType	\
	scap.ocil.core.TargetsType	\
	scap.ocil.core.TestActionConditionType	\
	scap.ocil.core.TestActionRefType	\
	scap.ocil.core.TestActionResultsType	\
	scap.ocil.core.TestActionResultType	\
	scap.ocil.core.TestActionsType	\
	scap.ocil.core.TextArtifactValueType	\
	scap.ocil.core.TextType	\
	scap.ocil.core.UserType	\
	scap.ocil.core.VariableDataType	\
	scap.ocil.core.VariableSetType	\
	scap.ocil.core.VariablesType	\
	scap.ocil.core.VariableType	\
	scap.ocil.variables.ObjectFactory	\
	scap.ocil.variables.OcilVariables	\
	scap.ocil.variables.package-info	\
	scap.ocil.variables.VariablesType	\
	scap.ocil.variables.VariableType	\
	scap.oval.common.CheckEnumeration	\
	scap.oval.common.ClassEnumeration	\
	scap.oval.common.ComplexDatatypeEnumeration	\
	scap.oval.common.DeprecatedInfoType	\
	scap.oval.common.ElementMapItemType	\
	scap.oval.common.ElementMapType	\
	scap.oval.common.ExistenceEnumeration	\
	scap.oval.common.FamilyEnumeration	\
	scap.oval.common.GeneratorType	\
	scap.oval.common.MessageLevelEnumeration	\
	scap.oval.common.MessageType	\
	scap.oval.common.NotesType	\
	scap.oval.common.ObjectFactory	\
	scap.oval.common.OperationEnumeration	\
	scap.oval.common.OperatorEnumeration	\
	scap.oval.common.package-info	\
	scap.oval.common.SimpleDatatypeEnumeration	\
	scap.oval.definitions.aix.EntityStateFilesetStateType	\
	scap.oval.definitions.aix.EntityStateFixInstallationStatusType	\
	scap.oval.definitions.aix.EntityStateInterimFixStateType	\
	scap.oval.definitions.aix.FilesetObject	\
	scap.oval.definitions.aix.FilesetState	\
	scap.oval.definitions.aix.FilesetTest	\
	scap.oval.definitions.aix.FixObject	\
	scap.oval.definitions.aix.FixState	\
	scap.oval.definitions.aix.FixTest	\
	scap.oval.definitions.aix.InterimFixObject	\
	scap.oval.definitions.aix.InterimFixState	\
	scap.oval.definitions.aix.InterimFixTest	\
	scap.oval.definitions.aix.NoObject	\
	scap.oval.definitions.aix.NoState	\
	scap.oval.definitions.aix.NoTest	\
	scap.oval.definitions.aix.ObjectFactory	\
	scap.oval.definitions.aix.OslevelObject	\
	scap.oval.definitions.aix.OslevelState	\
	scap.oval.definitions.aix.OslevelTest	\
	scap.oval.definitions.aix.package-info	\
	scap.oval.definitions.android.AppmanagerObject	\
	scap.oval.definitions.android.AppmanagerState	\
	scap.oval.definitions.android.AppmanagerTest	\
	scap.oval.definitions.android.BluetoothObject	\
	scap.oval.definitions.android.BluetoothState	\
	scap.oval.definitions.android.BluetoothTest	\
	scap.oval.definitions.android.CameraObject	\
	scap.oval.definitions.android.CameraState	\
	scap.oval.definitions.android.CameraTest	\
	scap.oval.definitions.android.CertificateObject	\
	scap.oval.definitions.android.CertificateState	\
	scap.oval.definitions.android.CertificateTest	\
	scap.oval.definitions.android.DevicesettingsObject	\
	scap.oval.definitions.android.DevicesettingsState	\
	scap.oval.definitions.android.DevicesettingsTest	\
	scap.oval.definitions.android.EncryptionObject	\
	scap.oval.definitions.android.EncryptionState	\
	scap.oval.definitions.android.EncryptionTest	\
	scap.oval.definitions.android.EntityStateEncryptionStatusType	\
	scap.oval.definitions.android.EntityStateKeyguardDisabledFeaturesType	\
	scap.oval.definitions.android.EntityStateNetworkType	\
	scap.oval.definitions.android.EntityStatePasswordQualityType	\
	scap.oval.definitions.android.EntityStateWifiAuthAlgorithmType	\
	scap.oval.definitions.android.EntityStateWifiCurrentStatusType	\
	scap.oval.definitions.android.EntityStateWifiGroupCipherType	\
	scap.oval.definitions.android.EntityStateWifiKeyMgmtType	\
	scap.oval.definitions.android.EntityStateWifiPairwiseCipherType	\
	scap.oval.definitions.android.EntityStateWifiProtocolType	\
	scap.oval.definitions.android.LocationserviceObject	\
	scap.oval.definitions.android.LocationserviceState	\
	scap.oval.definitions.android.LocationserviceTest	\
	scap.oval.definitions.android.NetworkObject	\
	scap.oval.definitions.android.NetworkState	\
	scap.oval.definitions.android.NetworkTest	\
	scap.oval.definitions.android.ObjectFactory	\
	scap.oval.definitions.android.package-info	\
	scap.oval.definitions.android.PasswordObject	\
	scap.oval.definitions.android.PasswordState	\
	scap.oval.definitions.android.PasswordTest	\
	scap.oval.definitions.android.SystemdetailsObject	\
	scap.oval.definitions.android.SystemdetailsState	\
	scap.oval.definitions.android.SystemdetailsTest	\
	scap.oval.definitions.android.TelephonyObject	\
	scap.oval.definitions.android.TelephonyState	\
	scap.oval.definitions.android.TelephonyTest	\
	scap.oval.definitions.android.WifinetworkObject	\
	scap.oval.definitions.android.WifinetworkState	\
	scap.oval.definitions.android.WifinetworkTest	\
	scap.oval.definitions.android.WifiObject	\
	scap.oval.definitions.android.WifiState	\
	scap.oval.definitions.android.WifiTest	\
	scap.oval.definitions.apache.HttpdObject	\
	scap.oval.definitions.apache.HttpdState	\
	scap.oval.definitions.apache.HttpdTest	\
	scap.oval.definitions.apache.ObjectFactory	\
	scap.oval.definitions.apache.package-info	\
	scap.oval.definitions.appleios.GlobalrestrictionsObject	\
	scap.oval.definitions.appleios.GlobalrestrictionsState	\
	scap.oval.definitions.appleios.GlobalrestrictionsTest	\
	scap.oval.definitions.appleios.ObjectFactory	\
	scap.oval.definitions.appleios.package-info	\
	scap.oval.definitions.appleios.PasscodepolicyObject	\
	scap.oval.definitions.appleios.PasscodepolicyState	\
	scap.oval.definitions.appleios.PasscodepolicyTest	\
	scap.oval.definitions.appleios.ProfileObject	\
	scap.oval.definitions.appleios.ProfileState	\
	scap.oval.definitions.appleios.ProfileTest	\
	scap.oval.definitions.asa.AclObject	\
	scap.oval.definitions.asa.AclState	\
	scap.oval.definitions.asa.AclTest	\
	scap.oval.definitions.asa.ClassMapObject	\
	scap.oval.definitions.asa.ClassMapState	\
	scap.oval.definitions.asa.ClassMapTest	\
	scap.oval.definitions.asa.EntityObjectAccessListIPVersionType	\
	scap.oval.definitions.asa.EntityStateAccessListInterfaceDirectionType	\
	scap.oval.definitions.asa.EntityStateAccessListIPVersionType	\
	scap.oval.definitions.asa.EntityStateAccessListUseType	\
	scap.oval.definitions.asa.EntityStateApplyServicePolicyType	\
	scap.oval.definitions.asa.EntityStateClassMapType	\
	scap.oval.definitions.asa.EntityStateInpsectionType	\
	scap.oval.definitions.asa.EntityStateMatchType	\
	scap.oval.definitions.asa.EntityStateSNMPAuthStringType	\
	scap.oval.definitions.asa.EntityStateSNMPPrivStringType	\
	scap.oval.definitions.asa.EntityStateSNMPSecLevelStringType	\
	scap.oval.definitions.asa.EntityStateSNMPVersionStringType	\
	scap.oval.definitions.asa.InterfaceObject	\
	scap.oval.definitions.asa.InterfaceState	\
	scap.oval.definitions.asa.InterfaceTest	\
	scap.oval.definitions.asa.LineObject	\
	scap.oval.definitions.asa.LineState	\
	scap.oval.definitions.asa.LineTest	\
	scap.oval.definitions.asa.ObjectFactory	\
	scap.oval.definitions.asa.package-info	\
	scap.oval.definitions.asa.PolicyMapObject	\
	scap.oval.definitions.asa.PolicyMapState	\
	scap.oval.definitions.asa.PolicyMapTest	\
	scap.oval.definitions.asa.ServicePolicyObject	\
	scap.oval.definitions.asa.ServicePolicyState	\
	scap.oval.definitions.asa.ServicePolicyTest	\
	scap.oval.definitions.asa.SnmpGroupObject	\
	scap.oval.definitions.asa.SnmpGroupState	\
	scap.oval.definitions.asa.SnmpGroupTest	\
	scap.oval.definitions.asa.SnmpHostObject	\
	scap.oval.definitions.asa.SnmpHostState	\
	scap.oval.definitions.asa.SnmpHostTest	\
	scap.oval.definitions.asa.SnmpUserObject	\
	scap.oval.definitions.asa.SnmpUserState	\
	scap.oval.definitions.asa.SnmpUserTest	\
	scap.oval.definitions.asa.TcpMapObject	\
	scap.oval.definitions.asa.TcpMapState	\
	scap.oval.definitions.asa.TcpMapTest	\
	scap.oval.definitions.asa.VersionObject	\
	scap.oval.definitions.asa.VersionState	\
	scap.oval.definitions.asa.VersionTest	\
	scap.oval.definitions.catos.LineObject	\
	scap.oval.definitions.catos.LineState	\
	scap.oval.definitions.catos.LineTest	\
	scap.oval.definitions.catos.ModuleObject	\
	scap.oval.definitions.catos.ModuleState	\
	scap.oval.definitions.catos.ModuleTest	\
	scap.oval.definitions.catos.ObjectFactory	\
	scap.oval.definitions.catos.package-info	\
	scap.oval.definitions.catos.Version55Object	\
	scap.oval.definitions.catos.Version55State	\
	scap.oval.definitions.catos.Version55Test	\
	scap.oval.definitions.catos.VersionObject	\
	scap.oval.definitions.catos.VersionState	\
	scap.oval.definitions.catos.VersionTest	\
	scap.oval.definitions.core.AffectedType	\
	scap.oval.definitions.core.ArithmeticEnumeration	\
	scap.oval.definitions.core.ArithmeticFunctionType	\
	scap.oval.definitions.core.BeginFunctionType	\
	scap.oval.definitions.core.ConcatFunctionType	\
	scap.oval.definitions.core.ConstantVariable	\
	scap.oval.definitions.core.CountFunctionType	\
	scap.oval.definitions.core.CriteriaType	\
	scap.oval.definitions.core.CriterionType	\
	scap.oval.definitions.core.DateTimeFormatEnumeration	\
	scap.oval.definitions.core.DefinitionsType	\
	scap.oval.definitions.core.DefinitionType	\
	scap.oval.definitions.core.EndFunctionType	\
	scap.oval.definitions.core.EntityComplexBaseType	\
	scap.oval.definitions.core.EntityObjectAnySimpleType	\
	scap.oval.definitions.core.EntityObjectBinaryType	\
	scap.oval.definitions.core.EntityObjectBoolType	\
	scap.oval.definitions.core.EntityObjectFieldType	\
	scap.oval.definitions.core.EntityObjectFloatType	\
	scap.oval.definitions.core.EntityObjectIntType	\
	scap.oval.definitions.core.EntityObjectIPAddressStringType	\
	scap.oval.definitions.core.EntityObjectIPAddressType	\
	scap.oval.definitions.core.EntityObjectRecordType	\
	scap.oval.definitions.core.EntityObjectStringType	\
	scap.oval.definitions.core.EntityObjectVersionType	\
	scap.oval.definitions.core.EntitySimpleBaseType	\
	scap.oval.definitions.core.EntityStateAnySimpleType	\
	scap.oval.definitions.core.EntityStateBinaryType	\
	scap.oval.definitions.core.EntityStateBoolType	\
	scap.oval.definitions.core.EntityStateComplexBaseType	\
	scap.oval.definitions.core.EntityStateEVRStringType	\
	scap.oval.definitions.core.EntityStateFieldType	\
	scap.oval.definitions.core.EntityStateFileSetRevisionType	\
	scap.oval.definitions.core.EntityStateFloatType	\
	scap.oval.definitions.core.EntityStateIntType	\
	scap.oval.definitions.core.EntityStateIOSVersionType	\
	scap.oval.definitions.core.EntityStateIPAddressStringType	\
	scap.oval.definitions.core.EntityStateIPAddressType	\
	scap.oval.definitions.core.EntityStateRecordType	\
	scap.oval.definitions.core.EntityStateSimpleBaseType	\
	scap.oval.definitions.core.EntityStateStringType	\
	scap.oval.definitions.core.EntityStateVersionType	\
	scap.oval.definitions.core.EscapeRegexFunctionType	\
	scap.oval.definitions.core.ExtendDefinitionType	\
	scap.oval.definitions.core.ExternalVariable	\
	scap.oval.definitions.core.Filter	\
	scap.oval.definitions.core.FilterActionEnumeration	\
	scap.oval.definitions.core.GlobToRegexFunctionType	\
	scap.oval.definitions.core.LiteralComponentType	\
	scap.oval.definitions.core.LocalVariable	\
	scap.oval.definitions.core.MetadataType	\
	scap.oval.definitions.core.Notes	\
	scap.oval.definitions.core.ObjectComponentType	\
	scap.oval.definitions.core.ObjectFactory	\
	scap.oval.definitions.core.ObjectRefType	\
	scap.oval.definitions.core.ObjectsType	\
	scap.oval.definitions.core.ObjectType	\
	scap.oval.definitions.core.OvalDefinitions	\
	scap.oval.definitions.core.package-info	\
	scap.oval.definitions.core.PossibleRestrictionType	\
	scap.oval.definitions.core.PossibleValueType	\
	scap.oval.definitions.core.ReferenceType	\
	scap.oval.definitions.core.RegexCaptureFunctionType	\
	scap.oval.definitions.core.RestrictionType	\
	scap.oval.definitions.core.Set	\
	scap.oval.definitions.core.SetOperatorEnumeration	\
	scap.oval.definitions.core.SplitFunctionType	\
	scap.oval.definitions.core.StateRefType	\
	scap.oval.definitions.core.StatesType	\
	scap.oval.definitions.core.StateType	\
	scap.oval.definitions.core.SubstringFunctionType	\
	scap.oval.definitions.core.TestsType	\
	scap.oval.definitions.core.TestType	\
	scap.oval.definitions.core.TimeDifferenceFunctionType	\
	scap.oval.definitions.core.UniqueFunctionType	\
	scap.oval.definitions.core.ValueType	\
	scap.oval.definitions.core.VariableComponentType	\
	scap.oval.definitions.core.VariablesType	\
	scap.oval.definitions.core.VariableType	\
	scap.oval.definitions.esx.EntityStateClassificationType	\
	scap.oval.definitions.esx.EntityStateSupportLevelType	\
	scap.oval.definitions.esx.ObjectFactory	\
	scap.oval.definitions.esx.package-info	\
	scap.oval.definitions.esx.Patch56Behaviors	\
	scap.oval.definitions.esx.Patch56Object	\
	scap.oval.definitions.esx.Patch56State	\
	scap.oval.definitions.esx.Patch56Test	\
	scap.oval.definitions.esx.PatchBehaviors	\
	scap.oval.definitions.esx.PatchObject	\
	scap.oval.definitions.esx.PatchState	\
	scap.oval.definitions.esx.PatchTest	\
	scap.oval.definitions.esx.VersionObject	\
	scap.oval.definitions.esx.VersionState	\
	scap.oval.definitions.esx.VersionTest	\
	scap.oval.definitions.esx.ViSdkManagedEntityBehaviors	\
	scap.oval.definitions.esx.VisdkmanagedobjectObject	\
	scap.oval.definitions.esx.VisdkmanagedobjectState	\
	scap.oval.definitions.esx.VisdkmanagedobjectTest	\
	scap.oval.definitions.freebsd.ObjectFactory	\
	scap.oval.definitions.freebsd.package-info	\
	scap.oval.definitions.freebsd.PortinfoObject	\
	scap.oval.definitions.freebsd.PortinfoState	\
	scap.oval.definitions.freebsd.PortinfoTest	\
	scap.oval.definitions.hpux.GetconfObject	\
	scap.oval.definitions.hpux.GetconfState	\
	scap.oval.definitions.hpux.GetconfTest	\
	scap.oval.definitions.hpux.NddObject	\
	scap.oval.definitions.hpux.NddState	\
	scap.oval.definitions.hpux.NddTest	\
	scap.oval.definitions.hpux.ObjectFactory	\
	scap.oval.definitions.hpux.package-info	\
	scap.oval.definitions.hpux.Patch53Behaviors	\
	scap.oval.definitions.hpux.Patch53Object	\
	scap.oval.definitions.hpux.Patch53State	\
	scap.oval.definitions.hpux.Patch53Test	\
	scap.oval.definitions.hpux.PatchObject	\
	scap.oval.definitions.hpux.PatchState	\
	scap.oval.definitions.hpux.PatchTest	\
	scap.oval.definitions.hpux.SwlistObject	\
	scap.oval.definitions.hpux.SwlistState	\
	scap.oval.definitions.hpux.SwlistTest	\
	scap.oval.definitions.hpux.TrustedObject	\
	scap.oval.definitions.hpux.TrustedState	\
	scap.oval.definitions.hpux.TrustedTest	\
	scap.oval.definitions.independent.EntityObjectEngineType	\
	scap.oval.definitions.independent.EntityObjectHashTypeType	\
	scap.oval.definitions.independent.EntityObjectVariableRefType	\
	scap.oval.definitions.independent.EntityStateEngineType	\
	scap.oval.definitions.independent.EntityStateFamilyType	\
	scap.oval.definitions.independent.EntityStateHashTypeType	\
	scap.oval.definitions.independent.EntityStateLdaptypeType	\
	scap.oval.definitions.independent.EntityStateVariableRefType	\
	scap.oval.definitions.independent.EntityStateWindowsViewType	\
	scap.oval.definitions.independent.Environmentvariable58Object	\
	scap.oval.definitions.independent.Environmentvariable58State	\
	scap.oval.definitions.independent.Environmentvariable58Test	\
	scap.oval.definitions.independent.EnvironmentvariableObject	\
	scap.oval.definitions.independent.EnvironmentvariableState	\
	scap.oval.definitions.independent.EnvironmentvariableTest	\
	scap.oval.definitions.independent.FamilyObject	\
	scap.oval.definitions.independent.FamilyState	\
	scap.oval.definitions.independent.FamilyTest	\
	scap.oval.definitions.independent.FileBehaviors	\
	scap.oval.definitions.independent.Filehash58Object	\
	scap.oval.definitions.independent.Filehash58State	\
	scap.oval.definitions.independent.Filehash58Test	\
	scap.oval.definitions.independent.FilehashObject	\
	scap.oval.definitions.independent.FilehashState	\
	scap.oval.definitions.independent.FilehashTest	\
	scap.oval.definitions.independent.Ldap57Object	\
	scap.oval.definitions.independent.Ldap57State	\
	scap.oval.definitions.independent.Ldap57Test	\
	scap.oval.definitions.independent.LdapBehaviors	\
	scap.oval.definitions.independent.LdapObject	\
	scap.oval.definitions.independent.LdapState	\
	scap.oval.definitions.independent.LdapTest	\
	scap.oval.definitions.independent.ObjectFactory	\
	scap.oval.definitions.independent.package-info	\
	scap.oval.definitions.independent.Sql57Object	\
	scap.oval.definitions.independent.Sql57State	\
	scap.oval.definitions.independent.Sql57Test	\
	scap.oval.definitions.independent.SqlObject	\
	scap.oval.definitions.independent.SqlState	\
	scap.oval.definitions.independent.SqlTest	\
	scap.oval.definitions.independent.Textfilecontent54Behaviors	\
	scap.oval.definitions.independent.Textfilecontent54Object	\
	scap.oval.definitions.independent.Textfilecontent54State	\
	scap.oval.definitions.independent.Textfilecontent54Test	\
	scap.oval.definitions.independent.TextfilecontentObject	\
	scap.oval.definitions.independent.TextfilecontentState	\
	scap.oval.definitions.independent.TextfilecontentTest	\
	scap.oval.definitions.independent.UnknownTest	\
	scap.oval.definitions.independent.VariableObject	\
	scap.oval.definitions.independent.VariableState	\
	scap.oval.definitions.independent.VariableTest	\
	scap.oval.definitions.independent.XmlfilecontentObject	\
	scap.oval.definitions.independent.XmlfilecontentState	\
	scap.oval.definitions.independent.XmlfilecontentTest	\
	scap.oval.definitions.ios.AclObject	\
	scap.oval.definitions.ios.AclState	\
	scap.oval.definitions.ios.AclTest	\
	scap.oval.definitions.ios.BgpneighborObject	\
	scap.oval.definitions.ios.BgpneighborState	\
	scap.oval.definitions.ios.BgpneighborTest	\
	scap.oval.definitions.ios.EntityObjectAccessListIPVersionType	\
	scap.oval.definitions.ios.EntityObjectRoutingProtocolType	\
	scap.oval.definitions.ios.EntityStateAccessListInterfaceDirectionType	\
	scap.oval.definitions.ios.EntityStateAccessListIPVersionType	\
	scap.oval.definitions.ios.EntityStateAccessListUseType	\
	scap.oval.definitions.ios.EntityStateRoutingAuthTypeStringType	\
	scap.oval.definitions.ios.EntityStateRoutingProtocolType	\
	scap.oval.definitions.ios.EntityStateSNMPAuthStringType	\
	scap.oval.definitions.ios.EntityStateSNMPModeStringType	\
	scap.oval.definitions.ios.EntityStateSNMPPrivStringType	\
	scap.oval.definitions.ios.EntityStateSNMPSecLevelStringType	\
	scap.oval.definitions.ios.EntityStateSNMPVersionStringType	\
	scap.oval.definitions.ios.EntityStateSwitchportModeType	\
	scap.oval.definitions.ios.EntityStateTrainIdentifierType	\
	scap.oval.definitions.ios.EntityStateTrunkEncapType	\
	scap.oval.definitions.ios.GlobalObject	\
	scap.oval.definitions.ios.GlobalState	\
	scap.oval.definitions.ios.GlobalTest	\
	scap.oval.definitions.ios.InterfaceObject	\
	scap.oval.definitions.ios.InterfaceState	\
	scap.oval.definitions.ios.InterfaceTest	\
	scap.oval.definitions.ios.LineObject	\
	scap.oval.definitions.ios.LineState	\
	scap.oval.definitions.ios.LineTest	\
	scap.oval.definitions.ios.ObjectFactory	\
	scap.oval.definitions.ios.package-info	\
	scap.oval.definitions.ios.RouterObject	\
	scap.oval.definitions.ios.RouterState	\
	scap.oval.definitions.ios.RouterTest	\
	scap.oval.definitions.ios.RoutingprotocolauthintfObject	\
	scap.oval.definitions.ios.RoutingprotocolauthintfState	\
	scap.oval.definitions.ios.RoutingprotocolauthintfTest	\
	scap.oval.definitions.ios.SectionObject	\
	scap.oval.definitions.ios.SectionState	\
	scap.oval.definitions.ios.SectionTest	\
	scap.oval.definitions.ios.SnmpcommunityObject	\
	scap.oval.definitions.ios.SnmpcommunityState	\
	scap.oval.definitions.ios.SnmpcommunityTest	\
	scap.oval.definitions.ios.SnmpgroupObject	\
	scap.oval.definitions.ios.SnmpgroupState	\
	scap.oval.definitions.ios.SnmpgroupTest	\
	scap.oval.definitions.ios.SnmphostObject	\
	scap.oval.definitions.ios.SnmphostState	\
	scap.oval.definitions.ios.SnmphostTest	\
	scap.oval.definitions.ios.SnmpObject	\
	scap.oval.definitions.ios.SnmpState	\
	scap.oval.definitions.ios.SnmpTest	\
	scap.oval.definitions.ios.SnmpuserObject	\
	scap.oval.definitions.ios.SnmpuserState	\
	scap.oval.definitions.ios.SnmpuserTest	\
	scap.oval.definitions.ios.SnmpviewObject	\
	scap.oval.definitions.ios.SnmpviewState	\
	scap.oval.definitions.ios.SnmpviewTest	\
	scap.oval.definitions.ios.TclshObject	\
	scap.oval.definitions.ios.TclshState	\
	scap.oval.definitions.ios.TclshTest	\
	scap.oval.definitions.ios.Version55Object	\
	scap.oval.definitions.ios.Version55State	\
	scap.oval.definitions.ios.Version55Test	\
	scap.oval.definitions.ios.VersionObject	\
	scap.oval.definitions.ios.VersionState	\
	scap.oval.definitions.ios.VersionTest	\
	scap.oval.definitions.iosxe.AclObject	\
	scap.oval.definitions.iosxe.AclState	\
	scap.oval.definitions.iosxe.AclTest	\
	scap.oval.definitions.iosxe.BgpneighborObject	\
	scap.oval.definitions.iosxe.BgpneighborState	\
	scap.oval.definitions.iosxe.BgpneighborTest	\
	scap.oval.definitions.iosxe.EntityObjectAccessListIPVersionType	\
	scap.oval.definitions.iosxe.EntityObjectRoutingProtocolType	\
	scap.oval.definitions.iosxe.EntityStateAccessListInterfaceDirectionType	\
	scap.oval.definitions.iosxe.EntityStateAccessListIPVersionType	\
	scap.oval.definitions.iosxe.EntityStateAccessListUseType	\
	scap.oval.definitions.iosxe.EntityStateRoutingAuthTypeStringType	\
	scap.oval.definitions.iosxe.EntityStateRoutingProtocolType	\
	scap.oval.definitions.iosxe.EntityStateSNMPAuthStringType	\
	scap.oval.definitions.iosxe.EntityStateSNMPModeStringType	\
	scap.oval.definitions.iosxe.EntityStateSNMPPrivStringType	\
	scap.oval.definitions.iosxe.EntityStateSNMPSecLevelStringType	\
	scap.oval.definitions.iosxe.EntityStateSNMPVersionStringType	\
	scap.oval.definitions.iosxe.EntityStateSwitchportModeType	\
	scap.oval.definitions.iosxe.EntityStateTrunkEncapType	\
	scap.oval.definitions.iosxe.GlobalObject	\
	scap.oval.definitions.iosxe.GlobalState	\
	scap.oval.definitions.iosxe.GlobalTest	\
	scap.oval.definitions.iosxe.InterfaceObject	\
	scap.oval.definitions.iosxe.InterfaceState	\
	scap.oval.definitions.iosxe.InterfaceTest	\
	scap.oval.definitions.iosxe.LineObject	\
	scap.oval.definitions.iosxe.LineState	\
	scap.oval.definitions.iosxe.LineTest	\
	scap.oval.definitions.iosxe.ObjectFactory	\
	scap.oval.definitions.iosxe.package-info	\
	scap.oval.definitions.iosxe.RouterObject	\
	scap.oval.definitions.iosxe.RouterState	\
	scap.oval.definitions.iosxe.RouterTest	\
	scap.oval.definitions.iosxe.RoutingprotocolauthintfObject	\
	scap.oval.definitions.iosxe.RoutingprotocolauthintfState	\
	scap.oval.definitions.iosxe.RoutingprotocolauthintfTest	\
	scap.oval.definitions.iosxe.SectionObject	\
	scap.oval.definitions.iosxe.SectionState	\
	scap.oval.definitions.iosxe.SectionTest	\
	scap.oval.definitions.iosxe.SnmpcommunityObject	\
	scap.oval.definitions.iosxe.SnmpcommunityState	\
	scap.oval.definitions.iosxe.SnmpcommunityTest	\
	scap.oval.definitions.iosxe.SnmpgroupObject	\
	scap.oval.definitions.iosxe.SnmpgroupState	\
	scap.oval.definitions.iosxe.SnmpgroupTest	\
	scap.oval.definitions.iosxe.SnmphostObject	\
	scap.oval.definitions.iosxe.SnmphostState	\
	scap.oval.definitions.iosxe.SnmphostTest	\
	scap.oval.definitions.iosxe.SnmpuserObject	\
	scap.oval.definitions.iosxe.SnmpuserState	\
	scap.oval.definitions.iosxe.SnmpuserTest	\
	scap.oval.definitions.iosxe.SnmpviewObject	\
	scap.oval.definitions.iosxe.SnmpviewState	\
	scap.oval.definitions.iosxe.SnmpviewTest	\
	scap.oval.definitions.iosxe.VersionObject	\
	scap.oval.definitions.iosxe.VersionState	\
	scap.oval.definitions.iosxe.VersionTest	\
	scap.oval.definitions.junos.EntityStateJunosReleaseTypeType	\
	scap.oval.definitions.junos.ObjectFactory	\
	scap.oval.definitions.junos.package-info	\
	scap.oval.definitions.junos.ShowObject	\
	scap.oval.definitions.junos.ShowState	\
	scap.oval.definitions.junos.ShowTest	\
	scap.oval.definitions.junos.VersionObject	\
	scap.oval.definitions.junos.VersionState	\
	scap.oval.definitions.junos.VersionTest	\
	scap.oval.definitions.junos.XmlConfigObject	\
	scap.oval.definitions.junos.XmlConfigState	\
	scap.oval.definitions.junos.XmlConfigTest	\
	scap.oval.definitions.junos.XmlShowObject	\
	scap.oval.definitions.junos.XmlShowState	\
	scap.oval.definitions.junos.XmlShowTest	\
	scap.oval.definitions.linux.DpkginfoObject	\
	scap.oval.definitions.linux.DpkginfoState	\
	scap.oval.definitions.linux.DpkginfoTest	\
	scap.oval.definitions.linux.EntityStateProtocolType	\
	scap.oval.definitions.linux.EntityStateRpmVerifyResultType	\
	scap.oval.definitions.linux.FileBehaviors	\
	scap.oval.definitions.linux.IflistenersObject	\
	scap.oval.definitions.linux.IflistenersState	\
	scap.oval.definitions.linux.IflistenersTest	\
	scap.oval.definitions.linux.InetlisteningserversObject	\
	scap.oval.definitions.linux.InetlisteningserversState	\
	scap.oval.definitions.linux.InetlisteningserversTest	\
	scap.oval.definitions.linux.ObjectFactory	\
	scap.oval.definitions.linux.package-info	\
	scap.oval.definitions.linux.PartitionObject	\
	scap.oval.definitions.linux.PartitionState	\
	scap.oval.definitions.linux.PartitionTest	\
	scap.oval.definitions.linux.RpmInfoBehaviors	\
	scap.oval.definitions.linux.RpminfoObject	\
	scap.oval.definitions.linux.RpminfoState	\
	scap.oval.definitions.linux.RpminfoTest	\
	scap.oval.definitions.linux.RpmVerifyBehaviors	\
	scap.oval.definitions.linux.RpmVerifyFileBehaviors	\
	scap.oval.definitions.linux.RpmverifyfileObject	\
	scap.oval.definitions.linux.RpmverifyfileState	\
	scap.oval.definitions.linux.RpmverifyfileTest	\
	scap.oval.definitions.linux.RpmverifyObject	\
	scap.oval.definitions.linux.RpmVerifyPackageBehaviors	\
	scap.oval.definitions.linux.RpmverifypackageObject	\
	scap.oval.definitions.linux.RpmverifypackageState	\
	scap.oval.definitions.linux.RpmverifypackageTest	\
	scap.oval.definitions.linux.RpmverifyState	\
	scap.oval.definitions.linux.RpmverifyTest	\
	scap.oval.definitions.linux.SelinuxbooleanObject	\
	scap.oval.definitions.linux.SelinuxbooleanState	\
	scap.oval.definitions.linux.SelinuxbooleanTest	\
	scap.oval.definitions.linux.SelinuxsecuritycontextObject	\
	scap.oval.definitions.linux.SelinuxsecuritycontextState	\
	scap.oval.definitions.linux.SelinuxsecuritycontextTest	\
	scap.oval.definitions.linux.SlackwarepkginfoObject	\
	scap.oval.definitions.linux.SlackwarepkginfoState	\
	scap.oval.definitions.linux.SlackwarepkginfoTest	\
	scap.oval.definitions.linux.SystemdunitdependencyObject	\
	scap.oval.definitions.linux.SystemdunitdependencyState	\
	scap.oval.definitions.linux.SystemdunitdependencyTest	\
	scap.oval.definitions.linux.SystemdunitpropertyObject	\
	scap.oval.definitions.linux.SystemdunitpropertyState	\
	scap.oval.definitions.linux.SystemdunitpropertyTest	\
	scap.oval.definitions.macos.AccountinfoObject	\
	scap.oval.definitions.macos.AccountinfoState	\
	scap.oval.definitions.macos.AccountinfoTest	\
	scap.oval.definitions.macos.AuthorizationdbObject	\
	scap.oval.definitions.macos.AuthorizationdbState	\
	scap.oval.definitions.macos.AuthorizationdbTest	\
	scap.oval.definitions.macos.CorestorageObject	\
	scap.oval.definitions.macos.CorestorageState	\
	scap.oval.definitions.macos.CorestorageTest	\
	scap.oval.definitions.macos.DiskutilObject	\
	scap.oval.definitions.macos.DiskutilState	\
	scap.oval.definitions.macos.DiskutilTest	\
	scap.oval.definitions.macos.EntityObjectDataTypeType	\
	scap.oval.definitions.macos.EntityStateDataTypeType	\
	scap.oval.definitions.macos.EntityStatePermissionCompareType	\
	scap.oval.definitions.macos.EntityStatePlistTypeType	\
	scap.oval.definitions.macos.GatekeeperObject	\
	scap.oval.definitions.macos.GatekeeperState	\
	scap.oval.definitions.macos.GatekeeperTest	\
	scap.oval.definitions.macos.Inetlisteningserver510Object	\
	scap.oval.definitions.macos.Inetlisteningserver510State	\
	scap.oval.definitions.macos.Inetlisteningserver510Test	\
	scap.oval.definitions.macos.InetlisteningserversObject	\
	scap.oval.definitions.macos.InetlisteningserversState	\
	scap.oval.definitions.macos.InetlisteningserversTest	\
	scap.oval.definitions.macos.KeychainObject	\
	scap.oval.definitions.macos.KeychainState	\
	scap.oval.definitions.macos.KeychainTest	\
	scap.oval.definitions.macos.LaunchdObject	\
	scap.oval.definitions.macos.LaunchdState	\
	scap.oval.definitions.macos.LaunchdTest	\
	scap.oval.definitions.macos.NvramObject	\
	scap.oval.definitions.macos.NvramState	\
	scap.oval.definitions.macos.NvramTest	\
	scap.oval.definitions.macos.ObjectFactory	\
	scap.oval.definitions.macos.package-info	\
	scap.oval.definitions.macos.Plist510Object	\
	scap.oval.definitions.macos.Plist510State	\
	scap.oval.definitions.macos.Plist510Test	\
	scap.oval.definitions.macos.PlistObject	\
	scap.oval.definitions.macos.PlistState	\
	scap.oval.definitions.macos.PlistTest	\
	scap.oval.definitions.macos.Pwpolicy59Object	\
	scap.oval.definitions.macos.Pwpolicy59State	\
	scap.oval.definitions.macos.Pwpolicy59Test	\
	scap.oval.definitions.macos.PwpolicyObject	\
	scap.oval.definitions.macos.PwpolicyState	\
	scap.oval.definitions.macos.PwpolicyTest	\
	scap.oval.definitions.macos.RlimitObject	\
	scap.oval.definitions.macos.RlimitState	\
	scap.oval.definitions.macos.RlimitTest	\
	scap.oval.definitions.macos.SoftwareupdateObject	\
	scap.oval.definitions.macos.SoftwareupdateState	\
	scap.oval.definitions.macos.SoftwareupdateTest	\
	scap.oval.definitions.macos.SystemprofilerObject	\
	scap.oval.definitions.macos.SystemprofilerState	\
	scap.oval.definitions.macos.SystemprofilerTest	\
	scap.oval.definitions.macos.SystemsetupObject	\
	scap.oval.definitions.macos.SystemsetupState	\
	scap.oval.definitions.macos.SystemsetupTest	\
	scap.oval.definitions.netconf.ConfigObject	\
	scap.oval.definitions.netconf.ConfigState	\
	scap.oval.definitions.netconf.ConfigTest	\
	scap.oval.definitions.netconf.ObjectFactory	\
	scap.oval.definitions.netconf.package-info	\
	scap.oval.definitions.pixos.LineObject	\
	scap.oval.definitions.pixos.LineState	\
	scap.oval.definitions.pixos.LineTest	\
	scap.oval.definitions.pixos.ObjectFactory	\
	scap.oval.definitions.pixos.package-info	\
	scap.oval.definitions.pixos.VersionObject	\
	scap.oval.definitions.pixos.VersionState	\
	scap.oval.definitions.pixos.VersionTest	\
	scap.oval.definitions.sharepoint.BestbetObject	\
	scap.oval.definitions.sharepoint.BestbetState	\
	scap.oval.definitions.sharepoint.BestbetTest	\
	scap.oval.definitions.sharepoint.EntityObjectUrlZoneType	\
	scap.oval.definitions.sharepoint.EntityStateEventSeverityType	\
	scap.oval.definitions.sharepoint.EntityStatePolicyFeatureStateType	\
	scap.oval.definitions.sharepoint.EntityStatePolicyRoleType	\
	scap.oval.definitions.sharepoint.EntityStateTraceSeverityType	\
	scap.oval.definitions.sharepoint.EntityStateUrlZoneType	\
	scap.oval.definitions.sharepoint.InfopolicycollObject	\
	scap.oval.definitions.sharepoint.InfopolicycollState	\
	scap.oval.definitions.sharepoint.InfopolicycollTest	\
	scap.oval.definitions.sharepoint.ObjectFactory	\
	scap.oval.definitions.sharepoint.package-info	\
	scap.oval.definitions.sharepoint.SpantivirussettingsObject	\
	scap.oval.definitions.sharepoint.SpantivirussettingsState	\
	scap.oval.definitions.sharepoint.SpantivirussettingsTest	\
	scap.oval.definitions.sharepoint.SpcrawlruleObject	\
	scap.oval.definitions.sharepoint.SpcrawlruleState	\
	scap.oval.definitions.sharepoint.SpcrawlruleTest	\
	scap.oval.definitions.sharepoint.SpdiagnosticslevelObject	\
	scap.oval.definitions.sharepoint.SpdiagnosticslevelState	\
	scap.oval.definitions.sharepoint.SpdiagnosticslevelTest	\
	scap.oval.definitions.sharepoint.SpdiagnosticsserviceObject	\
	scap.oval.definitions.sharepoint.SpdiagnosticsserviceState	\
	scap.oval.definitions.sharepoint.SpdiagnosticsserviceTest	\
	scap.oval.definitions.sharepoint.SpgroupObject	\
	scap.oval.definitions.sharepoint.SpgroupState	\
	scap.oval.definitions.sharepoint.SpgroupTest	\
	scap.oval.definitions.sharepoint.Spjobdefinition510Object	\
	scap.oval.definitions.sharepoint.Spjobdefinition510State	\
	scap.oval.definitions.sharepoint.Spjobdefinition510Test	\
	scap.oval.definitions.sharepoint.SpjobdefinitionObject	\
	scap.oval.definitions.sharepoint.SpjobdefinitionState	\
	scap.oval.definitions.sharepoint.SpjobdefinitionTest	\
	scap.oval.definitions.sharepoint.SplistObject	\
	scap.oval.definitions.sharepoint.SplistState	\
	scap.oval.definitions.sharepoint.SplistTest	\
	scap.oval.definitions.sharepoint.SppolicyfeatureObject	\
	scap.oval.definitions.sharepoint.SppolicyfeatureState	\
	scap.oval.definitions.sharepoint.SppolicyfeatureTest	\
	scap.oval.definitions.sharepoint.SppolicyObject	\
	scap.oval.definitions.sharepoint.SppolicyState	\
	scap.oval.definitions.sharepoint.SppolicyTest	\
	scap.oval.definitions.sharepoint.SpsiteadministrationObject	\
	scap.oval.definitions.sharepoint.SpsiteadministrationState	\
	scap.oval.definitions.sharepoint.SpsiteadministrationTest	\
	scap.oval.definitions.sharepoint.SpsiteObject	\
	scap.oval.definitions.sharepoint.SpsiteState	\
	scap.oval.definitions.sharepoint.SpsiteTest	\
	scap.oval.definitions.sharepoint.SpwebapplicationObject	\
	scap.oval.definitions.sharepoint.SpwebapplicationState	\
	scap.oval.definitions.sharepoint.SpwebapplicationTest	\
	scap.oval.definitions.sharepoint.SpwebObject	\
	scap.oval.definitions.sharepoint.SpwebState	\
	scap.oval.definitions.sharepoint.SpwebTest	\
	scap.oval.definitions.solaris.EntityObjectPublisherTypeType	\
	scap.oval.definitions.solaris.EntityStateClientUUIDType	\
	scap.oval.definitions.solaris.EntityStateLDOMRoleType	\
	scap.oval.definitions.solaris.EntityStatePermissionCompareType	\
	scap.oval.definitions.solaris.EntityStatePublisherTypeType	\
	scap.oval.definitions.solaris.EntityStateSmfServiceStateType	\
	scap.oval.definitions.solaris.EntityStateV12NEnvType	\
	scap.oval.definitions.solaris.FacetObject	\
	scap.oval.definitions.solaris.FacetState	\
	scap.oval.definitions.solaris.FacetTest	\
	scap.oval.definitions.solaris.ImageObject	\
	scap.oval.definitions.solaris.ImageState	\
	scap.oval.definitions.solaris.ImageTest	\
	scap.oval.definitions.solaris.IsainfoObject	\
	scap.oval.definitions.solaris.IsainfoState	\
	scap.oval.definitions.solaris.IsainfoTest	\
	scap.oval.definitions.solaris.NddObject	\
	scap.oval.definitions.solaris.NddState	\
	scap.oval.definitions.solaris.NddTest	\
	scap.oval.definitions.solaris.ObjectFactory	\
	scap.oval.definitions.solaris.package-info	\
	scap.oval.definitions.solaris.Package511Object	\
	scap.oval.definitions.solaris.Package511State	\
	scap.oval.definitions.solaris.Package511Test	\
	scap.oval.definitions.solaris.PackageavoidlistObject	\
	scap.oval.definitions.solaris.PackageavoidlistState	\
	scap.oval.definitions.solaris.PackageavoidlistTest	\
	scap.oval.definitions.solaris.PackageCheckBehaviors	\
	scap.oval.definitions.solaris.PackagecheckObject	\
	scap.oval.definitions.solaris.PackagecheckState	\
	scap.oval.definitions.solaris.PackagecheckTest	\
	scap.oval.definitions.solaris.PackagefreezelistObject	\
	scap.oval.definitions.solaris.PackagefreezelistState	\
	scap.oval.definitions.solaris.PackagefreezelistTest	\
	scap.oval.definitions.solaris.PackageObject	\
	scap.oval.definitions.solaris.PackagepublisherObject	\
	scap.oval.definitions.solaris.PackagepublisherState	\
	scap.oval.definitions.solaris.PackagepublisherTest	\
	scap.oval.definitions.solaris.PackageState	\
	scap.oval.definitions.solaris.PackageTest	\
	scap.oval.definitions.solaris.Patch54Object	\
	scap.oval.definitions.solaris.Patch54Test	\
	scap.oval.definitions.solaris.PatchBehaviors	\
	scap.oval.definitions.solaris.PatchObject	\
	scap.oval.definitions.solaris.PatchState	\
	scap.oval.definitions.solaris.PatchTest	\
	scap.oval.definitions.solaris.SmfObject	\
	scap.oval.definitions.solaris.SmfpropertyObject	\
	scap.oval.definitions.solaris.SmfpropertyState	\
	scap.oval.definitions.solaris.SmfpropertyTest	\
	scap.oval.definitions.solaris.SmfState	\
	scap.oval.definitions.solaris.SmfTest	\
	scap.oval.definitions.solaris.VariantObject	\
	scap.oval.definitions.solaris.VariantState	\
	scap.oval.definitions.solaris.VariantTest	\
	scap.oval.definitions.solaris.VirtualizationinfoObject	\
	scap.oval.definitions.solaris.VirtualizationinfoState	\
	scap.oval.definitions.solaris.VirtualizationinfoTest	\
	scap.oval.definitions.unix.DnscacheObject	\
	scap.oval.definitions.unix.DnscacheState	\
	scap.oval.definitions.unix.DnscacheTest	\
	scap.oval.definitions.unix.EntityStateCapabilityType	\
	scap.oval.definitions.unix.EntityStateEncryptMethodType	\
	scap.oval.definitions.unix.EntityStateEndpointType	\
	scap.oval.definitions.unix.EntityStateGconfTypeType	\
	scap.oval.definitions.unix.EntityStateInterfaceType	\
	scap.oval.definitions.unix.EntityStateRoutingTableFlagsType	\
	scap.oval.definitions.unix.EntityStateWaitStatusType	\
	scap.oval.definitions.unix.EntityStateXinetdTypeStatusType	\
	scap.oval.definitions.unix.FileBehaviors	\
	scap.oval.definitions.unix.FileextendedattributeObject	\
	scap.oval.definitions.unix.FileextendedattributeState	\
	scap.oval.definitions.unix.FileextendedattributeTest	\
	scap.oval.definitions.unix.FileObject	\
	scap.oval.definitions.unix.FileState	\
	scap.oval.definitions.unix.FileTest	\
	scap.oval.definitions.unix.GconfObject	\
	scap.oval.definitions.unix.GconfState	\
	scap.oval.definitions.unix.GconfTest	\
	scap.oval.definitions.unix.InetdObject	\
	scap.oval.definitions.unix.InetdState	\
	scap.oval.definitions.unix.InetdTest	\
	scap.oval.definitions.unix.InterfaceObject	\
	scap.oval.definitions.unix.InterfaceState	\
	scap.oval.definitions.unix.InterfaceTest	\
	scap.oval.definitions.unix.ObjectFactory	\
	scap.oval.definitions.unix.package-info	\
	scap.oval.definitions.unix.PasswordObject	\
	scap.oval.definitions.unix.PasswordState	\
	scap.oval.definitions.unix.PasswordTest	\
	scap.oval.definitions.unix.Process58Object	\
	scap.oval.definitions.unix.Process58State	\
	scap.oval.definitions.unix.Process58Test	\
	scap.oval.definitions.unix.ProcessObject	\
	scap.oval.definitions.unix.ProcessState	\
	scap.oval.definitions.unix.ProcessTest	\
	scap.oval.definitions.unix.RoutingtableObject	\
	scap.oval.definitions.unix.RoutingtableState	\
	scap.oval.definitions.unix.RoutingtableTest	\
	scap.oval.definitions.unix.RunlevelObject	\
	scap.oval.definitions.unix.RunlevelState	\
	scap.oval.definitions.unix.RunlevelTest	\
	scap.oval.definitions.unix.SccsObject	\
	scap.oval.definitions.unix.SccsState	\
	scap.oval.definitions.unix.SccsTest	\
	scap.oval.definitions.unix.ShadowObject	\
	scap.oval.definitions.unix.ShadowState	\
	scap.oval.definitions.unix.ShadowTest	\
	scap.oval.definitions.unix.SymlinkObject	\
	scap.oval.definitions.unix.SymlinkState	\
	scap.oval.definitions.unix.SymlinkTest	\
	scap.oval.definitions.unix.SysctlObject	\
	scap.oval.definitions.unix.SysctlState	\
	scap.oval.definitions.unix.SysctlTest	\
	scap.oval.definitions.unix.UnameObject	\
	scap.oval.definitions.unix.UnameState	\
	scap.oval.definitions.unix.UnameTest	\
	scap.oval.definitions.unix.XinetdObject	\
	scap.oval.definitions.unix.XinetdState	\
	scap.oval.definitions.unix.XinetdTest	\
	scap.oval.definitions.windows.AccesstokenBehaviors	\
	scap.oval.definitions.windows.AccesstokenObject	\
	scap.oval.definitions.windows.AccesstokenState	\
	scap.oval.definitions.windows.AccesstokenTest	\
	scap.oval.definitions.windows.Activedirectory57Object	\
	scap.oval.definitions.windows.Activedirectory57State	\
	scap.oval.definitions.windows.Activedirectory57Test	\
	scap.oval.definitions.windows.ActivedirectoryObject	\
	scap.oval.definitions.windows.ActivedirectoryState	\
	scap.oval.definitions.windows.ActivedirectoryTest	\
	scap.oval.definitions.windows.AuditeventpolicyObject	\
	scap.oval.definitions.windows.AuditeventpolicyState	\
	scap.oval.definitions.windows.AuditeventpolicysubcategoriesObject	\
	scap.oval.definitions.windows.AuditeventpolicysubcategoriesState	\
	scap.oval.definitions.windows.AuditeventpolicysubcategoriesTest	\
	scap.oval.definitions.windows.AuditeventpolicyTest	\
	scap.oval.definitions.windows.CmdletObject	\
	scap.oval.definitions.windows.CmdletState	\
	scap.oval.definitions.windows.CmdletTest	\
	scap.oval.definitions.windows.DnscacheObject	\
	scap.oval.definitions.windows.DnscacheState	\
	scap.oval.definitions.windows.DnscacheTest	\
	scap.oval.definitions.windows.EntityObjectCmdletVerbType	\
	scap.oval.definitions.windows.EntityObjectGUIDType	\
	scap.oval.definitions.windows.EntityObjectNamingContextType	\
	scap.oval.definitions.windows.EntityObjectProtocolType	\
	scap.oval.definitions.windows.EntityObjectRegistryHiveType	\
	scap.oval.definitions.windows.EntityObjectSystemMetricIndexType	\
	scap.oval.definitions.windows.EntityObjectUserRightType	\
	scap.oval.definitions.windows.EntityStateAddrTypeType	\
	scap.oval.definitions.windows.EntityStateAdstypeType	\
	scap.oval.definitions.windows.EntityStateAuditType	\
	scap.oval.definitions.windows.EntityStateCmdletVerbType	\
	scap.oval.definitions.windows.EntityStateDriveTypeType	\
	scap.oval.definitions.windows.EntityStateFileTypeType	\
	scap.oval.definitions.windows.EntityStateGUIDType	\
	scap.oval.definitions.windows.EntityStateInterfaceTypeType	\
	scap.oval.definitions.windows.EntityStateNamingContextType	\
	scap.oval.definitions.windows.EntityStateNTUserAccountTypeType	\
	scap.oval.definitions.windows.EntityStatePeSubsystemType	\
	scap.oval.definitions.windows.EntityStatePeTargetMachineType	\
	scap.oval.definitions.windows.EntityStateProtocolType	\
	scap.oval.definitions.windows.EntityStateRegistryHiveType	\
	scap.oval.definitions.windows.EntityStateRegistryTypeType	\
	scap.oval.definitions.windows.EntityStateServiceControlsAcceptedType	\
	scap.oval.definitions.windows.EntityStateServiceCurrentStateType	\
	scap.oval.definitions.windows.EntityStateServiceStartTypeType	\
	scap.oval.definitions.windows.EntityStateServiceTypeType	\
	scap.oval.definitions.windows.EntityStateSharedResourceTypeType	\
	scap.oval.definitions.windows.EntityStateSystemMetricIndexType	\
	scap.oval.definitions.windows.EntityStateUserRightType	\
	scap.oval.definitions.windows.EntityStateWindowsViewType	\
	scap.oval.definitions.windows.Fileauditedpermissions53Object	\
	scap.oval.definitions.windows.Fileauditedpermissions53State	\
	scap.oval.definitions.windows.Fileauditedpermissions53Test	\
	scap.oval.definitions.windows.FileauditedpermissionsObject	\
	scap.oval.definitions.windows.FileauditedpermissionsState	\
	scap.oval.definitions.windows.FileauditedpermissionsTest	\
	scap.oval.definitions.windows.FileAuditPermissions53Behaviors	\
	scap.oval.definitions.windows.FileAuditPermissionsBehaviors	\
	scap.oval.definitions.windows.FileBehaviors	\
	scap.oval.definitions.windows.FileEffectiveRights53Behaviors	\
	scap.oval.definitions.windows.Fileeffectiverights53Object	\
	scap.oval.definitions.windows.Fileeffectiverights53State	\
	scap.oval.definitions.windows.Fileeffectiverights53Test	\
	scap.oval.definitions.windows.FileEffectiveRightsBehaviors	\
	scap.oval.definitions.windows.FileeffectiverightsObject	\
	scap.oval.definitions.windows.FileeffectiverightsState	\
	scap.oval.definitions.windows.FileeffectiverightsTest	\
	scap.oval.definitions.windows.FileObject	\
	scap.oval.definitions.windows.FileState	\
	scap.oval.definitions.windows.FileTest	\
	scap.oval.definitions.windows.GroupObject	\
	scap.oval.definitions.windows.GroupSidObject	\
	scap.oval.definitions.windows.GroupSidState	\
	scap.oval.definitions.windows.GroupSidTest	\
	scap.oval.definitions.windows.GroupState	\
	scap.oval.definitions.windows.GroupTest	\
	scap.oval.definitions.windows.InterfaceObject	\
	scap.oval.definitions.windows.InterfaceState	\
	scap.oval.definitions.windows.InterfaceTest	\
	scap.oval.definitions.windows.LicenseObject	\
	scap.oval.definitions.windows.LicenseState	\
	scap.oval.definitions.windows.LicenseTest	\
	scap.oval.definitions.windows.LockoutpolicyObject	\
	scap.oval.definitions.windows.LockoutpolicyState	\
	scap.oval.definitions.windows.LockoutpolicyTest	\
	scap.oval.definitions.windows.MetabaseObject	\
	scap.oval.definitions.windows.MetabaseState	\
	scap.oval.definitions.windows.MetabaseTest	\
	scap.oval.definitions.windows.NTUserBehaviors	\
	scap.oval.definitions.windows.NtuserObject	\
	scap.oval.definitions.windows.NtuserState	\
	scap.oval.definitions.windows.NtuserTest	\
	scap.oval.definitions.windows.ObjectFactory	\
	scap.oval.definitions.windows.package-info	\
	scap.oval.definitions.windows.PasswordpolicyObject	\
	scap.oval.definitions.windows.PasswordpolicyState	\
	scap.oval.definitions.windows.PasswordpolicyTest	\
	scap.oval.definitions.windows.PeheaderObject	\
	scap.oval.definitions.windows.PeheaderState	\
	scap.oval.definitions.windows.PeheaderTest	\
	scap.oval.definitions.windows.PortObject	\
	scap.oval.definitions.windows.PortState	\
	scap.oval.definitions.windows.PortTest	\
	scap.oval.definitions.windows.PrinterEffectiveRightsBehaviors	\
	scap.oval.definitions.windows.PrintereffectiverightsObject	\
	scap.oval.definitions.windows.PrintereffectiverightsState	\
	scap.oval.definitions.windows.PrintereffectiverightsTest	\
	scap.oval.definitions.windows.Process58Object	\
	scap.oval.definitions.windows.Process58State	\
	scap.oval.definitions.windows.Process58Test	\
	scap.oval.definitions.windows.ProcessObject	\
	scap.oval.definitions.windows.ProcessState	\
	scap.oval.definitions.windows.ProcessTest	\
	scap.oval.definitions.windows.RegistryBehaviors	\
	scap.oval.definitions.windows.RegistryObject	\
	scap.oval.definitions.windows.RegistryState	\
	scap.oval.definitions.windows.RegistryTest	\
	scap.oval.definitions.windows.Regkeyauditedpermissions53Object	\
	scap.oval.definitions.windows.Regkeyauditedpermissions53State	\
	scap.oval.definitions.windows.Regkeyauditedpermissions53Test	\
	scap.oval.definitions.windows.RegkeyauditedpermissionsObject	\
	scap.oval.definitions.windows.RegkeyauditedpermissionsState	\
	scap.oval.definitions.windows.RegkeyauditedpermissionsTest	\
	scap.oval.definitions.windows.RegkeyAuditPermissions53Behaviors	\
	scap.oval.definitions.windows.RegkeyAuditPermissionsBehaviors	\
	scap.oval.definitions.windows.RegkeyEffectiveRights53Behaviors	\
	scap.oval.definitions.windows.Regkeyeffectiverights53Object	\
	scap.oval.definitions.windows.Regkeyeffectiverights53State	\
	scap.oval.definitions.windows.Regkeyeffectiverights53Test	\
	scap.oval.definitions.windows.RegkeyEffectiveRightsBehaviors	\
	scap.oval.definitions.windows.RegkeyeffectiverightsObject	\
	scap.oval.definitions.windows.RegkeyeffectiverightsState	\
	scap.oval.definitions.windows.RegkeyeffectiverightsTest	\
	scap.oval.definitions.windows.ServiceeffectiverightsObject	\
	scap.oval.definitions.windows.ServiceeffectiverightsState	\
	scap.oval.definitions.windows.ServiceeffectiverightsTest	\
	scap.oval.definitions.windows.ServiceObject	\
	scap.oval.definitions.windows.ServiceState	\
	scap.oval.definitions.windows.ServiceTest	\
	scap.oval.definitions.windows.SharedResourceAuditedPermissionsBehaviors	\
	scap.oval.definitions.windows.SharedresourceauditedpermissionsObject	\
	scap.oval.definitions.windows.SharedresourceauditedpermissionsState	\
	scap.oval.definitions.windows.SharedresourceauditedpermissionsTest	\
	scap.oval.definitions.windows.SharedResourceEffectiveRightsBehaviors	\
	scap.oval.definitions.windows.SharedresourceeffectiverightsObject	\
	scap.oval.definitions.windows.SharedresourceeffectiverightsState	\
	scap.oval.definitions.windows.SharedresourceeffectiverightsTest	\
	scap.oval.definitions.windows.SharedresourceObject	\
	scap.oval.definitions.windows.SharedresourceState	\
	scap.oval.definitions.windows.SharedresourceTest	\
	scap.oval.definitions.windows.SidBehaviors	\
	scap.oval.definitions.windows.SidObject	\
	scap.oval.definitions.windows.SidSidBehaviors	\
	scap.oval.definitions.windows.SidSidObject	\
	scap.oval.definitions.windows.SidSidState	\
	scap.oval.definitions.windows.SidSidTest	\
	scap.oval.definitions.windows.SidState	\
	scap.oval.definitions.windows.SidTest	\
	scap.oval.definitions.windows.SystemmetricObject	\
	scap.oval.definitions.windows.SystemmetricState	\
	scap.oval.definitions.windows.SystemmetricTest	\
	scap.oval.definitions.windows.UacObject	\
	scap.oval.definitions.windows.UacState	\
	scap.oval.definitions.windows.UacTest	\
	scap.oval.definitions.windows.UserObject	\
	scap.oval.definitions.windows.UserrightObject	\
	scap.oval.definitions.windows.UserrightState	\
	scap.oval.definitions.windows.UserrightTest	\
	scap.oval.definitions.windows.UserSid55Object	\
	scap.oval.definitions.windows.UserSid55State	\
	scap.oval.definitions.windows.UserSid55Test	\
	scap.oval.definitions.windows.UserSidObject	\
	scap.oval.definitions.windows.UserSidState	\
	scap.oval.definitions.windows.UserSidTest	\
	scap.oval.definitions.windows.UserState	\
	scap.oval.definitions.windows.UserTest	\
	scap.oval.definitions.windows.VolumeObject	\
	scap.oval.definitions.windows.VolumeState	\
	scap.oval.definitions.windows.VolumeTest	\
	scap.oval.definitions.windows.Wmi57Object	\
	scap.oval.definitions.windows.Wmi57State	\
	scap.oval.definitions.windows.Wmi57Test	\
	scap.oval.definitions.windows.WmiObject	\
	scap.oval.definitions.windows.WmiState	\
	scap.oval.definitions.windows.WmiTest	\
	scap.oval.definitions.windows.WuaUpdateSearcherBehaviors	\
	scap.oval.definitions.windows.WuaupdatesearcherObject	\
	scap.oval.definitions.windows.WuaupdatesearcherState	\
	scap.oval.definitions.windows.WuaupdatesearcherTest	\
	scap.oval.directives.ObjectFactory	\
	scap.oval.directives.OvalDirectives	\
	scap.oval.directives.package-info	\
	scap.oval.evaluation.EvaluationDefinitionIds	\
	scap.oval.evaluation.ObjectFactory	\
	scap.oval.evaluation.package-info	\
	scap.oval.results.ClassDirectivesType	\
	scap.oval.results.ContentEnumeration	\
	scap.oval.results.CriteriaType	\
	scap.oval.results.CriterionType	\
	scap.oval.results.DefaultDirectivesType	\
	scap.oval.results.DefinitionsType	\
	scap.oval.results.DefinitionType	\
	scap.oval.results.DirectivesType	\
	scap.oval.results.DirectiveType	\
	scap.oval.results.ExtendDefinitionType	\
	scap.oval.results.ObjectFactory	\
	scap.oval.results.OvalResults	\
	scap.oval.results.package-info	\
	scap.oval.results.ResultEnumeration	\
	scap.oval.results.ResultsType	\
	scap.oval.results.SystemType	\
	scap.oval.results.TestedItemType	\
	scap.oval.results.TestedVariableType	\
	scap.oval.results.TestsType	\
	scap.oval.results.TestType	\
	scap.oval.systemcharacteristics.aix.EntityItemFilesetStateType	\
	scap.oval.systemcharacteristics.aix.EntityItemFixInstallationStatusType	\
	scap.oval.systemcharacteristics.aix.EntityItemInterimFixStateType	\
	scap.oval.systemcharacteristics.aix.FilesetItem	\
	scap.oval.systemcharacteristics.aix.FixItem	\
	scap.oval.systemcharacteristics.aix.InterimFixItem	\
	scap.oval.systemcharacteristics.aix.NoItem	\
	scap.oval.systemcharacteristics.aix.ObjectFactory	\
	scap.oval.systemcharacteristics.aix.OslevelItem	\
	scap.oval.systemcharacteristics.aix.package-info	\
	scap.oval.systemcharacteristics.android.AppmanagerItem	\
	scap.oval.systemcharacteristics.android.BluetoothItem	\
	scap.oval.systemcharacteristics.android.CameraItem	\
	scap.oval.systemcharacteristics.android.CertificateItem	\
	scap.oval.systemcharacteristics.android.DevicesettingsItem	\
	scap.oval.systemcharacteristics.android.EncryptionItem	\
	scap.oval.systemcharacteristics.android.EntityItemEncryptionStatusType	\
	scap.oval.systemcharacteristics.android.EntityItemKeyguardDisabledFeaturesType	\
	scap.oval.systemcharacteristics.android.EntityItemNetworkType	\
	scap.oval.systemcharacteristics.android.EntityItemPasswordQualityType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiAuthAlgorithmType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiCurrentStatusType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiGroupCipherType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiKeyMgmtType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiPairwiseCipherType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiProtocolType	\
	scap.oval.systemcharacteristics.android.LocationserviceItem	\
	scap.oval.systemcharacteristics.android.NetworkItem	\
	scap.oval.systemcharacteristics.android.ObjectFactory	\
	scap.oval.systemcharacteristics.android.package-info	\
	scap.oval.systemcharacteristics.android.PasswordItem	\
	scap.oval.systemcharacteristics.android.SystemdetailsItem	\
	scap.oval.systemcharacteristics.android.TelephonyItem	\
	scap.oval.systemcharacteristics.android.WifiItem	\
	scap.oval.systemcharacteristics.android.WifinetworkItem	\
	scap.oval.systemcharacteristics.apache.HttpdItem	\
	scap.oval.systemcharacteristics.apache.ObjectFactory	\
	scap.oval.systemcharacteristics.apache.package-info	\
	scap.oval.systemcharacteristics.appleios.GlobalrestrictionsItem	\
	scap.oval.systemcharacteristics.appleios.ObjectFactory	\
	scap.oval.systemcharacteristics.appleios.package-info	\
	scap.oval.systemcharacteristics.appleios.PasscodepolicyItem	\
	scap.oval.systemcharacteristics.appleios.ProfileItem	\
	scap.oval.systemcharacteristics.asa.AclItem	\
	scap.oval.systemcharacteristics.asa.ClassMapItem	\
	scap.oval.systemcharacteristics.asa.EntityItemAccessListInterfaceDirectionType	\
	scap.oval.systemcharacteristics.asa.EntityItemAccessListIPVersionType	\
	scap.oval.systemcharacteristics.asa.EntityItemAccessListUseType	\
	scap.oval.systemcharacteristics.asa.EntityItemApplyServicePolicyType	\
	scap.oval.systemcharacteristics.asa.EntityItemClassMapType	\
	scap.oval.systemcharacteristics.asa.EntityItemInpsectionType	\
	scap.oval.systemcharacteristics.asa.EntityItemMatchType	\
	scap.oval.systemcharacteristics.asa.EntityItemSNMPAuthStringType	\
	scap.oval.systemcharacteristics.asa.EntityItemSNMPPrivStringType	\
	scap.oval.systemcharacteristics.asa.EntityItemSNMPSecLevelStringType	\
	scap.oval.systemcharacteristics.asa.EntityItemSNMPVersionStringType	\
	scap.oval.systemcharacteristics.asa.InterfaceItem	\
	scap.oval.systemcharacteristics.asa.LineItem	\
	scap.oval.systemcharacteristics.asa.ObjectFactory	\
	scap.oval.systemcharacteristics.asa.package-info	\
	scap.oval.systemcharacteristics.asa.PolicyMapItem	\
	scap.oval.systemcharacteristics.asa.ServicePolicyItem	\
	scap.oval.systemcharacteristics.asa.SnmpGroupItem	\
	scap.oval.systemcharacteristics.asa.SnmpHostItem	\
	scap.oval.systemcharacteristics.asa.SnmpUserItem	\
	scap.oval.systemcharacteristics.asa.TcpMapItem	\
	scap.oval.systemcharacteristics.asa.VersionItem	\
	scap.oval.systemcharacteristics.catos.LineItem	\
	scap.oval.systemcharacteristics.catos.ModuleItem	\
	scap.oval.systemcharacteristics.catos.ObjectFactory	\
	scap.oval.systemcharacteristics.catos.package-info	\
	scap.oval.systemcharacteristics.catos.VersionItem	\
	scap.oval.systemcharacteristics.core.CollectedObjectsType	\
	scap.oval.systemcharacteristics.core.EntityItemAnySimpleType	\
	scap.oval.systemcharacteristics.core.EntityItemBinaryType	\
	scap.oval.systemcharacteristics.core.EntityItemBoolType	\
	scap.oval.systemcharacteristics.core.EntityItemComplexBaseType	\
	scap.oval.systemcharacteristics.core.EntityItemEVRStringType	\
	scap.oval.systemcharacteristics.core.EntityItemFieldType	\
	scap.oval.systemcharacteristics.core.EntityItemFilesetRevisionType	\
	scap.oval.systemcharacteristics.core.EntityItemFloatType	\
	scap.oval.systemcharacteristics.core.EntityItemIntType	\
	scap.oval.systemcharacteristics.core.EntityItemIOSVersionType	\
	scap.oval.systemcharacteristics.core.EntityItemIPAddressStringType	\
	scap.oval.systemcharacteristics.core.EntityItemIPAddressType	\
	scap.oval.systemcharacteristics.core.EntityItemRecordType	\
	scap.oval.systemcharacteristics.core.EntityItemSimpleBaseType	\
	scap.oval.systemcharacteristics.core.EntityItemStringType	\
	scap.oval.systemcharacteristics.core.EntityItemVersionType	\
	scap.oval.systemcharacteristics.core.FlagEnumeration	\
	scap.oval.systemcharacteristics.core.InterfacesType	\
	scap.oval.systemcharacteristics.core.InterfaceType	\
	scap.oval.systemcharacteristics.core.ItemType	\
	scap.oval.systemcharacteristics.core.ObjectFactory	\
	scap.oval.systemcharacteristics.core.ObjectType	\
	scap.oval.systemcharacteristics.core.OvalSystemCharacteristics	\
	scap.oval.systemcharacteristics.core.package-info	\
	scap.oval.systemcharacteristics.core.ReferenceType	\
	scap.oval.systemcharacteristics.core.StatusEnumeration	\
	scap.oval.systemcharacteristics.core.SystemDataType	\
	scap.oval.systemcharacteristics.core.SystemInfoType	\
	scap.oval.systemcharacteristics.core.VariableValueType	\
	scap.oval.systemcharacteristics.esx.EntityItemClassificationType	\
	scap.oval.systemcharacteristics.esx.EntityItemSupportLevelType	\
	scap.oval.systemcharacteristics.esx.ObjectFactory	\
	scap.oval.systemcharacteristics.esx.package-info	\
	scap.oval.systemcharacteristics.esx.PatchItem	\
	scap.oval.systemcharacteristics.esx.VersionItem	\
	scap.oval.systemcharacteristics.esx.VisdkmanagedobjectItem	\
	scap.oval.systemcharacteristics.freebsd.ObjectFactory	\
	scap.oval.systemcharacteristics.freebsd.package-info	\
	scap.oval.systemcharacteristics.freebsd.PortinfoItem	\
	scap.oval.systemcharacteristics.hpux.GetconfItem	\
	scap.oval.systemcharacteristics.hpux.NddItem	\
	scap.oval.systemcharacteristics.hpux.ObjectFactory	\
	scap.oval.systemcharacteristics.hpux.package-info	\
	scap.oval.systemcharacteristics.hpux.PatchItem	\
	scap.oval.systemcharacteristics.hpux.SwlistItem	\
	scap.oval.systemcharacteristics.hpux.TrustedItem	\
	scap.oval.systemcharacteristics.independent.EntityItemEngineType	\
	scap.oval.systemcharacteristics.independent.EntityItemFamilyType	\
	scap.oval.systemcharacteristics.independent.EntityItemHashTypeType	\
	scap.oval.systemcharacteristics.independent.EntityItemLdaptypeType	\
	scap.oval.systemcharacteristics.independent.EntityItemVariableRefType	\
	scap.oval.systemcharacteristics.independent.EntityItemWindowsViewType	\
	scap.oval.systemcharacteristics.independent.Environmentvariable58Item	\
	scap.oval.systemcharacteristics.independent.EnvironmentvariableItem	\
	scap.oval.systemcharacteristics.independent.FamilyItem	\
	scap.oval.systemcharacteristics.independent.Filehash58Item	\
	scap.oval.systemcharacteristics.independent.FilehashItem	\
	scap.oval.systemcharacteristics.independent.Ldap57Item	\
	scap.oval.systemcharacteristics.independent.LdapItem	\
	scap.oval.systemcharacteristics.independent.ObjectFactory	\
	scap.oval.systemcharacteristics.independent.package-info	\
	scap.oval.systemcharacteristics.independent.Sql57Item	\
	scap.oval.systemcharacteristics.independent.SqlItem	\
	scap.oval.systemcharacteristics.independent.TextfilecontentItem	\
	scap.oval.systemcharacteristics.independent.VariableItem	\
	scap.oval.systemcharacteristics.independent.XmlfilecontentItem	\
	scap.oval.systemcharacteristics.ios.AclItem	\
	scap.oval.systemcharacteristics.ios.BgpneighborItem	\
	scap.oval.systemcharacteristics.ios.EntityItemAccessListInterfaceDirectionType	\
	scap.oval.systemcharacteristics.ios.EntityItemAccessListIPVersionType	\
	scap.oval.systemcharacteristics.ios.EntityItemAccessListUseType	\
	scap.oval.systemcharacteristics.ios.EntityItemRoutingAuthTypeStringType	\
	scap.oval.systemcharacteristics.ios.EntityItemRoutingProtocolType	\
	scap.oval.systemcharacteristics.ios.EntityItemSNMPAuthStringType	\
	scap.oval.systemcharacteristics.ios.EntityItemSNMPModeStringType	\
	scap.oval.systemcharacteristics.ios.EntityItemSNMPPrivStringType	\
	scap.oval.systemcharacteristics.ios.EntityItemSNMPSecLevelStringType	\
	scap.oval.systemcharacteristics.ios.EntityItemSNMPVersionStringType	\
	scap.oval.systemcharacteristics.ios.EntityItemSwitchportModeType	\
	scap.oval.systemcharacteristics.ios.EntityItemTrunkEncapType	\
	scap.oval.systemcharacteristics.ios.GlobalItem	\
	scap.oval.systemcharacteristics.ios.InterfaceItem	\
	scap.oval.systemcharacteristics.ios.LineItem	\
	scap.oval.systemcharacteristics.ios.ObjectFactory	\
	scap.oval.systemcharacteristics.ios.package-info	\
	scap.oval.systemcharacteristics.ios.RouterItem	\
	scap.oval.systemcharacteristics.ios.RoutingprotocolauthintfItem	\
	scap.oval.systemcharacteristics.ios.SectionItem	\
	scap.oval.systemcharacteristics.ios.SnmpcommunityItem	\
	scap.oval.systemcharacteristics.ios.SnmpgroupItem	\
	scap.oval.systemcharacteristics.ios.SnmphostItem	\
	scap.oval.systemcharacteristics.ios.SnmpItem	\
	scap.oval.systemcharacteristics.ios.SnmpuserItem	\
	scap.oval.systemcharacteristics.ios.SnmpviewItem	\
	scap.oval.systemcharacteristics.ios.TclshItem	\
	scap.oval.systemcharacteristics.ios.VersionItem	\
	scap.oval.systemcharacteristics.iosxe.AclItem	\
	scap.oval.systemcharacteristics.iosxe.BgpneighborItem	\
	scap.oval.systemcharacteristics.iosxe.EntityItemAccessListInterfaceDirectionType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemAccessListIPVersionType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemAccessListUseType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemRoutingAuthTypeStringType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemRoutingProtocolType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemSNMPAuthStringType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemSNMPModeStringType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemSNMPPrivStringType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemSNMPSecLevelStringType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemSNMPVersionStringType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemSwitchportModeType	\
	scap.oval.systemcharacteristics.iosxe.EntityItemTrunkEncapType	\
	scap.oval.systemcharacteristics.iosxe.GlobalItem	\
	scap.oval.systemcharacteristics.iosxe.InterfaceItem	\
	scap.oval.systemcharacteristics.iosxe.LineItem	\
	scap.oval.systemcharacteristics.iosxe.ObjectFactory	\
	scap.oval.systemcharacteristics.iosxe.package-info	\
	scap.oval.systemcharacteristics.iosxe.RouterItem	\
	scap.oval.systemcharacteristics.iosxe.RoutingprotocolauthintfItem	\
	scap.oval.systemcharacteristics.iosxe.SectionItem	\
	scap.oval.systemcharacteristics.iosxe.SnmpcommunityItem	\
	scap.oval.systemcharacteristics.iosxe.SnmpgroupItem	\
	scap.oval.systemcharacteristics.iosxe.SnmphostItem	\
	scap.oval.systemcharacteristics.iosxe.SnmpuserItem	\
	scap.oval.systemcharacteristics.iosxe.SnmpviewItem	\
	scap.oval.systemcharacteristics.iosxe.VersionItem	\
	scap.oval.systemcharacteristics.junos.EntityItemJunosReleaseTypeType	\
	scap.oval.systemcharacteristics.junos.ObjectFactory	\
	scap.oval.systemcharacteristics.junos.package-info	\
	scap.oval.systemcharacteristics.junos.ShowItem	\
	scap.oval.systemcharacteristics.junos.VersionItem	\
	scap.oval.systemcharacteristics.junos.XmlConfigItem	\
	scap.oval.systemcharacteristics.junos.XmlShowItem	\
	scap.oval.systemcharacteristics.linux.DpkginfoItem	\
	scap.oval.systemcharacteristics.linux.EntityItemProtocolType	\
	scap.oval.systemcharacteristics.linux.EntityItemRpmVerifyResultType	\
	scap.oval.systemcharacteristics.linux.IflistenersItem	\
	scap.oval.systemcharacteristics.linux.InetlisteningserversItem	\
	scap.oval.systemcharacteristics.linux.ObjectFactory	\
	scap.oval.systemcharacteristics.linux.package-info	\
	scap.oval.systemcharacteristics.linux.PartitionItem	\
	scap.oval.systemcharacteristics.linux.RpminfoItem	\
	scap.oval.systemcharacteristics.linux.RpmverifyfileItem	\
	scap.oval.systemcharacteristics.linux.RpmverifyItem	\
	scap.oval.systemcharacteristics.linux.RpmverifypackageItem	\
	scap.oval.systemcharacteristics.linux.SelinuxbooleanItem	\
	scap.oval.systemcharacteristics.linux.SelinuxsecuritycontextItem	\
	scap.oval.systemcharacteristics.linux.SlackwarepkginfoItem	\
	scap.oval.systemcharacteristics.linux.SystemdunitdependencyItem	\
	scap.oval.systemcharacteristics.linux.SystemdunitpropertyItem	\
	scap.oval.systemcharacteristics.macos.AccountinfoItem	\
	scap.oval.systemcharacteristics.macos.AuthorizationdbItem	\
	scap.oval.systemcharacteristics.macos.CorestorageItem	\
	scap.oval.systemcharacteristics.macos.DiskutilItem	\
	scap.oval.systemcharacteristics.macos.EntityItemDataTypeType	\
	scap.oval.systemcharacteristics.macos.EntityItemPermissionCompareType	\
	scap.oval.systemcharacteristics.macos.EntityItemPlistTypeType	\
	scap.oval.systemcharacteristics.macos.GatekeeperItem	\
	scap.oval.systemcharacteristics.macos.Inetlisteningserver510Item	\
	scap.oval.systemcharacteristics.macos.InetlisteningserversItem	\
	scap.oval.systemcharacteristics.macos.KeychainItem	\
	scap.oval.systemcharacteristics.macos.LaunchdItem	\
	scap.oval.systemcharacteristics.macos.NvramItem	\
	scap.oval.systemcharacteristics.macos.ObjectFactory	\
	scap.oval.systemcharacteristics.macos.package-info	\
	scap.oval.systemcharacteristics.macos.PlistItem	\
	scap.oval.systemcharacteristics.macos.Pwpolicy59Item	\
	scap.oval.systemcharacteristics.macos.PwpolicyItem	\
	scap.oval.systemcharacteristics.macos.RlimitItem	\
	scap.oval.systemcharacteristics.macos.SoftwareupdateItem	\
	scap.oval.systemcharacteristics.macos.SystemprofilerItem	\
	scap.oval.systemcharacteristics.macos.SystemsetupItem	\
	scap.oval.systemcharacteristics.netconf.ConfigItem	\
	scap.oval.systemcharacteristics.netconf.ObjectFactory	\
	scap.oval.systemcharacteristics.netconf.package-info	\
	scap.oval.systemcharacteristics.pixos.LineItem	\
	scap.oval.systemcharacteristics.pixos.ObjectFactory	\
	scap.oval.systemcharacteristics.pixos.package-info	\
	scap.oval.systemcharacteristics.pixos.VersionItem	\
	scap.oval.systemcharacteristics.sharepoint.BestbetItem	\
	scap.oval.systemcharacteristics.sharepoint.EntityItemEventSeverityType	\
	scap.oval.systemcharacteristics.sharepoint.EntityItemPolicyFeatureStateType	\
	scap.oval.systemcharacteristics.sharepoint.EntityItemPolicyRoleType	\
	scap.oval.systemcharacteristics.sharepoint.EntityItemTraceSeverityType	\
	scap.oval.systemcharacteristics.sharepoint.EntityItemUrlZoneType	\
	scap.oval.systemcharacteristics.sharepoint.InfopolicycollItem	\
	scap.oval.systemcharacteristics.sharepoint.ObjectFactory	\
	scap.oval.systemcharacteristics.sharepoint.package-info	\
	scap.oval.systemcharacteristics.sharepoint.SpantivirussettingsItem	\
	scap.oval.systemcharacteristics.sharepoint.SpcrawlruleItem	\
	scap.oval.systemcharacteristics.sharepoint.SpdiagnosticslevelItem	\
	scap.oval.systemcharacteristics.sharepoint.SpdiagnosticsserviceItem	\
	scap.oval.systemcharacteristics.sharepoint.SpgroupItem	\
	scap.oval.systemcharacteristics.sharepoint.Spjobdefinition510Item	\
	scap.oval.systemcharacteristics.sharepoint.SpjobdefinitionItem	\
	scap.oval.systemcharacteristics.sharepoint.SplistItem	\
	scap.oval.systemcharacteristics.sharepoint.SppolicyfeatureItem	\
	scap.oval.systemcharacteristics.sharepoint.SppolicyItem	\
	scap.oval.systemcharacteristics.sharepoint.SpsiteadministrationItem	\
	scap.oval.systemcharacteristics.sharepoint.SpsiteItem	\
	scap.oval.systemcharacteristics.sharepoint.SpwebapplicationItem	\
	scap.oval.systemcharacteristics.sharepoint.SpwebItem	\
	scap.oval.systemcharacteristics.solaris.EntityItemClientUUIDType	\
	scap.oval.systemcharacteristics.solaris.EntityItemLDOMRoleType	\
	scap.oval.systemcharacteristics.solaris.EntityItemPermissionCompareType	\
	scap.oval.systemcharacteristics.solaris.EntityItemPublisherTypeType	\
	scap.oval.systemcharacteristics.solaris.EntityItemSmfServiceStateType	\
	scap.oval.systemcharacteristics.solaris.EntityItemV12NEnvType	\
	scap.oval.systemcharacteristics.solaris.FacetItem	\
	scap.oval.systemcharacteristics.solaris.ImageItem	\
	scap.oval.systemcharacteristics.solaris.IsainfoItem	\
	scap.oval.systemcharacteristics.solaris.NddItem	\
	scap.oval.systemcharacteristics.solaris.ObjectFactory	\
	scap.oval.systemcharacteristics.solaris.package-info	\
	scap.oval.systemcharacteristics.solaris.Package511Item	\
	scap.oval.systemcharacteristics.solaris.PackageavoidlistItem	\
	scap.oval.systemcharacteristics.solaris.PackagecheckItem	\
	scap.oval.systemcharacteristics.solaris.PackagefreezelistItem	\
	scap.oval.systemcharacteristics.solaris.PackageItem	\
	scap.oval.systemcharacteristics.solaris.PackagepublisherItem	\
	scap.oval.systemcharacteristics.solaris.PatchItem	\
	scap.oval.systemcharacteristics.solaris.SmfItem	\
	scap.oval.systemcharacteristics.solaris.SmfpropertyItem	\
	scap.oval.systemcharacteristics.solaris.VariantItem	\
	scap.oval.systemcharacteristics.solaris.VirtualizationinfoItem	\
	scap.oval.systemcharacteristics.unix.DnscacheItem	\
	scap.oval.systemcharacteristics.unix.EntityItemCapabilityType	\
	scap.oval.systemcharacteristics.unix.EntityItemEncryptMethodType	\
	scap.oval.systemcharacteristics.unix.EntityItemEndpointType	\
	scap.oval.systemcharacteristics.unix.EntityItemGconfTypeType	\
	scap.oval.systemcharacteristics.unix.EntityItemInterfaceType	\
	scap.oval.systemcharacteristics.unix.EntityItemRoutingTableFlagsType	\
	scap.oval.systemcharacteristics.unix.EntityItemWaitStatusType	\
	scap.oval.systemcharacteristics.unix.EntityItemXinetdTypeStatusType	\
	scap.oval.systemcharacteristics.unix.FileextendedattributeItem	\
	scap.oval.systemcharacteristics.unix.FileItem	\
	scap.oval.systemcharacteristics.unix.GconfItem	\
	scap.oval.systemcharacteristics.unix.InetdItem	\
	scap.oval.systemcharacteristics.unix.InterfaceItem	\
	scap.oval.systemcharacteristics.unix.ObjectFactory	\
	scap.oval.systemcharacteristics.unix.package-info	\
	scap.oval.systemcharacteristics.unix.PasswordItem	\
	scap.oval.systemcharacteristics.unix.Process58Item	\
	scap.oval.systemcharacteristics.unix.ProcessItem	\
	scap.oval.systemcharacteristics.unix.RoutingtableItem	\
	scap.oval.systemcharacteristics.unix.RunlevelItem	\
	scap.oval.systemcharacteristics.unix.SccsItem	\
	scap.oval.systemcharacteristics.unix.ShadowItem	\
	scap.oval.systemcharacteristics.unix.SymlinkItem	\
	scap.oval.systemcharacteristics.unix.SysctlItem	\
	scap.oval.systemcharacteristics.unix.UnameItem	\
	scap.oval.systemcharacteristics.unix.XinetdItem	\
	scap.oval.systemcharacteristics.windows.AccesstokenItem	\
	scap.oval.systemcharacteristics.windows.Activedirectory57Item	\
	scap.oval.systemcharacteristics.windows.ActivedirectoryItem	\
	scap.oval.systemcharacteristics.windows.AuditeventpolicyItem	\
	scap.oval.systemcharacteristics.windows.AuditeventpolicysubcategoriesItem	\
	scap.oval.systemcharacteristics.windows.CmdletItem	\
	scap.oval.systemcharacteristics.windows.DnscacheItem	\
	scap.oval.systemcharacteristics.windows.EntityItemAddrTypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemAdstypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemAuditType	\
	scap.oval.systemcharacteristics.windows.EntityItemCmdletVerbType	\
	scap.oval.systemcharacteristics.windows.EntityItemDriveTypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemFileTypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemGUIDType	\
	scap.oval.systemcharacteristics.windows.EntityItemInterfaceTypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemNamingContextType	\
	scap.oval.systemcharacteristics.windows.EntityItemNTUserAccountTypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemPeSubsystemType	\
	scap.oval.systemcharacteristics.windows.EntityItemPeTargetMachineType	\
	scap.oval.systemcharacteristics.windows.EntityItemProtocolType	\
	scap.oval.systemcharacteristics.windows.EntityItemRegistryHiveType	\
	scap.oval.systemcharacteristics.windows.EntityItemRegistryTypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemServiceControlsAcceptedType	\
	scap.oval.systemcharacteristics.windows.EntityItemServiceCurrentStateType	\
	scap.oval.systemcharacteristics.windows.EntityItemServiceStartTypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemServiceTypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemSharedResourceTypeType	\
	scap.oval.systemcharacteristics.windows.EntityItemSystemMetricIndexType	\
	scap.oval.systemcharacteristics.windows.EntityItemUserRightType	\
	scap.oval.systemcharacteristics.windows.EntityItemWindowsViewType	\
	scap.oval.systemcharacteristics.windows.FileauditedpermissionsItem	\
	scap.oval.systemcharacteristics.windows.FileeffectiverightsItem	\
	scap.oval.systemcharacteristics.windows.FileItem	\
	scap.oval.systemcharacteristics.windows.GroupItem	\
	scap.oval.systemcharacteristics.windows.GroupSidItem	\
	scap.oval.systemcharacteristics.windows.InterfaceItem	\
	scap.oval.systemcharacteristics.windows.LicenseItem	\
	scap.oval.systemcharacteristics.windows.LockoutpolicyItem	\
	scap.oval.systemcharacteristics.windows.MetabaseItem	\
	scap.oval.systemcharacteristics.windows.NtuserItem	\
	scap.oval.systemcharacteristics.windows.ObjectFactory	\
	scap.oval.systemcharacteristics.windows.package-info	\
	scap.oval.systemcharacteristics.windows.PasswordpolicyItem	\
	scap.oval.systemcharacteristics.windows.PeheaderItem	\
	scap.oval.systemcharacteristics.windows.PortItem	\
	scap.oval.systemcharacteristics.windows.PrintereffectiverightsItem	\
	scap.oval.systemcharacteristics.windows.ProcessItem	\
	scap.oval.systemcharacteristics.windows.RegistryItem	\
	scap.oval.systemcharacteristics.windows.RegkeyauditedpermissionsItem	\
	scap.oval.systemcharacteristics.windows.RegkeyeffectiverightsItem	\
	scap.oval.systemcharacteristics.windows.ServiceeffectiverightsItem	\
	scap.oval.systemcharacteristics.windows.ServiceItem	\
	scap.oval.systemcharacteristics.windows.SharedresourceauditedpermissionsItem	\
	scap.oval.systemcharacteristics.windows.SharedresourceeffectiverightsItem	\
	scap.oval.systemcharacteristics.windows.SharedresourceItem	\
	scap.oval.systemcharacteristics.windows.SidItem	\
	scap.oval.systemcharacteristics.windows.SidSidItem	\
	scap.oval.systemcharacteristics.windows.SystemmetricItem	\
	scap.oval.systemcharacteristics.windows.UacItem	\
	scap.oval.systemcharacteristics.windows.UserItem	\
	scap.oval.systemcharacteristics.windows.UserrightItem	\
	scap.oval.systemcharacteristics.windows.UserSidItem	\
	scap.oval.systemcharacteristics.windows.VolumeItem	\
	scap.oval.systemcharacteristics.windows.Wmi57Item	\
	scap.oval.systemcharacteristics.windows.WmiItem	\
	scap.oval.systemcharacteristics.windows.WuaupdatesearcherItem	\
	scap.oval.variables.ObjectFactory	\
	scap.oval.variables.OvalVariables	\
	scap.oval.variables.package-info	\
	scap.oval.variables.VariablesType	\
	scap.oval.variables.VariableType	\
	scap.xccdf.CcOperatorEnumType	\
	scap.xccdf.CheckContentRefType	\
	scap.xccdf.CheckContentType	\
	scap.xccdf.CheckExportType	\
	scap.xccdf.CheckImportType	\
	scap.xccdf.CheckType	\
	scap.xccdf.ComplexCheckType	\
	scap.xccdf.ComplexValueType	\
	scap.xccdf.CPE2IdrefType	\
	scap.xccdf.DcStatusType	\
	scap.xccdf.FactType	\
	scap.xccdf.FixStrategyEnumType	\
	scap.xccdf.FixTextType	\
	scap.xccdf.FixType	\
	scap.xccdf.GroupType	\
	scap.xccdf.HtmlTextType	\
	scap.xccdf.HtmlTextWithSubType	\
	scap.xccdf.IdentityType	\
	scap.xccdf.IdentType	\
	scap.xccdf.IdrefListType	\
	scap.xccdf.IdrefType	\
	scap.xccdf.InstanceFixType	\
	scap.xccdf.InstanceResultType	\
	scap.xccdf.InterfaceHintType	\
	scap.xccdf.ItemType	\
	scap.xccdf.MessageType	\
	scap.xccdf.MetadataType	\
	scap.xccdf.Model	\
	scap.xccdf.MsgSevEnumType	\
	scap.xccdf.NoticeType	\
	scap.xccdf.ObjectFactory	\
	scap.xccdf.OverrideableCPE2IdrefType	\
	scap.xccdf.OverrideableIdrefType	\
	scap.xccdf.OverrideType	\
	scap.xccdf.package-info	\
	scap.xccdf.ParamType	\
	scap.xccdf.PlainTextType	\
	scap.xccdf.ProfileNoteType	\
	scap.xccdf.ProfileRefineRuleType	\
	scap.xccdf.ProfileRefineValueType	\
	scap.xccdf.ProfileSelectType	\
	scap.xccdf.ProfileSetComplexValueType	\
	scap.xccdf.ProfileSetValueType	\
	scap.xccdf.ProfileType	\
	scap.xccdf.RatingEnumType	\
	scap.xccdf.ReferenceType	\
	scap.xccdf.ResultEnumType	\
	scap.xccdf.RoleEnumType	\
	scap.xccdf.RuleResultType	\
	scap.xccdf.RuleType	\
	scap.xccdf.ScoreType	\
	scap.xccdf.SelChoicesType	\
	scap.xccdf.SelComplexValueType	\
	scap.xccdf.SelectableItemType	\
	scap.xccdf.SelNumType	\
	scap.xccdf.SelStringType	\
	scap.xccdf.SeverityEnumType	\
	scap.xccdf.SignatureType	\
	scap.xccdf.Status	\
	scap.xccdf.StatusType	\
	scap.xccdf.SubType	\
	scap.xccdf.SubUseEnumType	\
	scap.xccdf.TailoringType	\
	scap.xccdf.TargetFactsType	\
	scap.xccdf.TestResultType	\
	scap.xccdf.TextType	\
	scap.xccdf.TextWithSubType	\
	scap.xccdf.UriRefType	\
	scap.xccdf.ValueOperatorType	\
	scap.xccdf.ValueType	\
	scap.xccdf.ValueTypeType	\
	scap.xccdf.VersionType	\
	scap.xccdf.WarningCategoryEnumType	\
	scap.xccdf.WarningType	\
	scap.xccdf.XccdfBenchmark
