SCHEMAS=\
	ai-1.1/asset-identification_1.1.0.xsd	\
	arf-1.1/asset-reporting-format_1.1.0.xsd	\
	arf-1.1/reporting-core_1.1.0.xsd	\
	constructs-1.2/scap-constructs_1.2.xsd	\
	cpe-2.3/cpe-dictionary-extension_2.3.xsd	\
	cpe-2.3/cpe-dictionary_2.3.xsd	\
	cpe-2.3/cpe-language_2.3.xsd	\
	cpe-2.3/cpe-naming_2.3.xsd	\
	ds-1.2/scap-source-data-stream_1.2.xsd	\
	dublin/simpledc20021212.xsd	\
	joval/diagnostic-schema-1.0.xsd	\
	oasis/catalog-1.1.xsd	\
	oasis/xAL.xsd	\
	oasis/xNL.xsd	\
	ocil-2.0/ocil-2.0.xsd	\
	ocil-2.0/ocil-diagnostic-schema.xsd	\
	ocil-2.0/ocil-variables-schema.xsd	\
	oval-5.11.2/oval-common-schema.xsd	\
	oval-5.11.2/oval-definitions-schema.xsd	\
	oval-5.11.2/oval-definitions-extended-schema.xsd	\
	oval-5.11.2/oval-system-characteristics-schema.xsd	\
	oval-5.11.2/oval-results-schema.xsd	\
	oval-5.11.2/aix-definitions-schema.xsd	\
	oval-5.11.2/aix-system-characteristics-schema.xsd	\
	oval-5.11.2/android-definitions-schema.xsd	\
	oval-5.11.2/android-system-characteristics-schema.xsd	\
	oval-5.11.2/apache-definitions-schema.xsd	\
	oval-5.11.2/apache-system-characteristics-schema.xsd	\
	oval-5.11.2/apple-ios-definitions-schema.xsd	\
	oval-5.11.2/apple-ios-system-characteristics-schema.xsd	\
	oval-5.11.2/asa-definitions-schema.xsd	\
	oval-5.11.2/asa-system-characteristics-schema.xsd	\
	oval-5.11.2/catos-definitions-schema.xsd	\
	oval-5.11.2/catos-system-characteristics-schema.xsd	\
	oval-5.11.2/esx-definitions-schema.xsd	\
	oval-5.11.2/esx-system-characteristics-schema.xsd	\
	oval-5.11.2/freebsd-definitions-schema.xsd	\
	oval-5.11.2/freebsd-system-characteristics-schema.xsd	\
	oval-5.11.2/hpux-definitions-schema.xsd	\
	oval-5.11.2/hpux-system-characteristics-schema.xsd	\
	oval-5.11.2/independent-definitions-schema.xsd	\
	oval-5.11.2/independent-system-characteristics-schema.xsd	\
	oval-5.11.2/ios-definitions-schema.xsd	\
	oval-5.11.2/ios-system-characteristics-schema.xsd	\
	oval-5.11.2/iosxe-definitions-schema.xsd	\
	oval-5.11.2/iosxe-system-characteristics-schema.xsd	\
	oval-5.11.2/junos-definitions-schema.xsd	\
	oval-5.11.2/junos-system-characteristics-schema.xsd	\
	oval-5.11.2/linux-definitions-schema.xsd	\
	oval-5.11.2/linux-system-characteristics-schema.xsd	\
	oval-5.11.2/macos-definitions-schema.xsd	\
	oval-5.11.2/macos-system-characteristics-schema.xsd	\
	oval-5.11.2/netconf-definitions-schema.xsd	\
	oval-5.11.2/netconf-system-characteristics-schema.xsd	\
	oval-5.11.2/pixos-definitions-schema.xsd	\
	oval-5.11.2/pixos-system-characteristics-schema.xsd	\
	oval-5.11.2/sharepoint-definitions-schema.xsd	\
	oval-5.11.2/sharepoint-system-characteristics-schema.xsd	\
	oval-5.11.2/solaris-definitions-schema.xsd	\
	oval-5.11.2/solaris-system-characteristics-schema.xsd	\
	oval-5.11.2/unix-definitions-schema.xsd	\
	oval-5.11.2/unix-system-characteristics-schema.xsd	\
	oval-5.11.2/windows-definitions-schema.xsd	\
	oval-5.11.2/windows-system-characteristics-schema.xsd	\
	oval-5.11.2/oval-directives-schema.xsd	\
	oval-5.11.2/oval-variables-schema.xsd	\
	oval-5.11.2/evaluation-ids.xsd	\
	sce-1.0/sce-1.0-xccdf-extended-component.xsd	\
	sce-1.0/sce-result-schema.xsd	\
	xccdf-1.2/xccdf_1.2.xsd	\
	xml/xlink.xsd	\
	xml/xmldsig-core-schema.xsd

