SCHEMAS=\
	ai-1.1/asset-identification_1.1.0.xsd	\
	arf-1.1/asset-reporting-format_1.1.0.xsd	\
	arf-1.1/reporting-core_1.1.0.xsd	\
	constructs-1.2/scap-constructs_1.2.xsd	\
	cpe-2.3/cpe-dictionary-extension_2.3.xsd	\
	cpe-2.3/cpe-dictionary_2.3.xsd	\
	cpe-2.3/cpe-language_2.3.xsd	\
	cpe-2.3/cpe-naming_2.3.xsd	\
	ds-1.2/scap-source-data-stream_1.2.xsd	\
	dublin/simpledc20021212.xsd	\
	joval/diagnostic-schema-1.0.xsd	\
	oasis/catalog-1.1.xsd	\
	oasis/xAL.xsd	\
	oasis/xNL.xsd	\
	ocil-2.0/ocil-2.0.xsd	\
	ocil-2.0/ocil-diagnostic-schema.xsd	\
	ocil-2.0/ocil-variables-schema.xsd	\
	oval-5.11/oval-common-schema.xsd	\
	oval-5.11/oval-definitions-schema.xsd	\
	oval-5.11/oval-system-characteristics-schema.xsd	\
	oval-5.11/oval-results-schema.xsd	\
	oval-5.11/aix-definitions-schema.xsd	\
	oval-5.11/aix-system-characteristics-schema.xsd	\
	oval-5.11/android-definitions-schema.xsd	\
	oval-5.11/android-system-characteristics-schema.xsd	\
	oval-5.11/apache-definitions-schema.xsd	\
	oval-5.11/apache-system-characteristics-schema.xsd	\
	oval-5.11/apple-ios-definitions-schema.xsd	\
	oval-5.11/apple-ios-system-characteristics-schema.xsd	\
	oval-5.11/asa-definitions-schema.xsd	\
	oval-5.11/asa-system-characteristics-schema.xsd	\
	oval-5.11/catos-definitions-schema.xsd	\
	oval-5.11/catos-system-characteristics-schema.xsd	\
	oval-5.11/esx-definitions-schema.xsd	\
	oval-5.11/esx-system-characteristics-schema.xsd	\
	oval-5.11/freebsd-definitions-schema.xsd	\
	oval-5.11/freebsd-system-characteristics-schema.xsd	\
	oval-5.11/hpux-definitions-schema.xsd	\
	oval-5.11/hpux-system-characteristics-schema.xsd	\
	oval-5.11/independent-definitions-schema.xsd	\
	oval-5.11/independent-system-characteristics-schema.xsd	\
	oval-5.11/ios-definitions-schema.xsd	\
	oval-5.11/ios-system-characteristics-schema.xsd	\
	oval-5.11/iosxe-definitions-schema.xsd	\
	oval-5.11/iosxe-system-characteristics-schema.xsd	\
	oval-5.11/junos-definitions-schema.xsd	\
	oval-5.11/junos-system-characteristics-schema.xsd	\
	oval-5.11/linux-definitions-schema.xsd	\
	oval-5.11/linux-system-characteristics-schema.xsd	\
	oval-5.11/macos-definitions-schema.xsd	\
	oval-5.11/macos-system-characteristics-schema.xsd	\
	oval-5.11/netconf-definitions-schema.xsd	\
	oval-5.11/netconf-system-characteristics-schema.xsd	\
	oval-5.11/pixos-definitions-schema.xsd	\
	oval-5.11/pixos-system-characteristics-schema.xsd	\
	oval-5.11/sharepoint-definitions-schema.xsd	\
	oval-5.11/sharepoint-system-characteristics-schema.xsd	\
	oval-5.11/solaris-definitions-schema.xsd	\
	oval-5.11/solaris-system-characteristics-schema.xsd	\
	oval-5.11/unix-definitions-schema.xsd	\
	oval-5.11/unix-system-characteristics-schema.xsd	\
	oval-5.11/windows-definitions-schema.xsd	\
	oval-5.11/windows-system-characteristics-schema.xsd	\
	oval-5.11/oval-directives-schema.xsd	\
	oval-5.11/oval-variables-schema.xsd	\
	oval-5.11/evaluation-ids.xsd	\
	sce-1.0/sce-1.0-xccdf-extended-component.xsd	\
	sce-1.0/sce-result-schema.xsd	\
	xccdf-1.2/xccdf_1.2.xsd	\
	xml/xlink.xsd	\
	xml/xmldsig-core-schema.xsd

