SCHEMAS=\
	ai-1.1/asset-identification_1.1.0.xsd	\
	arf-1.1/asset-reporting-format_1.1.0.xsd	\
	arf-1.1/reporting-core_1.1.0.xsd	\
	constructs-1.2/scap-constructs_1.2.xsd	\
	cpe-2.3/cpe-dictionary-extension_2.3.xsd	\
	cpe-2.3/cpe-dictionary_2.3.xsd	\
	cpe-2.3/cpe-language_2.3.xsd	\
	cpe-2.3/cpe-naming_2.3.xsd	\
	ds-1.2/scap-source-data-stream_1.2.xsd	\
	dublin/simpledc20021212.xsd	\
	joval/diagnostic-schema-1.0.xsd	\
	oasis/catalog-1.1.xsd	\
	oasis/xAL.xsd	\
	oasis/xNL.xsd	\
	ocil-2.0/ocil-2.0.xsd	\
	ocil-2.0/ocil-diagnostic-schema.xsd	\
	ocil-2.0/ocil-variables-schema.xsd	\
	oval-5.10.1/aix-definitions-schema.xsd	\
	oval-5.10.1/aix-system-characteristics-schema.xsd	\
	oval-5.10.1/apache-definitions-schema.xsd	\
	oval-5.10.1/apache-system-characteristics-schema.xsd	\
	oval-5.10.1/catos-definitions-schema.xsd	\
	oval-5.10.1/catos-system-characteristics-schema.xsd	\
	oval-5.10.1/esx-definitions-schema.xsd	\
	oval-5.10.1/esx-system-characteristics-schema.xsd	\
	oval-5.10.1/evaluation-ids.xsd	\
	oval-5.10.1/freebsd-definitions-schema.xsd	\
	oval-5.10.1/freebsd-system-characteristics-schema.xsd	\
	oval-5.10.1/hpux-definitions-schema.xsd	\
	oval-5.10.1/hpux-system-characteristics-schema.xsd	\
	oval-5.10.1/independent-definitions-schema.xsd	\
	oval-5.10.1/independent-system-characteristics-schema.xsd	\
	oval-5.10.1/ios-definitions-schema.xsd	\
	oval-5.10.1/ios-system-characteristics-schema.xsd	\
	oval-5.10.1/linux-definitions-schema.xsd	\
	oval-5.10.1/linux-system-characteristics-schema.xsd	\
	oval-5.10.1/macos-definitions-schema.xsd	\
	oval-5.10.1/macos-system-characteristics-schema.xsd	\
	oval-5.10.1/oval-common-schema.xsd	\
	oval-5.10.1/oval-definitions-schema.xsd	\
	oval-5.10.1/oval-directives-schema.xsd	\
	oval-5.10.1/oval-results-schema.xsd	\
	oval-5.10.1/oval-system-characteristics-schema.xsd	\
	oval-5.10.1/oval-variables-schema.xsd	\
	oval-5.10.1/pixos-definitions-schema.xsd	\
	oval-5.10.1/pixos-system-characteristics-schema.xsd	\
	oval-5.10.1/sharepoint-definitions-schema.xsd	\
	oval-5.10.1/sharepoint-system-characteristics-schema.xsd	\
	oval-5.10.1/solaris-definitions-schema.xsd	\
	oval-5.10.1/solaris-system-characteristics-schema.xsd	\
	oval-5.10.1/unix-definitions-schema.xsd	\
	oval-5.10.1/unix-system-characteristics-schema.xsd	\
	oval-5.10.1/windows-definitions-schema.xsd	\
	oval-5.10.1/windows-system-characteristics-schema.xsd	\
	sce-1.0/sce-1.0-xccdf-extended-component.xsd	\
	sce-1.0/sce-result-schema.xsd	\
	xccdf-1.2/xccdf_1.2.xsd	\
	xml/xlink.xsd	\
	xml/xmldsig-core-schema.xsd

