REMOTE=\
	jcifs.smb.VolatileSmbFile					\
	org.joval.discovery.SessionFactory				\
	org.joval.identity.Credential					\
	org.joval.intf.identity.ICredential				\
	org.joval.intf.identity.ILocked					\
	org.joval.io.TailDashF						\
	org.joval.plugin.RemotePlugin					\
	org.joval.unix.remote.UnixCredential				\
	org.joval.unix.remote.io.SftpError				\
	org.joval.unix.remote.io.SftpFile				\
	org.joval.unix.remote.io.SftpFilesystem				\
	org.joval.unix.remote.system.SshProcess				\
	org.joval.unix.remote.system.UnixSession			\
	org.joval.util.JSchLogger					\
	org.joval.test.Remote						\
	org.joval.windows.remote.WindowsCredential			\
	org.joval.windows.remote.registry.Key				\
	org.joval.windows.remote.registry.Registry			\
	org.joval.windows.remote.smb.SmbFilesystem			\
	org.joval.windows.remote.smb.SmbFileProxy			\
	org.joval.windows.remote.smb.SmbRandomAccessProxy		\
	org.joval.windows.remote.system.WindowsProcess			\
	org.joval.windows.remote.system.WindowsSession			\
	org.joval.windows.remote.wmi.WmiConnection			\
	org.joval.windows.remote.wmi.process.ICreateFlags		\
	org.joval.windows.remote.wmi.process.IShowWindow		\
	org.joval.windows.remote.wmi.process.SWbemSecurity		\
	org.joval.windows.remote.wmi.process.Win32Process		\
	org.joval.windows.remote.wmi.process.Win32ProcessStartup	\
	org.joval.windows.remote.wmi.query.SimpleSWbemObject		\
	org.joval.windows.remote.wmi.query.SimpleSWbemObjectSet		\
	org.joval.windows.remote.wmi.query.SimpleSWbemProperty		\
	org.joval.windows.remote.wmi.query.SimpleSWbemPropertySet
