CLASSES=\
	com.microsoft.wsman.cim.interactive.ActionTypeType	\
	com.microsoft.wsman.cim.interactive.EventTypeType	\
	com.microsoft.wsman.cim.interactive.InteractiveEventComplexType	\
	com.microsoft.wsman.cim.interactive.InteractiveEventType	\
	com.microsoft.wsman.cim.interactive.InteractiveResponseType	\
	com.microsoft.wsman.cim.interactive.ObjectFactory	\
	com.microsoft.wsman.cim.interactive.package-info	\
	com.microsoft.wsman.cim.interactive.PromptTypeType	\
	com.microsoft.wsman.cim.interactive.ResponseType	\
	com.microsoft.wsman.config.ClientAuthType	\
	com.microsoft.wsman.config.ClientDefaultPortsType	\
	com.microsoft.wsman.config.ClientType	\
	com.microsoft.wsman.config.ConfigType	\
	com.microsoft.wsman.config.ListenerType	\
	com.microsoft.wsman.config.ObjectFactory	\
	com.microsoft.wsman.config.package-info	\
	com.microsoft.wsman.config.plugin.CapabilityEnumeration	\
	com.microsoft.wsman.config.plugin.CapabilityType	\
	com.microsoft.wsman.config.plugin.InitializationParametersType	\
	com.microsoft.wsman.config.plugin.ObjectFactory	\
	com.microsoft.wsman.config.plugin.OutputBufferingModeEnumeration	\
	com.microsoft.wsman.config.plugin.package-info	\
	com.microsoft.wsman.config.plugin.ParamType	\
	com.microsoft.wsman.config.plugin.PluginType	\
	com.microsoft.wsman.config.plugin.ResourcesContainerType	\
	com.microsoft.wsman.config.plugin.ResourceType	\
	com.microsoft.wsman.config.plugin.SecurityType	\
	com.microsoft.wsman.config.plugin.XmlRenderingTypeEnumeration	\
	com.microsoft.wsman.config.service.certmapping.CertMappingType	\
	com.microsoft.wsman.config.service.certmapping.ObjectFactory	\
	com.microsoft.wsman.config.service.certmapping.package-info	\
	com.microsoft.wsman.config.service.fault.MessageType	\
	com.microsoft.wsman.config.service.fault.ObjectFactory	\
	com.microsoft.wsman.config.service.fault.package-info	\
	com.microsoft.wsman.config.service.fault.ProviderFaultType	\
	com.microsoft.wsman.config.service.fault.WSManFaultType	\
	com.microsoft.wsman.config.ServiceAuthType	\
	com.microsoft.wsman.config.ServiceDefaultPortsType	\
	com.microsoft.wsman.config.ServiceType	\
	com.microsoft.wsman.config.WinrsType	\
	com.microsoft.wsman.shell.AuthenticationType	\
	com.microsoft.wsman.shell.ClientCertificateType	\
	com.microsoft.wsman.shell.CommandLine	\
	com.microsoft.wsman.shell.CommandResponse	\
	com.microsoft.wsman.shell.CommandStateType	\
	com.microsoft.wsman.shell.CustomRemoteShell	\
	com.microsoft.wsman.shell.DesiredStreamType	\
	com.microsoft.wsman.shell.EnvironmentVariable	\
	com.microsoft.wsman.shell.EnvironmentVariableList	\
	com.microsoft.wsman.shell.MachineIDType	\
	com.microsoft.wsman.shell.ObjectFactory	\
	com.microsoft.wsman.shell.package-info	\
	com.microsoft.wsman.shell.QueryListType	\
	com.microsoft.wsman.shell.QueryType	\
	com.microsoft.wsman.shell.Receive	\
	com.microsoft.wsman.shell.ReceiveResponse	\
	com.microsoft.wsman.shell.SelectType	\
	com.microsoft.wsman.shell.Send	\
	com.microsoft.wsman.shell.SendResponse	\
	com.microsoft.wsman.shell.ShellType	\
	com.microsoft.wsman.shell.Signal	\
	com.microsoft.wsman.shell.SignalResponse	\
	com.microsoft.wsman.shell.StreamType	\
	com.microsoft.wsman.shell.SubscriptionType	\
	com.microsoft.wsman.shell.ThumbprintType	\
	org.dmtf.cim.common.CimAnySimpleType	\
	org.dmtf.cim.common.CimBase64Binary	\
	org.dmtf.cim.common.CimBoolean	\
	org.dmtf.cim.common.CimByte	\
	org.dmtf.cim.common.CimChar16	\
	org.dmtf.cim.common.CimDateTime	\
	org.dmtf.cim.common.CimDouble	\
	org.dmtf.cim.common.CimFloat	\
	org.dmtf.cim.common.CimHexBinary	\
	org.dmtf.cim.common.CimInt	\
	org.dmtf.cim.common.CimLong	\
	org.dmtf.cim.common.CimReference	\
	org.dmtf.cim.common.CimShort	\
	org.dmtf.cim.common.CimString	\
	org.dmtf.cim.common.CimUnsignedByte	\
	org.dmtf.cim.common.CimUnsignedInt	\
	org.dmtf.cim.common.CimUnsignedLong	\
	org.dmtf.cim.common.CimUnsignedShort	\
	org.dmtf.cim.common.ObjectFactory	\
	org.dmtf.cim.common.package-info	\
	org.dmtf.cim.common.QualifierBoolean	\
	org.dmtf.cim.common.QualifierSArray	\
	org.dmtf.cim.common.QualifierSInt64	\
	org.dmtf.cim.common.QualifierString	\
	org.dmtf.cim.common.QualifierUInt32	\
	org.dmtf.wsman.AccessDenied	\
	org.dmtf.wsman.AlreadyExists	\
	org.dmtf.wsman.AnyListType	\
	org.dmtf.wsman.AttributableAny	\
	org.dmtf.wsman.AttributableDuration	\
	org.dmtf.wsman.AttributableEmpty	\
	org.dmtf.wsman.AttributableInt	\
	org.dmtf.wsman.AttributableLanguage	\
	org.dmtf.wsman.AttributableNonNegativeInteger	\
	org.dmtf.wsman.AttributablePositiveInteger	\
	org.dmtf.wsman.AttributableURI	\
	org.dmtf.wsman.AuthType	\
	org.dmtf.wsman.cimbinding.AssociatedInstancesType	\
	org.dmtf.wsman.cimbinding.AssociationInstancesType	\
	org.dmtf.wsman.cimbinding.CIMException	\
	org.dmtf.wsman.cimbinding.ObjectFactory	\
	org.dmtf.wsman.cimbinding.package-info	\
	org.dmtf.wsman.cimbinding.PolymorphismModeNotSupported	\
	org.dmtf.wsman.cimbinding.PolymorphismModeType	\
	org.dmtf.wsman.Concurrency	\
	org.dmtf.wsman.ConnectionRetryType	\
	org.dmtf.wsman.DeliveryRefused	\
	org.dmtf.wsman.DialectableMixedDataType	\
	org.dmtf.wsman.DroppedEventsType	\
	org.dmtf.wsman.EncodingLimit	\
	org.dmtf.wsman.EnumerationModeType	\
	org.dmtf.wsman.EventsType	\
	org.dmtf.wsman.EventType	\
	org.dmtf.wsman.FragmentDialectNotSupported	\
	org.dmtf.wsman.InternalError	\
	org.dmtf.wsman.InvalidBookmark	\
	org.dmtf.wsman.InvalidOptions	\
	org.dmtf.wsman.InvalidParameter	\
	org.dmtf.wsman.InvalidSelectors	\
	org.dmtf.wsman.ItemType	\
	org.dmtf.wsman.Locale	\
	org.dmtf.wsman.MaxEnvelopeSizeType	\
	org.dmtf.wsman.MixedDataType	\
	org.dmtf.wsman.NoAck	\
	org.dmtf.wsman.ObjectFactory	\
	org.dmtf.wsman.OptionSet	\
	org.dmtf.wsman.OptionType	\
	org.dmtf.wsman.package-info	\
	org.dmtf.wsman.PolicyType	\
	org.dmtf.wsman.QuotaLimit	\
	org.dmtf.wsman.RequestedEPRType	\
	org.dmtf.wsman.SchemaValidationError	\
	org.dmtf.wsman.SelectorSetType	\
	org.dmtf.wsman.SelectorType	\
	org.dmtf.wsman.TimedOut	\
	org.dmtf.wsman.UnsupportedFeature	\
	org.w3c.soap.envelope.Body	\
	org.w3c.soap.envelope.Detail	\
	org.w3c.soap.envelope.Envelope	\
	org.w3c.soap.envelope.Fault	\
	org.w3c.soap.envelope.Faultcode	\
	org.w3c.soap.envelope.Faultreason	\
	org.w3c.soap.envelope.Header	\
	org.w3c.soap.envelope.NotUnderstoodType	\
	org.w3c.soap.envelope.ObjectFactory	\
	org.w3c.soap.envelope.package-info	\
	org.w3c.soap.envelope.Reasontext	\
	org.w3c.soap.envelope.Subcode	\
	org.w3c.soap.envelope.SupportedEnvType	\
	org.w3c.soap.envelope.UpgradeType	\
	org.w3c.ws.addressing.AttributedQNameType	\
	org.w3c.ws.addressing.AttributedUnsignedLongType	\
	org.w3c.ws.addressing.AttributedURIType	\
	org.w3c.ws.addressing.EndpointReferenceType	\
	org.w3c.ws.addressing.MetadataType	\
	org.w3c.ws.addressing.ObjectFactory	\
	org.w3c.ws.addressing.package-info	\
	org.w3c.ws.addressing.ProblemActionType	\
	org.w3c.ws.addressing.ReferenceParametersType	\
	org.w3c.ws.addressing.RelatesToType	\
	org.xmlsoap.ws.addressing.AttributedQName	\
	org.xmlsoap.ws.addressing.AttributedURI	\
	org.xmlsoap.ws.addressing.EndpointReferenceType	\
	org.xmlsoap.ws.addressing.ObjectFactory	\
	org.xmlsoap.ws.addressing.package-info	\
	org.xmlsoap.ws.addressing.ReferenceParametersType	\
	org.xmlsoap.ws.addressing.ReferencePropertiesType	\
	org.xmlsoap.ws.addressing.Relationship	\
	org.xmlsoap.ws.addressing.ReplyAfterType	\
	org.xmlsoap.ws.addressing.RetryAfterType	\
	org.xmlsoap.ws.addressing.ServiceNameType	\
	org.xmlsoap.ws.enumeration.Enumerate	\
	org.xmlsoap.ws.enumeration.EnumerateResponse	\
	org.xmlsoap.ws.enumeration.EnumerationContextType	\
	org.xmlsoap.ws.enumeration.EnumerationEnd	\
	org.xmlsoap.ws.enumeration.FilterType	\
	org.xmlsoap.ws.enumeration.GetStatus	\
	org.xmlsoap.ws.enumeration.GetStatusResponse	\
	org.xmlsoap.ws.enumeration.ItemListType	\
	org.xmlsoap.ws.enumeration.LanguageSpecificStringType	\
	org.xmlsoap.ws.enumeration.ObjectFactory	\
	org.xmlsoap.ws.enumeration.package-info	\
	org.xmlsoap.ws.enumeration.Pull	\
	org.xmlsoap.ws.enumeration.PullResponse	\
	org.xmlsoap.ws.enumeration.Release	\
	org.xmlsoap.ws.enumeration.Renew	\
	org.xmlsoap.ws.enumeration.RenewResponse	\
	org.xmlsoap.ws.eventing.DeliveryType	\
	org.xmlsoap.ws.eventing.FilterType	\
	org.xmlsoap.ws.eventing.GetStatus	\
	org.xmlsoap.ws.eventing.GetStatusResponse	\
	org.xmlsoap.ws.eventing.LanguageSpecificStringType	\
	org.xmlsoap.ws.eventing.ObjectFactory	\
	org.xmlsoap.ws.eventing.package-info	\
	org.xmlsoap.ws.eventing.Renew	\
	org.xmlsoap.ws.eventing.RenewResponse	\
	org.xmlsoap.ws.eventing.Subscribe	\
	org.xmlsoap.ws.eventing.SubscribeResponse	\
	org.xmlsoap.ws.eventing.SubscriptionEnd	\
	org.xmlsoap.ws.eventing.Unsubscribe	\
	org.xmlsoap.ws.transfer.AnyXmlOptionalType	\
	org.xmlsoap.ws.transfer.AnyXmlType	\
	org.xmlsoap.ws.transfer.CreateResponseType	\
	org.xmlsoap.ws.transfer.ObjectFactory	\
	org.xmlsoap.ws.transfer.package-info	\
	org.xmlsoap.ws.transfer.ResourceCreated
