CLASSES=\
	org.joval.intf.plugin.IPlugin				\
	org.joval.intf.scap.arf.IReport				\
	org.joval.intf.scap.cpe.IDictionary			\
	org.joval.intf.scap.datastream.IDatastream		\
	org.joval.intf.scap.datastream.IDatastreamCollection	\
	org.joval.intf.scap.datastream.IView			\
	org.joval.intf.scap.ocil.IChecklist			\
	org.joval.intf.scap.ocil.IVariables			\
	org.joval.intf.scap.oval.IDefinitionFilter		\
	org.joval.intf.scap.oval.IDefinitions			\
	org.joval.intf.scap.oval.IEngine			\
	org.joval.intf.scap.oval.IProvider			\
	org.joval.intf.scap.oval.IResults			\
	org.joval.intf.scap.oval.ISystemCharacteristics		\
	org.joval.intf.scap.oval.IType				\
	org.joval.intf.scap.oval.IVariables			\
	org.joval.intf.scap.xccdf.SystemEnumeration		\
	org.joval.intf.scap.xccdf.IBenchmark			\
	org.joval.intf.scap.xccdf.IEngine			\
	org.joval.intf.scap.xccdf.ITailoring			\
	org.joval.intf.util.IObserver				\
	org.joval.intf.util.IProducer				\
	org.joval.intf.xml.ITransformable			\
	org.joval.plugin.PluginConfigurationException		\
	org.joval.scap.ScapException				\
	org.joval.scap.ScapFactory				\
	org.joval.scap.arf.ArfException				\
	org.joval.scap.arf.Factories				\
	org.joval.scap.arf.Report				\
	org.joval.scap.cpe.CpeException				\
	org.joval.scap.cpe.Dictionary				\
	org.joval.scap.datastream.Datastream			\
	org.joval.scap.datastream.DatastreamCollection		\
	org.joval.scap.datastream.View				\
	org.joval.scap.ocil.BooleanTestActionConditionType	\
	org.joval.scap.ocil.Checklist				\
	org.joval.scap.ocil.ChecklistResults			\
	org.joval.scap.ocil.Factories				\
	org.joval.scap.ocil.OcilException			\
	org.joval.scap.ocil.Variables				\
	org.joval.scap.oval.CollectException			\
	org.joval.scap.oval.DefinitionFilter			\
	org.joval.scap.oval.Definitions				\
	org.joval.scap.oval.Directives				\
	org.joval.scap.oval.Factories				\
	org.joval.scap.oval.ItemSet				\
	org.joval.scap.oval.OvalException			\
	org.joval.scap.oval.OvalFactory				\
	org.joval.scap.oval.Results				\
	org.joval.scap.oval.SystemCharacteristics		\
	org.joval.scap.oval.Variables				\
	org.joval.scap.oval.engine.CheckData			\
	org.joval.scap.oval.engine.DateTime			\
	org.joval.scap.oval.engine.Engine			\
	org.joval.scap.oval.engine.ExistenceData		\
	org.joval.scap.oval.engine.FlagData			\
	org.joval.scap.oval.engine.OperatorData			\
	org.joval.scap.oval.engine.RequestContext		\
	org.joval.scap.oval.engine.ResolveException		\
	org.joval.scap.oval.engine.TestException		\
	org.joval.scap.oval.types.AbstractType			\
	org.joval.scap.oval.types.BinaryType			\
	org.joval.scap.oval.types.BooleanType			\
	org.joval.scap.oval.types.EvrStringType			\
	org.joval.scap.oval.types.FilesetRevisionType		\
	org.joval.scap.oval.types.FloatType			\
	org.joval.scap.oval.types.IntType			\
	org.joval.scap.oval.types.IosVersionType		\
	org.joval.scap.oval.types.Ip4AddressType		\
	org.joval.scap.oval.types.Ip6AddressType		\
	org.joval.scap.oval.types.RecordType			\
	org.joval.scap.oval.types.StringType			\
	org.joval.scap.oval.types.TypeConversionException	\
	org.joval.scap.oval.types.TypeFactory			\
	org.joval.scap.oval.types.VersionType			\
	org.joval.scap.oval.xml.OvalNamespacePrefixMapper	\
	org.joval.scap.sce.SceException				\
	org.joval.scap.sce.SCEScript				\
	org.joval.scap.xccdf.Benchmark				\
	org.joval.scap.xccdf.Tailoring				\
	org.joval.scap.xccdf.TestResult				\
	org.joval.scap.xccdf.XccdfException			\
	org.joval.scap.xccdf.engine.Engine			\
	org.joval.scap.xccdf.engine.RuleResult			\
	org.joval.scap.xccdf.handler.OCILHandler		\
	org.joval.scap.xccdf.handler.OVALHandler		\
	org.joval.scap.xccdf.handler.SCEHandler			\
	org.joval.util.JOVALMsg					\
	org.joval.util.JOVALSystem				\
	org.joval.util.Producer					\
	org.joval.util.Version					\
	org.joval.xml.DOMTools					\
	org.joval.xml.SchemaRegistry				\
	org.joval.xml.SignatureValidator			\
	org.joval.xml.XPathTools
