CLASSES=\
	org.joval.intf.io.IRandomAccess				\
	org.joval.intf.oval.IDefinitionFilter			\
	org.joval.intf.oval.IDefinitions			\
	org.joval.intf.oval.IEngine				\
	org.joval.intf.oval.IProvider				\
	org.joval.intf.oval.IResults				\
	org.joval.intf.oval.ISystemCharacteristics		\
	org.joval.intf.oval.IType				\
	org.joval.intf.oval.IVariables				\
	org.joval.intf.plugin.IPlugin				\
	org.joval.intf.sce.IProvider				\
	org.joval.intf.util.ILoggable				\
	org.joval.intf.util.IObserver				\
	org.joval.intf.util.IPerishable				\
	org.joval.intf.util.IProducer				\
	org.joval.intf.util.IProperty				\
	org.joval.intf.xml.ITransformable			\
	org.joval.io.LittleEndian				\
	org.joval.io.StreamTool					\
	org.joval.os.windows.Timestamp				\
	org.joval.plugin.PluginConfigurationException		\
	org.joval.scap.ScapException				\
	org.joval.scap.oval.CollectException			\
	org.joval.scap.oval.DefinitionFilter			\
	org.joval.scap.oval.Definitions				\
	org.joval.scap.oval.Directives				\
	org.joval.scap.oval.Factories				\
	org.joval.scap.oval.ItemSet				\
	org.joval.scap.oval.OvalException			\
	org.joval.scap.oval.OvalFactory				\
	org.joval.scap.oval.Results				\
	org.joval.scap.oval.SystemCharacteristics		\
	org.joval.scap.oval.Variables				\
	org.joval.scap.oval.engine.CheckData			\
	org.joval.scap.oval.engine.DateTime			\
	org.joval.scap.oval.engine.Engine			\
	org.joval.scap.oval.engine.ExistenceData		\
	org.joval.scap.oval.engine.FlagData			\
	org.joval.scap.oval.engine.OperatorData			\
	org.joval.scap.oval.engine.RequestContext		\
	org.joval.scap.oval.engine.ResolveException		\
	org.joval.scap.oval.engine.TestException		\
	org.joval.scap.oval.types.AbstractType			\
	org.joval.scap.oval.types.BinaryType			\
	org.joval.scap.oval.types.BooleanType			\
	org.joval.scap.oval.types.EvrStringType			\
	org.joval.scap.oval.types.FilesetRevisionType		\
	org.joval.scap.oval.types.FloatType			\
	org.joval.scap.oval.types.IntType			\
	org.joval.scap.oval.types.IosVersionType		\
	org.joval.scap.oval.types.Ip4AddressType		\
	org.joval.scap.oval.types.Ip6AddressType		\
	org.joval.scap.oval.types.RecordType			\
	org.joval.scap.oval.types.StringType			\
	org.joval.scap.oval.types.TypeConversionException	\
	org.joval.scap.oval.types.TypeFactory			\
	org.joval.scap.oval.types.VersionType			\
	org.joval.scap.oval.xml.OvalNamespacePrefixMapper	\
	org.joval.util.Checksum					\
	org.joval.util.IniFile					\
	org.joval.util.JOVALMsg					\
	org.joval.util.JOVALSystem				\
	org.joval.util.Producer					\
	org.joval.util.PropertyUtil				\
	org.joval.util.StringTools				\
	org.joval.util.Version					\
	org.joval.xml.DOMTools					\
	org.joval.xml.SchemaRegistry				\
	org.joval.xml.SignatureValidator			\
	org.joval.xml.XPathTools
