SHARED=\
	org.joval.identity.windows.ActiveDirectory			\
	org.joval.identity.windows.Group				\
	org.joval.identity.windows.LocalDirectory			\
	org.joval.identity.windows.User					\
	org.joval.intf.io.IFile						\
	org.joval.intf.io.IFilesystem					\
	org.joval.intf.io.IPathRedirector				\
	org.joval.intf.io.IRandomAccess					\
	org.joval.intf.system.IEnvironment				\
	org.joval.intf.system.IProcess					\
	org.joval.intf.system.ISession					\
	org.joval.intf.unix.system.IUnixSession				\
	org.joval.intf.util.tree.IForest				\
	org.joval.intf.util.tree.INode					\
	org.joval.intf.util.tree.ITree					\
	org.joval.intf.util.tree.ITreeBuilder				\
	org.joval.intf.windows.registry.IKey				\
	org.joval.intf.windows.registry.IRegistry			\
	org.joval.intf.windows.registry.IBinaryValue			\
	org.joval.intf.windows.registry.IDwordValue			\
	org.joval.intf.windows.registry.IExpandStringValue		\
	org.joval.intf.windows.registry.IMultiStringValue		\
	org.joval.intf.windows.registry.IStringValue			\
	org.joval.intf.windows.registry.IValue				\
	org.joval.intf.windows.system.IWindowsSession			\
	org.joval.intf.windows.wmi.ISWbemObject				\
	org.joval.intf.windows.wmi.ISWbemObjectSet			\
	org.joval.intf.windows.wmi.ISWbemProperty			\
	org.joval.intf.windows.wmi.ISWbemPropertySet			\
	org.joval.intf.windows.wmi.IWmiProvider				\
	org.joval.io.BaseFile						\
	org.joval.io.LittleEndian					\
	org.joval.io.StreamTool						\
	org.joval.oval.di.BasePlugin					\
	org.joval.plugin.adapter.independent.EnvironmentvariableAdapter	\
	org.joval.plugin.adapter.independent.FamilyAdapter		\
	org.joval.plugin.adapter.independent.TextfilecontentAdapter	\
	org.joval.plugin.adapter.independent.Textfilecontent54Adapter	\
	org.joval.plugin.adapter.independent.VariableAdapter		\
	org.joval.plugin.adapter.independent.XmlfilecontentAdapter	\
	org.joval.plugin.adapter.linux.RpminfoAdapter			\
	org.joval.plugin.adapter.solaris.IsainfoAdapter			\
	org.joval.plugin.adapter.solaris.PackageAdapter			\
	org.joval.plugin.adapter.solaris.Patch54Adapter			\
	org.joval.plugin.adapter.solaris.PatchAdapter			\
	org.joval.plugin.adapter.solaris.SmfAdapter			\
	org.joval.plugin.adapter.unix.FileAdapter			\
	org.joval.plugin.adapter.unix.ProcessAdapter			\
	org.joval.plugin.adapter.unix.RunlevelAdapter			\
	org.joval.plugin.adapter.unix.UnameAdapter			\
	org.joval.plugin.adapter.windows.FileAdapter			\
	org.joval.plugin.adapter.windows.GroupAdapter			\
	org.joval.plugin.adapter.windows.GroupSidAdapter		\
	org.joval.plugin.adapter.windows.RegistryAdapter		\
	org.joval.plugin.adapter.windows.UserAdapter			\
	org.joval.plugin.adapter.windows.UserSid55Adapter		\
	org.joval.plugin.adapter.windows.UserSidAdapter			\
	org.joval.plugin.adapter.windows.Wmi57Adapter			\
	org.joval.plugin.adapter.windows.WmiAdapter			\
	org.joval.test.AD						\
	org.joval.test.Exec						\
	org.joval.test.FS						\
	org.joval.test.PE						\
	org.joval.test.Reg						\
	org.joval.test.WMI						\
	org.joval.unix.NetworkInterface					\
	org.joval.unix.Sudo						\
	org.joval.unix.UnixSystemInfo					\
	org.joval.unix.system.Environment				\
	org.joval.util.Base64						\
	org.joval.util.BaseSession					\
	org.joval.util.BaseFileAdapter					\
	org.joval.util.tree.CachingTree					\
	org.joval.util.tree.Forest					\
	org.joval.util.tree.Node					\
	org.joval.util.tree.Tree					\
	org.joval.windows.WindowsSystemInfo				\
	org.joval.windows.WOW3264PathRedirector				\
	org.joval.windows.pe.Characteristics				\
	org.joval.windows.pe.DLLCharacteristics				\
	org.joval.windows.pe.ImageDOSHeader				\
	org.joval.windows.pe.ImageFileHeader				\
	org.joval.windows.pe.ImageNTHeaders				\
	org.joval.windows.pe.ImageDataDirectory				\
	org.joval.windows.pe.ImageOptionalHeader			\
	org.joval.windows.pe.ImageOptionalHeader32			\
	org.joval.windows.pe.ImageOptionalHeader64			\
	org.joval.windows.pe.ImageSectionHeader				\
	org.joval.windows.pe.LanguageConstants				\
	org.joval.windows.pe.resource.ImageResourceDataEntry		\
	org.joval.windows.pe.resource.ImageResourceDirectory		\
	org.joval.windows.pe.resource.ImageResourceDirectoryEntry	\
	org.joval.windows.pe.resource.Types				\
	org.joval.windows.pe.resource.version.StringFileInfo		\
	org.joval.windows.pe.resource.version.StringStructure		\
	org.joval.windows.pe.resource.version.StringTable		\
	org.joval.windows.pe.resource.version.Var			\
	org.joval.windows.pe.resource.version.VarFileInfo		\
	org.joval.windows.pe.resource.version.VsFixedFileInfo		\
	org.joval.windows.pe.resource.version.VsVersionInfo		\
	org.joval.windows.registry.BaseRegistry				\
	org.joval.windows.registry.BinaryValue				\
	org.joval.windows.registry.DwordValue				\
	org.joval.windows.registry.ExpandStringValue			\
	org.joval.windows.registry.MultiStringValue			\
	org.joval.windows.registry.StringValue				\
	org.joval.windows.registry.Value				\
	org.joval.windows.system.Environment				\
	org.joval.windows.wmi.WmiException
