CLASSES=\
	org.joval.intf.di.IJovaldiPlugin				\
	org.joval.intf.oval.IResults					\
	org.joval.intf.plugin.IAdapter					\
	org.joval.intf.plugin.IRequestContext				\
	org.joval.intf.plugin.IPlugin					\
	org.joval.intf.util.IObserver					\
	org.joval.intf.util.IProducer					\
	org.joval.oval.OvalException					\
	org.joval.oval.ResolveException					\
	org.joval.oval.TestException					\
	org.joval.oval.di.ExecutionState				\
	org.joval.oval.di.Main						\
	org.joval.oval.engine.DefinitionFilter				\
	org.joval.oval.engine.Definitions				\
	org.joval.oval.engine.Directives				\
	org.joval.oval.engine.Engine					\
	org.joval.oval.engine.RequestContext				\
	org.joval.oval.engine.Results					\
	org.joval.oval.engine.SystemCharacteristics			\
	org.joval.oval.engine.Variables					\
	org.joval.oval.util.CheckData					\
	org.joval.oval.util.ExistenceData				\
	org.joval.oval.util.ItemSet					\
	org.joval.oval.util.OperatorData				\
	org.joval.oval.xml.OvalNamespacePrefixMapper			\
	org.joval.oval.xml.SchematronValidationException		\
	org.joval.oval.xml.SchematronValidator				\
	org.joval.util.Checksum						\
	org.joval.util.JOVALSystem					\
	org.joval.util.Producer						\
	org.joval.util.StringTools					\
	org.joval.util.Version						\
	org.joval.windows.Timestamp
