CLASSES=\
	cpe.schemas.dictionary.CheckType	\
	cpe.schemas.dictionary.ext.ChangeDescriptionType	\
	cpe.schemas.dictionary.ext.ChangeTypeType	\
	cpe.schemas.dictionary.ext.DeprecatedInfoType	\
	cpe.schemas.dictionary.ext.DeprecationType	\
	cpe.schemas.dictionary.ext.DeprecationTypeType	\
	cpe.schemas.dictionary.ext.EvidenceReferenceType	\
	cpe.schemas.dictionary.ext.EvidenceType	\
	cpe.schemas.dictionary.ext.ItemType	\
	cpe.schemas.dictionary.ext.ObjectFactory	\
	cpe.schemas.dictionary.ext.OrganizationType	\
	cpe.schemas.dictionary.ext.package-info	\
	cpe.schemas.dictionary.ext.ProvenanceRecordType	\
	cpe.schemas.dictionary.GeneratorType	\
	cpe.schemas.dictionary.ItemType	\
	cpe.schemas.dictionary.ListType	\
	cpe.schemas.dictionary.NotesType	\
	cpe.schemas.dictionary.ObjectFactory	\
	cpe.schemas.dictionary.package-info	\
	cpe.schemas.dictionary.ReferencesType	\
	cpe.schemas.dictionary.TextType	\
	cpe.schemas.language.CheckFactRefType	\
	cpe.schemas.language.CPEFactRefType	\
	cpe.schemas.language.FactRefType	\
	cpe.schemas.language.LogicalTestType	\
	cpe.schemas.language.ObjectFactory	\
	cpe.schemas.language.OperatorEnumeration	\
	cpe.schemas.language.package-info	\
	cpe.schemas.language.PlatformBaseType	\
	cpe.schemas.language.PlatformSpecificationType	\
	cpe.schemas.language.PlatformType	\
	cpe.schemas.language.TextType	\
	ocil.schemas.core.ArtifactRefsType	\
	ocil.schemas.core.ArtifactRefType	\
	ocil.schemas.core.ArtifactResultsType	\
	ocil.schemas.core.ArtifactResultType	\
	ocil.schemas.core.ArtifactsType	\
	ocil.schemas.core.ArtifactType	\
	ocil.schemas.core.ArtifactValueType	\
	ocil.schemas.core.BinaryArtifactValueType	\
	ocil.schemas.core.BooleanQuestionModelType	\
	ocil.schemas.core.BooleanQuestionResultType	\
	ocil.schemas.core.BooleanQuestionTestActionType	\
	ocil.schemas.core.BooleanQuestionType	\
	ocil.schemas.core.ChoiceAnswerType	\
	ocil.schemas.core.ChoiceGroupType	\
	ocil.schemas.core.ChoiceQuestionResultType	\
	ocil.schemas.core.ChoiceQuestionTestActionType	\
	ocil.schemas.core.ChoiceQuestionType	\
	ocil.schemas.core.ChoiceTestActionConditionType	\
	ocil.schemas.core.ChoiceType	\
	ocil.schemas.core.CompoundTestActionType	\
	ocil.schemas.core.ConstantVariableType	\
	ocil.schemas.core.DocumentType	\
	ocil.schemas.core.EmbeddedArtifactValueType	\
	ocil.schemas.core.EqualsTestActionConditionType	\
	ocil.schemas.core.ExceptionalResultType	\
	ocil.schemas.core.ExtensionContainerType	\
	ocil.schemas.core.ExternalVariableType	\
	ocil.schemas.core.GeneratorType	\
	ocil.schemas.core.InstructionsType	\
	ocil.schemas.core.ItemBaseType	\
	ocil.schemas.core.LocalVariableType	\
	ocil.schemas.core.NamedItemBaseType	\
	ocil.schemas.core.NumericQuestionResultType	\
	ocil.schemas.core.NumericQuestionTestActionType	\
	ocil.schemas.core.NumericQuestionType	\
	ocil.schemas.core.ObjectFactory	\
	ocil.schemas.core.OCILType	\
	ocil.schemas.core.OperationType	\
	ocil.schemas.core.OperatorType	\
	ocil.schemas.core.package-info	\
	ocil.schemas.core.PatternTestActionConditionType	\
	ocil.schemas.core.PatternType	\
	ocil.schemas.core.QuestionnaireResultsType	\
	ocil.schemas.core.QuestionnaireResultType	\
	ocil.schemas.core.QuestionnairesType	\
	ocil.schemas.core.QuestionnaireType	\
	ocil.schemas.core.QuestionResultsType	\
	ocil.schemas.core.QuestionResultType	\
	ocil.schemas.core.QuestionsType	\
	ocil.schemas.core.QuestionTestActionType	\
	ocil.schemas.core.QuestionTextType	\
	ocil.schemas.core.QuestionType	\
	ocil.schemas.core.RangeTestActionConditionType	\
	ocil.schemas.core.RangeType	\
	ocil.schemas.core.RangeValueType	\
	ocil.schemas.core.ReferenceArtifactValueType	\
	ocil.schemas.core.ReferencesType	\
	ocil.schemas.core.ReferenceType	\
	ocil.schemas.core.ResultsType	\
	ocil.schemas.core.SetExpressionBaseType	\
	ocil.schemas.core.SetExpressionBooleanType	\
	ocil.schemas.core.SetExpressionChoiceType	\
	ocil.schemas.core.SetExpressionPatternType	\
	ocil.schemas.core.SetExpressionRangeType	\
	ocil.schemas.core.StepType	\
	ocil.schemas.core.StringQuestionResultType	\
	ocil.schemas.core.StringQuestionTestActionType	\
	ocil.schemas.core.StringQuestionType	\
	ocil.schemas.core.SubstitutionTextType	\
	ocil.schemas.core.SystemTargetType	\
	ocil.schemas.core.TargetsType	\
	ocil.schemas.core.TestActionConditionType	\
	ocil.schemas.core.TestActionRefType	\
	ocil.schemas.core.TestActionResultsType	\
	ocil.schemas.core.TestActionResultType	\
	ocil.schemas.core.TestActionsType	\
	ocil.schemas.core.TextArtifactValueType	\
	ocil.schemas.core.TextType	\
	ocil.schemas.core.UserType	\
	ocil.schemas.core.VariableDataType	\
	ocil.schemas.core.VariableSetType	\
	ocil.schemas.core.VariablesType	\
	ocil.schemas.core.VariableType	\
	ocil.schemas.variables.ObjectFactory	\
	ocil.schemas.variables.OcilVariables	\
	ocil.schemas.variables.package-info	\
	ocil.schemas.variables.VariablesType	\
	ocil.schemas.variables.VariableType	\
	org.oasis.catalog.Catalog	\
	org.oasis.catalog.DelegatePublic	\
	org.oasis.catalog.DelegateSystem	\
	org.oasis.catalog.DelegateURI	\
	org.oasis.catalog.Group	\
	org.oasis.catalog.NextCatalog	\
	org.oasis.catalog.ObjectFactory	\
	org.oasis.catalog.package-info	\
	org.oasis.catalog.Public	\
	org.oasis.catalog.RewriteSystem	\
	org.oasis.catalog.RewriteURI	\
	org.oasis.catalog.System	\
	org.oasis.catalog.SystemOrPublic	\
	org.oasis.catalog.Uri	\
	org.openscap.sce.xccdf.ObjectFactory	\
	org.openscap.sce.xccdf.package-info	\
	org.openscap.sce.xccdf.LangEnumeration	\
	org.openscap.sce.xccdf.ScriptDataType	\
	org.purl.dc.ElementType	\
	org.purl.dc.ObjectFactory	\
	org.purl.dc.package-info	\
	org.w3c.xml.signature.CanonicalizationMethodType	\
	org.w3c.xml.signature.DigestMethodType	\
	org.w3c.xml.signature.DSAKeyValueType	\
	org.w3c.xml.signature.KeyInfoType	\
	org.w3c.xml.signature.KeyValueType	\
	org.w3c.xml.signature.ManifestType	\
	org.w3c.xml.signature.ObjectFactory	\
	org.w3c.xml.signature.ObjectType	\
	org.w3c.xml.signature.package-info	\
	org.w3c.xml.signature.PGPDataType	\
	org.w3c.xml.signature.ReferenceType	\
	org.w3c.xml.signature.RetrievalMethodType	\
	org.w3c.xml.signature.RSAKeyValueType	\
	org.w3c.xml.signature.SignatureMethodType	\
	org.w3c.xml.signature.SignaturePropertiesType	\
	org.w3c.xml.signature.SignaturePropertyType	\
	org.w3c.xml.signature.SignatureType	\
	org.w3c.xml.signature.SignatureValueType	\
	org.w3c.xml.signature.SignedInfoType	\
	org.w3c.xml.signature.SPKIDataType	\
	org.w3c.xml.signature.TransformsType	\
	org.w3c.xml.signature.TransformType	\
	org.w3c.xml.signature.X509DataType	\
	org.w3c.xml.signature.X509IssuerSerialType	\
	org.w3c.xml.xlink.ActuateType	\
	org.w3c.xml.xlink.ArcType	\
	org.w3c.xml.xlink.Extended	\
	org.w3c.xml.xlink.LocatorType	\
	org.w3c.xml.xlink.ObjectFactory	\
	org.w3c.xml.xlink.package-info	\
	org.w3c.xml.xlink.ResourceType	\
	org.w3c.xml.xlink.ShowType	\
	org.w3c.xml.xlink.Simple	\
	org.w3c.xml.xlink.TitleEltType	\
	org.w3c.xml.xlink.TypeType	\
	oval.schemas.common.CheckEnumeration	\
	oval.schemas.common.ClassEnumeration	\
	oval.schemas.common.ComplexDatatypeEnumeration	\
	oval.schemas.common.DeprecatedInfoType	\
	oval.schemas.common.ElementMapItemType	\
	oval.schemas.common.ElementMapType	\
	oval.schemas.common.ExistenceEnumeration	\
	oval.schemas.common.FamilyEnumeration	\
	oval.schemas.common.GeneratorType	\
	oval.schemas.common.MessageLevelEnumeration	\
	oval.schemas.common.MessageType	\
	oval.schemas.common.ObjectFactory	\
	oval.schemas.common.OperationEnumeration	\
	oval.schemas.common.OperatorEnumeration	\
	oval.schemas.common.package-info	\
	oval.schemas.common.SimpleDatatypeEnumeration	\
	oval.schemas.definitions.aix.EntityStateFilesetStateType	\
	oval.schemas.definitions.aix.EntityStateFixInstallationStatusType	\
	oval.schemas.definitions.aix.EntityStateInterimFixStateType	\
	oval.schemas.definitions.aix.FilesetObject	\
	oval.schemas.definitions.aix.FilesetState	\
	oval.schemas.definitions.aix.FilesetTest	\
	oval.schemas.definitions.aix.FixObject	\
	oval.schemas.definitions.aix.FixState	\
	oval.schemas.definitions.aix.FixTest	\
	oval.schemas.definitions.aix.InterimFixObject	\
	oval.schemas.definitions.aix.InterimFixState	\
	oval.schemas.definitions.aix.InterimFixTest	\
	oval.schemas.definitions.aix.NoObject	\
	oval.schemas.definitions.aix.NoState	\
	oval.schemas.definitions.aix.NoTest	\
	oval.schemas.definitions.aix.ObjectFactory	\
	oval.schemas.definitions.aix.OslevelObject	\
	oval.schemas.definitions.aix.OslevelState	\
	oval.schemas.definitions.aix.OslevelTest	\
	oval.schemas.definitions.aix.package-info	\
	oval.schemas.definitions.apache.HttpdObject	\
	oval.schemas.definitions.apache.HttpdState	\
	oval.schemas.definitions.apache.HttpdTest	\
	oval.schemas.definitions.apache.ObjectFactory	\
	oval.schemas.definitions.apache.package-info	\
	oval.schemas.definitions.catos.LineObject	\
	oval.schemas.definitions.catos.LineState	\
	oval.schemas.definitions.catos.LineTest	\
	oval.schemas.definitions.catos.ModuleObject	\
	oval.schemas.definitions.catos.ModuleState	\
	oval.schemas.definitions.catos.ModuleTest	\
	oval.schemas.definitions.catos.ObjectFactory	\
	oval.schemas.definitions.catos.package-info	\
	oval.schemas.definitions.catos.Version55Object	\
	oval.schemas.definitions.catos.Version55State	\
	oval.schemas.definitions.catos.Version55Test	\
	oval.schemas.definitions.catos.VersionObject	\
	oval.schemas.definitions.catos.VersionState	\
	oval.schemas.definitions.catos.VersionTest	\
	oval.schemas.definitions.core.AffectedType	\
	oval.schemas.definitions.core.ArithmeticEnumeration	\
	oval.schemas.definitions.core.ArithmeticFunctionType	\
	oval.schemas.definitions.core.BeginFunctionType	\
	oval.schemas.definitions.core.ConcatFunctionType	\
	oval.schemas.definitions.core.ConstantVariable	\
	oval.schemas.definitions.core.CountFunctionType	\
	oval.schemas.definitions.core.CriteriaType	\
	oval.schemas.definitions.core.CriterionType	\
	oval.schemas.definitions.core.DateTimeFormatEnumeration	\
	oval.schemas.definitions.core.DefinitionsType	\
	oval.schemas.definitions.core.DefinitionType	\
	oval.schemas.definitions.core.EndFunctionType	\
	oval.schemas.definitions.core.EntityComplexBaseType	\
	oval.schemas.definitions.core.EntityObjectAnySimpleType	\
	oval.schemas.definitions.core.EntityObjectBinaryType	\
	oval.schemas.definitions.core.EntityObjectBoolType	\
	oval.schemas.definitions.core.EntityObjectFieldType	\
	oval.schemas.definitions.core.EntityObjectFloatType	\
	oval.schemas.definitions.core.EntityObjectIntType	\
	oval.schemas.definitions.core.EntityObjectIPAddressStringType	\
	oval.schemas.definitions.core.EntityObjectIPAddressType	\
	oval.schemas.definitions.core.EntityObjectRecordType	\
	oval.schemas.definitions.core.EntityObjectStringType	\
	oval.schemas.definitions.core.EntityObjectVersionType	\
	oval.schemas.definitions.core.EntitySimpleBaseType	\
	oval.schemas.definitions.core.EntityStateAnySimpleType	\
	oval.schemas.definitions.core.EntityStateBinaryType	\
	oval.schemas.definitions.core.EntityStateBoolType	\
	oval.schemas.definitions.core.EntityStateComplexBaseType	\
	oval.schemas.definitions.core.EntityStateEVRStringType	\
	oval.schemas.definitions.core.EntityStateFieldType	\
	oval.schemas.definitions.core.EntityStateFileSetRevisionType	\
	oval.schemas.definitions.core.EntityStateFloatType	\
	oval.schemas.definitions.core.EntityStateIntType	\
	oval.schemas.definitions.core.EntityStateIOSVersionType	\
	oval.schemas.definitions.core.EntityStateIPAddressStringType	\
	oval.schemas.definitions.core.EntityStateIPAddressType	\
	oval.schemas.definitions.core.EntityStateRecordType	\
	oval.schemas.definitions.core.EntityStateSimpleBaseType	\
	oval.schemas.definitions.core.EntityStateStringType	\
	oval.schemas.definitions.core.EntityStateVersionType	\
	oval.schemas.definitions.core.EscapeRegexFunctionType	\
	oval.schemas.definitions.core.ExtendDefinitionType	\
	oval.schemas.definitions.core.ExternalVariable	\
	oval.schemas.definitions.core.Filter	\
	oval.schemas.definitions.core.FilterActionEnumeration	\
	oval.schemas.definitions.core.LiteralComponentType	\
	oval.schemas.definitions.core.LocalVariable	\
	oval.schemas.definitions.core.MetadataType	\
	oval.schemas.definitions.core.NotesType	\
	oval.schemas.definitions.core.ObjectComponentType	\
	oval.schemas.definitions.core.ObjectFactory	\
	oval.schemas.definitions.core.ObjectRefType	\
	oval.schemas.definitions.core.ObjectsType	\
	oval.schemas.definitions.core.ObjectType	\
	oval.schemas.definitions.core.OvalDefinitions	\
	oval.schemas.definitions.core.package-info	\
	oval.schemas.definitions.core.PossibleRestrictionType	\
	oval.schemas.definitions.core.PossibleValueType	\
	oval.schemas.definitions.core.ReferenceType	\
	oval.schemas.definitions.core.RegexCaptureFunctionType	\
	oval.schemas.definitions.core.RestrictionType	\
	oval.schemas.definitions.core.Set	\
	oval.schemas.definitions.core.SetOperatorEnumeration	\
	oval.schemas.definitions.core.SplitFunctionType	\
	oval.schemas.definitions.core.StateRefType	\
	oval.schemas.definitions.core.StatesType	\
	oval.schemas.definitions.core.StateType	\
	oval.schemas.definitions.core.SubstringFunctionType	\
	oval.schemas.definitions.core.TestsType	\
	oval.schemas.definitions.core.TestType	\
	oval.schemas.definitions.core.TimeDifferenceFunctionType	\
	oval.schemas.definitions.core.UniqueFunctionType	\
	oval.schemas.definitions.core.ValueType	\
	oval.schemas.definitions.core.VariableComponentType	\
	oval.schemas.definitions.core.VariablesType	\
	oval.schemas.definitions.core.VariableType	\
	oval.schemas.definitions.esx.EntityStateClassificationType	\
	oval.schemas.definitions.esx.EntityStateSupportLevelType	\
	oval.schemas.definitions.esx.ObjectFactory	\
	oval.schemas.definitions.esx.package-info	\
	oval.schemas.definitions.esx.Patch56Behaviors	\
	oval.schemas.definitions.esx.Patch56Object	\
	oval.schemas.definitions.esx.Patch56State	\
	oval.schemas.definitions.esx.Patch56Test	\
	oval.schemas.definitions.esx.PatchBehaviors	\
	oval.schemas.definitions.esx.PatchObject	\
	oval.schemas.definitions.esx.PatchState	\
	oval.schemas.definitions.esx.PatchTest	\
	oval.schemas.definitions.esx.VersionObject	\
	oval.schemas.definitions.esx.VersionState	\
	oval.schemas.definitions.esx.VersionTest	\
	oval.schemas.definitions.esx.ViSdkManagedEntityBehaviors	\
	oval.schemas.definitions.esx.VisdkmanagedobjectObject	\
	oval.schemas.definitions.esx.VisdkmanagedobjectState	\
	oval.schemas.definitions.esx.VisdkmanagedobjectTest	\
	oval.schemas.definitions.freebsd.ObjectFactory	\
	oval.schemas.definitions.freebsd.package-info	\
	oval.schemas.definitions.freebsd.PortinfoObject	\
	oval.schemas.definitions.freebsd.PortinfoState	\
	oval.schemas.definitions.freebsd.PortinfoTest	\
	oval.schemas.definitions.hpux.GetconfObject	\
	oval.schemas.definitions.hpux.GetconfState	\
	oval.schemas.definitions.hpux.GetconfTest	\
	oval.schemas.definitions.hpux.NddObject	\
	oval.schemas.definitions.hpux.NddState	\
	oval.schemas.definitions.hpux.NddTest	\
	oval.schemas.definitions.hpux.ObjectFactory	\
	oval.schemas.definitions.hpux.package-info	\
	oval.schemas.definitions.hpux.Patch53Behaviors	\
	oval.schemas.definitions.hpux.Patch53Object	\
	oval.schemas.definitions.hpux.Patch53State	\
	oval.schemas.definitions.hpux.Patch53Test	\
	oval.schemas.definitions.hpux.PatchObject	\
	oval.schemas.definitions.hpux.PatchState	\
	oval.schemas.definitions.hpux.PatchTest	\
	oval.schemas.definitions.hpux.SwlistObject	\
	oval.schemas.definitions.hpux.SwlistState	\
	oval.schemas.definitions.hpux.SwlistTest	\
	oval.schemas.definitions.hpux.TrustedObject	\
	oval.schemas.definitions.hpux.TrustedState	\
	oval.schemas.definitions.hpux.TrustedTest	\
	oval.schemas.definitions.independent.EntityObjectEngineType	\
	oval.schemas.definitions.independent.EntityObjectHashTypeType	\
	oval.schemas.definitions.independent.EntityObjectVariableRefType	\
	oval.schemas.definitions.independent.EntityStateEngineType	\
	oval.schemas.definitions.independent.EntityStateFamilyType	\
	oval.schemas.definitions.independent.EntityStateHashTypeType	\
	oval.schemas.definitions.independent.EntityStateLdaptypeType	\
	oval.schemas.definitions.independent.EntityStateVariableRefType	\
	oval.schemas.definitions.independent.EntityStateWindowsViewType	\
	oval.schemas.definitions.independent.Environmentvariable58Object	\
	oval.schemas.definitions.independent.Environmentvariable58State	\
	oval.schemas.definitions.independent.Environmentvariable58Test	\
	oval.schemas.definitions.independent.EnvironmentvariableObject	\
	oval.schemas.definitions.independent.EnvironmentvariableState	\
	oval.schemas.definitions.independent.EnvironmentvariableTest	\
	oval.schemas.definitions.independent.FamilyObject	\
	oval.schemas.definitions.independent.FamilyState	\
	oval.schemas.definitions.independent.FamilyTest	\
	oval.schemas.definitions.independent.FileBehaviors	\
	oval.schemas.definitions.independent.Filehash58Object	\
	oval.schemas.definitions.independent.Filehash58State	\
	oval.schemas.definitions.independent.Filehash58Test	\
	oval.schemas.definitions.independent.FilehashObject	\
	oval.schemas.definitions.independent.FilehashState	\
	oval.schemas.definitions.independent.FilehashTest	\
	oval.schemas.definitions.independent.Ldap57Object	\
	oval.schemas.definitions.independent.Ldap57State	\
	oval.schemas.definitions.independent.Ldap57Test	\
	oval.schemas.definitions.independent.LdapBehaviors	\
	oval.schemas.definitions.independent.LdapObject	\
	oval.schemas.definitions.independent.LdapState	\
	oval.schemas.definitions.independent.LdapTest	\
	oval.schemas.definitions.independent.ObjectFactory	\
	oval.schemas.definitions.independent.package-info	\
	oval.schemas.definitions.independent.Sql57Object	\
	oval.schemas.definitions.independent.Sql57State	\
	oval.schemas.definitions.independent.Sql57Test	\
	oval.schemas.definitions.independent.SqlObject	\
	oval.schemas.definitions.independent.SqlState	\
	oval.schemas.definitions.independent.SqlTest	\
	oval.schemas.definitions.independent.Textfilecontent54Behaviors	\
	oval.schemas.definitions.independent.Textfilecontent54Object	\
	oval.schemas.definitions.independent.Textfilecontent54State	\
	oval.schemas.definitions.independent.Textfilecontent54Test	\
	oval.schemas.definitions.independent.TextfilecontentObject	\
	oval.schemas.definitions.independent.TextfilecontentState	\
	oval.schemas.definitions.independent.TextfilecontentTest	\
	oval.schemas.definitions.independent.UnknownTest	\
	oval.schemas.definitions.independent.VariableObject	\
	oval.schemas.definitions.independent.VariableState	\
	oval.schemas.definitions.independent.VariableTest	\
	oval.schemas.definitions.independent.XmlfilecontentObject	\
	oval.schemas.definitions.independent.XmlfilecontentState	\
	oval.schemas.definitions.independent.XmlfilecontentTest	\
	oval.schemas.definitions.ios.EntityStateTrainIdentifierType	\
	oval.schemas.definitions.ios.GlobalObject	\
	oval.schemas.definitions.ios.GlobalState	\
	oval.schemas.definitions.ios.GlobalTest	\
	oval.schemas.definitions.ios.InterfaceObject	\
	oval.schemas.definitions.ios.InterfaceState	\
	oval.schemas.definitions.ios.InterfaceTest	\
	oval.schemas.definitions.ios.LineObject	\
	oval.schemas.definitions.ios.LineState	\
	oval.schemas.definitions.ios.LineTest	\
	oval.schemas.definitions.ios.ObjectFactory	\
	oval.schemas.definitions.ios.package-info	\
	oval.schemas.definitions.ios.SnmpObject	\
	oval.schemas.definitions.ios.SnmpState	\
	oval.schemas.definitions.ios.SnmpTest	\
	oval.schemas.definitions.ios.TclshObject	\
	oval.schemas.definitions.ios.TclshState	\
	oval.schemas.definitions.ios.TclshTest	\
	oval.schemas.definitions.ios.Version55Object	\
	oval.schemas.definitions.ios.Version55State	\
	oval.schemas.definitions.ios.Version55Test	\
	oval.schemas.definitions.ios.VersionObject	\
	oval.schemas.definitions.ios.VersionState	\
	oval.schemas.definitions.ios.VersionTest	\
	oval.schemas.definitions.junos.GlobalObject	\
	oval.schemas.definitions.junos.GlobalState	\
	oval.schemas.definitions.junos.GlobalTest	\
	oval.schemas.definitions.junos.LineObject	\
	oval.schemas.definitions.junos.LineState	\
	oval.schemas.definitions.junos.LineTest	\
	oval.schemas.definitions.junos.ObjectFactory	\
	oval.schemas.definitions.junos.package-info	\
	oval.schemas.definitions.junos.VersionObject	\
	oval.schemas.definitions.junos.VersionState	\
	oval.schemas.definitions.junos.VersionTest	\
	oval.schemas.definitions.junos.XmlLineObject	\
	oval.schemas.definitions.junos.XmlLineState	\
	oval.schemas.definitions.junos.XmlLineTest	\
	oval.schemas.definitions.linux.DpkginfoObject	\
	oval.schemas.definitions.linux.DpkginfoState	\
	oval.schemas.definitions.linux.DpkginfoTest	\
	oval.schemas.definitions.linux.EntityStateProtocolType	\
	oval.schemas.definitions.linux.EntityStateRpmVerifyResultType	\
	oval.schemas.definitions.linux.FileBehaviors	\
	oval.schemas.definitions.linux.IflistenersObject	\
	oval.schemas.definitions.linux.IflistenersState	\
	oval.schemas.definitions.linux.IflistenersTest	\
	oval.schemas.definitions.linux.InetlisteningserversObject	\
	oval.schemas.definitions.linux.InetlisteningserversState	\
	oval.schemas.definitions.linux.InetlisteningserversTest	\
	oval.schemas.definitions.linux.ObjectFactory	\
	oval.schemas.definitions.linux.package-info	\
	oval.schemas.definitions.linux.PartitionObject	\
	oval.schemas.definitions.linux.PartitionState	\
	oval.schemas.definitions.linux.PartitionTest	\
	oval.schemas.definitions.linux.RpmInfoBehaviors	\
	oval.schemas.definitions.linux.RpminfoObject	\
	oval.schemas.definitions.linux.RpminfoState	\
	oval.schemas.definitions.linux.RpminfoTest	\
	oval.schemas.definitions.linux.RpmVerifyBehaviors	\
	oval.schemas.definitions.linux.RpmVerifyFileBehaviors	\
	oval.schemas.definitions.linux.RpmverifyfileObject	\
	oval.schemas.definitions.linux.RpmverifyfileState	\
	oval.schemas.definitions.linux.RpmverifyfileTest	\
	oval.schemas.definitions.linux.RpmverifyObject	\
	oval.schemas.definitions.linux.RpmVerifyPackageBehaviors	\
	oval.schemas.definitions.linux.RpmverifypackageObject	\
	oval.schemas.definitions.linux.RpmverifypackageState	\
	oval.schemas.definitions.linux.RpmverifypackageTest	\
	oval.schemas.definitions.linux.RpmverifyState	\
	oval.schemas.definitions.linux.RpmverifyTest	\
	oval.schemas.definitions.linux.SelinuxbooleanObject	\
	oval.schemas.definitions.linux.SelinuxbooleanState	\
	oval.schemas.definitions.linux.SelinuxbooleanTest	\
	oval.schemas.definitions.linux.SelinuxsecuritycontextObject	\
	oval.schemas.definitions.linux.SelinuxsecuritycontextState	\
	oval.schemas.definitions.linux.SelinuxsecuritycontextTest	\
	oval.schemas.definitions.linux.SlackwarepkginfoObject	\
	oval.schemas.definitions.linux.SlackwarepkginfoState	\
	oval.schemas.definitions.linux.SlackwarepkginfoTest	\
	oval.schemas.definitions.macos.AccountinfoObject	\
	oval.schemas.definitions.macos.AccountinfoState	\
	oval.schemas.definitions.macos.AccountinfoTest	\
	oval.schemas.definitions.macos.DiskutilObject	\
	oval.schemas.definitions.macos.DiskutilState	\
	oval.schemas.definitions.macos.DiskutilTest	\
	oval.schemas.definitions.macos.EntityStatePermissionCompareType	\
	oval.schemas.definitions.macos.EntityStatePlistTypeType	\
	oval.schemas.definitions.macos.Inetlisteningserver510Object	\
	oval.schemas.definitions.macos.Inetlisteningserver510State	\
	oval.schemas.definitions.macos.Inetlisteningserver510Test	\
	oval.schemas.definitions.macos.InetlisteningserversObject	\
	oval.schemas.definitions.macos.InetlisteningserversState	\
	oval.schemas.definitions.macos.InetlisteningserversTest	\
	oval.schemas.definitions.macos.NvramObject	\
	oval.schemas.definitions.macos.NvramState	\
	oval.schemas.definitions.macos.NvramTest	\
	oval.schemas.definitions.macos.ObjectFactory	\
	oval.schemas.definitions.macos.package-info	\
	oval.schemas.definitions.macos.Plist510Object	\
	oval.schemas.definitions.macos.Plist510State	\
	oval.schemas.definitions.macos.Plist510Test	\
	oval.schemas.definitions.macos.PlistObject	\
	oval.schemas.definitions.macos.PlistState	\
	oval.schemas.definitions.macos.PlistTest	\
	oval.schemas.definitions.macos.Pwpolicy59Object	\
	oval.schemas.definitions.macos.Pwpolicy59State	\
	oval.schemas.definitions.macos.Pwpolicy59Test	\
	oval.schemas.definitions.macos.PwpolicyObject	\
	oval.schemas.definitions.macos.PwpolicyState	\
	oval.schemas.definitions.macos.PwpolicyTest	\
	oval.schemas.definitions.netconf.ConfigObject	\
	oval.schemas.definitions.netconf.ConfigState	\
	oval.schemas.definitions.netconf.ConfigTest	\
	oval.schemas.definitions.netconf.ObjectFactory	\
	oval.schemas.definitions.netconf.package-info	\
	oval.schemas.definitions.pixos.LineObject	\
	oval.schemas.definitions.pixos.LineState	\
	oval.schemas.definitions.pixos.LineTest	\
	oval.schemas.definitions.pixos.ObjectFactory	\
	oval.schemas.definitions.pixos.package-info	\
	oval.schemas.definitions.pixos.VersionObject	\
	oval.schemas.definitions.pixos.VersionState	\
	oval.schemas.definitions.pixos.VersionTest	\
	oval.schemas.definitions.sharepoint.BestbetObject	\
	oval.schemas.definitions.sharepoint.BestbetState	\
	oval.schemas.definitions.sharepoint.BestbetTest	\
	oval.schemas.definitions.sharepoint.EntityObjectUrlZoneType	\
	oval.schemas.definitions.sharepoint.EntityStateEventSeverityType	\
	oval.schemas.definitions.sharepoint.EntityStatePolicyFeatureStateType	\
	oval.schemas.definitions.sharepoint.EntityStatePolicyRoleType	\
	oval.schemas.definitions.sharepoint.EntityStateTraceSeverityType	\
	oval.schemas.definitions.sharepoint.EntityStateUrlZoneType	\
	oval.schemas.definitions.sharepoint.InfopolicycollObject	\
	oval.schemas.definitions.sharepoint.InfopolicycollState	\
	oval.schemas.definitions.sharepoint.InfopolicycollTest	\
	oval.schemas.definitions.sharepoint.ObjectFactory	\
	oval.schemas.definitions.sharepoint.package-info	\
	oval.schemas.definitions.sharepoint.SpantivirussettingsObject	\
	oval.schemas.definitions.sharepoint.SpantivirussettingsState	\
	oval.schemas.definitions.sharepoint.SpantivirussettingsTest	\
	oval.schemas.definitions.sharepoint.SpcrawlruleObject	\
	oval.schemas.definitions.sharepoint.SpcrawlruleState	\
	oval.schemas.definitions.sharepoint.SpcrawlruleTest	\
	oval.schemas.definitions.sharepoint.SpdiagnosticslevelObject	\
	oval.schemas.definitions.sharepoint.SpdiagnosticslevelState	\
	oval.schemas.definitions.sharepoint.SpdiagnosticslevelTest	\
	oval.schemas.definitions.sharepoint.SpdiagnosticsserviceObject	\
	oval.schemas.definitions.sharepoint.SpdiagnosticsserviceState	\
	oval.schemas.definitions.sharepoint.SpdiagnosticsserviceTest	\
	oval.schemas.definitions.sharepoint.SpgroupObject	\
	oval.schemas.definitions.sharepoint.SpgroupState	\
	oval.schemas.definitions.sharepoint.SpgroupTest	\
	oval.schemas.definitions.sharepoint.Spjobdefinition510Object	\
	oval.schemas.definitions.sharepoint.Spjobdefinition510State	\
	oval.schemas.definitions.sharepoint.Spjobdefinition510Test	\
	oval.schemas.definitions.sharepoint.SpjobdefinitionObject	\
	oval.schemas.definitions.sharepoint.SpjobdefinitionState	\
	oval.schemas.definitions.sharepoint.SpjobdefinitionTest	\
	oval.schemas.definitions.sharepoint.SplistObject	\
	oval.schemas.definitions.sharepoint.SplistState	\
	oval.schemas.definitions.sharepoint.SplistTest	\
	oval.schemas.definitions.sharepoint.SppolicyfeatureObject	\
	oval.schemas.definitions.sharepoint.SppolicyfeatureState	\
	oval.schemas.definitions.sharepoint.SppolicyfeatureTest	\
	oval.schemas.definitions.sharepoint.SppolicyObject	\
	oval.schemas.definitions.sharepoint.SppolicyState	\
	oval.schemas.definitions.sharepoint.SppolicyTest	\
	oval.schemas.definitions.sharepoint.SpsiteadministrationObject	\
	oval.schemas.definitions.sharepoint.SpsiteadministrationState	\
	oval.schemas.definitions.sharepoint.SpsiteadministrationTest	\
	oval.schemas.definitions.sharepoint.SpsiteObject	\
	oval.schemas.definitions.sharepoint.SpsiteState	\
	oval.schemas.definitions.sharepoint.SpsiteTest	\
	oval.schemas.definitions.sharepoint.SpwebapplicationObject	\
	oval.schemas.definitions.sharepoint.SpwebapplicationState	\
	oval.schemas.definitions.sharepoint.SpwebapplicationTest	\
	oval.schemas.definitions.sharepoint.SpwebObject	\
	oval.schemas.definitions.sharepoint.SpwebState	\
	oval.schemas.definitions.sharepoint.SpwebTest	\
	oval.schemas.definitions.solaris.EntityStatePermissionCompareType	\
	oval.schemas.definitions.solaris.EntityStateSmfProtocolType	\
	oval.schemas.definitions.solaris.EntityStateSmfServiceStateType	\
	oval.schemas.definitions.solaris.IsainfoObject	\
	oval.schemas.definitions.solaris.IsainfoState	\
	oval.schemas.definitions.solaris.IsainfoTest	\
	oval.schemas.definitions.solaris.NddObject	\
	oval.schemas.definitions.solaris.NddState	\
	oval.schemas.definitions.solaris.NddTest	\
	oval.schemas.definitions.solaris.ObjectFactory	\
	oval.schemas.definitions.solaris.package-info	\
	oval.schemas.definitions.solaris.PackageCheckBehaviors	\
	oval.schemas.definitions.solaris.PackagecheckObject	\
	oval.schemas.definitions.solaris.PackagecheckState	\
	oval.schemas.definitions.solaris.PackagecheckTest	\
	oval.schemas.definitions.solaris.PackageObject	\
	oval.schemas.definitions.solaris.PackageState	\
	oval.schemas.definitions.solaris.PackageTest	\
	oval.schemas.definitions.solaris.Patch54Object	\
	oval.schemas.definitions.solaris.Patch54Test	\
	oval.schemas.definitions.solaris.PatchBehaviors	\
	oval.schemas.definitions.solaris.PatchObject	\
	oval.schemas.definitions.solaris.PatchState	\
	oval.schemas.definitions.solaris.PatchTest	\
	oval.schemas.definitions.solaris.SmfObject	\
	oval.schemas.definitions.solaris.SmfState	\
	oval.schemas.definitions.solaris.SmfTest	\
	oval.schemas.definitions.unix.DnscacheObject	\
	oval.schemas.definitions.unix.DnscacheState	\
	oval.schemas.definitions.unix.DnscacheTest	\
	oval.schemas.definitions.unix.EntityStateCapabilityType	\
	oval.schemas.definitions.unix.EntityStateEncryptMethodType	\
	oval.schemas.definitions.unix.EntityStateEndpointType	\
	oval.schemas.definitions.unix.EntityStateGconfTypeType	\
	oval.schemas.definitions.unix.EntityStateInterfaceType	\
	oval.schemas.definitions.unix.EntityStateRoutingTableFlagsType	\
	oval.schemas.definitions.unix.EntityStateWaitStatusType	\
	oval.schemas.definitions.unix.EntityStateXinetdTypeStatusType	\
	oval.schemas.definitions.unix.FileBehaviors	\
	oval.schemas.definitions.unix.FileextendedattributeObject	\
	oval.schemas.definitions.unix.FileextendedattributeState	\
	oval.schemas.definitions.unix.FileextendedattributeTest	\
	oval.schemas.definitions.unix.FileObject	\
	oval.schemas.definitions.unix.FileState	\
	oval.schemas.definitions.unix.FileTest	\
	oval.schemas.definitions.unix.GconfObject	\
	oval.schemas.definitions.unix.GconfState	\
	oval.schemas.definitions.unix.GconfTest	\
	oval.schemas.definitions.unix.InetdObject	\
	oval.schemas.definitions.unix.InetdState	\
	oval.schemas.definitions.unix.InetdTest	\
	oval.schemas.definitions.unix.InterfaceObject	\
	oval.schemas.definitions.unix.InterfaceState	\
	oval.schemas.definitions.unix.InterfaceTest	\
	oval.schemas.definitions.unix.ObjectFactory	\
	oval.schemas.definitions.unix.package-info	\
	oval.schemas.definitions.unix.PasswordObject	\
	oval.schemas.definitions.unix.PasswordState	\
	oval.schemas.definitions.unix.PasswordTest	\
	oval.schemas.definitions.unix.Process58Object	\
	oval.schemas.definitions.unix.Process58State	\
	oval.schemas.definitions.unix.Process58Test	\
	oval.schemas.definitions.unix.ProcessObject	\
	oval.schemas.definitions.unix.ProcessState	\
	oval.schemas.definitions.unix.ProcessTest	\
	oval.schemas.definitions.unix.RoutingtableObject	\
	oval.schemas.definitions.unix.RoutingtableState	\
	oval.schemas.definitions.unix.RoutingtableTest	\
	oval.schemas.definitions.unix.RunlevelObject	\
	oval.schemas.definitions.unix.RunlevelState	\
	oval.schemas.definitions.unix.RunlevelTest	\
	oval.schemas.definitions.unix.SccsObject	\
	oval.schemas.definitions.unix.SccsState	\
	oval.schemas.definitions.unix.SccsTest	\
	oval.schemas.definitions.unix.ShadowObject	\
	oval.schemas.definitions.unix.ShadowState	\
	oval.schemas.definitions.unix.ShadowTest	\
	oval.schemas.definitions.unix.SysctlObject	\
	oval.schemas.definitions.unix.SysctlState	\
	oval.schemas.definitions.unix.SysctlTest	\
	oval.schemas.definitions.unix.UnameObject	\
	oval.schemas.definitions.unix.UnameState	\
	oval.schemas.definitions.unix.UnameTest	\
	oval.schemas.definitions.unix.XinetdObject	\
	oval.schemas.definitions.unix.XinetdState	\
	oval.schemas.definitions.unix.XinetdTest	\
	oval.schemas.definitions.windows.AccesstokenBehaviors	\
	oval.schemas.definitions.windows.AccesstokenObject	\
	oval.schemas.definitions.windows.AccesstokenState	\
	oval.schemas.definitions.windows.AccesstokenTest	\
	oval.schemas.definitions.windows.Activedirectory57Object	\
	oval.schemas.definitions.windows.Activedirectory57State	\
	oval.schemas.definitions.windows.Activedirectory57Test	\
	oval.schemas.definitions.windows.ActivedirectoryObject	\
	oval.schemas.definitions.windows.ActivedirectoryState	\
	oval.schemas.definitions.windows.ActivedirectoryTest	\
	oval.schemas.definitions.windows.AuditeventpolicyObject	\
	oval.schemas.definitions.windows.AuditeventpolicyState	\
	oval.schemas.definitions.windows.AuditeventpolicysubcategoriesObject	\
	oval.schemas.definitions.windows.AuditeventpolicysubcategoriesState	\
	oval.schemas.definitions.windows.AuditeventpolicysubcategoriesTest	\
	oval.schemas.definitions.windows.AuditeventpolicyTest	\
	oval.schemas.definitions.windows.CmdletObject	\
	oval.schemas.definitions.windows.CmdletState	\
	oval.schemas.definitions.windows.CmdletTest	\
	oval.schemas.definitions.windows.DnscacheObject	\
	oval.schemas.definitions.windows.DnscacheState	\
	oval.schemas.definitions.windows.DnscacheTest	\
	oval.schemas.definitions.windows.EntityObjectCmdletVerbType	\
	oval.schemas.definitions.windows.EntityObjectGUIDType	\
	oval.schemas.definitions.windows.EntityObjectNamingContextType	\
	oval.schemas.definitions.windows.EntityObjectProtocolType	\
	oval.schemas.definitions.windows.EntityObjectRegistryHiveType	\
	oval.schemas.definitions.windows.EntityStateAddrTypeType	\
	oval.schemas.definitions.windows.EntityStateAdstypeType	\
	oval.schemas.definitions.windows.EntityStateAuditType	\
	oval.schemas.definitions.windows.EntityStateCmdletVerbType	\
	oval.schemas.definitions.windows.EntityStateDriveTypeType	\
	oval.schemas.definitions.windows.EntityStateFileTypeType	\
	oval.schemas.definitions.windows.EntityStateGUIDType	\
	oval.schemas.definitions.windows.EntityStateInterfaceTypeType	\
	oval.schemas.definitions.windows.EntityStateNamingContextType	\
	oval.schemas.definitions.windows.EntityStatePeSubsystemType	\
	oval.schemas.definitions.windows.EntityStatePeTargetMachineType	\
	oval.schemas.definitions.windows.EntityStateProtocolType	\
	oval.schemas.definitions.windows.EntityStateRegistryHiveType	\
	oval.schemas.definitions.windows.EntityStateRegistryTypeType	\
	oval.schemas.definitions.windows.EntityStateServiceControlsAcceptedType	\
	oval.schemas.definitions.windows.EntityStateServiceCurrentStateType	\
	oval.schemas.definitions.windows.EntityStateServiceStartTypeType	\
	oval.schemas.definitions.windows.EntityStateServiceTypeType	\
	oval.schemas.definitions.windows.EntityStateSharedResourceTypeType	\
	oval.schemas.definitions.windows.EntityStateWindowsViewType	\
	oval.schemas.definitions.windows.Fileauditedpermissions53Object	\
	oval.schemas.definitions.windows.Fileauditedpermissions53State	\
	oval.schemas.definitions.windows.Fileauditedpermissions53Test	\
	oval.schemas.definitions.windows.FileauditedpermissionsObject	\
	oval.schemas.definitions.windows.FileauditedpermissionsState	\
	oval.schemas.definitions.windows.FileauditedpermissionsTest	\
	oval.schemas.definitions.windows.FileAuditPermissions53Behaviors	\
	oval.schemas.definitions.windows.FileAuditPermissionsBehaviors	\
	oval.schemas.definitions.windows.FileBehaviors	\
	oval.schemas.definitions.windows.FileEffectiveRights53Behaviors	\
	oval.schemas.definitions.windows.Fileeffectiverights53Object	\
	oval.schemas.definitions.windows.Fileeffectiverights53State	\
	oval.schemas.definitions.windows.Fileeffectiverights53Test	\
	oval.schemas.definitions.windows.FileEffectiveRightsBehaviors	\
	oval.schemas.definitions.windows.FileeffectiverightsObject	\
	oval.schemas.definitions.windows.FileeffectiverightsState	\
	oval.schemas.definitions.windows.FileeffectiverightsTest	\
	oval.schemas.definitions.windows.FileObject	\
	oval.schemas.definitions.windows.FileState	\
	oval.schemas.definitions.windows.FileTest	\
	oval.schemas.definitions.windows.GroupObject	\
	oval.schemas.definitions.windows.GroupSidObject	\
	oval.schemas.definitions.windows.GroupSidState	\
	oval.schemas.definitions.windows.GroupSidTest	\
	oval.schemas.definitions.windows.GroupState	\
	oval.schemas.definitions.windows.GroupTest	\
	oval.schemas.definitions.windows.InterfaceObject	\
	oval.schemas.definitions.windows.InterfaceState	\
	oval.schemas.definitions.windows.InterfaceTest	\
	oval.schemas.definitions.windows.LicenseObject	\
	oval.schemas.definitions.windows.LicenseState	\
	oval.schemas.definitions.windows.LicenseTest	\
	oval.schemas.definitions.windows.LockoutpolicyObject	\
	oval.schemas.definitions.windows.LockoutpolicyState	\
	oval.schemas.definitions.windows.LockoutpolicyTest	\
	oval.schemas.definitions.windows.MetabaseObject	\
	oval.schemas.definitions.windows.MetabaseState	\
	oval.schemas.definitions.windows.MetabaseTest	\
	oval.schemas.definitions.windows.ObjectFactory	\
	oval.schemas.definitions.windows.package-info	\
	oval.schemas.definitions.windows.PasswordpolicyObject	\
	oval.schemas.definitions.windows.PasswordpolicyState	\
	oval.schemas.definitions.windows.PasswordpolicyTest	\
	oval.schemas.definitions.windows.PeheaderObject	\
	oval.schemas.definitions.windows.PeheaderState	\
	oval.schemas.definitions.windows.PeheaderTest	\
	oval.schemas.definitions.windows.PortObject	\
	oval.schemas.definitions.windows.PortState	\
	oval.schemas.definitions.windows.PortTest	\
	oval.schemas.definitions.windows.PrinterEffectiveRightsBehaviors	\
	oval.schemas.definitions.windows.PrintereffectiverightsObject	\
	oval.schemas.definitions.windows.PrintereffectiverightsState	\
	oval.schemas.definitions.windows.PrintereffectiverightsTest	\
	oval.schemas.definitions.windows.Process58Object	\
	oval.schemas.definitions.windows.Process58State	\
	oval.schemas.definitions.windows.Process58Test	\
	oval.schemas.definitions.windows.ProcessObject	\
	oval.schemas.definitions.windows.ProcessState	\
	oval.schemas.definitions.windows.ProcessTest	\
	oval.schemas.definitions.windows.RegistryBehaviors	\
	oval.schemas.definitions.windows.RegistryObject	\
	oval.schemas.definitions.windows.RegistryState	\
	oval.schemas.definitions.windows.RegistryTest	\
	oval.schemas.definitions.windows.Regkeyauditedpermissions53Object	\
	oval.schemas.definitions.windows.Regkeyauditedpermissions53State	\
	oval.schemas.definitions.windows.Regkeyauditedpermissions53Test	\
	oval.schemas.definitions.windows.RegkeyauditedpermissionsObject	\
	oval.schemas.definitions.windows.RegkeyauditedpermissionsState	\
	oval.schemas.definitions.windows.RegkeyauditedpermissionsTest	\
	oval.schemas.definitions.windows.RegkeyAuditPermissions53Behaviors	\
	oval.schemas.definitions.windows.RegkeyAuditPermissionsBehaviors	\
	oval.schemas.definitions.windows.RegkeyEffectiveRights53Behaviors	\
	oval.schemas.definitions.windows.Regkeyeffectiverights53Object	\
	oval.schemas.definitions.windows.Regkeyeffectiverights53State	\
	oval.schemas.definitions.windows.Regkeyeffectiverights53Test	\
	oval.schemas.definitions.windows.RegkeyEffectiveRightsBehaviors	\
	oval.schemas.definitions.windows.RegkeyeffectiverightsObject	\
	oval.schemas.definitions.windows.RegkeyeffectiverightsState	\
	oval.schemas.definitions.windows.RegkeyeffectiverightsTest	\
	oval.schemas.definitions.windows.ServiceeffectiverightsObject	\
	oval.schemas.definitions.windows.ServiceeffectiverightsState	\
	oval.schemas.definitions.windows.ServiceeffectiverightsTest	\
	oval.schemas.definitions.windows.ServiceObject	\
	oval.schemas.definitions.windows.ServiceState	\
	oval.schemas.definitions.windows.ServiceTest	\
	oval.schemas.definitions.windows.SharedResourceAuditedPermissionsBehaviors	\
	oval.schemas.definitions.windows.SharedresourceauditedpermissionsObject	\
	oval.schemas.definitions.windows.SharedresourceauditedpermissionsState	\
	oval.schemas.definitions.windows.SharedresourceauditedpermissionsTest	\
	oval.schemas.definitions.windows.SharedResourceEffectiveRightsBehaviors	\
	oval.schemas.definitions.windows.SharedresourceeffectiverightsObject	\
	oval.schemas.definitions.windows.SharedresourceeffectiverightsState	\
	oval.schemas.definitions.windows.SharedresourceeffectiverightsTest	\
	oval.schemas.definitions.windows.SharedresourceObject	\
	oval.schemas.definitions.windows.SharedresourceState	\
	oval.schemas.definitions.windows.SharedresourceTest	\
	oval.schemas.definitions.windows.SidBehaviors	\
	oval.schemas.definitions.windows.SidObject	\
	oval.schemas.definitions.windows.SidSidBehaviors	\
	oval.schemas.definitions.windows.SidSidObject	\
	oval.schemas.definitions.windows.SidSidState	\
	oval.schemas.definitions.windows.SidSidTest	\
	oval.schemas.definitions.windows.SidState	\
	oval.schemas.definitions.windows.SidTest	\
	oval.schemas.definitions.windows.UacObject	\
	oval.schemas.definitions.windows.UacState	\
	oval.schemas.definitions.windows.UacTest	\
	oval.schemas.definitions.windows.UserObject	\
	oval.schemas.definitions.windows.UserSid55Object	\
	oval.schemas.definitions.windows.UserSid55State	\
	oval.schemas.definitions.windows.UserSid55Test	\
	oval.schemas.definitions.windows.UserSidObject	\
	oval.schemas.definitions.windows.UserSidState	\
	oval.schemas.definitions.windows.UserSidTest	\
	oval.schemas.definitions.windows.UserState	\
	oval.schemas.definitions.windows.UserTest	\
	oval.schemas.definitions.windows.VolumeObject	\
	oval.schemas.definitions.windows.VolumeState	\
	oval.schemas.definitions.windows.VolumeTest	\
	oval.schemas.definitions.windows.Wmi57Object	\
	oval.schemas.definitions.windows.Wmi57State	\
	oval.schemas.definitions.windows.Wmi57Test	\
	oval.schemas.definitions.windows.WmiObject	\
	oval.schemas.definitions.windows.WmiState	\
	oval.schemas.definitions.windows.WmiTest	\
	oval.schemas.definitions.windows.WuaUpdateSearcherBehaviors	\
	oval.schemas.definitions.windows.WuaupdatesearcherObject	\
	oval.schemas.definitions.windows.WuaupdatesearcherState	\
	oval.schemas.definitions.windows.WuaupdatesearcherTest	\
	oval.schemas.directives.core.ObjectFactory	\
	oval.schemas.directives.core.OvalDirectives	\
	oval.schemas.directives.core.package-info	\
	oval.schemas.evaluation.id.EvaluationDefinitionIds	\
	oval.schemas.evaluation.id.ObjectFactory	\
	oval.schemas.evaluation.id.package-info	\
	oval.schemas.results.core.ClassDirectivesType	\
	oval.schemas.results.core.ContentEnumeration	\
	oval.schemas.results.core.CriteriaType	\
	oval.schemas.results.core.CriterionType	\
	oval.schemas.results.core.DefaultDirectivesType	\
	oval.schemas.results.core.DefinitionsType	\
	oval.schemas.results.core.DefinitionType	\
	oval.schemas.results.core.DirectivesType	\
	oval.schemas.results.core.DirectiveType	\
	oval.schemas.results.core.ExtendDefinitionType	\
	oval.schemas.results.core.ObjectFactory	\
	oval.schemas.results.core.OvalResults	\
	oval.schemas.results.core.package-info	\
	oval.schemas.results.core.ResultEnumeration	\
	oval.schemas.results.core.ResultsType	\
	oval.schemas.results.core.SystemType	\
	oval.schemas.results.core.TestedItemType	\
	oval.schemas.results.core.TestedVariableType	\
	oval.schemas.results.core.TestsType	\
	oval.schemas.results.core.TestType	\
	oval.schemas.systemcharacteristics.aix.EntityItemFilesetStateType	\
	oval.schemas.systemcharacteristics.aix.EntityItemFixInstallationStatusType	\
	oval.schemas.systemcharacteristics.aix.EntityItemInterimFixStateType	\
	oval.schemas.systemcharacteristics.aix.FilesetItem	\
	oval.schemas.systemcharacteristics.aix.FixItem	\
	oval.schemas.systemcharacteristics.aix.InterimFixItem	\
	oval.schemas.systemcharacteristics.aix.NoItem	\
	oval.schemas.systemcharacteristics.aix.ObjectFactory	\
	oval.schemas.systemcharacteristics.aix.OslevelItem	\
	oval.schemas.systemcharacteristics.aix.package-info	\
	oval.schemas.systemcharacteristics.apache.HttpdItem	\
	oval.schemas.systemcharacteristics.apache.ObjectFactory	\
	oval.schemas.systemcharacteristics.apache.package-info	\
	oval.schemas.systemcharacteristics.catos.LineItem	\
	oval.schemas.systemcharacteristics.catos.ModuleItem	\
	oval.schemas.systemcharacteristics.catos.ObjectFactory	\
	oval.schemas.systemcharacteristics.catos.package-info	\
	oval.schemas.systemcharacteristics.catos.VersionItem	\
	oval.schemas.systemcharacteristics.core.CollectedObjectsType	\
	oval.schemas.systemcharacteristics.core.EntityItemAnySimpleType	\
	oval.schemas.systemcharacteristics.core.EntityItemBinaryType	\
	oval.schemas.systemcharacteristics.core.EntityItemBoolType	\
	oval.schemas.systemcharacteristics.core.EntityItemComplexBaseType	\
	oval.schemas.systemcharacteristics.core.EntityItemEVRStringType	\
	oval.schemas.systemcharacteristics.core.EntityItemFieldType	\
	oval.schemas.systemcharacteristics.core.EntityItemFilesetRevisionType	\
	oval.schemas.systemcharacteristics.core.EntityItemFloatType	\
	oval.schemas.systemcharacteristics.core.EntityItemIntType	\
	oval.schemas.systemcharacteristics.core.EntityItemIOSVersionType	\
	oval.schemas.systemcharacteristics.core.EntityItemIPAddressStringType	\
	oval.schemas.systemcharacteristics.core.EntityItemIPAddressType	\
	oval.schemas.systemcharacteristics.core.EntityItemRecordType	\
	oval.schemas.systemcharacteristics.core.EntityItemSimpleBaseType	\
	oval.schemas.systemcharacteristics.core.EntityItemStringType	\
	oval.schemas.systemcharacteristics.core.EntityItemVersionType	\
	oval.schemas.systemcharacteristics.core.FlagEnumeration	\
	oval.schemas.systemcharacteristics.core.InterfacesType	\
	oval.schemas.systemcharacteristics.core.InterfaceType	\
	oval.schemas.systemcharacteristics.core.ItemType	\
	oval.schemas.systemcharacteristics.core.ObjectFactory	\
	oval.schemas.systemcharacteristics.core.ObjectType	\
	oval.schemas.systemcharacteristics.core.OvalSystemCharacteristics	\
	oval.schemas.systemcharacteristics.core.package-info	\
	oval.schemas.systemcharacteristics.core.ReferenceType	\
	oval.schemas.systemcharacteristics.core.StatusEnumeration	\
	oval.schemas.systemcharacteristics.core.SystemDataType	\
	oval.schemas.systemcharacteristics.core.SystemInfoType	\
	oval.schemas.systemcharacteristics.core.VariableValueType	\
	oval.schemas.systemcharacteristics.esx.EntityItemClassificationType	\
	oval.schemas.systemcharacteristics.esx.EntityItemSupportLevelType	\
	oval.schemas.systemcharacteristics.esx.ObjectFactory	\
	oval.schemas.systemcharacteristics.esx.package-info	\
	oval.schemas.systemcharacteristics.esx.PatchItem	\
	oval.schemas.systemcharacteristics.esx.VersionItem	\
	oval.schemas.systemcharacteristics.esx.VisdkmanagedobjectItem	\
	oval.schemas.systemcharacteristics.freebsd.ObjectFactory	\
	oval.schemas.systemcharacteristics.freebsd.package-info	\
	oval.schemas.systemcharacteristics.freebsd.PortinfoItem	\
	oval.schemas.systemcharacteristics.hpux.GetconfItem	\
	oval.schemas.systemcharacteristics.hpux.NddItem	\
	oval.schemas.systemcharacteristics.hpux.ObjectFactory	\
	oval.schemas.systemcharacteristics.hpux.package-info	\
	oval.schemas.systemcharacteristics.hpux.PatchItem	\
	oval.schemas.systemcharacteristics.hpux.SwlistItem	\
	oval.schemas.systemcharacteristics.hpux.TrustedItem	\
	oval.schemas.systemcharacteristics.independent.EntityItemEngineType	\
	oval.schemas.systemcharacteristics.independent.EntityItemFamilyType	\
	oval.schemas.systemcharacteristics.independent.EntityItemHashTypeType	\
	oval.schemas.systemcharacteristics.independent.EntityItemLdaptypeType	\
	oval.schemas.systemcharacteristics.independent.EntityItemVariableRefType	\
	oval.schemas.systemcharacteristics.independent.EntityItemWindowsViewType	\
	oval.schemas.systemcharacteristics.independent.Environmentvariable58Item	\
	oval.schemas.systemcharacteristics.independent.EnvironmentvariableItem	\
	oval.schemas.systemcharacteristics.independent.FamilyItem	\
	oval.schemas.systemcharacteristics.independent.Filehash58Item	\
	oval.schemas.systemcharacteristics.independent.FilehashItem	\
	oval.schemas.systemcharacteristics.independent.Ldap57Item	\
	oval.schemas.systemcharacteristics.independent.LdapItem	\
	oval.schemas.systemcharacteristics.independent.ObjectFactory	\
	oval.schemas.systemcharacteristics.independent.package-info	\
	oval.schemas.systemcharacteristics.independent.Sql57Item	\
	oval.schemas.systemcharacteristics.independent.SqlItem	\
	oval.schemas.systemcharacteristics.independent.TextfilecontentItem	\
	oval.schemas.systemcharacteristics.independent.VariableItem	\
	oval.schemas.systemcharacteristics.independent.XmlfilecontentItem	\
	oval.schemas.systemcharacteristics.ios.GlobalItem	\
	oval.schemas.systemcharacteristics.ios.InterfaceItem	\
	oval.schemas.systemcharacteristics.ios.LineItem	\
	oval.schemas.systemcharacteristics.ios.ObjectFactory	\
	oval.schemas.systemcharacteristics.ios.package-info	\
	oval.schemas.systemcharacteristics.ios.SnmpItem	\
	oval.schemas.systemcharacteristics.ios.TclshItem	\
	oval.schemas.systemcharacteristics.ios.VersionItem	\
	oval.schemas.systemcharacteristics.junos.GlobalItem	\
	oval.schemas.systemcharacteristics.junos.LineItem	\
	oval.schemas.systemcharacteristics.junos.ObjectFactory	\
	oval.schemas.systemcharacteristics.junos.package-info	\
	oval.schemas.systemcharacteristics.junos.VersionItem	\
	oval.schemas.systemcharacteristics.junos.XmlLineItem	\
	oval.schemas.systemcharacteristics.linux.DpkginfoItem	\
	oval.schemas.systemcharacteristics.linux.EntityItemProtocolType	\
	oval.schemas.systemcharacteristics.linux.EntityItemRpmVerifyResultType	\
	oval.schemas.systemcharacteristics.linux.IflistenersItem	\
	oval.schemas.systemcharacteristics.linux.InetlisteningserverItem	\
	oval.schemas.systemcharacteristics.linux.ObjectFactory	\
	oval.schemas.systemcharacteristics.linux.package-info	\
	oval.schemas.systemcharacteristics.linux.PartitionItem	\
	oval.schemas.systemcharacteristics.linux.RpminfoItem	\
	oval.schemas.systemcharacteristics.linux.RpmverifyfileItem	\
	oval.schemas.systemcharacteristics.linux.RpmverifyItem	\
	oval.schemas.systemcharacteristics.linux.RpmverifypackageItem	\
	oval.schemas.systemcharacteristics.linux.SelinuxbooleanItem	\
	oval.schemas.systemcharacteristics.linux.SelinuxsecuritycontextItem	\
	oval.schemas.systemcharacteristics.linux.SlackwarepkginfoItem	\
	oval.schemas.systemcharacteristics.macos.AccountinfoItem	\
	oval.schemas.systemcharacteristics.macos.DiskutilItem	\
	oval.schemas.systemcharacteristics.macos.EntityItemPermissionCompareType	\
	oval.schemas.systemcharacteristics.macos.EntityItemPlistTypeType	\
	oval.schemas.systemcharacteristics.macos.Inetlisteningserver510Item	\
	oval.schemas.systemcharacteristics.macos.InetlisteningserverItem	\
	oval.schemas.systemcharacteristics.macos.NvramItem	\
	oval.schemas.systemcharacteristics.macos.ObjectFactory	\
	oval.schemas.systemcharacteristics.macos.package-info	\
	oval.schemas.systemcharacteristics.macos.PlistItem	\
	oval.schemas.systemcharacteristics.macos.Pwpolicy59Item	\
	oval.schemas.systemcharacteristics.macos.PwpolicyItem	\
	oval.schemas.systemcharacteristics.netconf.ConfigItem	\
	oval.schemas.systemcharacteristics.netconf.ObjectFactory	\
	oval.schemas.systemcharacteristics.netconf.package-info	\
	oval.schemas.systemcharacteristics.pixos.LineItem	\
	oval.schemas.systemcharacteristics.pixos.ObjectFactory	\
	oval.schemas.systemcharacteristics.pixos.package-info	\
	oval.schemas.systemcharacteristics.pixos.VersionItem	\
	oval.schemas.systemcharacteristics.sharepoint.BestbetItem	\
	oval.schemas.systemcharacteristics.sharepoint.EntityItemEventSeverityType	\
	oval.schemas.systemcharacteristics.sharepoint.EntityItemPolicyFeatureStateType	\
	oval.schemas.systemcharacteristics.sharepoint.EntityItemPolicyRoleType	\
	oval.schemas.systemcharacteristics.sharepoint.EntityItemTraceSeverityType	\
	oval.schemas.systemcharacteristics.sharepoint.EntityItemUrlZoneType	\
	oval.schemas.systemcharacteristics.sharepoint.InfopolicycollItem	\
	oval.schemas.systemcharacteristics.sharepoint.ObjectFactory	\
	oval.schemas.systemcharacteristics.sharepoint.package-info	\
	oval.schemas.systemcharacteristics.sharepoint.SpantivirussettingsItem	\
	oval.schemas.systemcharacteristics.sharepoint.SpcrawlruleItem	\
	oval.schemas.systemcharacteristics.sharepoint.SpdiagnosticslevelItem	\
	oval.schemas.systemcharacteristics.sharepoint.SpdiagnosticsserviceItem	\
	oval.schemas.systemcharacteristics.sharepoint.SpgroupItem	\
	oval.schemas.systemcharacteristics.sharepoint.Spjobdefinition510Item	\
	oval.schemas.systemcharacteristics.sharepoint.SpjobdefinitionItem	\
	oval.schemas.systemcharacteristics.sharepoint.SplistItem	\
	oval.schemas.systemcharacteristics.sharepoint.SppolicyfeatureItem	\
	oval.schemas.systemcharacteristics.sharepoint.SppolicyItem	\
	oval.schemas.systemcharacteristics.sharepoint.SpsiteadministrationItem	\
	oval.schemas.systemcharacteristics.sharepoint.SpsiteItem	\
	oval.schemas.systemcharacteristics.sharepoint.SpwebapplicationItem	\
	oval.schemas.systemcharacteristics.sharepoint.SpwebItem	\
	oval.schemas.systemcharacteristics.solaris.EntityItemPermissionCompareType	\
	oval.schemas.systemcharacteristics.solaris.EntityItemSmfProtocolType	\
	oval.schemas.systemcharacteristics.solaris.EntityItemSmfServiceStateType	\
	oval.schemas.systemcharacteristics.solaris.IsainfoItem	\
	oval.schemas.systemcharacteristics.solaris.NddItem	\
	oval.schemas.systemcharacteristics.solaris.ObjectFactory	\
	oval.schemas.systemcharacteristics.solaris.package-info	\
	oval.schemas.systemcharacteristics.solaris.PackagecheckItem	\
	oval.schemas.systemcharacteristics.solaris.PackageItem	\
	oval.schemas.systemcharacteristics.solaris.PatchItem	\
	oval.schemas.systemcharacteristics.solaris.SmfItem	\
	oval.schemas.systemcharacteristics.unix.DnscacheItem	\
	oval.schemas.systemcharacteristics.unix.EntityItemCapabilityType	\
	oval.schemas.systemcharacteristics.unix.EntityItemEncryptMethodType	\
	oval.schemas.systemcharacteristics.unix.EntityItemEndpointType	\
	oval.schemas.systemcharacteristics.unix.EntityItemGconfTypeType	\
	oval.schemas.systemcharacteristics.unix.EntityItemInterfaceType	\
	oval.schemas.systemcharacteristics.unix.EntityItemRoutingTableFlagsType	\
	oval.schemas.systemcharacteristics.unix.EntityItemWaitStatusType	\
	oval.schemas.systemcharacteristics.unix.EntityItemXinetdTypeStatusType	\
	oval.schemas.systemcharacteristics.unix.FileextendedattributeItem	\
	oval.schemas.systemcharacteristics.unix.FileItem	\
	oval.schemas.systemcharacteristics.unix.GconfItem	\
	oval.schemas.systemcharacteristics.unix.InetdItem	\
	oval.schemas.systemcharacteristics.unix.InterfaceItem	\
	oval.schemas.systemcharacteristics.unix.ObjectFactory	\
	oval.schemas.systemcharacteristics.unix.package-info	\
	oval.schemas.systemcharacteristics.unix.PasswordItem	\
	oval.schemas.systemcharacteristics.unix.Process58Item	\
	oval.schemas.systemcharacteristics.unix.ProcessItem	\
	oval.schemas.systemcharacteristics.unix.RoutingtableItem	\
	oval.schemas.systemcharacteristics.unix.RunlevelItem	\
	oval.schemas.systemcharacteristics.unix.SccsItem	\
	oval.schemas.systemcharacteristics.unix.ShadowItem	\
	oval.schemas.systemcharacteristics.unix.SysctlItem	\
	oval.schemas.systemcharacteristics.unix.UnameItem	\
	oval.schemas.systemcharacteristics.unix.XinetdItem	\
	oval.schemas.systemcharacteristics.windows.AccesstokenItem	\
	oval.schemas.systemcharacteristics.windows.Activedirectory57Item	\
	oval.schemas.systemcharacteristics.windows.ActivedirectoryItem	\
	oval.schemas.systemcharacteristics.windows.AuditeventpolicyItem	\
	oval.schemas.systemcharacteristics.windows.AuditeventpolicysubcategoriesItem	\
	oval.schemas.systemcharacteristics.windows.CmdletItem	\
	oval.schemas.systemcharacteristics.windows.DnscacheItem	\
	oval.schemas.systemcharacteristics.windows.EntityItemAddrTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemAdstypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemAuditType	\
	oval.schemas.systemcharacteristics.windows.EntityItemCmdletVerbType	\
	oval.schemas.systemcharacteristics.windows.EntityItemDriveTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemFileTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemGUIDType	\
	oval.schemas.systemcharacteristics.windows.EntityItemInterfaceTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemNamingContextType	\
	oval.schemas.systemcharacteristics.windows.EntityItemPeSubsystemType	\
	oval.schemas.systemcharacteristics.windows.EntityItemPeTargetMachineType	\
	oval.schemas.systemcharacteristics.windows.EntityItemProtocolType	\
	oval.schemas.systemcharacteristics.windows.EntityItemRegistryHiveType	\
	oval.schemas.systemcharacteristics.windows.EntityItemRegistryTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemServiceControlsAcceptedType	\
	oval.schemas.systemcharacteristics.windows.EntityItemServiceCurrentStateType	\
	oval.schemas.systemcharacteristics.windows.EntityItemServiceStartTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemServiceTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemSharedResourceTypeType	\
	oval.schemas.systemcharacteristics.windows.EntityItemWindowsViewType	\
	oval.schemas.systemcharacteristics.windows.FileauditedpermissionsItem	\
	oval.schemas.systemcharacteristics.windows.FileeffectiverightsItem	\
	oval.schemas.systemcharacteristics.windows.FileItem	\
	oval.schemas.systemcharacteristics.windows.GroupItem	\
	oval.schemas.systemcharacteristics.windows.GroupSidItem	\
	oval.schemas.systemcharacteristics.windows.InterfaceItem	\
	oval.schemas.systemcharacteristics.windows.LicenseItem	\
	oval.schemas.systemcharacteristics.windows.LockoutpolicyItem	\
	oval.schemas.systemcharacteristics.windows.MetabaseItem	\
	oval.schemas.systemcharacteristics.windows.ObjectFactory	\
	oval.schemas.systemcharacteristics.windows.package-info	\
	oval.schemas.systemcharacteristics.windows.PasswordpolicyItem	\
	oval.schemas.systemcharacteristics.windows.PeheaderItem	\
	oval.schemas.systemcharacteristics.windows.PortItem	\
	oval.schemas.systemcharacteristics.windows.PrintereffectiverightsItem	\
	oval.schemas.systemcharacteristics.windows.ProcessItem	\
	oval.schemas.systemcharacteristics.windows.RegistryItem	\
	oval.schemas.systemcharacteristics.windows.RegkeyauditedpermissionsItem	\
	oval.schemas.systemcharacteristics.windows.RegkeyeffectiverightsItem	\
	oval.schemas.systemcharacteristics.windows.ServiceeffectiverightsItem	\
	oval.schemas.systemcharacteristics.windows.ServiceItem	\
	oval.schemas.systemcharacteristics.windows.SharedresourceauditedpermissionsItem	\
	oval.schemas.systemcharacteristics.windows.SharedresourceeffectiverightsItem	\
	oval.schemas.systemcharacteristics.windows.SharedresourceItem	\
	oval.schemas.systemcharacteristics.windows.SidItem	\
	oval.schemas.systemcharacteristics.windows.SidSidItem	\
	oval.schemas.systemcharacteristics.windows.UacItem	\
	oval.schemas.systemcharacteristics.windows.UserItem	\
	oval.schemas.systemcharacteristics.windows.UserSidItem	\
	oval.schemas.systemcharacteristics.windows.VolumeItem	\
	oval.schemas.systemcharacteristics.windows.Wmi57Item	\
	oval.schemas.systemcharacteristics.windows.WmiItem	\
	oval.schemas.systemcharacteristics.windows.WuaupdatesearcherItem	\
	oval.schemas.variables.core.ObjectFactory	\
	oval.schemas.variables.core.OvalVariables	\
	oval.schemas.variables.core.package-info	\
	oval.schemas.variables.core.VariablesType	\
	oval.schemas.variables.core.VariableType	\
	scap.datastream.Component	\
	scap.datastream.ComponentRef	\
	scap.datastream.ContentSourceType	\
	scap.datastream.DataStream	\
	scap.datastream.DataStreamCollection	\
	scap.datastream.ExtendedComponent	\
	scap.datastream.ObjectFactory	\
	scap.datastream.package-info	\
	scap.datastream.RefListType	\
	scap.datastream.UseCaseType	\
	xccdf.schemas.core.BenchmarkType	\
	xccdf.schemas.core.CcOperatorEnumType	\
	xccdf.schemas.core.CheckContentRefType	\
	xccdf.schemas.core.CheckContentType	\
	xccdf.schemas.core.CheckExportType	\
	xccdf.schemas.core.CheckImportType	\
	xccdf.schemas.core.CheckType	\
	xccdf.schemas.core.ComplexCheckType	\
	xccdf.schemas.core.ComplexValueType	\
	xccdf.schemas.core.CPE2IdrefType	\
	xccdf.schemas.core.DcStatusType	\
	xccdf.schemas.core.FactType	\
	xccdf.schemas.core.FixStrategyEnumType	\
	xccdf.schemas.core.FixTextType	\
	xccdf.schemas.core.FixType	\
	xccdf.schemas.core.GroupType	\
	xccdf.schemas.core.HtmlTextType	\
	xccdf.schemas.core.HtmlTextWithSubType	\
	xccdf.schemas.core.IdentityType	\
	xccdf.schemas.core.IdentType	\
	xccdf.schemas.core.IdrefListType	\
	xccdf.schemas.core.IdrefType	\
	xccdf.schemas.core.InstanceFixType	\
	xccdf.schemas.core.InstanceResultType	\
	xccdf.schemas.core.InterfaceHintType	\
	xccdf.schemas.core.ItemType	\
	xccdf.schemas.core.MessageType	\
	xccdf.schemas.core.MetadataType	\
	xccdf.schemas.core.Model	\
	xccdf.schemas.core.MsgSevEnumType	\
	xccdf.schemas.core.NoticeType	\
	xccdf.schemas.core.ObjectFactory	\
	xccdf.schemas.core.OverrideableCPE2IdrefType	\
	xccdf.schemas.core.OverrideableIdrefType	\
	xccdf.schemas.core.OverrideType	\
	xccdf.schemas.core.package-info	\
	xccdf.schemas.core.ParamType	\
	xccdf.schemas.core.PlainTextType	\
	xccdf.schemas.core.ProfileNoteType	\
	xccdf.schemas.core.ProfileRefineRuleType	\
	xccdf.schemas.core.ProfileRefineValueType	\
	xccdf.schemas.core.ProfileSelectType	\
	xccdf.schemas.core.ProfileSetComplexValueType	\
	xccdf.schemas.core.ProfileSetValueType	\
	xccdf.schemas.core.ProfileType	\
	xccdf.schemas.core.RatingEnumType	\
	xccdf.schemas.core.ReferenceType	\
	xccdf.schemas.core.ResultEnumType	\
	xccdf.schemas.core.RoleEnumType	\
	xccdf.schemas.core.RuleResultType	\
	xccdf.schemas.core.RuleType	\
	xccdf.schemas.core.ScoreType	\
	xccdf.schemas.core.SelChoicesType	\
	xccdf.schemas.core.SelComplexValueType	\
	xccdf.schemas.core.SelectableItemType	\
	xccdf.schemas.core.SelNumType	\
	xccdf.schemas.core.SelStringType	\
	xccdf.schemas.core.SeverityEnumType	\
	xccdf.schemas.core.SignatureType	\
	xccdf.schemas.core.Status	\
	xccdf.schemas.core.StatusType	\
	xccdf.schemas.core.SubType	\
	xccdf.schemas.core.SubUseEnumType	\
	xccdf.schemas.core.TailoringType	\
	xccdf.schemas.core.TargetFactsType	\
	xccdf.schemas.core.TestResultType	\
	xccdf.schemas.core.TextType	\
	xccdf.schemas.core.TextWithSubType	\
	xccdf.schemas.core.UriRefType	\
	xccdf.schemas.core.ValueOperatorType	\
	xccdf.schemas.core.ValueType	\
	xccdf.schemas.core.ValueTypeType	\
	xccdf.schemas.core.VersionType	\
	xccdf.schemas.core.WarningCategoryEnumType	\
	xccdf.schemas.core.WarningType
