SCHEMAS=\
	cpe-2.3/cpe-dictionary-extension_2.3.xsd	\
	cpe-2.3/cpe-dictionary_2.3.xsd	\
	cpe-2.3/cpe-language_2.3.xsd	\
	cpe-2.3/cpe-naming_2.3.xsd	\
	ds-1.2/scap-source-data-stream_1.2.xsd	\
	dublin/simpledc20021212.xsd	\
	oasis/catalog-1.1.xsd	\
	ocil-2.0/ocil-2.0.xsd	\
	ocil-2.0/ocil-variables-schema.xsd	\
	oval-5.10.1/aix-definitions-schema.xsd	\
	oval-5.10.1/aix-system-characteristics-schema.xsd	\
	oval-5.10.1/apache-definitions-schema.xsd	\
	oval-5.10.1/apache-system-characteristics-schema.xsd	\
	oval-5.10.1/catos-definitions-schema.xsd	\
	oval-5.10.1/catos-system-characteristics-schema.xsd	\
	oval-5.10.1/esx-definitions-schema.xsd	\
	oval-5.10.1/esx-system-characteristics-schema.xsd	\
	oval-5.10.1/evaluation-ids.xsd	\
	oval-5.10.1/freebsd-definitions-schema.xsd	\
	oval-5.10.1/freebsd-system-characteristics-schema.xsd	\
	oval-5.10.1/hpux-definitions-schema.xsd	\
	oval-5.10.1/hpux-system-characteristics-schema.xsd	\
	oval-5.10.1/independent-definitions-schema.xsd	\
	oval-5.10.1/independent-system-characteristics-schema.xsd	\
	oval-5.10.1/ios-definitions-schema.xsd	\
	oval-5.10.1/ios-system-characteristics-schema.xsd	\
	oval-5.10.1/junos-definitions-schema.xsd	\
	oval-5.10.1/junos-system-characteristics-schema.xsd	\
	oval-5.10.1/linux-definitions-schema.xsd	\
	oval-5.10.1/linux-system-characteristics-schema.xsd	\
	oval-5.10.1/macos-definitions-schema.xsd	\
	oval-5.10.1/macos-system-characteristics-schema.xsd	\
	oval-5.10.1/netconf-definitions-schema.xsd	\
	oval-5.10.1/netconf-system-characteristics-schema.xsd	\
	oval-5.10.1/oval-common-schema.xsd	\
	oval-5.10.1/oval-definitions-schema.xsd	\
	oval-5.10.1/oval-directives-schema.xsd	\
	oval-5.10.1/oval-results-schema.xsd	\
	oval-5.10.1/oval-system-characteristics-schema.xsd	\
	oval-5.10.1/oval-variables-schema.xsd	\
	oval-5.10.1/pixos-definitions-schema.xsd	\
	oval-5.10.1/pixos-system-characteristics-schema.xsd	\
	oval-5.10.1/sharepoint-definitions-schema.xsd	\
	oval-5.10.1/sharepoint-system-characteristics-schema.xsd	\
	oval-5.10.1/solaris-definitions-schema.xsd	\
	oval-5.10.1/solaris-system-characteristics-schema.xsd	\
	oval-5.10.1/unix-definitions-schema.xsd	\
	oval-5.10.1/unix-system-characteristics-schema.xsd	\
	oval-5.10.1/windows-definitions-schema.xsd	\
	oval-5.10.1/windows-system-characteristics-schema.xsd	\
	xccdf-1.2/xccdf_1.2.xsd	\
	xml/xlink.xsd	\
	xml/xmldsig-core-schema.xsd
