CLASSES=\
	scap.oval.definitions.android.AppManagerObject	\
	scap.oval.definitions.android.AppManagerState	\
	scap.oval.definitions.android.AppManagerTest	\
	scap.oval.definitions.android.BluetoothObject	\
	scap.oval.definitions.android.BluetoothState	\
	scap.oval.definitions.android.BluetoothTest	\
	scap.oval.definitions.android.CameraObject	\
	scap.oval.definitions.android.CameraState	\
	scap.oval.definitions.android.CameraTest	\
	scap.oval.definitions.android.CertificateObject	\
	scap.oval.definitions.android.CertificateState	\
	scap.oval.definitions.android.CertificateTest	\
	scap.oval.definitions.android.DeviceAccessObject	\
	scap.oval.definitions.android.DeviceAccessState	\
	scap.oval.definitions.android.DeviceAccessTest	\
	scap.oval.definitions.android.DeviceSettingsObject	\
	scap.oval.definitions.android.DeviceSettingsState	\
	scap.oval.definitions.android.DeviceSettingsTest	\
	scap.oval.definitions.android.EncryptionObject	\
	scap.oval.definitions.android.EncryptionState	\
	scap.oval.definitions.android.EncryptionTest	\
	scap.oval.definitions.android.EntityStateEncryptionStatusType	\
	scap.oval.definitions.android.EntityStateExternalStorageType	\
	scap.oval.definitions.android.EntityStateKeyguardDisabledFeaturesType	\
	scap.oval.definitions.android.EntityStatePasswordQualityType	\
	scap.oval.definitions.android.EntityStateWifiAuthAlgorithmType	\
	scap.oval.definitions.android.EntityStateWifiCurrentStatusType	\
	scap.oval.definitions.android.EntityStateWifiGroupCipherType	\
	scap.oval.definitions.android.EntityStateWifiKeyMgmtType	\
	scap.oval.definitions.android.EntityStateWifiPairwiseCipherType	\
	scap.oval.definitions.android.EntityStateWifiProtocolType	\
	scap.oval.definitions.android.ExternalStorageObject	\
	scap.oval.definitions.android.ExternalStorageState	\
	scap.oval.definitions.android.ExternalStorageTest	\
	scap.oval.definitions.android.LocationServiceObject	\
	scap.oval.definitions.android.LocationServiceState	\
	scap.oval.definitions.android.LocationServiceTest	\
	scap.oval.definitions.android.NetworkObject	\
	scap.oval.definitions.android.NetworkState	\
	scap.oval.definitions.android.NetworkTest	\
	scap.oval.definitions.android.ObjectFactory	\
	scap.oval.definitions.android.package-info	\
	scap.oval.definitions.android.PasswordObject	\
	scap.oval.definitions.android.PasswordState	\
	scap.oval.definitions.android.PasswordTest	\
	scap.oval.definitions.android.SystemDetailsObject	\
	scap.oval.definitions.android.SystemDetailsState	\
	scap.oval.definitions.android.SystemDetailsTest	\
	scap.oval.definitions.android.WifiObject	\
	scap.oval.definitions.android.WifiSecurityObject	\
	scap.oval.definitions.android.WifiSecurityState	\
	scap.oval.definitions.android.WifiSecurityTest	\
	scap.oval.definitions.android.WifiState	\
	scap.oval.definitions.android.WifiTest	\
	scap.oval.definitions.junos.EntityStateJunosReleaseTypeType	\
	scap.oval.definitions.junos.ObjectFactory	\
	scap.oval.definitions.junos.package-info	\
	scap.oval.definitions.junos.ShowObject	\
	scap.oval.definitions.junos.ShowState	\
	scap.oval.definitions.junos.ShowTest	\
	scap.oval.definitions.junos.VersionObject	\
	scap.oval.definitions.junos.VersionState	\
	scap.oval.definitions.junos.VersionTest	\
	scap.oval.definitions.junos.XmlConfigObject	\
	scap.oval.definitions.junos.XmlConfigState	\
	scap.oval.definitions.junos.XmlConfigTest	\
	scap.oval.definitions.junos.XmlShowObject	\
	scap.oval.definitions.junos.XmlShowState	\
	scap.oval.definitions.junos.XmlShowTest	\
	scap.oval.definitions.netconf.ConfigObject	\
	scap.oval.definitions.netconf.ConfigState	\
	scap.oval.definitions.netconf.ConfigTest	\
	scap.oval.definitions.netconf.ObjectFactory	\
	scap.oval.definitions.netconf.package-info	\
	scap.oval.definitions.windowsx.EntityObjectSystemMetricIndexType	\
	scap.oval.definitions.windowsx.EntityStateSystemMetricIndexType	\
	scap.oval.definitions.windowsx.LicenseObject	\
	scap.oval.definitions.windowsx.LicenseState	\
	scap.oval.definitions.windowsx.LicenseTest	\
	scap.oval.definitions.windowsx.ObjectFactory	\
	scap.oval.definitions.windowsx.package-info	\
	scap.oval.definitions.windowsx.SystemmetricObject	\
	scap.oval.definitions.windowsx.SystemmetricState	\
	scap.oval.definitions.windowsx.SystemmetricTest	\
	scap.oval.systemcharacteristics.android.AppManagerItem	\
	scap.oval.systemcharacteristics.android.BluetoothItem	\
	scap.oval.systemcharacteristics.android.CameraItem	\
	scap.oval.systemcharacteristics.android.CertificateItem	\
	scap.oval.systemcharacteristics.android.DeviceAccessItem	\
	scap.oval.systemcharacteristics.android.DeviceSettingsItem	\
	scap.oval.systemcharacteristics.android.EncryptionItem	\
	scap.oval.systemcharacteristics.android.EntityItemEncryptionStatusType	\
	scap.oval.systemcharacteristics.android.EntityItemExternalStorageType	\
	scap.oval.systemcharacteristics.android.EntityItemKeyguardDisabledFeaturesType	\
	scap.oval.systemcharacteristics.android.EntityItemPasswordQualityType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiAuthAlgorithmType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiCurrentStatusType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiGroupCipherType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiKeyMgmtType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiPairwiseCipherType	\
	scap.oval.systemcharacteristics.android.EntityItemWifiProtocolType	\
	scap.oval.systemcharacteristics.android.ExternalStorageItem	\
	scap.oval.systemcharacteristics.android.LocationServiceItem	\
	scap.oval.systemcharacteristics.android.NetworkItem	\
	scap.oval.systemcharacteristics.android.ObjectFactory	\
	scap.oval.systemcharacteristics.android.package-info	\
	scap.oval.systemcharacteristics.android.PasswordItem	\
	scap.oval.systemcharacteristics.android.SystemDetailsItem	\
	scap.oval.systemcharacteristics.android.WifiItem	\
	scap.oval.systemcharacteristics.android.WifiSecurityItem	\
	scap.oval.systemcharacteristics.junos.EntityItemJunosReleaseTypeType	\
	scap.oval.systemcharacteristics.junos.ObjectFactory	\
	scap.oval.systemcharacteristics.junos.package-info	\
	scap.oval.systemcharacteristics.junos.ShowItem	\
	scap.oval.systemcharacteristics.junos.VersionItem	\
	scap.oval.systemcharacteristics.junos.XmlConfigItem	\
	scap.oval.systemcharacteristics.junos.XmlShowItem	\
	scap.oval.systemcharacteristics.netconf.ConfigItem	\
	scap.oval.systemcharacteristics.netconf.ObjectFactory	\
	scap.oval.systemcharacteristics.netconf.package-info	\
	scap.oval.systemcharacteristics.windowsx.EntityItemSystemMetricIndexType	\
	scap.oval.systemcharacteristics.windowsx.LicenseItem	\
	scap.oval.systemcharacteristics.windowsx.ObjectFactory	\
	scap.oval.systemcharacteristics.windowsx.package-info	\
	scap.oval.systemcharacteristics.windowsx.SystemmetricItem
