CLASSES=\
	cpe.schemas.dictionary.CheckType	\
	cpe.schemas.dictionary.ext.ChangeDescriptionType	\
	cpe.schemas.dictionary.ext.ChangeTypeType	\
	cpe.schemas.dictionary.ext.DeprecatedInfoType	\
	cpe.schemas.dictionary.ext.DeprecationType	\
	cpe.schemas.dictionary.ext.DeprecationTypeType	\
	cpe.schemas.dictionary.ext.EvidenceReferenceType	\
	cpe.schemas.dictionary.ext.EvidenceType	\
	cpe.schemas.dictionary.ext.ItemType	\
	cpe.schemas.dictionary.ext.ObjectFactory	\
	cpe.schemas.dictionary.ext.OrganizationType	\
	cpe.schemas.dictionary.ext.package-info	\
	cpe.schemas.dictionary.ext.ProvenanceRecordType	\
	cpe.schemas.dictionary.GeneratorType	\
	cpe.schemas.dictionary.ItemType	\
	cpe.schemas.dictionary.ListType	\
	cpe.schemas.dictionary.NotesType	\
	cpe.schemas.dictionary.ObjectFactory	\
	cpe.schemas.dictionary.package-info	\
	cpe.schemas.dictionary.ReferencesType	\
	cpe.schemas.dictionary.TextType	\
	cpe.schemas.language.CheckFactRefType	\
	cpe.schemas.language.CPEFactRefType	\
	cpe.schemas.language.FactRefType	\
	cpe.schemas.language.LogicalTestType	\
	cpe.schemas.language.ObjectFactory	\
	cpe.schemas.language.OperatorEnumeration	\
	cpe.schemas.language.package-info	\
	cpe.schemas.language.PlatformBaseType	\
	cpe.schemas.language.PlatformSpecificationType	\
	cpe.schemas.language.PlatformType	\
	cpe.schemas.language.TextType	\
