CLASSES=\
	org.joval.discovery.Local				\
	org.joval.os.unix.io.driver.AIXDriver			\
	org.joval.os.unix.io.driver.LinuxDriver			\
	org.joval.os.unix.io.driver.MacOSXDriver		\
	org.joval.os.unix.io.driver.SolarisDriver		\
	org.joval.os.unix.io.UnixCacheFileSerializer		\
	org.joval.os.unix.io.UnixFile				\
	org.joval.os.unix.io.UnixFileInfo			\
	org.joval.os.unix.io.UnixFilesystem			\
	org.joval.os.unix.system.BaseUnixSession		\
	org.joval.os.unix.system.Environment			\
	org.joval.os.unix.system.UnixSession			\
	org.joval.os.windows.identity.ActiveDirectory		\
	org.joval.os.windows.identity.Directory			\
	org.joval.os.windows.identity.Group			\
	org.joval.os.windows.identity.LocalACE			\
	org.joval.os.windows.identity.LocalDirectory		\
	org.joval.os.windows.identity.Principal			\
	org.joval.os.windows.identity.User			\
	org.joval.os.windows.io.WindowsCacheFileSerializer	\
	org.joval.os.windows.io.WindowsFile			\
	org.joval.os.windows.io.WindowsFileInfo			\
	org.joval.os.windows.io.WindowsFilesystem		\
	org.joval.os.windows.io.WOW3264FilesystemRedirector	\
	org.joval.os.windows.registry.BaseRegistry		\
	org.joval.os.windows.registry.BinaryValue		\
	org.joval.os.windows.registry.DwordValue		\
	org.joval.os.windows.registry.ExpandStringValue		\
	org.joval.os.windows.registry.Key			\
	org.joval.os.windows.registry.LicenseData		\
	org.joval.os.windows.registry.MultiStringValue		\
	org.joval.os.windows.registry.QwordValue		\
	org.joval.os.windows.registry.Registry			\
	org.joval.os.windows.registry.StringValue		\
	org.joval.os.windows.registry.Value			\
	org.joval.os.windows.registry.WOW3264RegistryRedirector	\
	org.joval.os.windows.system.Environment			\
	org.joval.os.windows.system.WindowsSession		\
	org.joval.os.windows.wmi.scripting.SWbemObject		\
	org.joval.os.windows.wmi.scripting.SWbemObjectSet	\
	org.joval.os.windows.wmi.scripting.SWbemProperty	\
	org.joval.os.windows.wmi.scripting.SWbemPropertySet	\
	org.joval.os.windows.wmi.WmiProvider			\
	org.joval.plugin.BasePlugin				\
	org.joval.plugin.LocalPlugin				\
	org.joval.test.AD					\
	org.joval.test.Default					\
	org.joval.test.Exec					\
	org.joval.test.FS					\
	org.joval.test.Reg					\
	org.joval.test.WMI					\
	org.joval.util.AbstractBaseSession			\
	org.joval.util.AbstractSession
