CLASSES=\
	org.joval.intf.identity.ICredential		\
	org.joval.intf.identity.ICredentialStore	\
	org.joval.intf.oval.IDefinitionFilter		\
	org.joval.intf.oval.IDefinitions		\
	org.joval.intf.oval.IEngine			\
	org.joval.intf.oval.IResults			\
	org.joval.intf.oval.ISystemCharacteristics	\
	org.joval.intf.oval.IType			\
	org.joval.intf.oval.IVariables			\
	org.joval.intf.plugin.IAdapter			\
	org.joval.intf.plugin.IPlugin			\
	org.joval.intf.plugin.IRequestContext		\
	org.joval.intf.system.IBaseSession		\
	org.joval.intf.system.IProcess			\
	org.joval.intf.net.ICIDR			\
	org.joval.intf.xml.ITransformable		\
	org.joval.net.Ip4Address			\
	org.joval.net.Ip6Address			\
	org.joval.os.windows.Timestamp			\
	org.joval.oval.CollectException			\
	org.joval.oval.DefinitionFilter			\
	org.joval.oval.Definitions			\
	org.joval.oval.Directives			\
	org.joval.oval.Factories			\
	org.joval.oval.ItemSet				\
	org.joval.oval.OvalException			\
	org.joval.oval.OvalFactory			\
	org.joval.oval.Results				\
	org.joval.oval.SystemCharacteristics		\
	org.joval.oval.Variables			\
	org.joval.oval.engine.CheckData			\
	org.joval.oval.engine.DateTime			\
	org.joval.oval.engine.Engine			\
	org.joval.oval.engine.ExistenceData		\
	org.joval.oval.engine.OperatorData		\
	org.joval.oval.engine.RequestContext		\
	org.joval.oval.engine.ResolveException		\
	org.joval.oval.engine.TestException		\
	org.joval.oval.sysinfo.IosNetworkInterface	\
	org.joval.oval.sysinfo.IosSystemInfo		\
	org.joval.oval.sysinfo.JunosNetworkInterface	\
	org.joval.oval.sysinfo.JunosSystemInfo		\
	org.joval.oval.sysinfo.SysinfoFactory		\
	org.joval.oval.sysinfo.UnixNetworkInterface	\
	org.joval.oval.sysinfo.UnixSystemInfo		\
	org.joval.oval.sysinfo.WindowsSystemInfo	\
	org.joval.oval.types.AbstractType		\
	org.joval.oval.types.BinaryType			\
	org.joval.oval.types.BooleanType		\
	org.joval.oval.types.EvrStringType		\
	org.joval.oval.types.FilesetRevisionType	\
	org.joval.oval.types.FloatType			\
	org.joval.oval.types.IntType			\
	org.joval.oval.types.IosVersionType		\
	org.joval.oval.types.Ip4AddressType		\
	org.joval.oval.types.Ip6AddressType		\
	org.joval.oval.types.RecordType			\
	org.joval.oval.types.StringType			\
	org.joval.oval.types.TypeFactory		\
	org.joval.oval.types.VersionType		\
	org.joval.oval.xml.OvalNamespacePrefixMapper	\
	org.joval.scap.ScapException
