CLASSES=\
	org.joval.intf.identity.ICredential				\
	org.joval.intf.identity.ICredentialStore			\
	org.joval.intf.oval.IDefinitionFilter				\
	org.joval.intf.oval.IDefinitions				\
	org.joval.intf.oval.IEngine					\
	org.joval.intf.oval.IResults					\
	org.joval.intf.oval.ISystemCharacteristics			\
	org.joval.intf.plugin.IAdapter					\
	org.joval.intf.plugin.IPlugin					\
	org.joval.intf.plugin.IRequestContext				\
	org.joval.intf.system.IBaseSession				\
	org.joval.intf.system.IProcess					\
	org.joval.intf.util.IObserver					\
	org.joval.intf.util.IProducer					\
	org.joval.intf.util.IProperty					\
	org.joval.os.windows.Timestamp					\
	org.joval.oval.NotCollectableException				\
	org.joval.oval.OvalException					\
	org.joval.oval.ResolveException					\
	org.joval.oval.TestException					\
	org.joval.oval.engine.DefinitionFilter				\
	org.joval.oval.engine.Definitions				\
	org.joval.oval.engine.Directives				\
	org.joval.oval.engine.Engine					\
	org.joval.oval.engine.RequestContext				\
	org.joval.oval.engine.Results					\
	org.joval.oval.engine.SystemCharacteristics			\
	org.joval.oval.engine.Variables					\
	org.joval.oval.util.CheckData					\
	org.joval.oval.util.ExistenceData				\
	org.joval.oval.util.ItemSet					\
	org.joval.oval.util.OperatorData				\
	org.joval.oval.xml.OvalNamespacePrefixMapper			\
	org.joval.util.Checksum						\
	org.joval.util.IniFile						\
	org.joval.util.JOVALMsg						\
	org.joval.util.JOVALSystem					\
	org.joval.util.Producer						\
	org.joval.util.PropertyUtil					\
	org.joval.util.StringTools					\
	org.joval.util.Version
