SHARED=\
	org.joval.io.fs.CacheFile					\
	org.joval.io.fs.CacheFilesystem					\
	org.joval.io.fs.DefaultFile					\
	org.joval.io.fs.FileAccessor					\
	org.joval.io.fs.FileInfo					\
	org.joval.io.StreamLogger					\
	org.joval.os.unix.NetworkInterface				\
	org.joval.os.unix.UnixSystemInfo				\
	org.joval.os.unix.io.IUnixFilesystemDriver			\
	org.joval.os.unix.io.UnixFileInfo				\
	org.joval.os.unix.io.UnixFilesystem				\
	org.joval.os.unix.io.driver.AIXDriver				\
	org.joval.os.unix.io.driver.MacOSXDriver			\
	org.joval.os.unix.io.driver.LinuxDriver				\
	org.joval.os.unix.io.driver.SolarisDriver			\
	org.joval.os.unix.system.BaseUnixSession			\
	org.joval.os.unix.system.Environment				\
	org.joval.os.windows.WindowsSystemInfo				\
	org.joval.os.windows.identity.ActiveDirectory			\
	org.joval.os.windows.identity.Directory				\
	org.joval.os.windows.identity.Group				\
	org.joval.os.windows.identity.LocalDirectory			\
	org.joval.os.windows.identity.Principal				\
	org.joval.os.windows.identity.User				\
	org.joval.os.windows.io.WindowsFileInfo				\
	org.joval.os.windows.io.WOW3264FilesystemRedirector		\
	org.joval.os.windows.io.WOW3264FilesystemRedirector		\
	org.joval.os.windows.registry.BaseRegistry			\
	org.joval.os.windows.registry.BinaryValue			\
	org.joval.os.windows.registry.DwordValue			\
	org.joval.os.windows.registry.ExpandStringValue			\
	org.joval.os.windows.registry.LicenseData			\
	org.joval.os.windows.registry.MultiStringValue			\
	org.joval.os.windows.registry.NoneValue				\
	org.joval.os.windows.registry.QwordValue			\
	org.joval.os.windows.registry.StringValue			\
	org.joval.os.windows.registry.Value				\
	org.joval.os.windows.registry.WOW3264RegistryRedirector		\
	org.joval.os.windows.system.Environment				\
	org.joval.plugin.BasePlugin					\
	org.joval.test.AD						\
	org.joval.test.Exec						\
	org.joval.test.FS						\
	org.joval.test.PE						\
	org.joval.test.Reg						\
	org.joval.test.WMI						\
	org.joval.util.Base64						\
	org.joval.util.AbstractBaseSession				\
	org.joval.util.AbstractSession					\
	org.joval.util.CachingHierarchy