CLASSES=\
	cpe.schemas.core.CheckType	\
	cpe.schemas.core.CpeItem	\
	cpe.schemas.core.CpeList	\
	cpe.schemas.core.ObjectFactory	\
	cpe.schemas.core.package-info	\
	cpe.schemas.core.ReferenceType	\
	cpe.schemas.platform.Application	\
	cpe.schemas.platform.Hardware	\
	cpe.schemas.platform.LogicalOperator	\
	cpe.schemas.platform.ObjectFactory	\
	cpe.schemas.platform.Os	\
	cpe.schemas.platform.package-info	\
	cpe.schemas.platform.Platform	\
	cpe.schemas.platform.PlatformDefinitions	\
	cpe.schemas.platform.Product	\
	cpe.schemas.platform.ProductType	\
	cpe.schemas.platform.Service	\
	cpe.schemas.platform.TextType	\
	cpe.schemas.platform.VersionOperatorType	\
	org.purl.dc.ElementType	\
	org.purl.dc.ObjectFactory	\
	org.purl.dc.package-info	\
	xccdf.schemas.core.Benchmark	\
	xccdf.schemas.core.CcOperatorEnumType	\
	xccdf.schemas.core.CheckContentRefType	\
	xccdf.schemas.core.CheckContentType	\
	xccdf.schemas.core.CheckExportType	\
	xccdf.schemas.core.CheckImportType	\
	xccdf.schemas.core.CheckType	\
	xccdf.schemas.core.ComplexCheckType	\
	xccdf.schemas.core.FactType	\
	xccdf.schemas.core.FixStrategyEnumType	\
	xccdf.schemas.core.FixTextType	\
	xccdf.schemas.core.FixType	\
	xccdf.schemas.core.GroupType	\
	xccdf.schemas.core.HtmlTextType	\
	xccdf.schemas.core.HtmlTextWithSubType	\
	xccdf.schemas.core.IdentityType	\
	xccdf.schemas.core.IdentType	\
	xccdf.schemas.core.IdrefListType	\
	xccdf.schemas.core.IdrefType	\
	xccdf.schemas.core.InstanceFixType	\
	xccdf.schemas.core.InstanceResultType	\
	xccdf.schemas.core.InterfaceHintType	\
	xccdf.schemas.core.ItemType	\
	xccdf.schemas.core.MessageType	\
	xccdf.schemas.core.MetadataType	\
	xccdf.schemas.core.Model	\
	xccdf.schemas.core.MsgSevEnumType	\
	xccdf.schemas.core.NoticeType	\
	xccdf.schemas.core.ObjectFactory	\
	xccdf.schemas.core.OverrideableIdrefType	\
	xccdf.schemas.core.OverrideableURIidrefType	\
	xccdf.schemas.core.OverrideType	\
	xccdf.schemas.core.package-info	\
	xccdf.schemas.core.ParamType	\
	xccdf.schemas.core.PlainTextType	\
	xccdf.schemas.core.ProfileNoteType	\
	xccdf.schemas.core.ProfileRefineRuleType	\
	xccdf.schemas.core.ProfileRefineValueType	\
	xccdf.schemas.core.ProfileSelectType	\
	xccdf.schemas.core.ProfileSetValueType	\
	xccdf.schemas.core.ProfileType	\
	xccdf.schemas.core.RatingEnumType	\
	xccdf.schemas.core.ReferenceType	\
	xccdf.schemas.core.ResultEnumType	\
	xccdf.schemas.core.RoleEnumType	\
	xccdf.schemas.core.RuleResultType	\
	xccdf.schemas.core.RuleType	\
	xccdf.schemas.core.ScoreType	\
	xccdf.schemas.core.SelChoicesType	\
	xccdf.schemas.core.SelectableItemType	\
	xccdf.schemas.core.SelNumType	\
	xccdf.schemas.core.SelStringType	\
	xccdf.schemas.core.SeverityEnumType	\
	xccdf.schemas.core.SignatureType	\
	xccdf.schemas.core.Status	\
	xccdf.schemas.core.StatusType	\
	xccdf.schemas.core.TargetFactsType	\
	xccdf.schemas.core.TestResultType	\
	xccdf.schemas.core.TextType	\
	xccdf.schemas.core.TextWithSubType	\
	xccdf.schemas.core.URIidrefType	\
	xccdf.schemas.core.UriRefType	\
	xccdf.schemas.core.ValueOperatorType	\
	xccdf.schemas.core.ValueType	\
	xccdf.schemas.core.ValueTypeType	\
	xccdf.schemas.core.VersionType	\
	xccdf.schemas.core.WarningCategoryEnumType	\
	xccdf.schemas.core.WarningType	\
	xccdf.schemas.platform.CheckContentRefType	\
	xccdf.schemas.platform.CheckContentType	\
	xccdf.schemas.platform.CheckType	\
	xccdf.schemas.platform.Fact	\
	xccdf.schemas.platform.FactRefType	\
	xccdf.schemas.platform.LogicOperatorEnumType	\
	xccdf.schemas.platform.LogicTestType	\
	xccdf.schemas.platform.ObjectFactory	\
	xccdf.schemas.platform.package-info	\
	xccdf.schemas.platform.Platform	\
	xccdf.schemas.platform.PlatformSpecification	\
	xccdf.schemas.platform.TextType
