SCHEMAS=	\
	aix-definitions-schema.xsd			\
	aix-system-characteristics-schema.xsd		\
	apache-definitions-schema.xsd			\
	apache-system-characteristics-schema.xsd	\
	catos-definitions-schema.xsd			\
	catos-system-characteristics-schema.xsd		\
	esx-definitions-schema.xsd			\
	esx-system-characteristics-schema.xsd		\
	evaluation-ids.xsd				\
	freebsd-definitions-schema.xsd			\
	freebsd-system-characteristics-schema.xsd	\
	hpux-definitions-schema.xsd			\
	hpux-system-characteristics-schema.xsd		\
	independent-definitions-schema.xsd		\
	independent-system-characteristics-schema.xsd	\
	ios-definitions-schema.xsd			\
	ios-system-characteristics-schema.xsd		\
	linux-definitions-schema.xsd			\
	linux-system-characteristics-schema.xsd		\
	macos-definitions-schema.xsd			\
	macos-system-characteristics-schema.xsd		\
	oval-common-schema.xsd				\
	oval-definitions-schema.xsd			\
	oval-directives-schema.xsd			\
	oval-results-schema.xsd				\
	oval-system-characteristics-schema.xsd		\
	oval-variables-schema.xsd			\
	pixos-definitions-schema.xsd			\
	pixos-system-characteristics-schema.xsd		\
	sharepoint-definitions-schema.xsd		\
	sharepoint-system-characteristics-schema.xsd	\
	solaris-definitions-schema.xsd			\
	solaris-system-characteristics-schema.xsd	\
	unix-definitions-schema.xsd			\
	unix-system-characteristics-schema.xsd		\
	windows-definitions-schema.xsd			\
	windows-system-characteristics-schema.xsd	\
	xmldsig-core-schema.xsd
