CLASSES=\
	org.joval.intf.apple.system.IiOSSession			\
	org.joval.intf.cisco.system.IIosSession			\
	org.joval.intf.cisco.system.ITechSupport		\
	org.joval.intf.io.IFile					\
	org.joval.intf.io.IFileEx				\
	org.joval.intf.io.IFilesystem				\
	org.joval.intf.io.IRandomAccess				\
	org.joval.intf.io.IReader				\
	org.joval.intf.juniper.system.IJunosSession		\
	org.joval.intf.juniper.system.ISupportInformation	\
	org.joval.intf.net.INetconf				\
	org.joval.intf.plugin.IPlugin				\
	org.joval.intf.ssh.system.IShell			\
	org.joval.intf.ssh.system.IShellProcess			\
	org.joval.intf.system.IBaseSession			\
	org.joval.intf.system.IEnvironment			\
	org.joval.intf.system.IProcess				\
	org.joval.intf.system.ISession				\
	org.joval.intf.unix.io.IUnixFileInfo			\
	org.joval.intf.unix.io.IUnixFilesystem			\
	org.joval.intf.unix.io.IUnixFilesystemDriver		\
	org.joval.intf.unix.system.IPrivilegeEscalationDriver	\
	org.joval.intf.unix.system.IUnixSession			\
	org.joval.intf.util.ILoggable				\
	org.joval.intf.util.IObserver				\
	org.joval.intf.util.IPathRedirector			\
	org.joval.intf.util.IPerishable				\
	org.joval.intf.util.IProducer				\
	org.joval.intf.util.IProperty				\
	org.joval.intf.util.ISearchable				\
	org.joval.intf.util.tree.ICacheable			\
	org.joval.intf.util.tree.IForest			\
	org.joval.intf.util.tree.INode				\
	org.joval.intf.util.tree.ITree				\
	org.joval.intf.windows.identity.IACE			\
	org.joval.intf.windows.identity.IDirectory		\
	org.joval.intf.windows.identity.IGroup			\
	org.joval.intf.windows.identity.IPrincipal		\
	org.joval.intf.windows.identity.IUser			\
	org.joval.intf.windows.io.IWindowsFileInfo		\
	org.joval.intf.windows.io.IWindowsFilesystem		\
	org.joval.intf.windows.registry.IBinaryValue		\
	org.joval.intf.windows.registry.IDwordValue		\
	org.joval.intf.windows.registry.IExpandStringValue	\
	org.joval.intf.windows.registry.IKey			\
	org.joval.intf.windows.registry.ILicenseData		\
	org.joval.intf.windows.registry.IMultiStringValue	\
	org.joval.intf.windows.registry.INoneValue		\
	org.joval.intf.windows.registry.IQwordValue		\
	org.joval.intf.windows.registry.IRegistry		\
	org.joval.intf.windows.registry.IStringValue		\
	org.joval.intf.windows.registry.IValue			\
	org.joval.intf.windows.powershell.IRunspace		\
	org.joval.intf.windows.powershell.IRunspacePool		\
	org.joval.intf.windows.system.IWindowsSession		\
	org.joval.intf.windows.wmi.ISWbemEventSource		\
	org.joval.intf.windows.wmi.ISWbemObject			\
	org.joval.intf.windows.wmi.ISWbemObjectSet		\
	org.joval.intf.windows.wmi.ISWbemProperty		\
	org.joval.intf.windows.wmi.ISWbemPropertySet		\
	org.joval.intf.windows.wmi.IWmiProvider			\
	org.joval.io.BufferedReader				\
	org.joval.io.LittleEndian				\
	org.joval.io.PerishableReader				\
	org.joval.io.StreamLogger				\
	org.joval.io.StreamTool					\
	org.joval.io.fs.CacheFile				\
	org.joval.io.fs.CacheFileSerializer			\
	org.joval.io.fs.CacheFilesystem				\
	org.joval.io.fs.DefaultFile				\
	org.joval.io.fs.FileAccessor				\
	org.joval.io.fs.FileInfo				\
	org.joval.os.windows.wmi.WmiException			\
	org.joval.util.AbstractEnvironment			\
	org.joval.util.Base64					\
	org.joval.util.CachingHierarchy				\
	org.joval.util.Checksum					\
	org.joval.util.Environment				\
	org.joval.util.IniFile					\
	org.joval.util.JOVALMsg					\
	org.joval.util.JOVALSystem				\
	org.joval.util.Producer					\
	org.joval.util.PropertyHierarchy			\
	org.joval.util.PropertyUtil				\
	org.joval.util.SafeCLI					\
	org.joval.util.SessionException				\
	org.joval.util.StringTools				\
	org.joval.util.Version					\
	org.joval.util.tree.Forest				\
	org.joval.util.tree.Node				\
	org.joval.util.tree.NodeSerializer			\
	org.joval.util.tree.Tree				\
	org.joval.util.tree.TreeHash				\
	org.joval.xml.SchemaRegistry
