CLASSES=\
	jcifs.smb.VolatileSmbFile					\
	org.joval.identity.SimpleCredentialStore			\
	org.joval.discovery.SessionFactory				\
	org.joval.identity.Credential					\
	org.joval.intf.identity.ICredential				\
	org.joval.intf.identity.ILocked					\
	org.joval.intf.net.INetconf					\
	org.joval.intf.ssh.ISftpError					\
	org.joval.intf.ssh.identity.ISshCredential			\
	org.joval.intf.ssh.system.ISshSession				\
	org.joval.intf.windows.identity.IWindowsCredential		\
	org.joval.io.StreamLogger					\
	org.joval.io.TailDashF						\
	org.joval.os.cisco.IosNetworkInterface				\
	org.joval.os.cisco.IosSystemInfo				\
	org.joval.os.cisco.system.IosSession				\
	org.joval.os.cisco.system.TechSupport				\
	org.joval.os.juniper.JunosNetworkInterface			\
	org.joval.os.juniper.JunosSystemInfo				\
	org.joval.os.juniper.system.JunosSession			\
	org.joval.os.juniper.system.SupportInformation			\
	org.joval.os.unix.remote.system.Sudo				\
	org.joval.os.unix.remote.system.UnixSession			\
	org.joval.os.windows.identity.WindowsCredential			\
	org.joval.os.windows.remote.identity.SmbACE			\
	org.joval.os.windows.remote.io.SmbFilesystem			\
	org.joval.os.windows.remote.io.SmbFileProxy			\
	org.joval.os.windows.remote.io.SmbRandomAccessProxy		\
	org.joval.os.windows.remote.registry.Key			\
	org.joval.os.windows.remote.registry.Registry			\
	org.joval.os.windows.remote.system.WindowsProcess		\
	org.joval.os.windows.remote.system.WindowsSession		\
	org.joval.os.windows.remote.wmi.WmiConnection			\
	org.joval.os.windows.constants.ICreateFlags			\
	org.joval.os.windows.constants.IShowWindow			\
	org.joval.os.windows.remote.wmi.scripting.SWbemObject		\
	org.joval.os.windows.remote.wmi.scripting.SWbemObjectSet	\
	org.joval.os.windows.remote.wmi.scripting.SWbemProperty		\
	org.joval.os.windows.remote.wmi.scripting.SWbemPropertySet	\
	org.joval.os.windows.remote.wmi.scripting.SWbemSecurity		\
	org.joval.os.windows.remote.wmi.win32.Win32Process		\
	org.joval.os.windows.remote.wmi.win32.Win32ProcessStartup	\
	org.joval.plugin.RemotePlugin					\
	org.joval.plugin.container.RemoteContainer			\
	org.joval.protocol.netconf.NetconfSession			\
	org.joval.ssh.identity.SshCredential				\
	org.joval.ssh.io.SftpFile					\
	org.joval.ssh.io.SftpFilesystem					\
	org.joval.ssh.system.SshProcess					\
	org.joval.ssh.system.SshSession					\
	org.joval.util.JSchLogger					\
	org.joval.test.Netconf						\
	org.joval.test.Remote
