REMOTE=\
	jcifs.smb.VolatileSmbFile					\
	org.joval.identity.SimpleCredentialStore			\
	org.joval.discovery.SessionFactory				\
	org.joval.identity.Credential					\
	org.joval.intf.cisco.system.IIosSession				\
	org.joval.intf.cisco.system.ITechSupport			\
	org.joval.intf.identity.ICredential				\
	org.joval.intf.identity.ILocked					\
	org.joval.io.StreamLogger					\
	org.joval.io.TailDashF						\
	org.joval.os.embedded.IosNetworkInterface			\
	org.joval.os.embedded.IosSystemInfo				\
	org.joval.os.embedded.system.IosSession				\
	org.joval.os.embedded.system.TechSupport			\
	org.joval.os.unix.remote.system.Sudo				\
	org.joval.os.unix.remote.system.UnixSession			\
	org.joval.os.windows.identity.WindowsCredential			\
	org.joval.os.windows.remote.identity.SmbACE			\
	org.joval.os.windows.remote.io.SmbFilesystem			\
	org.joval.os.windows.remote.io.SmbFileProxy			\
	org.joval.os.windows.remote.io.SmbRandomAccessProxy		\
	org.joval.os.windows.remote.registry.Key			\
	org.joval.os.windows.remote.registry.Registry			\
	org.joval.os.windows.remote.system.WindowsProcess		\
	org.joval.os.windows.remote.system.WindowsSession		\
	org.joval.os.windows.remote.wmi.WmiConnection			\
	org.joval.os.windows.constants.ICreateFlags			\
	org.joval.os.windows.constants.IShowWindow			\
	org.joval.os.windows.remote.wmi.scripting.SWbemObject		\
	org.joval.os.windows.remote.wmi.scripting.SWbemObjectSet	\
	org.joval.os.windows.remote.wmi.scripting.SWbemProperty		\
	org.joval.os.windows.remote.wmi.scripting.SWbemPropertySet	\
	org.joval.os.windows.remote.wmi.scripting.SWbemSecurity		\
	org.joval.os.windows.remote.wmi.win32.Win32Process		\
	org.joval.os.windows.remote.wmi.win32.Win32ProcessStartup	\
	org.joval.oval.di.RemoteContainer				\
	org.joval.plugin.RemotePlugin					\
	org.joval.ssh.identity.SshCredential				\
	org.joval.ssh.io.SftpError					\
	org.joval.ssh.io.SftpFile					\
	org.joval.ssh.io.SftpFilesystem					\
	org.joval.ssh.system.SshProcess					\
	org.joval.ssh.system.SshSession					\
	org.joval.util.JSchLogger					\
	org.joval.test.Remote
