CLASSES=\
	jcifs.smb.VolatileSmbFile					\
	org.joval.discovery.SessionFactory				\
	org.joval.identity.Credential					\
	org.joval.identity.SimpleCredentialStore			\
	org.joval.intf.identity.ICredential				\
	org.joval.intf.identity.ICredentialStore			\
	org.joval.intf.identity.ILocked					\
	org.joval.intf.ssh.identity.ISshCredential			\
	org.joval.intf.ssh.ISftpError					\
	org.joval.intf.ssh.system.ISshSession				\
	org.joval.intf.windows.identity.IWindowsCredential		\
	org.joval.io.TailDashF						\
	org.joval.os.cisco.system.IosSession				\
	org.joval.os.cisco.system.TechSupport				\
	org.joval.os.juniper.system.JunosSession			\
	org.joval.os.juniper.system.SupportInformation			\
	org.joval.os.unix.io.driver.AIXDriver				\
	org.joval.os.unix.io.driver.LinuxDriver				\
	org.joval.os.unix.io.driver.MacOSXDriver			\
	org.joval.os.unix.io.driver.SolarisDriver			\
	org.joval.os.unix.io.UnixCacheFileSerializer			\
	org.joval.os.unix.io.UnixFile					\
	org.joval.os.unix.io.UnixFileInfo				\
	org.joval.os.unix.io.UnixFilesystem				\
	org.joval.os.unix.remote.system.Sudo				\
	org.joval.os.unix.remote.system.UnixSession			\
	org.joval.os.unix.remote.system.driver.AbstractDriver		\
	org.joval.os.unix.remote.system.driver.AIXDriver		\
	org.joval.os.unix.remote.system.driver.LinuxDriver		\
	org.joval.os.unix.remote.system.driver.MacOSXDriver		\
	org.joval.os.unix.remote.system.driver.SolarisDriver		\
	org.joval.os.unix.system.BaseUnixSession			\
	org.joval.os.unix.system.Environment				\
	org.joval.os.windows.constants.ICreateFlags			\
	org.joval.os.windows.constants.IShowWindow			\
	org.joval.os.windows.identity.ActiveDirectory			\
	org.joval.os.windows.identity.Directory				\
	org.joval.os.windows.identity.Group				\
	org.joval.os.windows.identity.LocalDirectory			\
	org.joval.os.windows.identity.Principal				\
	org.joval.os.windows.identity.User				\
	org.joval.os.windows.identity.WindowsCredential			\
	org.joval.os.windows.io.WindowsFileInfo				\
	org.joval.os.windows.io.WOW3264FilesystemRedirector		\
	org.joval.os.windows.registry.BaseRegistry			\
	org.joval.os.windows.registry.BinaryValue			\
	org.joval.os.windows.registry.DwordValue			\
	org.joval.os.windows.registry.ExpandStringValue			\
	org.joval.os.windows.registry.LicenseData			\
	org.joval.os.windows.registry.MultiStringValue			\
	org.joval.os.windows.registry.NoneValue				\
	org.joval.os.windows.registry.QwordValue			\
	org.joval.os.windows.registry.RegistryException			\
	org.joval.os.windows.registry.StringValue			\
	org.joval.os.windows.registry.Value				\
	org.joval.os.windows.registry.WOW3264RegistryRedirector		\
	org.joval.os.windows.remote.identity.SmbACE			\
	org.joval.os.windows.remote.io.SmbAccessor			\
	org.joval.os.windows.remote.io.SmbCacheFileSerializer		\
	org.joval.os.windows.remote.io.SmbFileInfo			\
	org.joval.os.windows.remote.io.SmbFileProxy			\
	org.joval.os.windows.remote.io.SmbFilesystem			\
	org.joval.os.windows.remote.io.SmbRandomAccessProxy		\
	org.joval.os.windows.remote.registry.Key			\
	org.joval.os.windows.remote.registry.Registry			\
	org.joval.os.windows.remote.system.WindowsProcess		\
	org.joval.os.windows.remote.system.WindowsSession		\
	org.joval.os.windows.remote.wmi.scripting.SWbemObject		\
	org.joval.os.windows.remote.wmi.scripting.SWbemObjectSet	\
	org.joval.os.windows.remote.wmi.scripting.SWbemProperty		\
	org.joval.os.windows.remote.wmi.scripting.SWbemPropertySet	\
	org.joval.os.windows.remote.wmi.scripting.SWbemSecurity		\
	org.joval.os.windows.remote.wmi.win32.Win32Process		\
	org.joval.os.windows.remote.wmi.win32.Win32ProcessStartup	\
	org.joval.os.windows.remote.wmi.WmiConnection			\
	org.joval.os.windows.system.Environment				\
	org.joval.plugin.BasePlugin					\
	org.joval.plugin.RemotePlugin					\
	org.joval.protocol.netconf.NetconfSession			\
	org.joval.ssh.identity.SshCredential				\
	org.joval.ssh.io.SftpFile					\
	org.joval.ssh.io.SftpFileInfo					\
	org.joval.ssh.io.SftpFilesystem					\
	org.joval.ssh.system.ExecProcess				\
	org.joval.ssh.system.ShellProcess				\
	org.joval.ssh.system.SshProcess					\
	org.joval.ssh.system.SshSession					\
	org.joval.test.AD						\
	org.joval.test.Exec						\
	org.joval.test.FS						\
	org.joval.test.Netconf						\
	org.joval.test.Reg						\
	org.joval.test.Remote						\
	org.joval.test.WMI						\
	org.joval.util.AbstractBaseSession				\
	org.joval.util.AbstractSession					\
	org.joval.util.JSchLogger
